### ISSUE TITLE
Submission language selector bug

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#1000]
**Describe the bug**
When configuring a submission field to contain a language selector, the language is lost when clicking the "Add" button

**To Reproduce**
1. Add `<language value-pairs-name="common_iso_languages">true</language>` in submission-forms.xml (I've tested with dc.title.alternative)
2. Enter a value and select a language
3. Click on the "Add" button
4. The language is lost, and has to be selected again
5. https://www.dropbox.com/s/2edxvgg4aqjovbw/Schermopname%202021-01-27%20om%2011.33.32.mov?dl=0

**Expected behavior**
After clicking add, the language should remain present

**Comment by tdonohue** [comment]
May be related to #971, which @atarix83 is working on.

**Comment by benbosman** [comment]
That sounds related indeed. It would be good to check again once 971 is ready to review

**Comment by tdonohue** [comment]
I've tested this with #1025 applied and I've verified that PR fixes this bug.
