### ISSUE TITLE
Duplicate keys in en.json5

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#1010]
**Describe the bug**
The key menu.section.admin_search appears twice in the language catalog en.json5.
The consequence is that likely, the first label is overwritten by the second definition.
Lines 2324 and 3947

In addition to this, a block of keys, starting with "profile." at line 2750 is also duplicated starting at line 2836

**To Reproduce**
N/A

**Expected behavior**
Every key should only be defined once.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
I've created a small PR to clean this up. See #1033
