### ISSUE TITLE
Creating a new EPerson Group fails

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#1013]
**Describe the bug**
When trying to create a new EPerson group, the Group creation fails:
https://www.dropbox.com/s/6z778yh8dxxf2z3/Schermopname%202021-02-08%20om%2009.49.09.mov?dl=0

**To Reproduce**
1. Open /admin/access-control/groups/newGroup
2. Try to create a new group
3. Notice the group name is not passed to REST

**Expected behavior**
The group name should be passed to REST

**Comment by artlowel** [comment]
This will be fixed in the context of #962

**Comment by tdonohue** [comment]
Closing, this has been fixed & is no longer reproducible.
