### ISSUE TITLE
Search filter from entity page carries over to discovery

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1016]
**Describe the bug**
If you enter the URL of an entity page that contains a search at the bottom, and then open the search bar in the header, and enter an empty query, you'll get the same results on the search page that were on the item page. 

**To Reproduce**
1. Enter the URL of an entity page that contains a search at the bottom (e.g. https://demo7.dspace.org/items/fcbab2a4-d774-4cf0-83f6-1417f0b5567d)
2. Open the search bar in the header and press return
3. Verify that instead of all results for the entire repository, you get the exact same results you got on the entity page

**Expected behavior**
Unrelated searches shouldn't influence each other.

**Comment by artlowel** [comment]
I came across this issue, and I investigated because I thought it might be caused by the recent cache changes. But it turns out it's due to a fixedFilter being set in the store, but not removed afterwards in certain situations.

This will take an estimated **2h** to fix

Atmire would like to claim this task

**Comment by tdonohue** [comment]
@artlowel : Thanks, this sounds fine to me. I've added to Beta 5 and assigned to your team
