### ISSUE TITLE
Icons of disabled items in the admin sidebar are clickable

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1019]
**Describe the bug**
The icons of disabled items in the admin sidebar still react to hover and click events; route to the home page on click

**To Reproduce**
1. Log in as an administrator with limited access (e.g. dspacedemo+admin@gmail.com on https://demo7.dspace.org/home)
2. Mouse over & click on the _icons_ of disabled sidebar links

**Expected behavior**
The icons should be disabled just like the link text

**Comment by tdonohue** [comment]
Agreed & can reproduce, this is a minor usability issue. Scheduling for possible fixing in 7.0 (during testathon)
