### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1023]
While in Submission form drag&drop a file on form and "Upload Failed" appears on screen.

In developer tools network tab you can see an error response to workspace save request : 
`{timestamp: "2021-02-15T22:09:04.642+0000", status: 403, error: "Forbidden",…}
error: "Forbidden"
message: "Access is denied. Invalid CSRF token."
path: "/server/api/submission/workspaceitems/3508"
status: 403
timestamp: "2021-02-15T22:09:04.642+0000"`

**Comment by tdonohue** [comment]
The issues is with the `ng2-file-upload` library, which doesn't seem to fully support Http interceptors (like our `xsrf.interceptor.ts` which manages CSRF/XSRF tokens for all parts of our Angular app).  This is a known issue in `ng2-file-upload`:  https://github.com/valor-software/ng2-file-upload/issues/950

I've found a temporary workaround...but, longer term, this is another reason to move away from `ng2-file-upload` as originally recommended in #820

**Comment by vahem2lu** [comment]
Is there a temporary workaround for public as well? Or when is merge planned?

**Comment by tdonohue** [comment]
@vahem2lu : Unfortunately there's no easy workaround, unless you want to install the under review PR locally (https://github.com/DSpace/dspace-angular/pull/1024).  Merging will occur as soon as that PR is approved...currently it's undergoing further testing though (it seems to mostly work, but initial tests found an additional bug...now it's waiting for a follow-up review).

**Comment by tdonohue** [comment]
@vahem2lu : Just a quick follow up. This bug has now been fixed on our "main" branch, as the PR was approved & merged today.
