### ISSUE TITLE
Unit test false negatives (usage of `fixture.debugElement.query` + `toBeDefined`)

### ISSUE THREAD

**Issue by bruno-atmire** [DSpace/dspace-angular#1026]
**Describe the bug**
Multiple unit tests always succeed (even when they should fail). This happens because `expect(...).toBeDefined()` checks are used on variables that will never be set to `undefined`.

[For example](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts#L52):
```js
const btn = fixture.debugElement.query(By.css('.btn-success'));
expect(btn).toBeDefined();
```
If `fixture.debugElement.query` can find a match, it will return a DebugElement. (So far so good.)
However, if no element can be found, it will return `null`. Consequently, the test still passes, but it is supposed to fail.

**To Reproduce**
Building on the example:
1. run `yarn test --include src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts` (all tests should pass)
2. change the [css selector here](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts#L50), e.g. to `.this-class-does-not-exist` (optionally log `btn` to the console)
3. run the tests again (still passes)

**Expected behavior**
When the tests are run the second time, they should fail, because no element with class `.this-class-does-not-exist` exists in the component.

**Possible fix**
Replace `expect(...).toBeDefined()` with `expect(...).not.toBeNull()`. (Better checks may be crafted on a case-by-case basis.)

**Occurrences**
- https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts#L52
- https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/mydspace-actions/claimed-task/approve/claimed-task-actions-approve.component.spec.ts#L61
- https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/mydspace-actions/claimed-task/edit-metadata/claimed-task-actions-edit-metadata.component.spec.ts#L47
- ...

A text search on `toBeDefined` yields 100+ results, so chances are high this issue occurs in other tests as well.

**Comment by tdonohue** [comment]
This does seem like an issue, though it may require a more detailed analysis of how many tests have this issue.  Therefore scheduling for 7.1 and adding `Estimate TBD`

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this, it will take an estimate of 3h
