### ISSUE TITLE
Stale remotedata emitted first

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1027]
**Describe the bug**
Currently, if you set a remotedata object to stale, and immediately afterwards retrieve it again, you can still get the stale remote data object as the first emitted object of the returned observable.

That is because a dataservice returns an observable looking at the expected place in the store immediately after sending the request. However the request is dispatched to the store, and the reducers and effects execute in their own zone (think of it as a separate thread that gets executed when the current one finishes), so the code to retrieve the remotedata is executed before the reducer that overwrites it with the new request.

**To Reproduce**
The scenario described by @alemarte in [this comment](https://github.com/DSpace/dspace-angular/pull/978#issuecomment-775993429) on [this commit](https://github.com/DSpace/dspace-angular/pull/978/commits/d015b6caefa06dfc72ce649e6f716cf1ea2c9095) is a consistent way to trigger the behavior. [This findByHref](https://github.com/4Science/dspace-angular/blob/d015b6caefa06dfc72ce649e6f716cf1ea2c9095/src/app/core/tasks/tasks.service.ts#L139) will return a stale remotedata first, when you claim the same task for the second time

**Expected behavior**
If you call findByHref or findAllByHref on a dataservice you should never get a stale remotedata object emitted first.
If allow the use of a cached version, and there is a cached version it could be completed, in all other cases the first emitted remotedata object should be loading. The only way you should be able to end up with a stale remote data object from a dataservice method is to already be subscribed to it as it becomes stale.

**Related work**
The issue came to light in #978, it was introduced by #961

**Comment by tdonohue** [comment]
@artlowel : While you work on an estimate, I'd also appreciate any advice on the priority of this one. For instance, is this something we should work to solve in Beta 5, or is it lower priority as it's not encountered frequently?  Thanks for getting this logged

**Comment by artlowel** [comment]
We'll have to filter out stale remote data objects in the find methods in dataservice. This will take an estimated **4h**. 
I think should be done ASAP, to prevent losing time on other hard to debug problems that ultimately end up being caused by this issue.

Atmire would like to claim this task
