### ISSUE TITLE
Pagination doesn't work with javascript disabled

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#103]
If you use the pagination component, added in PR #95, and you have javascript enabled, the url will update if you navigate to a page, change the number of results, etc. 

If javascript is disabled, and the page is rendered on the server, you always arrive at the first page with the default options.

Ideally, using the same URL should yield the same result with or without javascript support

**Comment by atarix83** [comment]
If javascript is disabled pagination component renders page properly but it doesn't allow to change page. 
We wouldn’t start creating our own wrapper around the bootstrap pagination for now, so I've opened an [issue](https://github.com/ng-bootstrap/ng-bootstrap/issues/1616) on ng-bootstrap to find a way to solve the issue.

**Comment by atarix83** [comment]
ng-bootstrap has closed my issue, they won't do our request.
So if we want fix the problem we should consider other ways.

**Comment by tdonohue** [comment]
@atarix83 and @artlowel : The `ng-bootstrap` team responded to my question on their ticket. We need to provide them with more info on how to reproduce this behavior in a minimal fashion. Then they may reopen the ticket, if they can reproduce.

**Comment by atarix83** [comment]
@artlowel  @tdonohue : 

I've tried to provide them more explanations on the ticket.
