### ISSUE TITLE
Issues with modifying Date field in Submission

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1032]
**Describe the bug**
When you modify or delete values out of the Date field in the Submission UI, and click "Save" or "Save for Later" you can trigger a 500 error on the backend.  After triggering that error, it's impossible to save any other edits -- you have to click away from your submission and start over.

**To Reproduce**
1. Create a new submission, adding all mandatory fields, especially the **Date of Issue**
2. Click "Save for later"
3. Now, edit that same submission. remove (or replace) the values in that "Date of Issue" field. 
4. Click "Save for later"...you'll see a 500 error from the PATCH command (if you are watching in Chrome DevTools)
5. Edit a different field, e.g. Title.  Click "Save for later" again.  Still a 500 error.

**Expected behavior**
You should be allowed to edit a Date field without corrupting the submission.

**Comment by tdonohue** [comment]
@atarix83 : Could you look into this and provide an estimate?  It's seemingly a UI level issue in the Submission UI.

**Comment by atarix83** [comment]
@tdonohue I'm sorry but I can't reproduce the issue. I've test it over main branch and also over #1025 and for both I can't reproduce it

**Comment by tdonohue** [comment]
@atarix83 : Thanks for testing. I'll claim this ticket back and re-test on my end.  Maybe I had something misconfigured when I was hitting this error a few days ago.

**Comment by tdonohue** [comment]
Closing, as I'm no longer reliably able to reproduce this.  When I have reproduced this, it appears to be a CSRF mismatch issue which seems resolved by ensuring the CSRF token changes less frequently (see https://github.com/DSpace/DSpace/pull/3168).
