### ISSUE TITLE
Write policies on items show the edit button on the item page, but redirect to a 403 page

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/dspace-angular#1047]
**Describe the bug**
When users have a write policy on an item, the UI shows the edit button on the item page, but it redirects to a 403 forbidden  page when clicked. If the user has the appropriate rights, he/she should be allowed to alter (a subset, for example the metadata) of the item's information.

**To Reproduce**
1. As an admin, edit an item, and give a non admin user a write policy on the item
2. Impersonate that particular non admin user
3. Navigate to the initial item page
4. Click the edit button -> This shows a 403 page
5. Navigate straight to /items/{{uuid}}/edit/metadata -> This shows a 403

**Expected behavior**
The write policy for the item should allow the non-admin users to edit the actual item (Or at least the metadata, since the write policies already allow this)
The actual 'parts' of the item that this type of user/policy combination can alter could be created to be configurable

**Comment by tdonohue** [comment]
estimated at 2hrs by @artlowel .

**Comment by tdonohue** [comment]
As discussed today, the upcoming PR for this ticket can be assigned to @tdonohue and @atarix83
