### ISSUE TITLE
Error deleting an item when its entity type has no relations

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1054]
When an entity type has no existent relations the item deletion is not executed.

1. Create a temporary entity type with no relation (ex: TmpType)
2. Create an item with the metadata 'relationship.type' with the value 'TmpType'.
3. Go to the item edit page and click on Permanently Delete and then on Delete.

The application should execute a DELETE Http Request.

**Comment by alemarte** [comment]
There is an observable of types to subscribe in order to execute the deletion, but when types are empty it never emit. 

Estimated 2h. 

4science can claim this task.

**Comment by tdonohue** [comment]
@alemarte : Thanks, this sounds like something to definitely fix.  Assigning this back to you to work on.  (I realize this might be hard to implement by our current PR deadline of before the meeting on Thurs, but do your best to get this done this week if possible)
