### ISSUE TITLE
UI sends wrong request when creating new metadata field without qualifier

### ISSUE THREAD

**Issue by bruno-atmire** [DSpace/dspace-angular#1067]
**Describe the bug**
Use the UI to create a new metadata field. (It does not matter which metadata schema is used.) Leave the qualifier form input blank.

A POST request is sent to `<url>/api/core/metadatafields?schemaId=<schema id>` with the following body:
```
{"element":"mytest1","qualifier":"","scopeNote":"created via GUI"}
```

Note that qualifier contains an empty string (instead of `null`). The request is able to create the metadata field, but an empty string is stored in the database, instead of the customary `NULL` value. (That in turn leads to the metadata field not being retrievable by some parts of DSpace.)

**To Reproduce**
1. Use the UI to create a new metadata field. Leave the qualifier blank.
2. Observe that an empty string is sent to the backend
3. Observe that an empty string is saved to the database

**Expected behavior**
When the qualifier input is left blank, the request should be:
```
{"element":"mytest1","qualifier":null,"scopeNote":"created via GUI"}
```
or even omit the qualifier:
```
{"element":"mytest1","scopeNote":"created via GUI"}
```

Additionally the backend may want to reject empty values with `422 Unprocessable Entity`, or convert them to `null` automatically.

When reproducing the bug locally, I used the [latest dspace-angular](https://github.com/DSpace/dspace-angular/tree/1115c585378c890b1b7421b6ececbc24d50a38c0) and the [latest backend](https://github.com/DSpace/DSpace/tree/2b4f22be65d9997194d30cf01a49b9cac539b4a2) (at time of writing).

**Comment by tdonohue** [comment]
Estimated by @benbosman as 4 hours total (2 hours REST, 2 hours Angular).  Assigning to @benbosman  to try to fit in prior to Testathon.
