### ISSUE TITLE
Add fine-grained permission checks for the edit item page

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1073]
**Describe the bug**
The work we did for #1047 made it clear that apart from edit metadata, which that ticket addressed, there are also a lot of other parts of the edit item page and its tabs that can use more fine grained feature checking

**Expected behavior**
After we've come to an agreement and have an implementation for https://github.com/DSpace/DSpace/issues/3201 we should go over the edit item page and disable the tabs and certain individual features unless you have permission to use each specific feature. Here's an overview of the tabs and the features that are relevant for the tab itself or the features inside

- Status
	- canManageMappedItems  (proposed in https://github.com/DSpace/DSpace/issues/3201)
	- withdrawItem
	- reinstateItem
	- canManagePolicies
	- canMakePrivate
	- canDelete
	- canMove
- Bitstreams
	- canManageBitstreams (proposed in https://github.com/DSpace/DSpace/issues/3201)
	- canReorderBitstreams
	- canCreateBundle
	- canCreateBitstream
- Metadata
	- canEditMetadata (will be the case after the PR for #1047)
- Relationships
	- canManageRelationShips (proposed in https://github.com/DSpace/DSpace/issues/3201)
	- canEditMetadata (will be the case after the PR for #1047)
- VersionHistory
	- canManageVersions (proposed in https://github.com/DSpace/DSpace/issues/3201)
	- canSeeVersions
	- canCreateVersions
- CollectionMapper
	- canManageMappedItems  (proposed in https://github.com/DSpace/DSpace/issues/3201)

This means that we'll also need a way to check more than one feature in a guard for route (e.g. for the status route we need to check if the user is authorized for at least one of the features mentioned). This is currently not the case. 

**Related work**
- #1047
- https://github.com/DSpace/DSpace/issues/3201

**Comment by artlowel** [comment]
We'll need to:
- Add the ability to combine features for a guard in an OR query
- Implement the guards for the routes
- enable/disable the tabs and buttons on the edit item page itself based on authorization for these features.

This will take an estimated **16 hours**

**Comment by tdonohue** [comment]
Thanks @artlowel .  I'll tentatively schedule this for 7.0 (to be built during/after Testathon), and assign back to your team.
