### ISSUE TITLE
Provide a default privacy statement and end-user agreement

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1080]
**Describe the bug**
We added components for a privacy statement and end-user agreement in #862. However, currently they contain filler, lorem ipsum text. Before 7.0 we should preferably replace that filler text with a good default for both documents, or if we can't do that, disable the components by default.

**To Reproduce**
Click the privacy policy or end-user agreement links in the footer.

**Expected behavior**
Out of the box, DSpace should not show any filler text that has to be replaced in order to be usable.

**Related work**
https://github.com/DSpace/dspace-angular/pull/862
https://github.com/DSpace/dspace-angular/issues/736
https://github.com/DSpace/DSpace/issues/2808

**Comment by tdonohue** [comment]
@pnbecker : I recall you were working with the DSpace GDPR Working Group on perhaps drafting some default privacy statement / end-user agreement text.  Is this still accurate, and can it be made available in time for 7.0 final?

**Comment by pnbecker** [comment]
I wrote to the mailing list from the GDPR working group. We haven't bin in touch for some while, but I'll try to come up with something.

**Comment by pnbecker** [comment]
Do we have a list of CDNs that we include content from? Do we have a list of external services that we include (e.g. Google Analytics, if it is switched on)?

**Comment by tdonohue** [comment]
@pnbecker : I don't believe we use any CDNs.  Everything is precompiled and served directly from your server running Angular to the client.  The client isn't pulling anything from elsewhere.

I'm not sure what sort of external services would qualify here.  Google Analytics is only used when enabled.  But, we do have many other services similarly available to enable, like ORCID, Sherpa, etc. Though, those are all only used to *search* and pull content in, so I'm not sure whether you'd want a list of those as well?  Or is it just a list of services we are sending data to? (which is a much much smaller list, namely just Google Analytics, if enabled, and IRUS, also if enabled)

**Comment by tdonohue** [comment]
@pnbecker : I'm assigning this ticket to you officially, since you are taking the lead on this (per discussions in DSpace Governance meetings).  Let us know obviously what support you may need.

**Comment by bbranan** [comment]
@tdonohue @pnbecker I've been looking into creating a default/example end-user agreement for use on DSpaceDirect sites and wanted to share what I have so far as a potential starting point for community discussion: https://docs.google.com/document/d/1QSB2cyUDagM_GnupxmLureTGAVNjYXGjdErh3tx0Yq4/edit.

This started as output from https://app.termly.io/ with several irrelevant sections removed and a bit of editing on our end. There may be some parts of this that are currently more US-centric, as that's where we are doing our hosting. Feel free to comment or edit as you see fit.

**Comment by davidatmire** [comment]
Hi @tdonohue , @bbranan , @pnbecker ,

I have no data privacy / GDPR expertise, but would just like to share a possible alternative for the default text of the end-user agreement.

This could be considered as a simplified default version of the agreement, which might be particularly applicable to institutions using SSO and having their users agree on a institution-specific data policy / GDPR agreement.

> End User Agreement
> 
> This is a University of XXX computer system. Access to this computer system, including all related equipment, networks, and network devices (including internet access) and electronic resources at the University of XXX is restricted to employees, students, or other individuals authorised by the University or its affiliates and is subject to all applicable laws and the University statutes, policies and regulations.
> 
> By ticking the box, you acknowledge that you have read and agree to the End User Agreement.

**Comment by pilasou** [comment]
Hi, providing a standard licence can be an avenue but I would tend to prefer one that would take the form of a template. One can be found on GDPR website (https://gdpr.eu/privacy-notice/). It is providing a good starting point to replace the lorem ipsum text. Maybe the stanrdard licence can come later? What do you think?

**Comment by pnbecker** [comment]
@pilasou we have a budget to contract a lawyer to right one for DSpace. Unfortunately every state has it's own law and the GDPR just defines a minimum that every state has to guarantee. The lawyer will write it following German law which is one of the most strict data protection laws within the EU and probably worldwide.
Why isn't it there yet? I do miss the time to gather all the information the lawyer need. It is on my desk and I hope I can do it soon. Currently with the ongoing pandemic, I can't guarantee anything, sorry.

**Comment by tdonohue** [comment]
@pnbecker : I'd like to make sure this gets into 7.4 (later this year) as this has been in the works for some time now.  If we need to reassign this, please let us know.  We could also look more closely at the draft privacy statement written/shared by the DSpaceDirect team (see [comment above](https://github.com/DSpace/dspace-angular/issues/1080#issuecomment-1006801347)) at https://docs.google.com/document/d/1QSB2cyUDagM_GnupxmLureTGAVNjYXGjdErh3tx0Yq4/edit 

I think this needs to be in the 7.4 release, so let me know what I can do to help move this along soon.

**Comment by tdonohue** [comment]
@pnbecker : This appears to have been forgotten for a long time but is still assigned to you.  Are you still interested in this work, or should I look for another volunteer?  It looks like one option here could be to simply use the drafted statements donated by the DSpaceDirect team (in this google doc: https://docs.google.com/document/d/1QSB2cyUDagM_GnupxmLureTGAVNjYXGjdErh3tx0Yq4/edit).  That may not necessarily be "perfect", but it is better than nothing & could be enhanced at a later time.

**Comment by pnbecker** [comment]
Good idea, let’s use the one from DSpace Direct. Thanks!

**Comment by tdonohue** [comment]
@pnbecker :  Just to clarify, does Library Code want to keep this ticket as "claimed" and submit a PR which is the draft statement from DSpaceDirect?  Or would you rather "unclaim" this?  If you'd rather unclaim this, I'll see if I can find someone from DSpaceDirect (or perhaps I can claim this if I can find time to simply copy that text over into our codebase).

**Comment by tdonohue** [comment]
Claiming this to see if I can simply add the DSpaceDirect statements into DSpace itself.
