### ISSUE TITLE
Metadata Registry create new metadata schema doesn't appear without reload

### ISSUE THREAD

**Issue by ubks-mp** [DSpace/dspace-angular#1081]
**Describe the bug**
On Metadata Registry page, when creating a new schema, the new schema is not listed after successful submit.
Name-field keeps old value.

**To Reproduce**
Create a new schema.

**Expected behavior**
New schema should list as last entry, both Namespace- and Name-fields should be empty.

**Temporary solution**
Reload.

**Comment by tdonohue** [comment]
@artlowel : Assigning to you (or your team to review).  To me, it sounds like a caching issue.  Placing this as low priority for now, as it works but is annoying

**Comment by hugo-escire** [comment]
Hi @tdonohue, I want to take this task.
