### ISSUE TITLE
Repeatable fields with look up still broken in some cases

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1091]
**Describe the bug**

I'm testing main with the [latest changes](https://github.com/DSpace/dspace-angular/pull/1025) to the submission repeatable fields against the candidate [PR](https://github.com/DSpace/DSpace/pull/3224) rest side and I've found a couple of bugs still.

1. If the first inserted value comes from a lookup, the form breaks because in that case the auto save is not fired.
2. If you remove a virtual value by clicking on the Trash button, the form breaks because the auto save is not fired.
3. If there is only one virtual value you, the Trash button is not disabled (as happens for a plain value) and clicking on it breaks the form.

**To Reproduce**

Start a submission in a collection with a repeatable field configured for lookup selection and follow the cases descibed above.

**Comment by abollini** [comment]
@tdonohue this has requested 3 hours of work
