### ISSUE TITLE
CSS for a custom theme should be selected/loaded automatically.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1093]
**Describe the bug**
Discovered during the review of https://github.com/DSpace/dspace-angular/pull/1063#discussion_r610419190

When creating a custom theme (or even the "dspace" base theme), it is currently recommended to modify the `src/index.html` to reference your theme's CSS directly. See https://github.com/DSpace/dspace-angular/blob/main/src/index.html#L10

**Expected behavior**
Ideally, this CSS should be selected automatically and/or written into the file by webpack, for example https://medium.com/dailyjs/inserting-variables-into-html-and-javascript-with-webpack-80f33625edc6

This would make it easier to enable a custom theme just by modifying configuration (and no longer needing to touch the main `index.html`).

Tentatively scheduling for 7.0 as this seems like something we may want to clean up prior to final release.

**Comment by artlowel** [comment]
I created PR #1212 to fix this issue and #1134. It took 2 hours
