### ISSUE TITLE
Add npm scripts to start in production mode with AoT

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#11]
```npm run build:prod:ngc:json``` will build the project for production.

```node dist/server/index.js``` will start the app in production.

```
"start:prod:node": "node dist/server/index.js",
"start:prod": "npm run build:prod:ngc:json && npm run start:prod:node",
```
this could work and ```npm run start:prod``` will build and start production.

**Comment by artlowel** [comment]
nodemon is primarily designed to watch for file changes right? Wouldn't something like [forever](https://github.com/foreverjs/forever) be better suited for a production environment? 
It seems to me that updating production should be a conscious decision, not something that happens automatically when a file in the src dir changes

**Comment by artlowel** [comment]
… or was your point that we should develop in "production" mode because of the issue you mentioned yesterday?

**Comment by wwelling** [comment]
Ah yes. My bad. nodemon would not be the package for starting the production server. The main objective is to build production with AoT using ngc.

**Comment by mwoodiupui** [comment]
Certainly we should *test* that production will actually work, especially if the code has some way of knowing whether it is in production.

Donning my sysadmin. hat:  I get really annoyed with packages that ignore the facilities with which I'm running the rest of the host and try to do everything themselves.  If I want something to be always running, guaranteed, I'd put it under control of monit, or in extreme cases add it to inittab.
