### ISSUE TITLE
Adding relationships from the edit item page is broken

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1103]
**Describe the bug**
If you try to add a relationship from the edit item tab as an admin the modal it will keep loading. It looks like this was broken by #1025, where a [number of observables specific to the submission where added to the modal](https://github.com/DSpace/dspace-angular/pull/1025/files#diff-7153c84b248096cb62023c0a8281c69489e686b19e1aa93210b193ba9907cca6R209-R226) and used to [determine when to show the loading component](https://github.com/DSpace/dspace-angular/pull/1025/files#diff-0a149d5d15da577df45c655558cbf4aba647c8c25c1767c3a9a8ca060c133986R9-R10)

**To Reproduce**
1. Authenticate as an admin
2. Go to an edit item page, on the relationships tab
3. Try to add a relationship

**Expected behavior**
The modal should work properly both in the submission and on the edit item page.

**Related work**
#1025

**Comment by tdonohue** [comment]
@artlowel : Assigning this back to you for analysis & estimation. It sounds like something that should be fixed in 7.0, so I gave it a `medium` priority.

**Comment by artlowel** [comment]
@atarix83 Could you tell me why [this setItem method](https://github.com/DSpace/dspace-angular/pull/1025/files#diff-7153c84b248096cb62023c0a8281c69489e686b19e1aa93210b193ba9907cca6R209-R226) was added? The item was already being set by the method that initializes the modal in [the submission](https://github.com/DSpace/dspace-angular/blob/31e4aa788ee484815c3588a7077e56d11af1068a/src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-form-control-container.component.ts#L433) and on the [edit item page](https://github.com/DSpace/dspace-angular/blob/c66de4fe91aa3448e0f6f2674ef053aa8faa8419/src/app/+item-page/edit-item-page/item-relationships/edit-relationship-list/edit-relationship-list.component.ts#L148), and was independent of anything submission related. At first sight it seems like simply removing setItem could fix this issue.

**Comment by atarix83** [comment]
@artlowel that method has been added to retrieve the item end collection when I've tried to place the lookup button, along the `Add more` button in the form.component. There, both submission and collection are not available so I made that method. In the current implementation is not needed but we should keep in mind if we'll move the lookup button as suggested by @tdonohue [here](https://github.com/DSpace/dspace-angular/pull/1092#pullrequestreview-634699497)

**Comment by artlowel** [comment]
In that case we can fix it in **1 hour**

**Comment by tdonohue** [comment]
Sounds good @artlowel . I've assigned back to your team to begin work
