### ISSUE TITLE
Shibboleth authentication is broken due to CSRF token

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1108]
**Describe the bug**
After the introducing of CSRF token the shibboleth authentication is no longer working. The issue consists that after the user has logged-id with shibboleth the angular application make a login request but receive an 403 response with `Access is denied. Invalid CSRF token.` error 

**To Reproduce**
1. go to the demo site https://demo7.dspace.org/home
2. try to login by selecting `Log in with Shibboleth` option

**Comment by abollini** [comment]
it is worth to note that the shibboleth login works in the HAL browser

**Comment by tdonohue** [comment]
Assigning this to myself for initial analysis, since it seems CSRF related.  This is definitely high priority for 7.0
