### ISSUE TITLE
Deleting a single file in a multi-file submission makes all files disappear.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1110]
**Describe the bug**
If you start a submission, and upload many files, then delete one...all of the files disappear from the submission.  However, only the one is deleted.  The others will reappear if you exit the submission & reopen it.

**To Reproduce**
1. Start a new Item submission
2. Upload 3 files.  This succeeds. All three files will be listed.
3. Now, delete one file.  **This succeeds, but now all files disappear from the submission form.**
4. Click "Save for Later"
5. Now, go back in and edit the same submission. You'll see that 2 files now remain.

**Expected behavior**
Deleting one file should only cause that file to disappear from the submission form.

**Comment by tdonohue** [comment]
@atarix83 : Could you look into this bug for me & see if you can figure out what may be going on? (Please provide an estimate & let me know if your team is interested in working on it.)  It sounds (to me) like some sort of caching issue -- all the files are removed from the cache & "disappear", even though only one is actually deleted.

**Comment by atarix83** [comment]
@tdonohue this should take about 2-3 hours to fix, we are interested to fix it

**Comment by tdonohue** [comment]
Thanks @atarix83 ! That sounds good to me.  Adding the estimate & will keep you assigned so that your team can start work on fixing this.
