### ISSUE TITLE
"Burger" (3-line) menu doesn't work on most pages.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1111]
**Describe the bug**
(Copied from [Test Plan, Item T008](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

> On the homepage there is a burger menu (I'm on Firefox on Android mobile) in the top right hand side which does nothing when I click on it. I was hoping the menu would include a link to the Statistics, which exists in the desktop version, unfortunately I cannot tell if it is supposed to be available. Whereas, when I click the burger menu on a community or collection page, some options appear but they are overlaid over the page content, so they are not readable. I can just make out the word 'Statistics' but nothing happens when I try to click on it. There is also a line that says 'All of DSpace' just like the desktop version, but when I try to click on that, or on the dropdown icon next to it, they just clear and go back to the collection or community page, whereas that option in the desktop version allows you to choose to browse 'all of DSpace' by author or by subject etc so those are not available to me on mobile. Which is ok if that is the intention, but the links should not be appearing in that case. On the homepage I'm not sure if the links are not appearing or maybe are just invisible because the background is dark. 

**To Reproduce**
This is also reproducible on a desktop by making your window small. I've been able to reproduce on both Chrome & Firefox as follows: 
1. Load up homepage
2. Drag window to be very small, until the 3-line menu option appears in upper right.
3. Click it. Nothing will happen.
4. Now, go to the "Community & Collections" page.
5. Again, drag the window to be small, until the 3-line menu option appears in upper right.
6. Click it. This time, you'll see a brief flash. But you cannot really read the menu options as they blend in with the page content.

**Expected behavior**
Menu options should be available on mobile / small browsers.

**Comment by tdonohue** [comment]
@atarix83 : Could you look into this one as well & report back?  It sounds like something may have accidentally broken in the recent theme/accessibility rework that you did in the header.

**Comment by atarix83** [comment]
@tdonohue 
it's due to a missing style, I've already resolved I can open directly a PR if you prefer

**Comment by tdonohue** [comment]
@atarix83 : Yes, please open a PR immediately whenever you know the fix is small.  Will keep this assigned to you and just add a 1 hour estimate since it was quick to fix.
