### ISSUE TITLE
Forgot Password page not working (disappears after initial load)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1113]
**Describe the bug**
(Copied from [Test Plan, Item T012](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

>"Password reset link is received upon entering mail id in field available in forgot password. However, page opening after clicking unique URL received does not have stable behavior. link shows reset password field for few seconds and then state move to page loading for indefinite period.
> Screenshot: https://ibb.co/XJSXmct"

**To Reproduce**
1. Create a new account (if needed) at https://demo7.dspace.org/ (or locally)
2. Use the "Forgot Password" page.
2. Password reset link will be sent via email
3. Click the link. If you are watching closely the Forgot Password page will briefly appear (as a flash).  Then, you'll see the loading screen as shown in the screenshot

**Expected behavior**
Forgot password page should appear & work.

**Comment by tdonohue** [comment]
@artlowel : Could you or someone on your team look at this?  This appears (to me) to be a UI issue...and it looks like your team initially built this feature.

**Comment by artlowel** [comment]
This is due to an error in the EpersonRegistrationService.searchByToken logic. It doesn't work if the response has already been cached server side.

This will take an estimated **3 hours** to fix.

**Comment by tdonohue** [comment]
Thanks @artlowel .  Adding the estimate & assigning back to you & your team to work on.
