### ISSUE TITLE
Collection selector always shows loading image on some pages

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1114]
**Describe the bug**
(Copied from [Test Plan, Item T017](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

>"Upon clicking ""Item"" under ""New"", New submission popup appears for selecting collection. In first run, latest collection added in the DSpace appeared. However, upon repeating same steps only pre loader is appearing in the collection list area.
> New Submission step performed from various parts of the repository but issue remained same.
> Collection name appears after entering its name. its happening on random basis.
> Screenshot: https://ibb.co/HFXJG4M"

**To Reproduce**
I've been able to reproduce, and it seems like it has to do with whether the Collection select finds a collection or not.

For, instance, it works perfectly if you browse to a Collection first:
1. Browse to any Collection
2. Click "New -> Item".  The Collection you are on is selected.

However, if you select "New -> Item" from a non-Collection page, you always see "No collection found" with a " ....." loading message.  For instance:
1. Go to the Search Results. Or, simply go to the homepage
2. Click "New -> Item".  You'll see "No collection found" and the loading icon.
3. If you type in a Collection name, it will appear.  So, it's just that the behavior is *confusing*.  I'd expect that you would not see a "No collection found" message until you type something in.  I'd also expect that the loading icon would only appear temporarily while it was loading results.

**Expected behavior**
I'd expect that you would not see a "No collection found" message until you type something in.  
I'd also expect that the loading icon would only appear temporarily while it was loading results.

Ideally, if a Collection cannot be found based on your context in the site, the first 5 collections should just be listed.  Or, alternatively, we could leave an empty list until a Collection name is typed.  Either behavior would be better than the current behavior.

**Comment by tdonohue** [comment]
@artlowel : Another one for your team to look at.  This also appears to be a UI level issue.

**Comment by artlowel** [comment]
We should:
- Show the unfiltered list of collections before the user starts typing
- Only show the no results alert if a search has occurred first
- Not show the loading component if there are no results

This will take an estimated **4 hours**

**Comment by tdonohue** [comment]
Thanks @artlowel .  Estimate sounds good & assigning back to you for your team to work on.
