### ISSUE TITLE
Private/Withdrawn filters no longer working in Administrative Search

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1115]
**Describe the bug**
The Private/Withdrawn filters in the Administrative Search always seem to return zero results.

**To Reproduce**
1. Login as an Admin and go to https://demo7.dspace.org/admin/search
2. Currently, on the demo site, there is one Withdrawn item & one Private Item
3. Click the "Withdrawn: Yes" filter. You'll see zero results, even though one withdrawn item exists here: https://demo7.dspace.org/items/56cb766d-4b8a-40f6-a18f-0f8ae41e1ba1
    * NOTE: After selecting this filter, the value strangely changes to "True"
4. Click the "Private: Yes" filter. You'll also see zero results, even though one private item exists here: https://demo7.dspace.org/items/517e94a2-f2c2-4653-8a92-ea718c14a1ee
    * NOTE: After selecting this filter, the value strangely changes to "False"

**Expected behavior**
Obviously, these filters should both work. Also, ideally the value shouldn't change from "Yes" to True/False" after selecting it.  Either the value should always be "Yes/No" or always be "True/False" (either is fine).

**Comment by tdonohue** [comment]
@benbosman : Could you (or someone on your team) take a look at this? I *think* it actually may be a server-side Solr issue, as it looks (to me) like the proper request is being sent from the UI, but the results returned are zero.  For now, leaving this as a `dspace-angular` ticket though until we determine where the cause is.

**Comment by benbosman** [comment]
This is due to solr containing `"discoverable": "true"` and the filter is `fq=discoverable_keyword:true`
Since `discoverable_keyword` is not indexed, this doesn't work
This is indeed an API querying issue, and also an indication of a missing IT

This can be solved in 3 hours, including the IT
We can work on this

**Comment by tdonohue** [comment]
Thanks @benbosman .  Sounds good & assigning back to you for your team to start work.

(Please also keep in mind that there *might* be a small Angular fix here too...notice how you select the value "yes" or "no" but in the Angular UI it changes to "true" or "false" once selected.  I suspect we may need a small Angular PR to fix that too.  This could be assigned to @artlowel 's team as needed, if I'm correct.)
