### ISSUE TITLE
Item-level statistics pages no longer working

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1116]
**Describe the bug**
(Copied from [Test Plan, Item T122](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

>Error 404 Page not found. NB the link is the destination of the 'Statistics' link at the top of the page of the Item of the PhD of Francis Mumbanza. If you click on 'Statistics' on that Item page, nothing happens. https://demo7.dspace.org/entities/project/b1bc3a49-49b1-417a-ac90-8d5c7ba5e0ac Even though the stats for the collection can be displayed easily, and show numerous visits to this Item. If we want the users only to click on Statistics on the Collection page and not on the Item page, the link should be hidden, or if we expect them to view the item stats as part of the collection stats, the link should point to the collection stats page. This issue is the same in Microsoft Edge. 

**To Reproduce**
1. Login as an Admin
2. Browse to an Item
3. Click on the "Statistics" link the header (nothing happens)
4. Browse to a Collection
5. Click on the "Statistics" link in the header -- you see Collection-level statistics

**Expected behavior**
Obviously, Item-level statistics should be viewable.

**Related work**
This used to work, as it was added in #851

**Comment by artlowel** [comment]
The problem is that it re-uses the item page resolver to determine for which item to retrieve the stats, but that resolver was changed to redirect to the entity url for #1001. So that resolver needs to be split up so the logic can be shared but so the one for the stats page doesn't redirect.

This can be done in an estimated **2 hours**

**Comment by tdonohue** [comment]
Thanks @artlowel , estimate sounds good. Assigning back to you for your team to work on
