### ISSUE TITLE
Pagination of ORCID search results not functioning properly.

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1117]
**Describe the bug**
(Copied from [Test Plan, Item T113](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

> "The results per page shows the correct number of results, but the ""Now showing X - Y of Z"" message always shows ""Now showing 1 - 5 of Z"". Also the page links doesn't work properly, when one of the page links are clicked the list isn't updated with the new results
"

**To Reproduce**
Verified on demo site
1. Login as an Admin
2. Start a new Submission to the "Articles" collection (or any collection which has Publication Entities enabled)
2. Click the Lookup button next to the "Author" field
3. Click on the ORCID tab & run a search with many results (e.g. "Donohue")
4. Notice the pagination will say "Now showing 1 - 5 of ___"
5. Now, change the Results per page to "1".  Only 1 result will show, but you'll still see "Now showing 1 - 5 of ___" (and the same number of pages at the bottom)
6. Now, change the Results per page to "40".  40 result will show, but you'll still see "Now showing 1 - 5 of ___" (and the same number of pages at the bottom)
7. Click page 2.  The "Now showing" will update, but you won't see any new entries (you are still on page 1).

**Expected behavior**
Pagination should work & should update based on the "Results per page" value. ( Unrelated, but we may also want to consider removing values > 40, as even 40 results per page take a very long time to load)

**Related work**
This used to work, as it was added in #539

**Comment by tdonohue** [comment]
@artlowel : This looks like it was originally built by your team (namely @Atmire-Kristof )....so, assigning to you to analyze. Please feel free to delegate though, as I know you have a lot of these analyses on your plate.

**Comment by artlowel** [comment]
This was likely broken by #1048. The pagination params in the URL are wrong.

It will take an estimated **3 hours** to fix

**Comment by tdonohue** [comment]
Thanks @artlowel .  Estimate sounds good & assigning back to you for your team to work on.
