### ISSUE TITLE
Item Collection Mapper search for Collection not working

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1120]
**Describe the bug**
(Copied from [Test Plan, Item T037](https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815)): 

> Started with item, "Test work for CBL" > Edit > Collection Mapper > Map new collections. Tab: Browse mapped collections: "No collections to show." Tab: Map new collections: Searched for Books. Checked box next to Books > Map item to selected collections. Results: Pop-up box: "Mapping errors. Errors occurred for mapping of item to 1 collections."

**To Reproduce**
1. Login as an Admin (for example at https://demo7.dspace.org/)
2. Browse/search for an Item & Edit it
3. Go to the "Collection Mapper" tab
4. Go to the "Map new collections" subtab
5. Search for a Collection or click the "Search" button.  The results always show "No collections to show".  It appears the search/pagination may be broken?

**Expected behavior**
It should be possible to map an Item to a Collection

**Comment by tdonohue** [comment]
@artlowel : Assigning this to you & your team for analysis, as it seems like the search/pagination is broken here as well.  Strangely the original testathon report says they tried to map a Collection & it failed, but I cannot even get Collections to appear in search results.  So, see what you can reproduce here.  In any case, flagging this as high priority for 7.0

**Comment by artlowel** [comment]
@tdonohue It seems there is currently an issue with discovery on the backend. The call to search for collections to map returns [an inconsistent result](https://api7.dspace.org/server/#/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&query=Collection%20AND%20-search.resourceid:38b3d22d-ad91-4daf-a4e1-3dc683523f9f&dsoType=COLLECTION). It has a nonzero totalPages and totalElements, but no searchResults.

A regular discovery search also doesn't work at the moment

**Comment by artlowel** [comment]
Now the discovery index is rebuilt I seem to be able to map items just fine. Tried multiple item and collection combinations. One at a time, multiple at once. It all seems to work.

Granted I can no longer find the "Test work for CBL" item, or the Books collection in order to test the exact issue being reported. 

I'm closing this for now. Feel free to reopen if there's a way to reproduce it.
