### ISSUE TITLE
Files disappear in submission process

### ISSUE THREAD

**Issue by gsteinhart** [DSpace/dspace-angular#1121]
When I upload a file and complete metadata, then accept the license, the uploaded file disappears. If I try to upload again, I see BOTH files. If I try to delete one before completing the submission, they BOTH disappear.

**Comment by tdonohue** [comment]
Thanks @gsteinhart !

@atarix83 : I believe this is a duplicate of #1110  (or at least caused by that same bug). So, I'm assigning to you for analysis...if it is a duplicate, we can close this ticket in favor of #1110 (which I know is already in progress).

**Comment by atarix83** [comment]
@tdonohue I think is something related the bug reported in #1110 so it can be fixed within that issue

**Comment by tdonohue** [comment]
Thanks @atarix83 , leaving this assigned to you then & moving to "in progress".
