### ISSUE TITLE
Delete community/collection should be disable when a delete operation is in progress

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1122]
**Describe the bug**
This is a follow-up issue of https://github.com/DSpace/DSpace/issues/3243.
During the analysis made for https://github.com/DSpace/DSpace/issues/3243 it is obvious as that many consecutive delete request on the same community have been made by the user. 
This is due to the delete community/collection page where the delete button is not disabled while the request is in progress. Moreover the button should show the fact that an operation is processing as has been done for other similar functionality. 
![Schermata da 2021-04-22 15-56-48](https://user-images.githubusercontent.com/2486489/115727531-f6b48100-a383-11eb-816e-663bf77a109a.png)

**To Reproduce**
1. As admin go to the collection/community edit page
2. click to delete button
3. in the confirmation page click on the confirm button
4. you are able to click several time on the button, even if the delete operation is being processed by the rest

**Expected behavior**
the confirm button should be disable while the delete operation is being processed by the rest and it should also show spin icon as in the screenshot

**Comment by tdonohue** [comment]
@atarix83 : As mentioned today, I'm assigning this back to you for your team to investigate and provide an estimate. I've also labeled as high priority for 7.0

**Comment by atarix83** [comment]
I estimate about 1 hour to fix it

**Comment by tdonohue** [comment]
Thanks @atarix83 ! I'll add that estimate & assign to you for your team to work on (when you are ready)
