### ISSUE TITLE
Access control section is visible to non admin users

### ISSUE THREAD

**Issue by santit96** [DSpace/dspace-angular#1124]
When logged in as an collection administrator i can to visualize and even access the Access control section. I even can see the groups and people lists and access to person and group details. But i can't edit groups that i don't belong to (this is ok)

1. Log in as an collection admin
2. Open the "Access control" section in the menu
3. Enter groups or people sections

A collection admin shouldn't be able to visualize the access control section

**Comment by tdonohue** [comment]
@artlowel : assigning this to you for your feedback.  I suspect this is a "side effect" of the fact that Community/Collection Admins *can view* People & Groups (as they need to be able to view them in order to manage Community/Collection based groups).  However, I wonder if there's a way to either hide the "Access Control" section, or perhaps somehow make it clearer that they only have *read-only* access to much of the information in that section?

**Comment by artlowel** [comment]
I don't think we can hide the groups page entirely for community or collection admins. They need to manage the groups related to the communities and collections they manage. See #927

The best solution for groups in my opinion would be to add a search endpoint for groups similar to [findSubmitAuthorized for collection](https://github.com/DSpace/RestContract/blob/main/collections.md#findsubmitauthorized), to allow us to only return the groups a user has edit or delete access to.

A less ideal, but perhaps easier way to fix this would be to still list everything, but to add a canManageGroup feature (or perhaps extend canEditMetadata to also work for groups) that we could use to determine for each individual group in the list whether you can edit it. We already use the canDelete feature to do that for the delete button in that list.

Either solution would take about **4 hours** on the angular side, but either solution needs some rest work first

For epersons I can't think of a reason why collection or community admins would ever need access to that page, so I propsose we put that route behind an isAdmin check. This can be done within the 4 hours of the estimate.

**Comment by tdonohue** [comment]
@artlowel : thanks for the notes. I agree that your "best solution" is ideal in this scenario, but the other solution would also work and be good enough (if the best solution is too complex to implement at this time).

@benbosman : Assigning this over to you for REST API analysis (as you worked on this previously).  Do you agree with the solution proposed by @artlowel , and could you share an estimate for fixing it on the REST side?

**Comment by benbosman** [comment]
The best solution suggested by Art was a search endpoint for groups: e.g. findManageGroupsAuthorized, which will only return the groups a user has edit or delete access to.
This would require a scalable solution to identify which groups a user can manage, and thus implies the groups will need to be indexed in discovery. I would expect 1-2 days of work to deal with this


The less ideal solution suggested by Art was to use a canManageGroup feature that we could use to determine for each individual group in the list whether you can edit it. This already exists in REST: https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageGroupsFeature.java

**Comment by benbosman** [comment]
Just discussed this with Art, we already have canManageGroups, but not canManageGroup (given a specific group), I will update the ticket based on that

**Comment by benbosman** [comment]
We can create a `canManageGroup` feature, with the group as resource type. It will check whether the user is admin for that specific group
Including ITs, this should be realistic in 2 hours

**Comment by tdonohue** [comment]
Thanks @benbosman & @artlowel  .  In that case, let's go with the easier approach for 7.0.
* REST API: Implement `canManageGroup` (estimate 2 hours)
* Angular UI: Use `canManageGroup` to only display an edit button next to groups you can edit.  Update EPerson management to be behind an `isAdmin` check. (estimate 4 hours)
    * This will mean that Community/Collection Admins see all Groups still. I'm OK with that though, as they already can see all Groups when they edit/create a Community/Collection Group (as they have the ability to select subgroups). 

I'll assign this to both of you as there's two parts to this ticket.  I'll also add the overall estimate of 6hours
