### ISSUE TITLE
Remove menu options for disabled features

### ISSUE THREAD

**Issue by bbranan** [DSpace/dspace-angular#1125]
**Describe the bug**
In DSpace 7.0 beta 5 the *Statistics Task* and *Control Panel* options in the sidebar menu are always disabled. This is because these features are not completed and not planned for inclusion in DSpace 7.0. These menu options should be removed or hidden until the features that they point to are completed.

The purpose of this change is to avoid user confusion. If a feature does not exist or is not enabled, it shouldn't be present on the menu.

**To Reproduce**
1. Log in as an administrator
2. Look at the sidebar menu

The "Statistics Task" option is also available in the sidebar for users that are not administrators.

**Expected behavior**
Only features that are enabled and relevant to the logged in user will be included in the list of menu options.

**Comment by tdonohue** [comment]
@artlowel : Assigning this to your team.  It's definitely a small task (likely 1 hr), but I agree with @bbranan that we should remove / comment out the grayed out menu options (which currently don't exist).

**Comment by artlowel** [comment]
This can be done in **1 hour**

Atmire would like to claim this issue

**Comment by tdonohue** [comment]
@artlowel : Assigning back to you for your team to work on. Thanks!
