### ISSUE TITLE
Cannot add/edit Embargo on Bitstream of archived Item

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1129]
**Describe the bug**
Cannot add/change the Embargo on a Bitstream of an Archived Item

**To Reproduce**
1. Login as someone with Admin level permissions (full Admin, Comm/Coll Admin)
2. Eit an Item
3. Go to Bitstreams tab
4. Edit a Bitstream
5. The "Embargo until specific date" field will be listed but it's grayed out.

**Expected behavior**
It should be possible to modify an embargo (previously added during the Submission), or add a new embargo at the Bitstream level

**Comment by tdonohue** [comment]
@atarix83 : I'm assigning this to you for your team to investigate & estimate.  It looks (to me) like we may have forgotten to implement this feature as the field appears to always be grayed out.

**Comment by atarix83** [comment]
Since the issue is due to a missing implementation on rest side the and it can be done anyway by editing resource policy of the bitstream, the solution could be to remove the disabled field and to add a shortcut to the edit page for bitstream's resource policy.

I estimate about 1 hour

**Comment by tdonohue** [comment]
@atarix83 : That sounds reasonable to remove the field for now & replace it with a link to edit the resource policies.  I'll add your estimate & assign to you for your team to work on.
