### ISSUE TITLE
Runtime theme switch unexpected behavior

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1134]
**Describe the bug**
There is a very weird behavior when Angular draws a ThemedComponent involving a theme switch at runtime.
In fact it seems that the component is first drawn by using the previous active theme, and then updated with the new one.
It is odd especially when themes have significant differences in term of colors contrasts (which I think can happen sometimes).

**To Reproduce**
To quickly test this behaviour I've pushed this [branch](https://github.com/4Science/dspace-angular/tree/main-theme-issue) to test against the demo rest api. In this configuration the content of the collection with the handle '10673/1167' has a darken navbar theme.

1. Go to the collection page with the configured handle http://localhost:4000/collections/cec4e466-724f-41f7-b04b-ed87c94c7a35
2. Navigate back to the home page

**Expected behavior**
The displaying of the navbar should be deferred until the proper theme to use has been evaulated.

**Comment by tdonohue** [comment]
@artlowel : I'd appreciate your feedback on this.  I've tentatively labeled as `medium priority`, but I'd like to better understand the complexity of fixing this.  If it's overly complex, we may be able to delay past 7.0 (and simply document the problem), but it'd be nice to fix now if plausible.

**Comment by artlowel** [comment]
I created PR #1212 to fix this issue and #1093. It took 2 hours

**Comment by tdonohue** [comment]
Thanks @artlowel !  I'll add 1 hour to each ticket then.
