### ISSUE TITLE
Old 6.x URL paths should redirect to new 7.x location (for SEO)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1147]
**Describe the bug**
To ease in upgrading, major 6.x URLs should redirect to the new location in 7.x.  Several of these already work (so this ticket is documenting that), but a few remain to be fixed:

Community URLs
* `/handle/[prefix]/[suffix]` (6.x) -> `/communities/[uuid]` (7.x)  - ALREADY WORKS

Collections URLs
* `/handle/[prefix]/[suffix]` (6.x) -> `/collections/[uuid]` (7.x)  - ALREADY WORKS

Item URLs
* `/handle/[prefix]/[suffix]` (6.x) -> `/items/[uuid]` (7.x)  - ALREADY WORKS

Bitstream URLs
* `/bitstream/handle/[prefix]/[suffix]/[filename]?sequence=[sequence_id]&isAllowed=y` (6.x XMLUI) -> `/bitstreams/[uuid]/download` (7.x)  - **DOESN'T WORK**
* `/bitstream/handle/[prefix]/[suffix]/[filename]` (6.x XMLUI, alternative with no querystring) -> `/bitstreams/[uuid]/download` (7.x)  - **DOESN'T WORK**
* `/bitstream/[prefix]/[suffix]/[sequence_id]/[filename]` (6.x JSPUI) -> `/bitstreams/[uuid]/download` (7.x)  - **DOESN'T WORK**

**Comment by tdonohue** [comment]
@artlowel : Assigning this to you for your team to investigate, as I know you've helped with Bitstream download URLs in the past.  In this situation, as you'll see, we simply need to redirect old URLs to the new Bitstream download URL.  Rated this `high priority` as it was mentioned by Google Scholar as necessary for their spiders when they crawl after an upgrade from 6.x -> 7.x.

**Comment by artlowel** [comment]
This will require a new rest endpoint: a search endpoint for bitstreams that allows us to find one based on the combination of handle, filename and sequence id. Since handle is a param it could also conceivable be housed under the pid/find endpoint instead.

After we have that, we can add Angular support in an estimated **4 hours**

**Comment by benbosman** [comment]
I would recommend to create a new Rest endpoint:
`/api/core/bitstreams/search/bySequenceId?handle=[prefix]/[suffix]&sequence=[sequence_id]`

This would return a single bitstream (not a list) if there's a match

The implementation and ITs would require **4 hours**

**Comment by tdonohue** [comment]
@benbosman : That seems reasonable...although I've just found a third URL pattern we need to support which does *not* include the sequence ID.  This XMLUI URL pattern also works: `/bitstream/handle/[prefix]/[suffix]/[filename]`

So, I think we may need to modify that REST endpoint to be something like

`/api/core/bitstreams/search/byItemHandle?handle=[prefix]/[suffix]&sequence=[sequence_id]&filename=[filename]`

In this endpoint, both `sequence` and `filename` would be _optional_, but it's expected that you pass _at least one_ (with the `sequence` taking priority over `filename` if both are passed in).

In any case, I think the implementation would be pretty much the same.  So, I'll add `8hours` total to this ticket, and assign to both you and @artlowel to have your teams work on when you get the chance.
