### ISSUE TITLE
LDAP user information should be read-only

### ISSUE THREAD

**Issue by mgrothe-gu** [DSpace/dspace-angular#1152]
**Describe the bug**
In DSpace 7 Beta 5.0 users managed via an LDAP directory can edit their information in their user profile. Changing the password is said to be successful by the UI, but the password is in fact not changed. First name and last name can be edited. The email address can be edited by admins.

**To Reproduce**
Log in with an LDAP user and navigate to the user profile or as an admin open any LDAP user's profile and try to edit the information.

**Expected behavior**
Information retrieved from LDAP directories should be read-only and greyed-out in the user interface.

**Comment by tdonohue** [comment]
@abollini : I'd appreciate your feedback on this on. This sounds, to me, like it may require backend changes to let the UI know when User Profile information is editable (or not) -- and it's also be needed for Shibboleth.  Perhaps this is a new auth "feature" (`/api/authz/features/`)?  My guess is this might need to wait for 7.1 to do correctly, but let me know if you disagree.

**Comment by tdonohue** [comment]
Moving to 7.1 for now as this seems unlikely to be fixed in time for 7.0

**Comment by tdonohue** [comment]
Closing, as this appears to have been fixed in https://github.com/DSpace/DSpace/pull/8050 (see also https://github.com/DSpace/DSpace/issues/7959)

That PR added restrictions so that LDAP and Shib users can no longer change their password.
