### ISSUE TITLE
Sidemenu incomplete after Shibboleth login 

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1179]
**Describe the bug**
When a user with administrative permission log in via shibboleth, the sidebar is populated with an incomplete items set. After a page refresh the sidebar is then populated correctly.

**To Reproduce**
1. Perform the login via shibboleth with a user with administrative permission (ex sheldon/bazinga).
![sheldon1](https://user-images.githubusercontent.com/63857/117965050-9ed5be00-b322-11eb-97b0-e34809071c50.png)

2. Check the sidemenu content
![sheldon2](https://user-images.githubusercontent.com/63857/117965068-a39a7200-b322-11eb-9dd2-260c152173d9.png)
3. Perform a page refresh
![sheldon3](https://user-images.githubusercontent.com/63857/117965072-a5fccc00-b322-11eb-8f0e-57a53d482fdb.png)

**Expected behavior**
The sidemenu should be populated correctly after the successful login redirect.

**Comment by tdonohue** [comment]
@atarix83 : Assigning this to you to look into & estimate.  Is it perhaps as easy as doing a hard refresh (which I know also occurs after a default login with username/password)?  In any case, this sounds high priority if we want Shibboleth to work correctly, but let me know what you find.

**Comment by atarix83** [comment]
We found out the way to resolve the issue we can fix it in about 4 hours

**Comment by tdonohue** [comment]
Thanks @atarix83 ! I'll add that estimate & assign to you for your team to work on (when you are ready)
