### ISSUE TITLE
Dspace 7 doesn't load

### ISSUE THREAD

**Issue by ipcraiurosario** [DSpace/dspace-angular#1189]
Hi,

I just installed Dspace 7 (backend and frontend) however, the front end doesn't load as expected.

Here is what my browser shows:

![image](https://user-images.githubusercontent.com/53486765/118190162-542e7180-b408-11eb-901e-adf0edb7dd23.png)

something that doesn't seems right is the error in the console, dspace tries to get data from http://localhost:8080//api/config/properties/google.analytics.key and it should be http://localhost:8080/server/api/config/properties/google.analytics.key as I set it on environment.prod.ts:

![image](https://user-images.githubusercontent.com/53486765/118190567-ec2c5b00-b408-11eb-99ef-8116fa764671.png)

any idea how can I fix this issue?

Best regards,

Juan

**Comment by ipcraiurosario** [comment]
Something to have in mind, my /server/api/config/properties/google.analytics.key returns my key without any issue:

{"name":"google.analytics.key","values":["**mykeygoesHere**"],"type":"property","_links":{"self":{"href":"http://**myIPgoesHere**:8080/server/api/config/properties/google.analytics.key"}}}

**Comment by tdonohue** [comment]
Please check that your backend configurations are correct, mainly `dspace.server.url` and `dspace.ui.url`. Make sure the `dspace.server.url` includes the `/server` path.

Also, be sure to check our "Common installation issues": https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-CommonInstallationIssues

**Comment by ipcraiurosario** [comment]
That solved it! my dspace.server.url was declared like "localhost:8080/" the "server" after the / was missing.

Thank you very much!
