### ISSUE TITLE
Pagination Issues

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#119]
Switching to changeDetection.OnPush in [this commit](https://github.com/DSpace/dspace-angular/pull/117/commits/f57c0a4fac240e69601b4b54f6c2b1b5cfbaecef) has the effect that changing the page size no longer works. This points to an underlying problem that not all state of the pagination component is stored in the ngrx store, otherwise onPush would work.

Another likely related issues is that if you go to the second page of a paginated list, click on an item and use the browser's back button, you see the results of the first page, but the second page is still highlighted

**Comment by atarix83** [comment]
I should have solved the resize issue by adding local change detection checks as [here](https://github.com/4Science/dspace-angular/commit/d46b66f87f83230b80b1d9215cd75c0ca26a834f).

About the second issue I think that the right behavior should be to get back to the last page visited, that in the example is the second page. In this case I've seen that the PaginationComponent works properly, should it be an issue related to cache or REST call? I've tested a simple paginated list page and the same use case works well.

**Comment by wwelling** [comment]
Pagination has a glitch with universal. When the pre-render finishes and swaps the state on the client the pagination switches to the first page and back to the desired page quickly. It is not noticible in development mode and more so in replay redux prerender strategy. In production mode with rehydrate prerender strategy it happens but so quick it cannot be noticed. If the console is opened it slows everything down enough to notice it even in production mode.

This may be an issue with ngx-pagination library. Does it fully support Angular Universal. 

The desired behavior would be to never fetch and render any page but the desired.

This is required for smooth page refresh and deep linking.
