### ISSUE TITLE
Dspace 7 beta 5 - Login error

### ISSUE THREAD

**Issue by ipcraiurosario** [DSpace/dspace-angular#1192]
Hi, 

I'm trying to login with my administrator account that I've created with ./dspace create-administrator however, I get this:

![image](https://user-images.githubusercontent.com/53486765/118286201-d5811500-b497-11eb-9714-efa0aa57d0b9.png)
and this error in my browser console:

![image](https://user-images.githubusercontent.com/53486765/118286236-de71e680-b497-11eb-861f-6a798146c294.png)

However, if I check the URL showed in the error I get this response:
![image](https://user-images.githubusercontent.com/53486765/118286350-fb0e1e80-b497-11eb-95a0-57388a25fcfd.png)

And also, I'm seeing some errors in my home page:

![image](https://user-images.githubusercontent.com/53486765/118285902-8b982f00-b497-11eb-9065-7e9214d75da3.png)

this is what my localhost:8080/api/server shows:

`{"dspaceUI":"http://localhost:4000","dspaceName":"DSpace UR 7 beta 5","dspaceServer":"http://localhost:8080/server","dspaceVersion":"DSpace 7.0-beta5","type":"root","_links":{"authn":{"href":"http://localhost:8080/server/api/authn"},"authorizations":{"href":"http://localhost:8080/server/api/authz/authorizations"},"bitstreamformats":{"href":"http://localhost:8080/server/api/core/bitstreamformats"},"bitstreams":{"href":"http://localhost:8080/server/api/core/bitstreams"},"browses":{"href":"http://localhost:8080/server/api/discover/browses"},"bundles":{"href":"http://localhost:8080/server/api/core/bundles"},"claimedtasks":{"href":"http://localhost:8080/server/api/workflow/claimedtasks"},"claimedtasks-search":{"href":"http://localhost:8080/server/api/workflow/claimedtasks/search"},"collections":{"href":"http://localhost:8080/server/api/core/collections"},"communities":{"href":"http://localhost:8080/server/api/core/communities"},"discover":{"href":"http://localhost:8080/server/api/discover"},"dso":{"href":"http://localhost:8080/server/api/dso/find{?uuid}","templated":true},"entitytypes":{"href":"http://localhost:8080/server/api/core/entitytypes"},"eperson-registration":{"href":"http://localhost:8080/server/api/eperson/registrations"},"epersons":{"href":"http://localhost:8080/server/api/eperson/epersons"},"externalsources":{"href":"http://localhost:8080/server/api/integration/externalsources"},"features":{"href":"http://localhost:8080/server/api/authz/features"},"groups":{"href":"http://localhost:8080/server/api/eperson/groups"},"items":{"href":"http://localhost:8080/server/api/core/items"},"itemtemplates":{"href":"http://localhost:8080/server/api/core/itemtemplates"},"metadatafields":{"href":"http://localhost:8080/server/api/core/metadatafields"},"metadataschemas":{"href":"http://localhost:8080/server/api/core/metadataschemas"},"pid":{"href":"http://localhost:8080/server/api/pid/find{?id}","templated":true},"pooltasks":{"href":"http://localhost:8080/server/api/workflow/pooltasks"},"pooltasks-search":{"href":"http://localhost:8080/server/api/workflow/pooltasks/search"},"processes":{"href":"http://localhost:8080/server/api/system/processes"},"properties":{"href":"http://localhost:8080/server/api/config/properties"},"registrations":{"href":"http://localhost:8080/server/api/eperson/registrations"},"relationships":{"href":"http://localhost:8080/server/api/core/relationships"},"relationshiptypes":{"href":"http://localhost:8080/server/api/core/relationshiptypes"},"resourcepolicies":{"href":"http://localhost:8080/server/api/authz/resourcepolicies"},"resourcepolicies-search":{"href":"http://localhost:8080/server/api/authz/resourcepolicies/search"},"scripts":{"href":"http://localhost:8080/server/api/system/scripts"},"self":{"href":"http://10.194.194.13:8080/server/api"},"shibboleth":{"href":"http://localhost:8080/server/api/authn"},"sites":{"href":"http://localhost:8080/server/api/core/sites"},"statistics":{"href":"http://localhost:8080/server/api/statistics"},"submissioncclicenseUrls":{"href":"http://localhost:8080/server/api/config/submissioncclicenseUrls"},"submissioncclicenseUrls-search":{"href":"http://localhost:8080/server/api/config/submissioncclicenseUrls/search"},"submissioncclicenses":{"href":"http://localhost:8080/server/api/config/submissioncclicenses"},"submissiondefinitions":{"href":"http://localhost:8080/server/api/config/submissiondefinitions"},"submissionforms":{"href":"http://localhost:8080/server/api/config/submissionforms"},"submissionsections":{"href":"http://localhost:8080/server/api/config/submissionsections"},"submissionuploads":{"href":"http://localhost:8080/server/api/config/submissionuploads"},"usagereports":{"href":"http://localhost:8080/server/api/statistics/usagereports"},"versionhistories":{"href":"http://localhost:8080/server/api/versioning/versionhistories"},"versions":{"href":"http://localhost:8080/server/api/versioning/versions"},"vocabularies":{"href":"http://localhost:8080/server/api/submission/vocabularies"},"vocabularyEntryDetails":{"href":"http://localhost:8080/server/api/submission/vocabularyEntryDetails"},"vocabularyEntryDetails-search":{"href":"http://localhost:8080/server/api/submission/vocabularyEntryDetails/search"},"workflowactions":{"href":"http://localhost:8080/server/api/config/workflowactions"},"workflowdefinitions":{"href":"http://localhost:8080/server/api/config/workflowdefinitions"},"workflowitems":{"href":"http://localhost:8080/server/api/workflow/workflowitems"},"workflowsteps":{"href":"http://localhost:8080/server/api/config/workflowsteps"},"workspaceitems":{"href":"http://localhost:8080/server/api/submission/workspaceitems"}}}`

Am I missing something? 🤔

**Comment by tdonohue** [comment]
@ipcraiurosario : These questions are better asked on [Slack](https://wiki.lyrasis.org/display/DSPACE/Slack) or our [Mailing lists](https://wiki.lyrasis.org/display/DSPACE/Mailing+Lists).  Opening up multiple tickets just to ask questions is not encouraged as we use issues for known bugs/problems.

That said, I highly suspect you are hitting one of the "common installation problems" (especially if the response from the login is actually a 403 error or CORS error): https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-CommonInstallationIssues 

If it's not one of those, it's also possible your UI simply cannot find "localhost:8080"...in which case make sure you are accessing the UI from the same machine where the REST API is installed.  Since you are using "localhost" URLs, you will not be able to access the UI from a different machine.  To access the REST API from a separate machine it must use a non-localhost URL.
