### ISSUE TITLE
Bugs on submission form

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1195]
**Describe the bug**
I've fount out a couple of bugs in the submission form.

**To Reproduce**
Bug #1
1. start a new submission
2. edit the title
3. save the submission form
3. edit again the title by cancelling all the text and then point the form focus to another form's field
4. edit again the title by entering a new text 
5. save the submission form, you should get an error notification

Bug #2
1. start a new submission
2. add an empty new item in a repeatable field by clicking on the `Add more` button
3. delete the new item added by clicking on the trash icon
4. save the submission form, you should get an error notification

**Expected behavior**
In case of bug#1 the form should properly save the change. In case of bug #2 no changes to save should be detected

**Comment by atarix83** [comment]
@tdonohue the estimation is about 2 hours and I can open the new PR to resolve them

**Comment by tdonohue** [comment]
@atarix83 : Yes, these sound like issues to fix immediately.  Thanks, I'll add the 2 hr estimate & move to the 7.0 board for your team to work on.
