### ISSUE TITLE
[Deque Analysis] Fix non-text Color Contrast issues

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1202]
> Serious: This issue results in serious barriers for people with disabilities, and will partially prevent them from accessing fundamental features or content. People relying on assistive technologies will experience significant frustration as a result. Issues falling under this category are major problems, and remediation should be a priority. 

## Deque Analysis Summary

Three main non-text color contrast (serious) issues have been reported across the entire site, spread across 31 Deque issues: 

1. **"Focus indicator of an active component lacks 3:1 contrast ratio."**
    * (IDs 469778, 469994, 470016, 470047) **On Submission Form:**
        * the Collection dropdown (at top of page) when it is focused (by pressing tab on the keyboard).  The focus indicator has insufficient contrast: Focus indicator color: `#A1A8AF`, Background: `#FFFFFF`, The contrast ratio is: 2.4:1
        * the delete/trash buttons on the right of multi-valued fields when they are focused (by pressing tab on the keyboard).  The focus indicator has insufficient contrast: Focus indicator color: `#C5C5C5`, Background: `#FFFFFF`, The contrast ratio is: 1.7:1
        * the calendar button (for the calendar popup) on the embargo fields, when it is focused (by pressing tab on the keyboard).  The focus indicator has insufficient contrast: Focus indicator color: `#A1A8AF`, Background: `#FFFFFF`, The contrast ratio is: 2.4:1
        * the "I confirm the license above" checkbox. The focus indicator has insufficient contrast: Focus indicator color: `#D0D3D7`, Background: `#FFFFFF`, The contrast ratio is: 1.5:1
        * the "Save" & "Save for Later" buttons at the bottom of form. The focus indicator has insufficient contrast:  Focus indicator color: `#ADB0B3`, Background: `#CED4DA`, The contrast ratio is: 1.5:1
        * the "Discard" red button at the bottom of the form. The focus indicator has insufficient contrast:  Focus indicator color: `#D29A9D`, Background: `#CED4DA`, The contrast ratio is: 1.6:1
    *  (ID: 468926) **On Search Results:** All form fields (search selectbox, textbox, button, pagination links, text boxes in facets, results per page/sort selectboxes) do NOT have "at least a 3 to 1 luminosity contrast ratio with either the inner or outer adjacent background."  (This is the color contrast when the field is selected/in focus, e.g. when you tab to it.)
        * Search fields have Foreground: `#C3C3C3`, Background: `#FFFFFF`, The contrast ratio is: 1.8:1
        * Pagination links have Foreground: `#D0D3D7`, Background: `#FFFFFF`, The contrast ratio is: 1.5:1 
        * Filter textboxes / sort / results per page have Foreground: `#BFC4CE`, Background: `#E8EBF3`, The contrast ratio is: 1.5:1
    * (ID 469476) **On Browse by Author**, in two places:
         * First, on the textbox that says "Type the first 2 letters...".  When that textbox is focused, it has Foreground: `#D0D3D7` (focus indicator color), Background: `#FFFFFF`, The contrast ratio is: 1.5:1
         * Second, on the gear button (dropdown where "Results per page" and "Sort options" are visible). When the gear button is focused, it has Foreground: `#C5C5C5` (focus indicator color), Background: `#FFFFFF` (outer background), The contrast ratio is: 1.7:1
             * _ALSO occurs on Community Homepage, so this should be fixed in a general location._ See also ID 471648
2. **"State of an active component lacks 3:1 contrast ratio."**
    * (IDs 471036, 471060) **On Item page:** the "Full Item page" button.  When this button is in focus, it doesn't have enough color contrast. The state of an ACTIVE user interface component color : `#A1A8AF`, Background: `#FFFFFF`, The contrast ratio is: 2.4:1
    * (ID 471433) **On Collection Edit:** When in focus (tabbed via keyboard), several buttons/fields do not have at least a 3 to 1 luminosity contrast ratio with either the inner or outer adjacent background.
        * All text input fields (Name, Intro text, short description, etc): The state of an ACTIVE user interface component color: `#D0D3D7`, Background: `#FFFFFF`, The contrast ratio is: 1.5:1.
        * Delete (for item template) & back button and delete icon (for uploaded collection logo): The state of an ACTIVE user interface component color: `#EAAFAF`, Background: `#FFFFFF`, The contrast ratio is: 1.9:1.
        * Edit button (for item template) & Save button: The state of an ACTIVE user interface component color: `#AFB5BB`, Background: `#FFFFFF`, The contrast ratio is: 2.1:1.
    *  (ID 470955, 470950) **On Item Edit, "Bitstreams" tab** several buttons are affected in different scenarios
        * Green Upload button, on focus (tab via keyboard): Focus indicator color: `#BDD998`, Adjacent background color: `#E9ECEF`, Contrast ratio: 1.3:1
        * Green Upload button, on hover: Icon color: `#FFFFFF`, Adjacent background color: `#92c642`, Contrast ratio: 2:1. 
        * Yellow Undo button (after editing a row), on focus (tab via keyboard): Focus indicator color: `#EFAF7F`, Adjacent background color: `#F2CBCB`, Contrast ratio: 1.3:1
        * Yellow Undo icon (after editing a row), on hover: Icon color: `#FFFFFF`, Adjacent background color: `#EC9433`, Contrast ratio: 2.4:1. 
        * Download & Edit icons, on focus (tab via keyboard): Focus indicator color: `#A1A8AF`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2.4:1
        * Delete icon, on focus (tab via keyboard): Focus indicator color: `#E7A1A1`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2.1:1
    * (ID 471049) **On Item Edit, "Bitstreams" tab:** the top & bottom "global" buttons (above & below the bitstream table) -- Upload, Discard, Back.
        * Green upload button: Focus indicator color: `#D0E7AE`, Adjacent background color: `#92C642`, Contrast ratio: 1.5:1
        * Red discard button: Focus indicator color: `#EAAFAF`, Adjacent background color: `#CF4444`, Contrast ratio: 2.5:1
        * Back button (at bottom): Focus indicator color: `#BBBBBB`, Adjacent background color: `#FFFFFF`, Contrast ratio: 1.9:1
    * (IDs 471435, 471436, 471437) **On Item Edit,"Metadata" tab:** all buttons
        * Edit Icon on focus (tab via keyboard) does not have at least a 3 to 1 luminosity contrast ratio with either row background.  
            * Focus indicator color: `#A1A8AF`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2.4:1
            * Focus indicator color: `#A1A8AF`, Adjacent background color: `#E8EBF3`, Contrast ratio: 2:1
        * Delete icon on focus (tab via keyboard) does not have at least a 3 to 1 luminosity contrast ratio with either row background. 
            * Focus indicator color: `#E7A1A1`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2.1:1
            * Focus indicator color: `#E7A1A1`, Adjacent background color: `#E8EBF3`, Contrast ratio: 1.8:1
        * Stop editing (checkmark after edit is clicked) icon on focus (tab via keyboard) does not have at least a 3 to 1 luminosity contrast ratio with either row background.
            * Focus indicator color: `#C8E2A0`, Adjacent background color: `#FFFFFF`, Contrast ratio: 1.4:1
            * Focus indicator color: `#C8E2A0`, Adjacent background color: `#E8EBF3`, Contrast ratio: 1.2:1
        * Stop editing (checkmark after edit is clicked) _on hover_ contrast ratio is not at least 3 to 1
            * On hover: Icon color: `#FFFFFF`, Adjacent background color: `#92C642`, Contrast ratio: 2:1
        * Undo icon (shown after edit is clicked) on focus (tab via keyboard) does not have at least a 3 to 1 luminosity contrast ratio with either row background. 
            * Focus indicator color: `#F5C999`, Adjacent background color: `#FFFFFF`, Contrast ratio: 1.5:1
            * Focus indicator color: `#F5C999`, Adjacent background color: `#E8EBF3`, Contrast ratio: 1.3:1
            * Focus indicator color: `#F5C999`, Adjacent background color: `#F2CBCB`, Contrast ratio: 1:1
        * Undo icon (shown after edit is clicked)  _on hover_ contrast ratio is not at least 3 to 1
            * On hover: Icon color: `#FFFFFF`, Adjacent background color: `#EC9433`, Contrast ratio: 2.4:1
    * (ID 471468) **On Item Edit, "Metadata tab:** green "Add" button at top of page, when in focus
        * Focus indicator color: `#D0E7AE`, Inner Adjacent background color: `#92C642`, Contrast ratio: 1.5:1
        * Focus indicator color: `#D0E7AE`, Outer Adjacent background color: `#FFFFFF`, Contrast ratio: 1.3:1
    * (ID 471069) **On Item Edit, "Status" tab:** on all buttons (Authorizations, Mapped Collections, Withdraw, Make it private, permanently delete, etc). Also includes the "<-Back" button at the bottom. 
        * When the button is in focus (tabbed to via keyboard), the component does not have at least a 3 to 1 luminosity contrast ratio. The state of an ACTIVE user interface component color: #A0A7AE, Background: #FFFFFF, The contrast ratio is: 2.4:1.
    * (ID 470027) **On Submission form:**  the "I confirm the license above" checkbox doesn't have a 3 to 1 luminosity contrast ratio when it is in the *unchecked* state. Unchecked state: Foreground: `#ADB5BD`, Background: `#FFFFFF`, The contrast ratio is: 2.1:1
    * (ID 470749) **On MyDspace page:** on the red "Delete" button which appears next to in progress submissions.  Currently, it doesn't have enough contrast when it is in focus (e.g. when tabbing to it via keyboard): Focus indicator color: `#EAAFAF`, Inner Adjacent background color: `#CF4444`, Contrast ratio: 2.5:1
    * (ID 470069) **On Browse Community/Collection:** (this occurs on each of the expand/contract icons/chevrons).  The state of an ACTIVE user interface component color: `#D0D3D7`, Background: `#FFFFFF`, The contrast ratio is: 1.5:1.
    * (ID 470961, 471648) **On Community/Collection Homepage** 
        * in pagination links: state of an ACTIVE user interface component color: `#D0D3D7`, Background: `#FFFFFF`, The contrast ratio is: 1.5:1
        * on the gear button (dropdown where "Results per page" and "Sort options" are visible). When the gear button is focused, it has Foreground: `#C5C5C5` (focus indicator color), Background: `#FFFFFF` (outer background), The contrast ratio is: 1.7:1
3. **"An icon lacks 3:1 contrast ratio"**
    * **On Item Edit, "Bitstreams" tab: several buttons affected:**
        * (ID 470948) Green Upload button: Default Icon color: `#92c642`, Adjacent background color: `#E9ECEF`, Contrast ratio: 1.7:1. 
        * (ID 470957) Yellow Undo icon (after editing a row) : Default Icon color: `#EC9433`, Adjacent background color: `#F2CBCB`, Contrast ratio: 1.6:1.  
        * (ID 470959) Drag icon (on left side, used to reorder) lacks 3 to 1 color contrast *after* clicking/activating the Delete button (i.e. once the row has turned red).  Icon color: `#959595`, Adjacent background color: `#F2CBCB`, Contrast ratio: 2:1
            * NOTE: This might also be fixed by just disabling the ability to reorder a deleted row, as that concept doesn't make sense anyways.
    * (ID 471436) **On Item Edit, "Metadata" tab**:
        * Stop editing (checkmark after edit is clicked) default contrast ratio is not at least 3 to 1 with different row backgrounds
            * Icon color: `#92C642`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2:1
            * Icon color: `#92C642`, Adjacent background color: `#E8EBF3`, Contrast ratio: 1.7:1
        * Undo icon (shown after edit is clicked)  default contrast ratio is not at least 3 to 1 with different row backgrounds
            * Icon color: `#EC9433`, Adjacent background color: `#FFFFFF`, Contrast ratio: 2.4:1
            * Icon color: `#EC9433`, Adjacent background color: `#E8EBF3`, Contrast ratio: 2:1
            * Icon color: `#EC9433`, Adjacent background color: `#F2CBCB`, Contrast ratio: 1.6:1
    * (ID 469768) **On Submission form:** on the Success/Failure popup messages that appear after uploading a file.  Specifically the "x" (close button) doesn't have proper contrast.
        * In Upload successful, Icon color: `#9BAE7E`, Background: `#E9F4D9`, The contrast ratio is: 2.1:1
        * In Upload failed, Icon color: `#B17F7F`, Background: `#F5DADA`, The contrast ratio is: 2.6:1
        * NOTE: This issue obviously would also exist wherever these success/failure popups are shown, so it should be fixed in a general location.
    * (IDs 469929, 469996, 470005) **On Submission form:** in several other areas:
        * draggable icon (for reordering values, to left of value): Foreground: `#959595`, Background: `#FFFFFF`, The contrast ratio is: just below 3:1 (2.995:1)
        * orange exclamation status (on right side of section header): Foreground: `#FFFFFF`, Background: `#EC9433`, The contrast ratio is: 2.4:1
         * green check status (on right side of section header): Foreground: `#FFFFFF`, Background: `#92C642`, The contrast ratio is: 2:1
         * open/close arrows/chevron (on right side of each section header): Foreground: `#8CB7C8`, Background: `#F7F7F7`, The contrast ratio is: 2:1
         * Close button (x) in info message in Upload file section: Icon color: `#72919D`, Background: `#D2E4EA`, The contrast ratio is: 2.6:1
         * Green save icon (when editing an uploaded file): Foreground: `#92C642`, Background: `#FFFFFF`, The contrast ratio is: 2:1
         * Orange cancel icon (when editing an uploaded file):  Foreground: `#EC9433`, Background: `#FFFFFF`, The contrast ratio is: 2.4:1
    * (IDs: 469008, 469013) **On Search Results:**  occurs two places on the date sliders (the draggable sliders themselves). 
        * First, the draggable gray bars don't have a contrast ratio of 3 to 1 against adjacent colors.  Foreground: `#D9D9D9`, Background: `#FFFFFF`, The contrast ratio is: 1.4:1
        * Second, when dragged, the white/empty bar that appears doesn't have enough contrast with the green. Foreground: `#FAFAFA` (white shade), Background: `#92C642` (green), The contrast ratio is: 1.9:1
        * Third, the draggable gray bar doesn't have enough contrast with the green. Foreground: `#D9D9D9` (grey line indicating value min and max), Background: `#92C642` (green color), The contrast ratio is: 1.4:1
    

Full list of issues is viewable at (requires login): https://axeauditor.dequecloud.com/test-run/0856438a-a19a-11eb-bc31-b7d5be387c86/issues?activeTab=dt-issue&page=0&pageSize=50&sortField=ordinal&sortDir=asc&filter%5Bidentifier%5D%5B0%5D=1.4.11.c&filter%5Bidentifier%5D%5B1%5D=1.4.11.b&row=9

## More Information / Tools

* Consider using [Deque's free Chrome plugin](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US) to check your work
* Deque's color contrast tool: https://dequeuniversity.com/rules/axe/4.1/color-contrast?application=axeAPI

**Comment by tdonohue** [comment]
@artlowel : Per your suggestion in #1183, I've grouped all the "non-text" color contrast issues into this ticket.  It may be a bit larger than you anticipated, as it doesn't *just* deal with white backgrounds, and it also contains contrast issues with icons.  So, I'm assigning this to you for reanalysis/estimation, as I suspect it may be larger than the original 3 hours you estimated previously.

**Comment by michdyk** [comment]
@tdonohue Could you assign me to this issue? My team and I have investigated the accessibility of the system recently, so I guess it will be great to have done this task until we are fresh after our initial analysis.

**Comment by tdonohue** [comment]
@michdyk : Please feel free to work on this task and the others you asked to claim.  Keep in mind there are a large number of small issues listed in this ticket.  It's possible some have already been addressed (even accidentally) in more recent code.. so I'd recommend first re-verifying any of the issues you work on.

**Comment by michdyk** [comment]
@tdonohue please assign my colleague @Dawnkai to this task. He is going to provide the PR for this issue. Also when it will be accepted, I kindly ask to give credits for this bug fix contribution to PCG Academia. Thanks

**Comment by tdonohue** [comment]
@michdyk : I cannot add @Dawnkai as he is not a member of this project.  If @Dawnkai will be an ongoing contributor, I can add him to the `dspace-angular` project.  Let me know if you prefer that.

However it is also OK for you to keep this task claimed for yourself but have @Dawnkai work on the PR.  The assignee on issues is only meant to be a _person to contact_ if we have questions.  It does *not* need to be the person who will submit the PR.  Since you are already the assignee, no one else will work on this without contacting you / PCG Academia.

Thanks in advance for the work on this ticket & the other accessibility tickets you have claimed!  I look forward to the PR!  Keep in mind, if you want this to be potentially included in 7.6.1, we'd appreciate a PR soon (or break the work up into several PRs).  We are hoping to get 7.6.1 released by early to mid November.  So, to have time to review for 7.6.1, we would need PRs to ideally be created in October (or as soon as possible).

(I'm only adding this comment to this ticket.  But, the answer is the same for your same comments on #1149, #1159, #1161, and #1163 ... which are all already assigned to you / PCG Academia)

**Comment by michdyk** [comment]
@tdonohue: Thanks for that information. I will add the PR for that request today. However, after careful consideration, we need to add the PR for all accessibility tasks without separation on each task. All of them are strongly connected to each other and in some cases, they are duplicated in tasks #1149 #1159 #1161 #1163. That is why I recommend assigning a reviewer to all these tasks together.

**Comment by tdonohue** [comment]
@michdyk : That's perfectly OK to submit as a single PR when issues are strongly connected.  We will assign reviewers on the PR itself.  I already gave the PR a very quick code review as I saw some misunderstandings in the code itself.  Hopefully that gives good initial feedback and we'll work on finding more testers/reviewers.
