### ISSUE TITLE
Creating a new submission should redirect to workspaceitem edit page

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1205]
**Is your feature request related to a problem? Please describe.**
When the user create a new submission it's redirected to the submit page (`/submit`). This sometimes generates some problems when the user refreshes the page and finds a totally new submission instead the current already started.

**Describe the solution you'd like**
The solution could be to redirect directly to the workspaceitems edit page after the new submission is generated.

**Comment by atarix83** [comment]
@tdonohue  the solution ca be implemented in 1 hour

**Comment by tdonohue** [comment]
@atarix83 : Sounds good and reasonable. I'll move this over to the 7.0 board, label this as `medium priority` and assign to you for your team to work on. Thanks!
