### ISSUE TITLE
Improve error handling during submission

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1206]
**Is your feature request related to a problem? Please describe.**
The error handling of the submission form is not always aligned between the form error state and the errors present in the workspaceitem object, this can cause the icon status of the submission form sections does not always represent the errors status.
It happens for example when the validation of a form's field is triggered on blur. the error is shown on the field but the sections status icon does not reflect the presence of an error
![Schermata da 2021-05-25 18-52-25](https://user-images.githubusercontent.com/2486489/119543581-17139900-bd91-11eb-9ec8-056d31e2e779.png)

**Describe the solution you'd like**
In case submission's section form the section status icon should reflect the status of the form validation as well as the errors present in the workspaceitem object

**Comment by atarix83** [comment]
@tdonohue we've already resolved the issue for dspace cris 7 taking 34 hours. We can estimate porting and manage of PR in about 4/8 hours

**Comment by tdonohue** [comment]
@atarix83 : That sounds reasonable.  I'll move this into 7.0, but I'm going to label it as `medium priority` as the current behavior is problematic, but we could deal with it in 7.0 (if the port or review of the code takes longer).  Assigning back to you for your team to work on
