### ISSUE TITLE
positioning of buttons in the submission form

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1207]
**Is your feature request related to a problem? Please describe.**
After tests on the submission form, we have received feedback on the following usability problems : 

- the position of the discard button, together with all other buttons, generate confusions because it seems the main operation
- not all users can really understand why sometimes the save button is disabled

**Describe the solution you'd like**
Regarding the first problem the solution should be to place the discard button, as the previous versions, on the left in the button bar separated from the other ones.
Regarding the second issue the solution could be to add a text, next to the save button, that represents the saving status of the submission, like it happens while using Google documents or office. So the text could indicate when submission is saving, if all is saved or there are pending changes

**Comment by atarix83** [comment]
@tdonohue the estimation for the changes is about 3 hours

**Comment by tdonohue** [comment]
@atarix83 : Makes sense. I'll move this into the 7.0 board, but labeling as `low priority` for now.  This doesn't seem like it has to be fixed in 7.0, but it'd be nice to get to if we find time.
