### ISSUE TITLE
cclicense panel doesn't work

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1208]
**Describe the bug**
The cclicense panel doesn't work. Once a license has been selected a loading icon will stay on the screen, no error are reported to the user and the data are not saved

**To Reproduce**
1. enable the cclicense step
2. try to use it

**Expected behavior**
The selected cclicense should be saved

**Related work**
The error is due to the change in the link name agreed in https://github.com/DSpace/DSpace/issues/2890

Indeed this is the error that appear in the console
``` 
doesn't contain the link submissioncclicenseUrl-search
    at MapSubscriber.project (hal-endpoint.service.ts:71)
    at MapSubscriber._next (map.js:29)
    at MapSubscriber.next (Subscriber.js:49)
    at MapSubscriber._next (map.js:35)
    at MapSubscriber.next (Subscriber.js:49)
```
as the link name now is submissioncclicenseUrls-search (based on the plural form)

**Comment by tdonohue** [comment]
Thanks @abollini .  This sounds like a high priority issue to bring into 7.0 (especially since it's a quick fix).
