### ISSUE TITLE
Detail page for an item without fulltext is broken

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#121]
If an item doesn't have bitstreams in the original bundle, a blank page is shown.

I have reinstated an item on the public REST demo so to have a test item that can be used to work on this bug
http://dspace7.4science.it/dspace-spring-rest/api/core/items/6212604b-c778-42b3-88e4-cc3b1262ad28/bitstreams

**Comment by rivaldi8** [comment]
I'm no longer able to reproduce this issue. Has it been fixed?

**Comment by artlowel** [comment]
It seems like it. Most likely due to the angular 4 upgrade.
One thing that should still be fixed however, is that the "Files" header is still shown if there are no bitstreams
