### ISSUE TITLE
Thumbnail resolution should happen on the rest side

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1213]
**Is your feature request related to a problem? Please describe.**
Finding the correct thumbnail for an item or a bitstream is every slow at the moment, because it is done client side. The UI has to download the entire thumbnail bundle, ignoring pagination, to compare filenames with bitstreams in the ORIGINAL bundle and find a match.

We've never had much issues with this because we've never used DSpace 7 in a situation where we had a lot of items with a lot of bitstreams and thumbnails. If you do the performance becomes very poor in situations where you need to resolve multiple thumbnails quickly, e.g. the search result grid view.

**Describe the solution you'd like**
I created https://github.com/DSpace/DSpace/issues/3286 to get this issue addressed by adding optional `thumbnail` links to bitstreams and items. 

Afterwards we'll need to update the UI to make use of these links and to get rid of the old matching code

This can be done in an estimated **4 hours**

**Comment by tdonohue** [comment]
Thanks @artlowel .  I'm going to move both of these tickets (REST & Angular side) over into our 7.0 board with `medium priority`.  Currently though I'll leave unassigned until we have the REST side estimated, as I think that could impact whether we can fit this into 7.0 or not.
