### ISSUE TITLE
Pending json patch operations should be canceled when leaving the submission page

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1217]
**Describe the bug**
JSON patch operations are queued inside the json/patch feature of the ngrx store.
When the user leaves the submission page without saving, this pending json patch operations are not removed and could be commited on behalf of the user during possible following submissions.

**To Reproduce**
1. Start a new submission (ex. Publication)
2. Edit the author field (dc.contributor.author metadata). (new store state is shown below)
![deletependingpatchscreenshot](https://user-images.githubusercontent.com/63857/120002253-ecb21d80-bfd4-11eb-932b-2aad7e5f65d8.png)
3. Navigate to a different page (ex. My Dspace)
4. Start a new submission of the same kind
5. Edit the title field (dc.title) (new store state is shown below)
![deletependingpatchscreenshot2](https://user-images.githubusercontent.com/63857/120002283-f2a7fe80-bfd4-11eb-9fba-10648a9d1efd.png)
6. Save
7. The previous author value has been committed too.

**Expected behavior**
A submission shouldn't be affected by previous user's submission interactions.

**Comment by atarix83** [comment]
@tdonohue we've spent 3 hours to fix it and we can open the PR

**Comment by tdonohue** [comment]
@atarix83 : Sounds good. I'll move this over to the 7.0 board with `medium priority` and assign to your team.
