### ISSUE TITLE
Bug on repeatable qualdrop value

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1220]
**Describe the bug**
trying to delete a qualdrop fields with different metadata generates an error

**To Reproduce**
1. start a new submission with a qualdrop value field (e.g a publication has `Identifiers` field)
2. enter a new identifier
3. save submission
4. click add more to add a new identifier
5. select a different identifier than the one saved before
6. enter the new identifier
7. save the submission
8. click on the Trash icon to delete the last identifier added
9. save the submission an error message should be displayed

**Expected behavior**
The delete operation should be saved successfully

**Comment by atarix83** [comment]
@tdonohue it takes 1hour to fix, I can include fix directly in the current #1201

**Comment by tdonohue** [comment]
@atarix83 : Sounds good. Moving onto the 7.0 board. Feel free to fix in 1201
