### ISSUE TITLE
Workflow rejection reasons are not properly encoded

### ISSUE THREAD

**Issue by bruno-atmire** [DSpace/dspace-angular#1224]
**Describe the bug**
When an item is rejected in the workflow, the user has the option to provide a rejection "reason". That "reason" is not properly encoded when it is sent to the backend. In particular, the ampersand character causes the remainder of the message to be "ignored".
I was able to reproduce the bug on https://demo7.dspace.org/. [The bug is located here](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/data/request.service.ts#L268).

**To Reproduce**
1. Set up a collection and assign yourself to the reviewers group (default DSpace workflow)
2. Add a new item to that collection
3. Reject the item and add special characters to the reason, e.g. `&`, `@`...
4. Submit the reason
5. Observe that the body of the POST request contains the specified reason, up until the first ampersand. Also observe that additional properties are sent that should not be present.
6. Submit the item again and this time accept it
7. Observe that in `dc.description.provenance`, the "rejection reason" is incomplete.

**Expected behavior**
The rejection reason should be encoded properly, such that it cannot be interpreted as a form parameter. Then the POST request will contain the complete message, and so will the provenance value. No changes are needed to the backend.

**Comment by benbosman** [comment]
@tdonohue this should be doable with 1 hour of work

**Comment by tdonohue** [comment]
Thanks @benbosman and @bruno-atmire for getting this added. I'll pull this into the 7.0 board with `medium priority` and assign to your team. That said, please do feel free to work on this once `high priority` tickets are all completed/in progress, as it seems like something that'd be good to fix in 7.0
