### ISSUE TITLE
Deposit license in submission is reset because of page-changes

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/dspace-angular#1229]
**Describe the bug**

During the submission, even for a codebase that is [completely default DSpace](https://demo7.dspace.org/), when you tick the licence and fill a metadata and/or a upload a file afterwards, the licence gets unticked.

**To Reproduce**
1. Start a submission
2. Fill in some metadata
3. Tick the 'I confirm the license above' box at the bottom of the page
4. Fill in some other metadata (or simply click a text box, you don't even need to change anything)
5. The checkbox is unticked again

**Expected behavior**
The actual page-changes to the submission should not 'revert' the ticking of the checkbox mentioned above.

**Comment by tdonohue** [comment]
@jonas-atmire : Thanks for reporting this. I've verified this is an existing bug, but I've also verified it's fixed by #1201 (which fixes several other similar submission bugs).  So, I'll link this up to #1201... thanks!
