### ISSUE TITLE
Labels in delete collection screen refer to community instead than collection

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1231]
**Describe the bug**
The confirmation message for a delete collection request talks about community instead than collection

Delete Community
Are you sure you want to delete community "Suspendisse pretium"

**To Reproduce**
1. visit the collection https://demo7.dspace.org/collections/d2ad146a-0f69-4cb2-9759-fddaf50a4651
2. try to delete it https://demo7.dspace.org/collections/d2ad146a-0f69-4cb2-9759-fddaf50a4651/delete

**Expected behavior**
The message should say Delete **Collection**. Are you sure you want to delete **collection** "..."

**Comment by tdonohue** [comment]
Thanks @abollini : I can reproduce this.  It's a typo in the UI (wrong i18n key is used).  I'll claim it and create a tiny PR shortly.
