### ISSUE TITLE
Switching submission collection between ones with different submission definitions doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1234]
**Describe the bug**
When during a submission with the collection step enabled, switching collection between ones with different submission definitions doesn't work. Indeed the submission form show an hanging loading icon after trying to switch collection.

**To Reproduce**
1. Configure two collections mapped to different submission definitions with the collection step enabled
2. Start a new submission with an user who have permissions to submit to both collections
3. Switch to the collection with different submission definition
4. Verify that submission form loads infinitely after the switch

**Expected behavior**
The submission should change collection and form should adapt to the different submission definition

**Comment by atarix83** [comment]
@tdonohue We have already resolved on DSpace-CRIS and we can create the PR immediatly. It took 1 hour

**Comment by tdonohue** [comment]
@atarix83 : This sounds like something we should fix in v7.0, so I've moved it to that board.  Flagging as "medium" priority. But, once your team is done with high priority tasks, feel free to create a PR.

**Comment by f-rapp** [comment]
Is the "change collection" action intended for workspace items only or for workflow items as well?
Changing the item's collection during workflow did not work:
![grafik](https://user-images.githubusercontent.com/67266996/134866349-325d8091-40bb-460c-a141-2b6240947bf0.png)
I was wondering if this was intended?

**Comment by atarix83** [comment]
@f-rapp 

it should work for the workflow as well.

if you're encountering any problem please open an issue

**Comment by f-rapp** [comment]
I opened an issue: https://github.com/DSpace/DSpace/issues/7965
