### ISSUE TITLE
Embargo date not saving properly during submission

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1256]
**Describe the bug**
When you attempt to select & save an embargo date in the submission form, the date selected is not saved.
This is reproducible locally and on https://demo7.dspace.org ... in both cases I'm using Chrome

**To Reproduce**
Video showing the behavior
https://user-images.githubusercontent.com/483997/123482592-07bf7f80-d5cb-11eb-8d6b-78091a3af178.mp4

1. Start a submission. Upload a file
2. Edit the bitstream, add an embargo date of `2021-07-31`. Click green save icon. Embargo date will be saved as `2021-07-30` (one day earlier)
3. Click Edit on same bitstream. In form, embargo date will now appear as `2021-07-29` (one day earlier again).  Click green save icon without making changes.  Now embargo date will be saved as `2021-07-28`.
4. If you continue step 3, the date keeps moving forward one day at a time.

**Expected behavior**
Obviously, embargo date should be saved correctly.

**Related work**
Discovered while testing #1201 .  Similar behavior also appears in #1233 when editing the embargo date on an archived item.

**Comment by tdonohue** [comment]
@atarix83 : Here's the embargo date issue that I'm seeing. Assigning to you for quick analysis. I've rated this `high priority` as I'd like to ensure it's fixed (assuming others can reproduce it) in 7.0, as it's important to have accurate embargo dates.

**Comment by tdonohue** [comment]
@atarix83 and @artlowel : Here's the `PATCH` request payload sent when I select `2021-07-31` (using the calendar tool *or* manually entered -- I tried both options and the PATCH request was the same each time):
```
[{"op":"add","path":"/sections/upload/files/0/metadata/dc.title","value":[{"value":"test_pdf.pdf","language":null,"authority":null,"display":"test_pdf.pdf","confidence":-1,"place":0,"otherInformation":null}]},{"op":"add","path":"/sections/upload/files/0/accessConditions","value":[{"name":"embargo","startDate":"2021-07-30T00:00:00Z"}]}]
```

As you can see above, the Angular UI is sending the wrong `startDate` to the REST API.  It is already changed to a day earlier `2021-07-30` (my expectation is it should be `2021-07-31T00:00:00Z`, since I selected `2021-07-31`). The time is zeroed out, so it doesn't seem to be a factor here.   That said, it still may be a time zone related issue...it just isn't clear to me why the UI code is time zone specific.

**Comment by tdonohue** [comment]
@atarix83 and @artlowel : I just searched our codebase for anything to do with timezone specific code, and I stumbled on this `dateToISOFormat` method: https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/date.util.ts#L30

I wonder if this is the cause...my selected date is being turned into a UTC date by the UI, which changes the actual *day* I selected.

**Comment by atarix83** [comment]
probably we are encountering in this issue

https://stackoverflow.com/questions/55829344/momentjs-getting-wrong-timestamp-from-date-in-a-different-timezone

we're using moment here
https://github.com/DSpace/dspace-angular/blob/de8e306d9ffe24ba512a469aff7aa247e08e7b7a/src/app/shared/date.util.ts#L48

**Comment by tdonohue** [comment]
@atarix83 : If that's the case, it looks like there's a simple fix...maybe we need to force that date to be UTC from the beginning, as it sounds like it defaults to local timezone. Would you be able to create a quick PR that I could test tomorrow?

**Comment by tdonohue** [comment]
@atarix83 : I played around with this a bit today, and I have a **partial solution**... I've figured out it DEFINITELY is a timezone issue.  I'm now certain of that.  However, there's *two issues* it seems:

1. First, when I select a date in the calendar or manually enter it, it decreases by one day in the PATCH request.  This appears to be a **UTC to local timezone conversion** issue.  The selected/entered date is assumed to be UTC time, and it is then converted to my local time before the PATCH is sent.  So, for example, if I select `2021-07-31` in the calendar, it is assumed to be UTC (`2021-07-31T00:00:00Z`), and then is transformed into my local time (I am -5:00 hours) which turns that date/time into `2021-07-30T19:00:00Z` which is then sent as `2021-07-30` (one day earlier) in the PATCH request.
    * **I've figured out how to fix this issue.** Here's [the commit](https://github.com/DSpace/dspace-angular/commit/7926ea7c864f9c7ac929e2495e4e9b579e17dfb7) that does it.  All I'm doing is making sure the `Date` object is ALWAYS working with UTC dates....it seems to default to wanting to convert things to local timezone.  **This commit ensures the proper PATCH is sent to the backend and saved on the backend**
2. Second, I've discovered there is a separate issue with **reading dates from the backend**.   If I use the above commit, it saves the correct date to my backend.  But, if I go back in and try to **edit** that Bitstream's embargo date, the date is **again** converted my local timezone (it appears something is parsing the correct date coming from the REST API, and again converting it into my local timezone, instead of leaving it as UTC).  This means that if the date comes from the REST API as `2021-07-31T00:00:00Z`, it ends up populated in the form field as `2021-07-30` again.

I've had difficulty figuring out how/where the date is parsed from the backend so that it can be populated in the form field.  That parsing seems to also be converting the date from UTC to local, when it should be kept as a UTC time. If you could either provide me a hint, or link to the code where this occurs, I think it's the last step to fixing this annoying bug.

**Comment by tdonohue** [comment]
Figured out the fix! https://github.com/DSpace/dspace-angular/pull/1262

**Comment by mwoodiupui** [comment]
Nice detective work.  I thought it smelled like a timezone issue.

IMHO the originally reported behavior is backwards:  by the principle of least surprise, the date entered by the user should be assumed to be local to the user's location (unless a zone is explicitly stated on the form) while the API should always use UTC and the repository should store UTC.  When reading dates back, the UI should receive UTC and convert to local.

It might actually be more useful for the date to be accepted and (explicitly!) presented in the repository's timezone rather than the user's.  That would require an endpoint for the UI to discover the repository's timezone.

I have never read any embargo agreements, though, so I wonder whether they are zoned.  It might be *most* useful to be able to specify the publisher's zone, regardless of where the submitter *or* the repository is located.  That level of complexity probably ought to be a future improvement, not a fix for 7.0.

But overall, I suggest that the UI accept and present a localized date while the backend stores UTC.

**Comment by tdonohue** [comment]
@mwoodiupui : what you are describing is the current behavior.  On `main`, the UI is accepting/presenting a localized date while the backend stores UTC.  This results in a very buggy experience with embargo dates. Here's an example:
1. Backend returns that an embargo is until `2021-07-31T00:00:00Z` (UTC time)
2. Frontend translates that to local time. For me, I'm at -5:00 hours, so it translates the embargo date to `2021-07-30T19:00:00Z`. 
3. Now, if I try to edit the embargo date in the Frontend, it changes it automatically to `2021-07-30` (as we don't use times for embargoes, it gets dropped).
4. If I make no changes but click save, it is sent to the backend as `2021-07-30`, which the backend assumes is UTC and translates to ` 2021-07-30T00:00:00Z` (UTC time).  I.e. the embargo date has accidentally moved forward a day.
5. If I repeat steps 3-4, it moves forward a day each time, as the backend assumes UTC, while the frontend is sending things in local time.

The only way I could find around this issue was to make *both* the frontend & backend always assume/use UTC (which is what this PR does), so that we do not hit time conversion issues.  

That said, longer term, we might be able to rethink this approach if embargo dates have a *time* associated with them (instead of always assuming 00:00:00) and/or the UI translates every date to UTC before sending it to the backend.  But, those scenarios are a bit more complex to accurately achieve, so I went for a simple solution of UTC everywhere for now.

**Comment by tdonohue** [comment]
@mwoodiupui : I think we are saying the same thing in different ways. Essentially, the embargo date field/selector (in the UI) currently isn't supporting datetime, so it simplifies everything to a date, and that doesn't work well when translating between timezones.

In any case, I think the only solution we can achieve in time for 7.0 is moving everything to UTC (i.e. PR #1262).  But, I do agree there may be a way to support a *localized* date in the frontend, **if** we can treat all dates as datetimes **and** they are all converted back to UTC before sending to the REST API.  But, those two tasks look like a lot of work (at a glance) & need some thorough testing. So, I think that work likely will need to wait for at least 7.1.
