### ISSUE TITLE
User groups inaccessible from the 'Assign Roles' tab - Edit Collection & Edit Community

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1257]
**Describe the bug**
A user group created in the 'Assign Roles' tab within the 'Edit Collection' module is inaccessible.  

**To Reproduce**
1. Go to the 'Edit Collection' by clicking on edit icon on the collection homepage.
2. Click on the Assign Roles tab
3. Click on Create button under any of the role
4. Click on the group link generated to access the group
5. Application will show 403 forbidden page
Please refer video walkthrough link below to reproduce the error

https://youtu.be/ibj1MXiAQH8 

**Expected behavior**
Clicking on the group link should take users to the group page for managing users.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
This will be fixed by https://github.com/DSpace/DSpace/pull/3293.  It seems I accidentally merged a front-end change too early, without the corresponding backend change. My apologies.  It'll be fixed as soon as the backend PR is merged.
