### ISSUE TITLE
Unable to edit group from Authorizations tab in Edit Collection & Edit Community

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1258]
**Describe the bug**
Unable to edit the user group using edit group button appearing next to the authorization policies listed in the Authorizations tab. Similar issue in the Edit Community as well.

**To Reproduce**
1. Click on the Edit button on the collection homepage
2. CLick on the Authorizations tab
3. Click on edit group appearing next to any policy
4. Application will take to 403 forbidden access page
Please refer to below link for the video walkthrough of above steps

https://youtu.be/2fuRiKKKJ24

**Expected behavior**
The application should have taken the user to the edit group page.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
This is the same bug as #1257 (just found in a different location). It will also be fixed by https://github.com/DSpace/DSpace/pull/3293

**Comment by DSquareTechnologies** [comment]
Identical issue found in the Edit Community section as well. Adding Community in the issue.
