### ISSUE TITLE
Unable to add/edit Users in the policy under Authorizations tab in Edit Collection & Edit Community

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1259]
**Describe the bug**
It is not possible to add or update users while trying to add any policy under the authorizations tab in the Edit Collection & Edit community section. Upon clicking the Edit policy button, there is no place for adding users.

**To Reproduce**
1. Click on the edit button on the collection home page
2. click on the authorizations tab
3. Click on the edit policy button available next to any policy
4. No option for adding/updating users to the policy
Please see below video walkthrough for above steps
https://youtu.be/Ui-7hNQSgLY

**Expected behavior**
List of Epeople/groups added in the policy should appear and provision for updating the list.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Can confirm this is an issue. The workaround for now is to simply create a new policy & delete the old one.  Currently, existing policies cannot be fully edited.

Scheduling this tentatively for 7.1 as I don't believe there's time to get this into 7.0.

**Comment by DSquareTechnologies** [comment]
Thanks Tim. These bugs are identified while preparing user manual for 7.0. Have updated the manual based on available functionality.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DSquareTechnologies** [comment]
Hi Tim,

Identical issue is with the community also. Updating Issue title from Collection to the Collection & Community.

**Comment by tdonohue** [comment]
Closing, this bug has been fixed.  I'm not sure when/where it was fixed, but is no longer reproducible in 7.5
