### ISSUE TITLE
Opening new tab from search result toggles truncatable

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1260]
**Describe the bug**
Opening an Item page in a new tab from a `<ds-item-search-result-list-element>` can toggle its `<ds-truncatable>` component

**To Reproduce**

1. Open [demo7.dspace.org/search](https://demo7.dspace.org/search?spc.page=1&query=dc.description.abstract:*&spc.sf=score&spc.sd=DESC&f.entityType=Publication,equals&scope=) and look for an Item with a truncated description
2. Open the Item's page in a new tab ~ `Right click > Open in new tab` on the title link
   * Behaves as expected
3. Open the Item's page in a new tab ~ `Middle click` or `Ctrl/Cmd + Left click` on the title link
   * The page opens in a new tab, but the `<ds-truncatable>` component is toggled at the same time

**Expected behavior**
The the `<ds-truncatable>` component should not get toggled when clicking on the title

**Comment by tdonohue** [comment]
Thanks for reporting @ybnd .  That said, this seems extremely minor to me (and unlikely to be encountered frequently)...but we may want to fix at some point. For now, putting this into 7.2

**Comment by tdonohue** [comment]
Closing, as this was fixed by #1619 / #1551 and the fix was included in 7.3
