### ISSUE TITLE
Downloading bistream during submission doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1265]
**Describe the bug**
Downloading bistreams for worksapceitems/workflowsitems doesn't work, indeed clicking on the download button presents on the upload section of the submission page does not lead to any result.
![Schermata da 2021-07-02 13-30-59](https://user-images.githubusercontent.com/2486489/124268730-3218bc00-db3a-11eb-9ba0-a10787cddc3c.png)

**To Reproduce**
1. create a new submission
2. upload a new file
3. try to download it by clicking on the download icon
4. nothing happens 

**Expected behavior**
it should allow to download the bitstream

**Comment by atarix83** [comment]
@tdonohue it tooks 1hour to fix, I've opened directly the PR because it was easy to fix and it can be reviewed quickly

**Comment by tdonohue** [comment]
Thanks @atarix83 : I've pulled this into the 7.0 board since it's tiny. I'll give the PR a test today & see if I can merge immediately.
