### ISSUE TITLE
Migrate e2e tests from Protractor to Cypress

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1274]
Angular has seemingly started to take a big step back from Protractor as newer (supposedly easier to use) e2e test solutions have become more widely used. 

> In light of this, we have decided not to include Protractor in new projects starting from version 12, and instead work with partners to integrate their solution with Angular CLI via schematic/builder to make sure the ng e2e command continues to work seamlessly. So far we have reached out and heard back from Cypress, TestCafe, and WebdriverIO. We will continue to expand our collaboration with other partners going forward (please reach out to us!).

Additionally

> The Angular team plans to end development of Protractor at the end of 2022 (in conjunction with Angular v15).

Source: https://github.com/angular/protractor/issues/5502#issuecomment-837432362 (see full issue ticket for lots more details).

I've also started to (anecdotally) see more and more mentions of migrating from Protractor to [Cypress](https://www.cypress.io/) for Angular projects.  Here's one longer blog post comparing the two: https://christianlydemann.com/why-i-moved-from-protractor-to-cypress/

While I have no strong opinions on what to migrate to, it's very obvious (by looking at our codebase) that Protractor is hard to build tests for...and we've occasionally hit fragility in those e2e tests, including frustrating errors that are harder to track down.

Therefore, this ticket is a placeholder for us to consider migrating to an easier to use platform.  At this time (as of 7.0), the migration would not be too complex, as we have very few e2e test (almost all of our tests are unit tests/specs).  But, if we move to a platform which is easier to work with, this may encourage the creation of more e2e tests, which can better detect when we accidentally break things (e.g. when we accidentally broke SSR and didn't realize it for several weeks, see #1273)

_Feedback welcome on this ticket, as it'll help me to better determine how to prioritize it._

**Comment by tdonohue** [comment]
NOTE: Cypress also has a nice GitHub Action which seems very configurable: https://github.com/cypress-io/github-action

**Comment by hardyoyo** [comment]
Consider me interested... I have spent the morning trying to get the e2e tests working in my local dev environment, and had to set it aside.
