### ISSUE TITLE
If there's no correlation ID cookie, server side rendering crashes

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1279]
**Describe the bug**
The log interceptor [gets the correlation ID from the cookie](https://github.com/DSpace/dspace-angular/blob/e9a03994e208e52337f32080d936997fef1b1dfc/src/app/core/log/log.interceptor.ts#L22) and [adds it as a request header](https://github.com/DSpace/dspace-angular/blob/e9a03994e208e52337f32080d936997fef1b1dfc/src/app/core/log/log.interceptor.ts#L26). However if you set a request header that's undefined, [HttpClient will crash when sending the request](https://github.com/angular/angular/issues/18743#issuecomment-323215006).

If it doesn't exist, a correlation ID is generated in [an APP_INITIALIZER function](https://github.com/DSpace/dspace-angular/blob/e9a03994e208e52337f32080d936997fef1b1dfc/src/app/app.module.ts#L136-L147), and stored as a cookie. But you can't store cookies server side, [that method isn't implemented](https://github.com/DSpace/dspace-angular/blob/e9a03994e208e52337f32080d936997fef1b1dfc/src/app/core/services/server-cookie.service.ts#L8-L10)

**To Reproduce**
- open an incognito window, or clear your cookies
- disable javascript
- open the dspace UI in prod mode
- It will keep loading forever

**Expected behavior**
- The correlation ID should be moved to the ngrx store 
- That initializer function should check if there's a cookie and init the store with it, if it exists, or generate a new one and put _that_ in the store if it doesn't
- The interceptor should get the value from the store
- The interceptor should check if the id exists before adding it as a header, to ensure we don't get undefined headers

That last part is the critical thing to get rid of the symptoms, so I'll create a small PR to add that check, and some better error logging for these kinds of issues. 

Until we fix the other parts, we won't get correlation IDs for the very first request of a client with JS, or for any request of a client without JS. 

The rest can be done in an estimated **3 hours** (moved to #1281)

I already spent **2 hours** on analysis. (this was the work done in #1280)

To prevent similar issues it may also be a good idea to remove the 'set' and 'remove' methods from the cookieservice interface, and implement them only on ClientCookieService. That way you need to be sure you're on the client before calling them. I tried throwing an exception when these methods are called server-side in my PR, but that happens a lot, so that would litter the logs with unnecessary warnings. 

**Related work**
Introduced by #1255

**Comment by tdonohue** [comment]
This ticket has been split into two:
1. Current 1279 ticket: re-scoped to **only fix** the immediate SSR bug, see #1280 
2 Additional `CORRELATION_ID` issues were moved to #1281 and rescheduled for 7.1
