### ISSUE TITLE
Old views stay visible when the route changes

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#128]
If you go to the "DSpace related records in PubMed Europe" collection, and click on a Recent Submission, the item view page opens, but the collection homepage doesn't disappear. The Item homepage is rendered above it.

If you keep clicking links afterwards this keeps happening, the new page opens above the old page.

This only seems to happen for that specific collection, and the bug was introduced with [the upgrade to Angular 4](https://github.com/DSpace/dspace-angular/pull/123).

![screen shot 2017-07-27 at 15 44 59](https://user-images.githubusercontent.com/1567693/28673353-91ec7e74-72e2-11e7-98ee-4f7c8e481961.png)

**Comment by wwelling** [comment]
Seems to only occur on /items/6212604b-c778-42b3-88e4-cc3b1262ad28

Solution structure of apamin determined by nuclear magnetic resonance and distance geometry

**Comment by wwelling** [comment]
https://dspace7-demo.atmire.com/collections/8e0928a0-047a-4369-8883-12669f32dd64

try clicking on 

Solution structure of apamin determined by nuclear magnetic resonance and distance geometry

**Comment by artlowel** [comment]
I found the issue, it was a preexisting bug. The symptoms have just changed due to the update. I'll open a PR soon

**Comment by wwelling** [comment]
Good to know. Symptoms seem less severe after the upgrade.
