### ISSUE TITLE
DSpace UI Issue

### ISSUE THREAD

**Issue by unibravo** [DSpace/dspace-angular#1291]
Not Home Banner Image and Login panel the page https://repository.myuni.edu.
The page is not fully loaded https://repository.myuni.edu/home

in Browser Console:
No _links section found at https://repository.myuni.edu/server/api
hal-endpoint.service.ts:42

**Comment by artlowel** [comment]
That likely means your rest sever can't be reached. What do you see if you go to the url in the "No _links section found" error message?

**Comment by tdonohue** [comment]
Closing this ticket as answered.  As this same "No _links section found" error has been encountered by several people on lists & in Slack, I've added it to our "Common Installation Issues" at https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-%22No_linkssectionfoundat...%22errorfromUserInterface
