### ISSUE TITLE
Input fields in "Edit group" form that should be disabled by default are instead editable (until the page is refreshed)

### ISSUE THREAD

**Issue by davidenegretti-4science** [DSpace/dspace-angular#1296]
**Describe the bug**
In "Edit group" page the fields "Group name" and "Description" should be disabled if the group is permanent. When the page is accessed through the group list in ([access-control/groups](https://demo7.dspace.org/access-control/groups)) the fields are editable. If the page is accessed through its link, or is reloaded, the fields are disabled as expected.

**To Reproduce**
1. Log in as administrator
2. Go to page "Access Control > Groups"
3. Edit a permanent group (e.g. the one named "Administrator"): the fields will be editable
4. Refresh the page: the fields will be disabled

**Expected behavior**
Aforementioned fields should be disabled when the page is reached from the group list

**Comment by tdonohue** [comment]
I'm able to reproduce this locally.  The Group cannot be edited (result is a failure), but the name field is not disabled properly on the first page load. 

This seems low priority, but I'd welcome a PR to fix it.  It also might be fixable as part of other work, for example in the #1298 open PR from @davidenegretti-4science

**Comment by alemarte** [comment]
@tdonohue it seems that this issue is not reproducible anymore (maybe after upgrading the dynamic form library). Tested today on the Demo.

**Comment by tdonohue** [comment]
@alemarte : Thanks for the note. I agree, this is no longer reproducible.

Closing as fixed.
