### ISSUE TITLE
DSpace 7 - Profile page renders a blank page with no errors when using the custom theme

### ISSUE THREAD

**Issue by HunterBlacker** [DSpace/dspace-angular#1308]
In the custom theme, the [profile-page.component.ts](https://github.com/DSpace/dspace-angular/blob/main/src/themes/custom/app/profile-page/profile-page.component.ts) styleUrls and templateUrls point back to the custom theme's directory with the empty scss and html files which is unlike every other component class file.
```
@Component({
  selector: 'ds-profile-page',
  styleUrls: ['./profile-page.component.scss'],
  templateUrl: './profile-page.component.html'
})
```
To be consistent with the other component classes in the custom theme, I updated the component class file to refer to the profile-page components in the src/app/profile-page directory instead.
```
@Component({
  selector: 'ds-profile-page',
  // styleUrls: ['./profile-page.component.scss'],
  styleUrls: ['../../../../app/profile-page/profile-page.component.scss'],
  // templateUrl: './profile-page.component.html'
  templateUrl: '../../../../app/profile-page/profile-page.component.html'
})
```
However, this would not compile because the 'ds-profile-page-metadata-form' is not exported in the module.
```
ERROR in src/app/profile-page/profile-page.component.html:7:9 - error NG8001: 'ds-profile-page-metadata-form' is not a known element:
1. If 'ds-profile-page-metadata-form' is an Angular component, then verify that it is part of this module.
2. If 'ds-profile-page-metadata-form' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
The fix for this was to add the ' ProfilePageMetadataFormComponent' to the exports in the ' [profile-page.module.ts](https://github.com/DSpace/dspace-angular/blob/main/src/app/profile-page/profile-page.module.ts)' component.
```
@NgModule({
  imports: [
    ProfilePageRoutingModule,
    CommonModule,
    SharedModule
  ],
  exports: [
    ProfilePageMetadataFormComponent,
    ProfilePageSecurityFormComponent
  ],
  declarations: [
    ProfilePageComponent,
    ThemedProfilePageComponent,
    ProfilePageMetadataFormComponent,
    ProfilePageSecurityFormComponent
  ]
})
```

**Comment by tdonohue** [comment]
@artlowel : This sounds like a bug in the `custom` theme template.  Could you take a look?  If it is a bug, it seems like something to fix quickly in 7.1.  Thanks!
