### ISSUE TITLE
T048 Non-compliance: item page rendering breaks for bitstream names +45 characters without spaces

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#1313]
**Describe the bug**
DSpace 7.0

When bitstream file names get longer than 45 characters, without spaces, the rendering of the filename breaks into the metadata right column

**To Reproduce**
1. Add a bitstream with filename +45 characters (no spaces in filename) to an item
2. Watch the rendering of the bitstream name and link on the item page

**Expected behavior**
The fact that the bitstream has a long filename should not break the rendering of the page

**Related work**
T048 in the public test plan at https://docs.google.com/spreadsheets/d/1BdK8SzytA7HoxOZgldCIHabMxeR4mYTXt_ynVT_-KR8/edit#gid=1865680815

**Comment by SufiyanShaikhPeerbits** [comment]
Rendering of the bitstream name with 45+ characters with no spaces is showing correctly in current code.
Check this item [https://demo7.dspace.org/items/96081ac6-aa50-4ce9-b071-d231940b2bb9](https://demo7.dspace.org/items/96081ac6-aa50-4ce9-b071-d231940b2bb9)

**Comment by tdonohue** [comment]
@SufiyanShaikhPeerbits : Thanks for letting us know this appears to be fixed!  I'll close the ticket as fixed.  (I'm not sure when exactly this was fixed, but it definitely does work in 7.4)
