### ISSUE TITLE
edit item metadata not working when changing metadata field name

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1317]
**Describe the bug**
This is a bug shown Edit Item page.
It is related with edition of the metadata of an item, concretely, with the edition of the field of the metadata related with an item.
When the user tries to edit the field of one of the metadatas, with which it is related, an error is shown with popup in the edit item page. 

**To Reproduce**
1. The first step is going into Menu → Edit → Item → Selecting an item from popup list of items. 

![image-20210824-095956](https://user-images.githubusercontent.com/70699836/133603307-23e5e71e-b53e-4988-bafa-c87a706dd886.png)
![image-20210824-100124](https://user-images.githubusercontent.com/70699836/133603302-43ef02f4-a02a-4d11-a5e7-63be86a43de6.png)

2. In the Edit Item page, select the third option “Metadata“ to work with.

![image-20210824-100336](https://user-images.githubusercontent.com/70699836/133603352-574ff026-853c-403e-8339-8ffcfa39dfa4.png)

3. Click button edit (the first button) in the section Edit of the table (the last column) for one of the rows. 

![image-20210824-100531](https://user-images.githubusercontent.com/70699836/133603910-e86fb2c6-8f64-4b75-af8c-15a9a5d972a2.png)

4. Try to edit the first column → named “Field“ (representing the metadata field) and replace it with another metadata field, for example replace dc.description with person.identifier.orcid. After that click check button (the first button in the last column with check sign). 

![image-20210824-100736](https://user-images.githubusercontent.com/70699836/133603494-5c782be5-42a2-4a75-939e-b6a77a6e61a3.png)

5. After check button, click Save button shown above, in blue color. Change won't be saved and a popup error will appear

![image-20210824-101128](https://user-images.githubusercontent.com/70699836/133603537-570e90fa-cb12-445f-8880-c9a59e581b06.png)

In the console is shown this request  sending a replace operation with the new metadata field set by the user, as it is shown in images below (the request and the error thrown  by the server):

![image-20210824-101417](https://user-images.githubusercontent.com/70699836/133603719-6573f391-c99f-4bbe-9077-435fb31466b2.png)
![image-20210824-101330](https://user-images.githubusercontent.com/70699836/133603724-5fd2bc7b-9e0a-4794-8549-1640a9e10a77.png)

**Expected behavior**
Is expected that after edition of the metadata field,  the metadata related with this item should be changed successfully  and must be related with the new field replaced by the user.  

A popup of confirmation should be shown in the edit item page as it is shown below, as an example. Also in the table (in the row edited) must be shown the row of the metadata edited,  containing in the first column,  the new field replaced by the user. 

We (4Science) can take in charge the fix of this bug, with two different approaches: 

1. block the possibility of editing metadata field name by disabling it (and removing angular code triggered when metadata field name is changed) 
OR
2. Handle the metadata field name change. When metadata field name changes:  i) a  remove is performed for the metadata which field is being changed, in case of repeated metadata only metadata in position (place) related to field being changed should be removed, and then an add in append (“/new-metadata/-”) for the new metadata  is performed.

First approach would roughly require 6 to 8 hours, including tests, while the second 12 to 16 hours.

**Comment by tdonohue** [comment]
@corrad82-4s : I'd recommend the **first approach** for this bug.  I think we should block the ability to edit the metadata field (either by disabling it, or removing the input field altogether, so it's just text).   So, I'll add a **7 hour** estimate to this and assign back to you for 4Science to work on.  Thanks!
