### ISSUE TITLE
Reload of My Dspace results is broken

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1320]
**Describe the bug**
Reload of My Dspace results is broken.

**To Reproduce**
1. Go to the MyDspace page and select **Task**
2. Perform an action which cause a state transition (ex **Claim** a task)
3. The row of the my dspace disappears

**Expected behavior**
The reloaded object should appear in place of the previous one.

**Comment by alemarte** [comment]
4Science can immediately work on this issue. Estimated 2 hours

**Comment by tdonohue** [comment]
Thanks @alemarte !  I'll assign this back to you to proceed with the fix.  I've added the estimate as well.
