### ISSUE TITLE
Can't change embargo resource policy on bitstream to open access during submission

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1337]
**Describe the bug**
When you add an embargo resource policy to a bitstream during submission and save, but during the same submission later change the embargo selected to open access and save then that patch/action fails because the start date previously set for the embargo is also passed along in the patch despite the start date being grayed out when you change the option to open access. (From Log: `Caused by: java.lang.IllegalStateException: The access condition openaccess cannot contain a start date.`)

**To Reproduce**
1. Go to an item in submission (or submit new item), add a bitstream
2. Edit the bitstream and add an embargo on the bitstream with a start date, save it ([example workspace item](https://demo7.dspace.org/workspaceitems/4242/edit))
3. Edit the same bitstream again and change the embargo resource policy to open access and save it
4. This patch fails (`{"op":"add","path":"/sections/upload/files/0/accessConditions","value":[{"name":"openaccess","startDate":"2024-06-01T02:00:00Z"}]}]' \`) => Contains startDate and openaccess, not allowed combination

**Expected behavior**
Should be able to change the embargo resource policy on a bitstream to open access. When the option is changed and the start/end dates are greyed out depending on the option, then those start/end date parameters should not be sent along with the RP replace patch.

**Comment by abollini** [comment]
@tdonohue estimation 2 hours, you can assign to us if you wish

**Comment by tdonohue** [comment]
Thanks @abollini ! Added estimate & assigned to @atarix83

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977
