### ISSUE TITLE
Display full hierarchy of chosen collection (during submission/workflow)

### ISSUE THREAD

**Issue by f-rapp** [DSpace/dspace-angular#1340]
**Determining which collection an item was submitted to (during submission/workflow)**
It is essential that users can see which collection a workspace / workflow item was submitted to during the submission process. While they see the collection's name, they do not see the hierarchy, e.g. the community the collection belongs to. Since collection names often occur more than once, this is a problem.
For example, editors who need to check whether the collection was choosen rightly by the submitter cannot easily do this.

![grafik](https://user-images.githubusercontent.com/67266996/135402706-efd6d594-18be-4249-8c72-96b3211d2f38.png)

**Describe the solution you'd like**
Similar to the dropdown where users can see the community the collection belongs to, it would make sense to show this for the current owning collection as well. I suggest that the *full* hierarchy is displayed (or presented via mouseover), since it is possible that it is not enough to display only the collection and one hierarchy level above. There may be identical names as well.

![grafik](https://user-images.githubusercontent.com/67266996/135403105-81fd2b2d-351b-4cf2-9c89-7eb1845140c1.png)

**Comment by f-rapp** [comment]
Would this be a good first issue?

**Comment by alawvt** [comment]
I agree that this is needed. It is common for repositories to have repeated collection names and depend on the hierarchy to distinguish them. The full hieirarchy also needs to be show in the workflow view so approvers can make sure the item is submitted to the correction collection.

**Comment by tdonohue** [comment]
Closing, as this has since been replaced by #1602 (which has some more recent activity).  These two tickets appear to be the same issue, so I'm closing this one as a "duplicate"
