### ISSUE TITLE
Edit EPerson | Reset Password disabled

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#1349]
**Describe the bug**
Logged on as a member of Administrator, on the Edit EPerson page,  Reset Password is disabled.

**To Reproduce**
1. Log on as a member of Administrator.
2. Try to reset someone's password.

**Expected behavior**
A member of Administrator should be able to reset someone's password.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
I agree this should be easier, so pulling this onto our 7.2 board.  There is a current workaround however.

**Workaround**
1. Enable `webui.user.assumelogin=true` on backend (no need to restart backend, it enables dynamically)
1. Login as an Administrator
2. Edit other EPerson
3. Click "Impersonate EPerson"
4. Go to Profile (as that other EPerson).  Change Password.
5. Click "Stop Impersonating EPerson" button

All that said, completely agree that this should be made much easier for Admins. The button should just be enabled.

**Comment by abollini** [comment]
Hi @tdonohue this should took 1-2hours, we have done that in dspace-cris for a customer so it would be mostly cherry-picking, verification and fixing issue. If you want we can claim it

**Comment by tdonohue** [comment]
@abollini : Sounds good. Will assign to @atarix83 for your team to work on & add the estimate to this ticket.
