### ISSUE TITLE
Enhance download bitstream function

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1352]
On current official demo site "https://demo7.dspace.org/" download bitstream function is bit different than on site generated by standard code.
Official site downloads bitstream in the same page where request originated from.
On site generated by standard dspace-angular code (latest for 11.Okt 2021) download triggers the same href, but it ends up loading a new page showing "Now downloading 'filename'...".

The solution on demo site is more user friendly, please add that approach to standard code.
Standard code does not perform the UI internal redirect, instead   bitstream-page-routing.module.ts does the /download route redirection to BitstreamDownloadPageComponent (my best understanding of it..)

P.S.
Demo site leverages these 2 requests : 
![image](https://user-images.githubusercontent.com/2697696/136848119-2d289106-fe42-4c31-94ab-7e9cb3d2a9fc.png)

![image](https://user-images.githubusercontent.com/2697696/136848159-5be0ba94-2e11-410f-82b7-a938c0e25e2b.png)

**Comment by tdonohue** [comment]
@MarisArins : The demo7.dspace.org site is running standard code. It's running what is on the `main` branch at https://github.com/DSpace/dspace-angular/ with no customizations to the code.

When I run the Angular UI locally (starting it using `yarn start`), I see the same internal redirect that occurs on the demo site.  It's possible that internal redirect requires running in production mode (with server-side rendering enabled).

Closing as "won't fix" as this doesn't appear to be a reproducible bug.  My best guess is you either have a configuration issue or you are not using server-side rendering.
