### ISSUE TITLE
Empty required name input not displaying error message after saving

### ISSUE THREAD

**Issue by Atmire-Kristof** [DSpace/dspace-angular#1353]
**Describe the bug**
Input fields of type "name" don't display an error message when left empty after saving the form in submission.

**To Reproduce**
- Setup a DSpace 7 with a submission form containing required input(s) of type "name" (doesn't matter if it's wrapped in a relation-field or not, both contain the bug)
- Go to submission and fill in a couple of fields, but leave the required name field empty
- Click Save
- The name field doesn't show any error messages. Other required fields do.

**Expected behavior**
The required name field should display an error message after clicking save and leaving it empty.

**Comment by tdonohue** [comment]
This definitely sounds like a bug. I suspect this simply doesn't work because we don't have a `name` field in default submission configs, and no one has tested it recently. Estimates or fixes welcome
