### ISSUE TITLE
Enable/Disable start/end date picker in submission broken when no access condition which has start/end date = true config

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1359]
**Describe the bug**
If you change the [`access-conditions.xml`](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/access-conditions.xml) config so that your `UploadConfiguration.metadata.options` no longer contains an option which has true for `hasEndDate` (or `hasStartDate`) then the enable/disable of the date picker of that field in submission doesn't work (is always enabled).

If for example you remove the 'lease' option then there is no option that and hasEndDate=true resulting in the endDate option always being enabled in the submission.

This config gets assigned to the form data config [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts#L187-L206), resulting in:

- confStart: 

  ```
  [
      {
          "match": "ENABLED",
          "operator": "OR",
          "when": [
              {
                  "id": "name",
                  "value": "embargo"
              }
          ]
      }
  ]
  ```

- confEnd:

  ```
  [
      {
          "match": "ENABLED",
          "operator": "OR",
          "when": []
      }
  ]
  ```

  => This empty when makes it so this condition doesn't work for enabling/disabling the date picker

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove `lease` upload config option [here](https://github.com/DSpace/DSpace/blob/main/dspace/config/spring/api/access-conditions.xml#L14)
2. Go to submission, add a bitstream, edit the bitstream 
3. On all options the endDate date picker will be enabled, despite all having config `hasEndDate=false`

**Expected behaviour**
The end date picker should be disabled for all options

**Possible solution**
Before checking all accessConditionsConfig [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/upload/file/edit/section-upload-file-edit.component.ts#L188), add an empty `name=''` so the when is never empty:

```
      const hasStart = [];
      hasStart.push({ id: 'name', value: '' });
      const hasEnd = [];
      hasEnd.push({ id: 'name', value: '' });
      const hasGroups = [];
      hasGroups.push({ id: 'name', value: '' });
```

**Comment by tdonohue** [comment]
Moving this and the related ticket to 7.2 for further analysis. Definitely sounds like a bug in our current logic here.

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977
