### ISSUE TITLE
Cannot download embargoed file as administrator from edit bitstreams page

### ISSUE THREAD

**Issue by KevinVdV** [DSpace/dspace-angular#1361]
**Describe the bug**
If you download a file from the edit item bitstream page tab you get the following exception:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Oct 19 09:22:06 UTC 2021
There was an unexpected error (type=Unauthorized, status=401).
Authentication is required
```
You can see it in effect here: https://demo7.dspace.org/items/1fa91144-d42b-48ab-97c7-1cc280bc5f8b/edit/bitstreams

**To Reproduce**
1. Submit a new item with an embargoed file
2. Navigate to edit item
3. Navigate to the "Bitstreams" tab
4. Click on the download icon for the embargoed file

**Expected behavior**
Admins should be able to download the file.

**Comment by tdonohue** [comment]
This sounds like a small, but obvious bug.  The download of the embargoed file works perfectly fine if you download from the main Item page (e.g. https://demo7.dspace.org/items/1fa91144-d42b-48ab-97c7-1cc280bc5f8b).  It's only broken if you try to download it from the Edit Bitstreams page.

So, I suspect the Edit Bitstreams page download button just needs to be updated to have the correct link/action.

Flagging this as high priority as it's annoying.  Likely a quick fix though that any developer could make.  (Let me know if someone from Atmire is interested)

**Comment by artlowel** [comment]
Nevermind, after a hard refresh I can
