### ISSUE TITLE
The search loads indefinitely if the written query is invalid

### ISSUE THREAD

**Issue by LucaGiamminonni** [DSpace/dspace-angular#1365]
**Describe the bug**
The search that can be done from the search page and from the mydspace does not produce results, and loads indefinitely, if the query entered in the input is not valid. 
Example: https://demo7.dspace.org/search?spc.page=1&query=test:&spc.sf=score&spc.sd=DESC

**To Reproduce**
1. Search for a string like 'test:' or for any other string that does not represent a syntactically valid query

**Expected behavior**
At least one error message should be shown when this problem occurs.
It should also be considered whether to allow the user to search by escaping the characters entered in the input or using the DisMax Query Parser (https://solr.apache.org/guide/8_1/the-dismax-query-parser.html). A search of this type could be useful for example if you want to search for a word ending with ':' .

**Comment by tdonohue** [comment]
@LucaGiamminonni : Yep, this is definitely a bug.  Moving over to the 7.2 board for someone to claim (let me know if you or your team is interested).  I'd also recommend treating your question about searching by escaping characters separately.  I think some basic character escaping already works... I'm not against doing more, but that should be a separate task from fixing this obvious bug.

**Comment by abollini** [comment]
Estimation 8 hours
- to catch the error on the server side and returning a 422 instead than 500
- implement error handling on the angular side to present an invalid query message

**Comment by tdonohue** [comment]
Thanks @abollini .  Added the estimate and assigned back to both you and @atarix83 , as it sounds like it'll require both frontend & backend fixes.  Feel free to delegate, obviously.
