### ISSUE TITLE
Statistic view displays some statistics without name

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1369]
After some use of DSpace 7 app, Site-statistics page may show some elements without title :
![image](https://user-images.githubusercontent.com/2697696/138612763-f110e7b8-3209-4412-9086-454b5242cbdc.png)

This is caused by particular items being unavailable to the user viewing them (not logged in or less access rights than needed for READ)

These either need to show item title or should not be included in statistics displayed for such user.

**Comment by tdonohue** [comment]
This appears like it may be the same issue as #8121

**Comment by tdonohue** [comment]
This issue has been partially fixed by https://github.com/DSpace/DSpace/pull/8446

However, some situations still appear where a bitstream name will not be displayed, see https://github.com/DSpace/DSpace/issues/8474

Closing this as this is replaced by https://github.com/DSpace/DSpace/issues/8474
