### ISSUE TITLE
Add an Item Thumbnail bitstream in 

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1377]
In current solution browse-by views not only do not display any thumbnails, but also the data sets delivered from services do not contain "followLinks" for Thumbnails.
If these could be included, then in GridView the resulting item cards could be formed with thumbnails.

**Comment by tdonohue** [comment]
@MarisArins : I'm not sure I understand this ticket, or what you are asking for.  You mention the "Browse by" sections, but you also mention "GridView".  Currently, the GridView is only supported in *Search Results* (not in browse).  The current Search GridView already displays thumbnails (if they exist).

Browse By options would be much harder to support GridView (except for possibly Browse by Title), as usually the Browse By results are not displaying a single Item/object.  Instead, "Browse by Subject" displays a single "dc.subject" value (which cannot have a thumbnail), similarly "Browse by Author" displays a single "dc.contributor" metadata value (which also cannot have a thumbnail).

So, I'm not sure how to address your ticket, as nearly all "Browse By" options (except Browse by Title) cannot easily support thumbnails, as you are browsing metadata values, and not individual Items.

Am I misunderstanding the request here?

**Comment by tdonohue** [comment]
Moving to "unscheduled backlog" until further info provided

**Comment by tdonohue** [comment]
Closing, as 7.4 now includes Thumbnails in "Browse By" pages by default.
