### ISSUE TITLE
Enhance browse-by-title and browse-by-subject functional presentation

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1378]
When selecting a particular letter from which to start displaying results, e.g. "M", all the letters from A until picked "start-point" (from A until L in the given example) could be marked in lighter color or in other way made clear that they are not included in presentation.

![image](https://user-images.githubusercontent.com/2697696/138938829-018e3a86-34bb-418c-a71e-25f7eea28e15.png)

**Comment by tdonohue** [comment]
Closing as this is outdated. The letters have been removed from Browse By Title/Subject.
