### ISSUE TITLE
Upload bitstream view should always present at least the standard 3 bundles to pick from

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1380]
If you start editing bitstreams for an Item where not all bundles are present (as in example there is no THUMBNAILS bundle), user must manually create a THUMBNAIL bundle if he wants to add thumbnail.
That seems normal for a well educated editor/admin, but its not very clear for a new starter, also there is a chance of mistakes in this process.

![image](https://user-images.githubusercontent.com/2697696/138943852-acd09c81-bf41-43c0-a944-01f712c27c4b.png)
![image](https://user-images.githubusercontent.com/2697696/138944017-1c933a7d-d6ed-4757-84a2-83b73d3d30a4.png)

To avoid confusions the 3 standard Bundle names could always be present in the Bundle selector, even if these bundles are not available in the particular Item.

**Comment by tdonohue** [comment]
Agreed, this is a usability issue & a bug as it invites human mistakes.  Moving it to 7.2 and making high priority.

**Comment by artlowel** [comment]
I'd make the list of bundle names that are shown by default configurable in the angular config

This can be done in an estimated **3 hours**
We'd like to claim this issue

**Comment by tdonohue** [comment]
@artlowel : That seems reasonable.  

I admit, a part of me wonders if this should eventually be a backend configuration/setting. But it appears Bundle Name is "uncontrolled" on the backend right now, as it's just a `dc.title` value.  So, making it a frontend configuration seems reasonable for now.  If, in the future, there's ever a way to do a lookup of valid Bundle names from the backend we can always swap it out later.

In any case, adding the estimate & assigning back to you.
