### ISSUE TITLE
DSO sub-routes aren't displaying the correct titles

### ISSUE THREAD

**Issue by Atmire-Kristof** [DSpace/dspace-angular#1381]
**Describe the bug**
Some sub-routes of DSO pages aren't displaying the configured i18n title as the browser tab's name. Instead, they're showing the DSO's title, which should only be the case on the DSO's page itself or if the sub-route doesn't have a title configured.

[this part of the metadata-service](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/metadata/metadata.service.ts#L108-L112) normally takes care of translating the title and adding it to the page's metadata.
However, if the page's data contains a "dso", [this part](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/metadata/metadata.service.ts#L135) seems to overwrite the title, even for child routes.

**To Reproduce**
1. Visit a collection's itemtemplate route (e.g. /collections/3c17ceef-43d7-4ad1-bba4-61d4ecc05a81/itemtemplate)
2. Notice how the browser tab's name is equal to the collection's name and not "Edit Template Item" as it should be.

For whatever reason, this doesn't seem to happen on community/collection/item edit pages and I can't seem to figure out why. The only thing I've noticed is that there's no "dso" in the deepest child route data for these pages.

**Expected behavior**
The translated i18n message should be the browser tab's title instead of the DSO's name.

**Comment by tdonohue** [comment]
@Atmire-Kristof :  I'm able to reproduce this.  As you noted, it doesn't appear to affect all subpaths however....I also see that "Edit" pages (including all tabs on that page) work perfectly OK, e.g.  `/collections/b7bf809e-b8ea-41bf-b16a-38d78785f557/edit/metadata`

Moving this over to 7.2 for now & flagging as estimate TBD as it'd need someone to look at more closely to determine how to fix.
