### ISSUE TITLE
Many notifications when trying to create a group with an already existing name

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1386]
**Describe the bug**
The behavior described in https://github.com/DSpace/dspace-angular/issues/1325 occurs also with groups management when the user tries to create a group with an already existing name

**To Reproduce**
1. connect to the demo and login as an Administrator
2. create a group with a not existing name
3. go back to "Access Control / Groups" 
4. click "add group"
5. use the same name of point 2
6. The group won't be created but the user will see three error notifications
![image](https://user-images.githubusercontent.com/70699836/139807981-476ec654-a862-4a65-a7a9-e2ccaf11de3b.png)

**Expected behavior**
Three different notifications might be a bit confusing for the user, we believe he / she should be  made unable to perform the "save" action if the group name is already in use.

We (4 Science) are available to take in charge this improvement by adding using a validator similar to what already done for https://github.com/DSpace/dspace-angular/issues/1325. To add this feature and its test we estimate 4 to 8 hours of effort.

**Comment by tdonohue** [comment]
@corrad82-4s : Sounds good to me.  Assigning back to you for your team to work on for 7.2
