### ISSUE TITLE
Add new fields to edit bitstream when IIIF is enabled

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1388]
**Is your feature request related to a problem? Please describe.**
When an item is IIIF-enabled it should be possible to edit the metadata fields used to generate the IIIF manifest.  This would, for example, make it possible for a collection curator to easily update the _label_ or _table of contents_ entry that appears in the viewer.

**Describe the solution you'd like**
When an item is IIIF-enabled, add bitstream form fields for `label`, `toc`, `height` and `width`.

**Comment by tdonohue** [comment]
@mspalti : Seems reasonable. I'll flag this as medium priority for now, but feel free to work on it already if it's of interest. Priority only applies to development paid out of DSpace's budget.
