### ISSUE TITLE
Show an error page if the REST API is not available

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1389]
**Is your feature request related to a problem? Please describe.**
When the rest endpoint is not reachable due to a problem, the angular application doesn't work but show only a page with an hanging load spinner. It'd be nice instead to have a 500 page where to redirect in this case

**Describe the solution you'd like**
A possible solution is to create an angular guard that make a rest request to `/server/api` and in case it gets an error response it redirect to a general 500 page (that looks like the 404 page)

**Comment by tdonohue** [comment]
@atarix83 : I agree this would be a nice feature.  It'd also be helpful to people who are first installing DSpace if we can provide this sort of better error handling for an unresponsive (or invalid) REST API.

Moving this to the 7.2 board in case we can get to it.  Flagging as needing an estimate though.

**Comment by abollini** [comment]
@tdonohue estimation 4 hours. We are working on it

**Comment by tdonohue** [comment]
Reopening, as PR #1407 had to be reverted as it broke Authentication. Leaving assigned to @atarix83 who is working on a new PR to replace #1407.
