### ISSUE TITLE
Range root needs viewing hint to render properly in Mirador.

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1395]
**Describe the bug**
Currently, the table of contents view does not include the "top" viewing hint. From the docs:

> [top viewing hint] Valid only for ranges. A Range with this viewingHint is the top-most node in a hierarchy of ranges that represents a structure to be rendered by the client to assist in navigation. For example, a table of contents within a paged object, major sections of a 3d object, the textual areas within a single scroll, and so forth.

Without this viewing hint, the Mirador viewer displays redundant information: an expandable "table of contents" element that includes all ranges and the same ranges listed separately.

UPDATE: Since this is actually an omission in the IIIF backend service I created a new DSpace issue to track that work: 
https://github.com/DSpace/DSpace/issues/8048

**To Reproduce**
Choose the index (in the left navigation panel) for this test item:

https://digitalcollections.willamette.edu/items/0a53d851-319b-4883-9d80-6bf0148ee2ed

**Expected behavior**
There should be a list of all ranges, with the redundant table of contents hidden.

**Comment by mspalti** [comment]
@tdonohue , fyi, this issue can probably be closed. I created a new DSpace issue (and added it to the 7.2 board) because the fix is on the backend and I was having trouble linking the PR to this dspace-angular issue.

**Comment by tdonohue** [comment]
@mspalti : Sounds good! Closing in favor of the new #8048 ticket
