### ISSUE TITLE
Image processing tool for IIIF metadata

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1396]
This proposal is for something we might include in the 7.2 release. I think it would be a helpful addition but I haven't explored the details yet. If anyone has thoughts on what I describe I'd welcome your input.

**Is your feature request related to a problem? Please describe.**
IIIF canvases are containers for the images rendered in an IIIF viewer. Canvases have height and width dimensions that should always have the same aspect ratio as the image and usually the same overall dimensions. 

Height and width dimensions can be expressed in bitstream metadata using `iiif.image.height` and `iiif.image.width`. If these values are not provided in bitstream metadata, the IIIF service uses default values. These fallback height and width dimensions are part of the `iiif.cfg` configuration. In addition, work on deriving fallback dimensions dynamically, by fetching the dimensions for the _first_ bitstream, is described in this issue: https://github.com/DSpace/DSpace/issues/8021

Determining the h/w dimensions dynamically should be a big improvement that makes `iiif.image.height` and `iiif.image.width` unnecessary in the most simple use cases. But the need for accurate image metadata for each bitstream still exists, especially in multi-image records. 

In large digitization projects, the height and width dimensions for each image will often be obtained _prior_ to importing records into DSpace. However, this may not always be possible. Also, there may be cases when images are replaced with new images. In cases like these (and others) a batch process for updating canvas dimensions would be helpful. 

**Describe the solution you'd like**
I'd like to propose a new curation tool, analogous to Media Filter, that can be applied to communities, collections or items. The tool will identify iiif-enabled items, check their metadata for `iiif.image.height` and `iiif.image.width` values. If these are missing, the tool will retrieve the image dimensions and create the metadata. It should be possible to force updates by adding an optional flag.

**Comment by mspalti** [comment]
@tdonohue  it looks like once again I created an IIIF issue on the wrong repository. Now I understand the limitation!!

This a pull request for the new feature. https://github.com/DSpace/DSpace/pull/8074

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/DSpace/pull/8074
