### ISSUE TITLE
Add an npm script to install global dependencies

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#14]
Some npm scripts won't work unless certain dependencies are installed globally. `webpack-bundle-size-analyzer` is one such example. We need to identify the others, and add an npm script to install them.

**Comment by wwelling** [comment]
Here is what I would suggest:
```"global": "npm install -g angular-cli nodemon npm-check-updates rimraf ts-node typedoc typescript webpack webpack-bundle-size-analyzer marked node-gyp"```
