### ISSUE TITLE
Upgrade to bootstrap 4 beta

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#140]
Bootstrap 4's beta version has been released. We should upgrade from the alpha version provided @ng-bootstrap is compatible

**Comment by wwelling** [comment]
https://github.com/twbs/bootstrap/issues/24078

I would wait until the bootstrap 4 CSS only package is released. We probably do not want jquery or popper.

**Comment by artlowel** [comment]
As discussed in today's meeting, we'll upgrade to beta now, but switch to bootstrap-css when it comes out.

https://github.com/DSpace/dspace-angular/issues/154

**Comment by wwelling** [comment]
This upgrade is complete. An issue has been opened to address the peer dependency warnings. #154.

Please refer to [Bootstrap 4](https://getbootstrap.com/) for styling and variables. Refer to [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) for functional UI components.

Closing now.
