### ISSUE TITLE
Difference in processes execution times timestamps

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1402]
**Describe the bug**
There is a difference in how the processes start and end dates appears in the processes list page and in the process details page, dates are expressed in different timezones.

**To Reproduce**
1. login to dspace 7 demo as administrator
2. Go to  Processes overview page
3. Process times are expressed UTC + 1
![image](https://user-images.githubusercontent.com/70699836/141798041-f76124bf-79d2-47cb-add7-9dd0cee4f701.png)
4. Select first process and go to its details page
5. Start and end timestamps are expressed in UTC timezone
![image](https://user-images.githubusercontent.com/70699836/141798190-e3ac6a22-889f-4650-844a-a787e697855c.png)

**Expected behavior**
To avoid users get confused, Timestamps should be expressed with same timezone, which could be the one used in process details page. In addition, it could be worthwhile adding offset to timestamps expressed in process list page. 

We (4Science) can look into this, for which we estimate 1 hour of work

**Comment by tdonohue** [comment]
@corrad82-4s : This seems fine. It's a tiny fix, but I agree it could be confusing. Assigning back to you to work on.
