### ISSUE TITLE
Porting the MathJax display from previous DSpace versions

### ISSUE THREAD

**Issue by jonas-atmire** [DSpace/dspace-angular#1404]
**Description of the feature request**
Previous versions of DSpace contained the possibility of enabling the rendering of scientific formulas and symbols on different item pages.
This should also be ported to DSpace 7 for preservation of default functionality.

An example of how this is currently displayed in DSpace:
The 2 formulas that are present in the abstract are:
* $\text{H}_2$/$\text{O}_2$
* $\text{H}_2 + \text{O}_2(1\Delta) = \text{H} + \text{HO}_2$

When actually displaying the values, it's rendered as an actual formula, and not simply as the text that is present in the DB
![Screenshot 2021-11-16 at 09 49 45](https://user-images.githubusercontent.com/11884252/141953220-c06a7434-f138-4393-b7b1-7ad71dba202a.png)

**Describe the solution you'd like**
The current configuration possibility should be ported to the DSpace 7 codebase.
Most, if not all, of this work would be present in the angular side of things.
Rest should only be relevant for the enabling/disabling of the config.

**Comment by mwoodiupui** [comment]
This is part of a larger issue:  in earlier releases, `textarea` fields could be formatted.  In 7.3, line breaks entered in the item editor are removed, and entering even plain HTML markup causes it to be displayed as-is.

We have abstracts with multiple paragraphs and even tables.  Line breaks are quite common.  Markup is rare but we have some.

The 7.x documentation still has a page on "Simple HTML Fragment Markup" which is no longer true and probably does not represent well the eventual resolution of this issue.

**Comment by tdonohue** [comment]
Added a zero hour estimate as this will be include in fix for #1762
