### ISSUE TITLE
Process status not updated when passing from list to details

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1405]
**Describe the bug**
When passing from process list to a single process details, its status remains the same visible in list page, despite its actual status. 

**To Reproduce**
1. login to the demo as administrator
2. trigger a process (i.e. metadata-export)
3. wait several seconds in process list page and then click on its details
4. the details page will show the process as "Running", but outcome file(s) are available

![Screenshot from 2021-11-16 16-49-59](https://user-images.githubusercontent.com/70699836/142024560-d04528c5-a4c7-494c-a335-9a745df1d502.png)
![Screenshot from 2021-11-16 16-50-07](https://user-images.githubusercontent.com/70699836/142024583-4ad5b3b8-67fd-44d6-b93b-d00f96f78481.png)

**Expected behavior**
Status of process updated (if changed) when passing from process list to process details.

We (4Science) can look into this, our estimation is 1 hour of work

**Comment by tdonohue** [comment]
@corrad82-4s : Thanks, agreed that this sounds like a bug needing a fix.  Adding the estimate & assigning back to you for your team to create the small PR.
