### ISSUE TITLE
Can't delete description on bitstream

### ISSUE THREAD

**Issue by davidenegretti-4science** [DSpace/dspace-angular#1415]
**Describe the bug**
While working on issue #1337 I found another bug in bitstream edit form.
If the bitstream have a description it is not possible to delete it.
When saving the bitstream the submission is not removed (`remove` is not present in the patch).
The patch is successful and the user does not receive any error notification.

**To Reproduce**
1. Go to an item in submission (or submit new item)
2. Add a bitstream with a non empty description and save it
3. Edit the same bitstream again and delete the content of the description field

**Comment by atarix83** [comment]
@tdonohue 

this takes about 2hours yoc can assign to @davidenegretti-4science who is working on https://github.com/DSpace/dspace-angular/issues/1337

**Comment by tdonohue** [comment]
@atarix83 and @davidenegretti-4science : Sounds good. I've assigned it and moved to our 7.2 board

**Comment by davidenegretti-4science** [comment]
Solved together with:
- #1337 
- #1359 
- #1399 
- #1415 
- DSpace/Dspace#7977
