### ISSUE TITLE
Runtime config

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#1422]
**Is your feature request related to a problem? Please describe.**

The app config (environment file in Angular) is determined at build time and unable to change configuration without entire build. Making container images non portable and lengthy build times to test configuration changes.

**Describe the solution you'd like**

Build config file at server start and host as static resource. Support external configuration and override of all config values via convention driven environment variables. Define typed interface for config, define injection token, fetch config before bootstrap, and define as provider to the app module. This should one-to-one replace the statically imported environment.

**Describe alternatives or workarounds you've considered**

An alternative solution to fetching config before bootstrap could be to figure out how to serve it during the initial server-side rendering. 

**Additional context**

https://12factor.net/config

**Comment by tdonohue** [comment]
As discussed briefly in Slack, this is definitely of interest to myself (& @artlowel mentioned his support as well).  Therefore, I'll pull this over onto the 7.2 board.  But, at this time, I'm going to flag it as "help wanted", as it seems like it'd likely need a volunteer to step forward to make this happen in 7.2 (so let me know @wwelling if it's of interest to you to implement).

**Comment by wwelling** [comment]
@tdonohue I will begin working on this shortly.
