### ISSUE TITLE
Authority controlled values filtered by value (should filter on authority)

### ISSUE THREAD

**Issue by cwilper** [DSpace/dspace-angular#1423]
**Describe the bug**
When a user attempts to filter on authority controlled values, the filtering is incorrectly done based on the text value rather than the authority key. This is a UI issue only -- DSpace 7 REST is fully capable of providing authority key-filtered "objects" and "facets" results when the client correctly uses the `authority` operator.

**To Reproduce**
1. Index some items with authority-controlled values for a field that is configured as a site-wide facet, such as author.
2. Visit site-wide search and note that when those values show up in the facets, the link to apply the filter does not include the authority key.
3. Upon clicking the link, notice that the matches are based on the text value rather than the authority key. You can verify by watching the REST traffic and confirming that the authority key is not passed to REST as it should be. Only the text value is passed.

**Expected behavior**
The filtering should be based on the authority key when the selected facet value is authority-based.

**Related links**
* [Discussion of searching by key in the Authority Control of Metadata Values original development proposal](https://wiki.lyrasis.org/display/DSPACE/Authority+Control+of+Metadata+Values#AuthorityControlofMetadataValues-Search)
* [Example of using the authority operator in REST](https://github.com/DSpace/RestContract/blob/main/search-endpoint.md#matching-dspace-objects-search-results)

**Interest/Estimate**
We are interested in taking on this work and estimate the overall effort will be about half a day.

**Comment by tdonohue** [comment]
@cwilper : Thanks for submitting this.  I agree this sounds like something we'd want to fix soon to provide more logical behavior.  I'll assign this back to you for your team to work on, add the estimate & pull this over to the 7.2 board.  Feel free to work on for 7.2

**Comment by santit96** [comment]
Hi! Just wanted to notice that this problem also affects the browse-by page when the browse is configured to use authority keys instead of text values. In that case when clicking on a browse result to list items filtered by that value, it filters by text value instead of authority value
