### ISSUE TITLE
Non-ergonomic display of long metadatavalue without space on admin metadata + bitstream edit AND public item pages

### ISSUE THREAD

**Issue by davidatmire** [DSpace/dspace-angular#1429]
**Describe the bug**
When an item has a very long metadata value without space (e.g. a long URL stored in dc.identifier.uri for example), the display of the admin metadata edit is not ergonomic, as in the admin user has to scroll to the right to be able to see the edit/delete buttons for ALL metadata of the item.
<img width="1139" alt="Screenshot 2021-12-02 at 22 48 19" src="https://user-images.githubusercontent.com/41991272/144508574-0f672214-50c5-4ef9-af27-9f49cd4bad34.png">

This was tested on both Firefox and Chrome on demo 7 (7.2-SNAPSHOT at the time of writing this comment).

**To Reproduce**
1. Go to demo7
2. Log in as admin user
3. Edit any random item
4. Add a new metadata (e.g. dc.identifier.uri) with a very long metadata value without space
5. Check the impact on the display after adding this metadata

**Expected behavior**
A line break should be forced as from a certain width, to keep the buttons on the right side of the metadata always visible.

**Related work**
NA

**Comment by tdonohue** [comment]
Thanks @davidatmire , I agree this is a usability bug we should look at fixing soon.  For now, pulled it over to the 7.2 board to see if we can find someone to look at this for 7.2.  If your team is interested (or anyone else reading this later), let me know & please provide a rough estimate of the effort (in hours).

**Comment by davidatmire** [comment]
@tdonohue thank you for your prompt answer.
When checking with @artlowel, we have noticed that the same issues appear at different places : 
- Admin metadata edit (mentioned in my previous comment)
- Admin bitstream edit:
![Screenshot 2021-12-07 at 11 51 32](https://user-images.githubusercontent.com/41991272/145016184-c7fb2868-65e3-4c22-8309-63c47a5c36c3.png)
- Item view, both at the level of metadata and bitstream names:
![Screenshot 2021-12-07 at 11 52 09](https://user-images.githubusercontent.com/41991272/145016213-f81121a4-bd54-43da-a305-f4b08a541888.png)

The solution needs to be determined on a case-by-case basis and is going to be a compromise between completeness and usability (e.g. for admin pages it may be ok to simply cut off words halfway, for public facing pages we may need a more complicated solution).

Estimate : 4 hours to identify and implement the ad-hoc compromise solution for the cases mentioned above.

**Comment by tdonohue** [comment]
Thanks @davidatmire : I'll add your 4hrs estimate to this ticket & assign this back to you for implementation. Please feel free to delegate as needed to someone else within Atmire.
