### ISSUE TITLE
Redux DevTools can degradate heavily the overall platform performance

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#1430]
It is known that Redux Dev Tools can cause unpredictable performance issues as described [here](https://github.com/DSpace/dspace-angular/issues/1330).

At 4Science, we came across a very similar problem related to the MyDspace and we could only solve it by disabling the Redux DevTools in production.
For this particular customization (but not so uncommon in our opinion), a lot of information are embedded during the MyDspace search to properly display the search result items in an efficient way. So a lot of stuff has to be stored quickly in the Cache Store, but this not happen in time. The result is that every search result item causes singular rest requests to fetch information that should be easily retrieavable from the store.
Moreover (and as a consequence) a lot of UI elements result freezed during the Cache indexing.

Our testing proves that disabling the extension solves the problem and the user experience turns to be as smooth as usual.

Since we cannot make assumption over the presence of the Redux Dev Tools on the client side, our suggestion is to disable it by default in production environment.

**Comment by tdonohue** [comment]
@alemarte : Isn't Redux DevTools a Chrome browser extension (i.e. not a part of DSpace itself)?https://github.com/zalmoxisus/redux-devtools-extension

I do agree that browser extension results in sometimes bad performance when using DSpace 7 -- so I've disabled it in my own Chrome browser by default, but keep it around in case I need it for development/debugging.

Overall, I agree that we should recommend others not use this browser extension, but I'm not sure what changes you are recommending to *DSpace* in this ticket?  Are you just looking for us to better document why we recommend *against* using Redux DevTools extension?  Or do you see necessary code changes we should be making in the DSpace Angular codebase?

**Comment by alemarte** [comment]
@tdonohue The Redux DevTools is indeed a Chrome extension and is currently configured and enabled by default on DSpace production environment (we can see it on the demo, the icon turned on).

![Screenshot_2021-12-09_10-48-47](https://user-images.githubusercontent.com/63857/145373506-bd2f30e9-1dba-42e1-80d6-86325f500dc1.png)

This means that every user with this extensions installed (usually developers, worst case belonging to quality assurance teams) might be afflicted by the described system instability.
So we do need a mechanism to at least disable via configuration this extension in such cases.

This is the current configuration (just ensure that in production environment the state management isn't modifiable and corruptible within the plugin, _logOnly_ parameter)
```
IMPORTS.push(
  StoreDevtoolsModule.instrument({
    maxAge: 1000,
    logOnly: environment.production,
  })
);
```

**Comment by tdonohue** [comment]
@alemarte : Thanks for clarifying!  I hadn't realized that enabling that plugin requires configuration in our codebase.  So, I see now that the code you reference is in our `app.module.ts` here: https://github.com/DSpace/dspace-angular/blob/main/src/app/app.module.ts#L93-L98

I agree, we need to either remove/disable that code, or change it to only allow it for **development** environments (it could even be based on configuration, but not sure if that's necessary).

I'll move this ticket over into the 7.2 board.  If you or your team are interested in fixing this for 7.2, please let me know & provide an estimate for how much effort it'd take.

**Comment by artlowel** [comment]
This can be done in **1 hour**
We'd like to claim this ticket

**Comment by tdonohue** [comment]
Thanks @artlowel .  Adding the estimate and assigning to you.
