### ISSUE TITLE
In the german file missing definition

### ISSUE THREAD

**Issue by WolfgangT71** [DSpace/dspace-angular#1460]
This line is missing in de.json5 
`"home.search-form.placeholder": "Durchsuche Repositorium",`

**Comment by WolfgangT71** [comment]
At appears to be missing in different language files, as also hu.json5 is missing it.

**Comment by tdonohue** [comment]
@WolfgangT71 : Could you submit a Pull Request (PR) when you want to make small updates like this?  That'd help us, as it means we can quickly review it and merge in the changes for the next release.  Otherwise, I have to try to find a different developer to create the PR.
