### ISSUE TITLE
Hard/impossible to change main thumbnail of item

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1463]
If you create a material with lots of files , e.g 20+ there will be a thumbnail generated for each file that can produce a thumbnail.
These thumbnails will be arranged in paginated list.
If you want to specify a thumbnail from last page as the main thumbnail, it is not possible to move it to top of list as that is in different page.
Button "primary file" seems not to work in this situation:
![image](https://user-images.githubusercontent.com/2697696/146686746-4aaf63c1-6a8d-4348-8e28-d29247756770.png)

Expected some clear mechanism for administrative users to specify any thumbnail as "Primary thumbnail"

**Comment by tdonohue** [comment]
Closing as this was fixed by https://github.com/DSpace/dspace-angular/pull/2213  The "Primary" toggle now works in 7.6
