### ISSUE TITLE
Workspaceitem's bitstreams are not available when setting an access condition during submission

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1473]
**Describe the bug**
While working on the https://github.com/DSpace/dspace-angular/issues/767 we found an issue with bitstreams access conditions reflected also on the new item embargo implementation. 
During the submission if I set an access conditions to an uploaded bitstream then is no longer possible to download it from the upload section's download button.

**To Reproduce**
1. create a new submission as not admin user
2. upload a new file to the submission
3. try to download it using the upload section's download button
4. it works
5. add any policy to the bitstream
6. try afain to download it using the upload section's download button
7. it doesn't work and a 403 page is shown 

**Expected behavior**
the bitstream should be available for the submitter during the submission

**Related work**
https://github.com/DSpace/dspace-angular/issues/767

**Comment by atarix83** [comment]
@tdonohue 

we already found the problem and the reason is that when adding a new policy to the bitstream the existing policies of `TYPE SUBMISSION` are deleted from the bitstream by mistake. This no longer makes the bitstream available during submission. We will resolve in the same PR of the item embargo functionality and takes about 8hours

**Comment by tdonohue** [comment]
@atarix83 : Thanks for digging into this. I'll add the 8hr estimate and assign back to you for your team.
