### ISSUE TITLE
Back button is missing from download page

### ISSUE THREAD

**Issue by davidenegretti-4science** [DSpace/dspace-angular#1477]
**Describe the bug**
Try to download an attached file from a publication. A "Now downloading page" is displayed without any link back to the item. A back button should be provided.

**To Reproduce**
1. Search for a [publication with attached files](https://demo7.dspace.org/search?spc.page=1&query=&spc.sf=score&spc.sd=DESC&f.entityType=Publication,equals&f.has_content_in_original_bundle=true,equals), e.g. [this one](https://demo7.dspace.org/entities/publication/3149d355-7c13-4abb-8537-1852c181d9b2)
2. Download a file
3. There is no back button to the item's page

**Comment by davidenegretti-4science** [comment]
We could handle this one, it should take 2 hours

**Comment by tdonohue** [comment]
@davidenegretti-4science : I'll move this over to the 7.2 board, in case we can still fit it in there & add the estimate. Feel free to start this and we'll see if it can make it into 7.2
