### ISSUE TITLE
Item submission form validation sometimes not correctly triggered

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1484]
Issue observable on a form that has mandatory fields in "second page".
If user clicks and fills in order mandatory fields, as last clicking on Licence agreement checkbox, sometimes "second page" remains in "error" state even if all mandatory fields are filled.
Only clicking around some input fields in different pages can trigger revalidation that finally marks it as valid.
Likely reason for such an issue is fact that when person navigates from first page fields to second page fields, second page instantly goes to "error" state, as at this point it has all required fields empty.

Initial warning state:
![image](https://user-images.githubusercontent.com/2697696/148357616-28459b32-aeb1-4b92-978b-9cc405f3dc4b.png)

Error state after navigation:
![image](https://user-images.githubusercontent.com/2697696/148357352-18d58b51-5c2f-4cce-b92c-b59e98dc9620.png)

Expected:
Second page would be properly validated upon navigation from second page to any element outside of it (even to file drop-box element)

**Comment by tdonohue** [comment]
This seems to be fixed now that we've changed the submission to always enable the deposit button, see https://github.com/DSpace/dspace-angular/pull/1427 and follow-up tickets/fixes.

I'd recommend trying the latest code or 7.3 (once released).
