### ISSUE TITLE
Make label and error messages for license-step accept-checkbox available to i18n

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#1487]
**Describe the bug**
In the license submission step, the label of the checkbox and the error messages are hardcoded strings in `section-license.model.ts`.

```
export const SECTION_LICENSE_FORM_MODEL = [
  {
    id: 'granted',
    label: 'I confirm the license above',
    required: true,
    value: false,
    validators: {
      required: null
    },
    errorMessages: {
      required: 'You must accept the license',
      notgranted: 'You must accept the license'
    },
    type: 'CHECKBOX',
  }
];
```

**Expected behavior**
In order to be able to customise and translate those messages, they should be made available for i18n.

**Discussion**
I tried to solve this myself, but could not find the right place to put an i18n key. If you put an i18n key at the place of the hardcoded string in `section-license.model.ts` the key will be displayed, not the message from `xxx.json5`. I also could not figure out at what section of code I would put `| translate` or `translateService.get(key)` to make use of this key. As we want to be able to switch the language dynamically, we cannot populate constant values with translations? Following the use of the constant, I never got to the place, where the label and error messages were actually used.

If someone points me to right place, I will try to fix it myself and make a pull request. I am aware of the documentation at https://github.com/ngx-translate/core (Thanks, @mwoodiupui)

**Comment by atarix83** [comment]
hi @MW3000 you can take cue from what is done here https://github.com/DSpace/dspace-angular/blob/2835597073085108bc7b7479710fa48aec119812/src/app/submission/sections/upload/file/edit/section-upload-file-edit.model.ts#L89-L109

Pratically in the model you need to put the i18n key you will use for the translation, e.g. 

```
export const SECTION_LICENSE_FORM_MODEL = [
  {
    id: 'granted',
    label: 'submission.sections.license.granted-label',
    required: true,
    value: false,
    validators: {
      required: null
    },
    errorMessages: {
      required: 'submission.sections.license.required',
      notgranted:  'submission.sections.license.notgranted'
    },
    type: 'CHECKBOX',
  }
];
```
and than in the language file you will add the translation with those keys

**Comment by MW3000** [comment]
Thank you, @atarix83. It is clear so far. This is my reason for opening the issue.

If I modify `section-license.model.ts` like you suggested above and add the keys and translations to `en.json5`, then not the translation, but the key is shown as label next to the checkbox in the running app.

So, I suspect, that somehow the `label` from the model gets put in verbatim for a checkbox, and is not translated. But I cannot find the place, where this translation is missing.

**Comment by toniprieto** [comment]
It seems that the ng-dynamic-forms library used to show this section doesn't translate the labels of checkbox.

This is also mentioned in this issue #1335 that is a duplicate. See: https://github.com/DSpace/dspace-angular/issues/1335#issuecomment-927979820

I'll submit a new PR that uses the TranslateService to force the translation of the label in onSectionInit function.
