### ISSUE TITLE
mismatch of the text items in Harvest Controls

### ISSUE THREAD

**Issue by astrowq** [DSpace/dspace-angular#1492]
**Describe the bug**

The order of the harvest info items is wrong, specifically, the `Last time harvested` and `Harvest info`. See the screenshot below:

![image](https://user-images.githubusercontent.com/46059781/150510465-2e1962ff-132e-4be3-88e2-08bf369dd73c.png)

**To Reproduce**

1. Make a collection harvest OAI
2. Wait to see the mismatched text items

**Expected behaviour**

`Last time harvested` should show the time instead of `harvest info`, vice versa.

**Related work**

None.

**Note**

A fix is fairly simple, only two lines of code are enough. I can open a pull request to fix this. Since it is my first time to contribute to the dspace-angular, I would love to do it as my first ever contribution.

**Comment by tdonohue** [comment]
@astrowq : PRs are welcome & encouraged. We don't have a centralized dev team for DSpace, so all code is built/maintained/improved by community members or service providers who use DSpace.  Please feel free to submit a PR, linking it up to this ticket, and we'll get it reviewed.

**Comment by corrad82-4s** [comment]
@tdonohue : Hi, we were checking harvesting on current DSpace7 demo, and we noticed that labels seems to be as expected. 
![image](https://user-images.githubusercontent.com/70699836/203815182-d9617b83-7ee3-4950-b4f2-da125d99c901.png)
