### ISSUE TITLE
Delete item confirmation page is broken

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1501]
**Describe the bug**
If you try to delete an item the confirmation page is currently broken. Confirming the delete operation will trigger NO rest call

**To Reproduce**
1. login as administrator
2. visit an item, i.e https://demo7.dspace.org/items/209eba26-7f6a-4f53-b0d4-21d6f96f8722
3. try to delete it, no call to the REST API are performed

**Expected behavior**
It should work ;)

**Comment by firoball** [comment]
I think this issue might relate (see discussion after closure):

https://github.com/DSpace/dspace-angular/issues/1481
