### ISSUE TITLE
Standardize terminology in UI between "Discoverable" and "Private/Public" items

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1510]
**Describe the bug**
Discovered this usability issue while writing/updating documentation for the 7.2 release.  We use two terms for the same thing within our User Interface. We should obviously use the same terminology throughout to avoid confusion.

1. Submission UI's new "Item Access Condition" step provides a "discoverable" checkbox.  This allows you to select whether an item is discoverable (i.e. public) or non-discoverable (i.e. private)
    * This is a new terminology for the "Private" item, which has always been a problematic term, see for example this old ticket https://github.com/DSpace/DSpace/issues/7334
2. In the Item Edit > Status tab, we still have a "Make it private..." button.
3. In Administrative Search, the filter is named "Private".  When a Private item is found the button says "Make Public"
3. When an Item is non-discoverable, it gets a "Private" red label (in Administrative Search for example)

**Expected behavior**
We should use the same terminology throughout DSpace.

I personally like the new "Discoverable" terminology, as it more accurately describes this item state.  We should consider renaming all terminology in the UI as follows:
* Private => Hidden (or possibly Non-Discoverable)
* Public => Discoverable

**Comment by mwoodiupui** [comment]
Yes, please.  I will add my support for the more accurate "discoverable".

**Comment by artlowel** [comment]
Atmire would like to claim this. It will take an estimated **2 hours**

**Comment by tdonohue** [comment]
@artlowel: sounds good! Will assign to you, so that you or your team can work on it.
