### ISSUE TITLE
Relationships between same entity types are not supported

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/dspace-angular#1511]
**Describe the bug**

DSpace angular is currently missing support for relationships between the same type. 
Example: Linked publications, or parent and child projects. 

In the edit item -> relationships tab, you will only get one of those relationships and won't be able to add more items. 

**To Reproduce**
1. Set up a stock Dspace 7.2 to serve as the backend
2. Configure a relationship that uses the same entity type on both ends. 
```    <type>
        <leftType>Publication</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isPublicationLinkedTo</leftwardType>
        <rightwardType>isPublicationLinkingTo</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToRight>true</copyToRight>
    </type>
```
3. Go to the front end and ensure a couple of publications are present in the repository. 
4. Go to the edit Item page of one of the publications and to the relationships tab
5. Look through the present relationships 
6. Verify that there is a relationship present without a header, but just an add button
7. Verify that clicking that add button opens an empty modal instead of the normal lookup window

**Expected behavior**
1. The publication to publication relationship should be shown with proper title for both sides of the relationship. 
2. Users should be able to add new relationships through the add buttons
3. The added relationships should be displayed under the correct side of the relationship (isPublicationLinkedTo vs isPublicationLinkingTo)

**Comment by tdonohue** [comment]
Bumping up priority to *medium* as a slightly clearer use case may exist (based on this [dspace-tech thread](https://groups.google.com/g/dspace-tech/c/OyFlPHHVOTM/m/YCdDv7amAQAJ)).  One use case is relating an OrgUnit to another OrgUnit (which would be necessary to create an OrgUnit hierarchy).

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue
