### ISSUE TITLE
Detail component is missing for archived item in the mydspace

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1514]
**Describe the bug**
The archived items don't have the detailed component used in the mydspace with the detail view mode

**To Reproduce**
1. open the mydspace page
2. filter for only archived items
2. turn to the detail view mode using the view mode switcher 
3. since the there is no component using the detailed context for archived user the default list component is displayed
 
![Schermata da 2022-02-10 09-19-29](https://user-images.githubusercontent.com/2486489/153366124-647b79d2-0249-4fd1-a3dc-6f99ac9e16f2.png)

**Expected behavior**
The detailed view should display more information as done with workspaceitems or workflowitems, e.g. : 

![Schermata da 2022-02-10 09-14-41](https://user-images.githubusercontent.com/2486489/153366275-cb3fd51c-c833-49fc-a9f3-87034faff78f.png)

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Moving this to the 7.3 board.  Added a zero hour estimate to this task, as this bug will be fixed as part of #772, and is included in the 10hr estimate in that separate ticket.
