### ISSUE TITLE
Upload filename disappears on incomplete deposit

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1518]
**Describe the bug**
When depositing an incomplete submission, filenames disappear from the headings of `ds-submission-upload-section-file`

Before clicking "Deposit":
![20220214-112150](https://user-images.githubusercontent.com/31547038/153846488-b7a25c37-71ab-447a-b7d6-77cf9c303776.png)
After clicking "Deposit":
![20220214-112158](https://user-images.githubusercontent.com/31547038/153846583-28f8b004-06b1-48b9-ba92-74ff11592d49.png)

**To Reproduce**
1. Start a new submission (don't fill out any metadata)
2. Upload a file
3. Deposit
  * The submission should be saved, but not deposited since it's incomplete
  * **Bug: the upload's filename disappears from the top line**

**Expected behavior**
The uploaded file entry should stay exactly the same

**Related work**
#1427

**Comment by tdonohue** [comment]
Re-tested today, and this is no longer reproducible (on latest code, pre-7.3). I'm not sure when it was fixed, but appears to be fixed.
