### ISSUE TITLE
"Browsing by issue date" is stuck on loading

### ISSUE THREAD

**Issue by davidenegretti-4science** [DSpace/dspace-angular#1523]
**Describe the bug**

[Browsing by Issue Date](https://demo7.dspace.org/browse/dateissued)

Component: `browse-by-date-page`

If the first item contains a `dc.date.issued` metadata whose value is not a valid date, then:

-  the `lowerLimit` variable becomes undefined
-  this causes the `startsWithOptions` variable to remain undefined
-  this causes the loader to be indefinitely shown.

An additional check must be added in order to preserve the default value of `lowerLimit`

**Comment by davidenegretti-4science** [comment]
This is a 5-minute fix, could you assign it to me?

**Comment by tdonohue** [comment]
@davidenegretti-4science : Sure, will do! When it's a very quick fix, you are welcome to just create a corresponding PR immediately, in which case I'll assign it to you after the fact.  Thanks!
