### ISSUE TITLE
Errors using the "custom" theme in DSpace 7.2

### ISSUE THREAD

**Issue by pnbecker** [DSpace/dspace-angular#1528]
**Describe the bug**
When using the custom theme in DSpace 7.2, I see errors in the browser's console:

```
ERROR TypeError: Cannot read properties of undefined (reading 'injector')
    at NavbarComponent_ng_container_15_Template (navbar.component.html:9:109)
    at executeTemplate (core.js:9614:1)
    at refreshView (core.js:9480:1)
    at refreshEmbeddedViews (core.js:10605:1)
    at refreshView (core.js:9504:1)
    at refreshComponent (core.js:10651:1)
    at refreshChildComponents (core.js:9277:1)
    at refreshView (core.js:9530:1)
    at refreshEmbeddedViews (core.js:10605:1)
    at refreshView (core.js:9504:1)
```

This error is repeated multiple times.

The site looks like I would expect it should, but when I make any search, I do not see any results, filters, ...

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/6109314/154362089-f16cb4de-639c-4a55-839d-15f2399dcc1f.png">

**To Reproduce**
1. Checkout dspace-7.2
2. Copy config/config.example.yml to config/config.dev.yml
3. Edit config/config.dey.yml and change `themes.name` to `'custom'`
4. Edit docker/docker-compose.yml to set api7.demo.org as backend
5. Change directory into docker and run docker-compose build --no-cache && docker-compose up -d && docker-compose logs -f
6. When everything is running, open a browser, go to localhost:4000 and Open your browser's console.

**Expected behavior**
No error should show up in the browser's console when using an the custom theme without any changes. Opening the search should work normally.

**Comment by tdonohue** [comment]
@pnbecker : After further testing, I *am* able to reproduce this error. The reason I thought it worked is that I *never see this error on the Homepage*.  However, if I click on a Community, then I do see that error.  

I also see a different (but possibly related) error in my DevTools Console if I attempt to run a search (and no search results  page appears blank in the UI):
```
ERROR NullInjectorError: R3InjectorError(e)[InjectionToken searchConfigurationService -> InjectionToken searchConfigurationService -> InjectionToken searchConfigurationService -> InjectionToken searchConfigurationService]: 
  NullInjectorError: No provider for InjectionToken searchConfigurationService!
```

Pulling this onto the 7.3 board for analysis & flagging as `high priority`.  @artlowel , would you or someone on your team have a chance to look at this?  It looks like it's specific to the `custom` theme, as I'm not seeing this same behavior with the `dspace` theme.

**Comment by ybnd** [comment]
* [This provider](https://github.com/DSpace/dspace-angular/blob/736802cdbda6a78868b2a4cfaa4ab04bfd1ed9b0/src/app/search-page/search-page.component.ts#L8-L13) is missing from the `custom` themed component, adding it solves the main issue. 
Since this is theme-related & minor I'll add it on to #1512 tomorrow.
* The undefined `injector` issue is something else altogether
    * Sometimes (some of) the navbar items fail to render until you click the page
    * Adding a `?`-check when accessing the injector [here](https://github.com/DSpace/dspace-angular/blob/736802cdbda6a78868b2a4cfaa4ab04bfd1ed9b0/src/app/navbar/navbar.component.html#L9-L9) seems to solve this; I'm not seeing the errors anymore and the navbar always loads properly now.
    * Don't know if this fits in the theme PR though, on the other hand it's a one-character fix -- where should this go?

**Comment by tdonohue** [comment]
@ybnd : Since that `injector` issue is a one-line fix, I'm OK with simply adding it to your existing PR.  Other PRs sometimes cleanup small, unrelated bugs in a similar manner...as sometimes developers just stumble on something else while creating the PR.  Just add a note about it in the PR description.

**Comment by TimKuntze** [comment]
Solution by @ybnd solves this issue. Thanks a lot!

**Comment by pnbecker** [comment]
@ybnd thank you!

**Comment by tdonohue** [comment]
For the record, this issue was fixed by these two commits (in a larger PR):
* https://github.com/DSpace/dspace-angular/commit/fba1dfb689b18263b5c7ef9e92f301f6d2e2b528
* https://github.com/DSpace/dspace-angular/commit/2830da955739b61c91c15f587051b0d75f4e5464
