### ISSUE TITLE
Create "System Wide Alerts" feature for Angular UI

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1537]
**Is your feature request related to a problem? Please describe.**
In DSpace 6.x XMLUI, the Control Panel had a "System-wide Alerts" tab which allowed Administrators to enable an alert notification which would be displayed across every page in the DSpace site.  

Here's what that feature looked like:
![systemwide](https://user-images.githubusercontent.com/483997/155581417-f212c938-2a40-477c-b248-af336339a440.png)

As implied by that screenshot, it offered the options to:
1. Optionally, set a "Count down" timer.  When enabled, the alert would provide a countdown (in minutes).  This could be used to alert active users that the "Site will be going doing for maintenance in 1 hour" (for example)
2. Optionally, disable all authentication in the system.  This blocked users from newly authenticating into the system as soon as the systemwide alert was displayed. There was also the option to kill all existing sessions (which would immediately logout all authenticated users *except* System Administrators)

When enabled, this system-wide alert was automatically disabled if the site was restarted.  

**Describe the solution you'd like**

In DSpace 7, at a minimum, I think we should implement:
1. The ability to display such a system-wide alert, and enable/disable it as needed.
2. (ideally) Add the "count down" timer feature.

I feel the ability to block new authentication is _optional_ (but nice to have), as that may require a way for the Frontend to tell the Backend to block all authentication actions (and or to destroy existing JWTs).  It may therefore require more design & backend changes.

**Additional context**
While this feature was previously part of the Control Panel, we decided (in a meeting on Feb 24, 2022) that this should be broken out from #801 as a separate task, as this feature meets a slightly different Administrative use case.  It may even appear under a separate Administrative menu option in DSpace 7

**Comment by alawvt** [comment]
We use this in DSpace 6.x on a regular basis, for instance creating notices over vacation breaks about limited serve  and before planned down time. We'd like this DSpace 7.

**Comment by artlowel** [comment]
We'd like to claim this ticket

**Comment by tdonohue** [comment]
Sounds good @artlowel . Assigning to you for your team to work on. Please provide an estimate when you can do so.

**Comment by tdonohue** [comment]
Closing, fixed by #2025 and DSpace/DSpace#8624
