### ISSUE TITLE
Enable Coveralls to check test coverage for new PRs

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#155]
As suggested in #151, we should enable Coveralls.io to check the test coverage of any new PRs.  The goal would be that test coverage should improve over time. Therefore, ideally, no new PRs should decrease test coverage (though we can always make exceptions if necessary at times.

I've already given Coveralls access to this GitHub repo:
https://coveralls.io/github/DSpace/dspace-angular

But, I'm not sure I understand how to enable/configure it for an Angular / Typescript project (instructions seem to be Ruby specific). 

@wwelling is this something you'd be interested in helping quickly configure?

**Comment by wwelling** [comment]
@tdonohue yeah, I can do this.
