### ISSUE TITLE
Improve usability of TruncatableComponet

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1551]
**Is your feature request related to a problem? Please describe.**
Currently the `TruncatableComponent` has the aim of truncate long text and make it extendible/collapsible. We have received several feedback that detect it not so user friendly. Indeed the user needs to click on the text to extend/collapse itself and it is resulted not perfectly understandable.

**Describe the solution you'd like**
We suggest to add a more explicit button to use for extending/collapsing after the truncated text.
It should look similar to the following : 

![Schermata da 2022-03-11 11-14-31](https://user-images.githubusercontent.com/2486489/157849824-fc51cf16-8e03-41b0-b70a-70a74b89f3cd.png)

**Comment by atarix83** [comment]
@tdonohue
 
I'd add this topic as to discuss on the next community meeting, Do you agree?

**Comment by tdonohue** [comment]
@atarix83 : Sure, I'll add this to next week's meeting.  I do agree that it may need usability improvements. We also should keep in mind that it was noted as having accessibility issues as well, see #1164

**Comment by atarix83** [comment]
this is just another option where the toggle has a different style

![image-20220316-052430](https://user-images.githubusercontent.com/2486489/158819303-d086db2b-72dd-40dc-8a74-967584cc1f4b.png)

**Comment by ybnd** [comment]
The proposed fix would also address #1260
