### ISSUE TITLE
UX: delete a workflow group causes an error without enough information

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1557]
**Describe the bug**
If you try to remove  workflow group that is associated with some workflow tasks the backend raise a 422 error but the UI will just report a generic error

**To Reproduce**
1. create a collection
2. assign an editor role to the collection setting an user as member of the created group
3. deposit an item in such collection
4. try to remove the editor group

**Expected behavior**
A message saying that there are related workflow tasks and so the group cannot be removed would be more appropriate

**Comment by abollini** [comment]
would be appropriate to assume that the 422 status is only returned in such scenario as by the current code? if so, we can easily fix that just in the message otherwise this would required a major redesign of the error message on the rest side to include more details

**Comment by artlowel** [comment]
Showing a more specific error in case rest returns a 422 can be done in **2 hours**
We'd like to claim this task

**Comment by tdonohue** [comment]
@artlowel : Sounds good. Adding estimate & assigning to you.
