### ISSUE TITLE
Facet filters don't work if search field is used

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1575]
**WORKING**

Select a value from the facet, e.g. "HUMANITIES and RELIGION" from the Subject facet. The application will open this page, containing the search results:
[https://demo7.dspace.org/search?spc.page=1&f.subject=HUMANITIES%20and%20RELIGION,equals](https://demo7.dspace.org/search?spc.page=1&f.subject=HUMANITIES%20and%20RELIGION,equals)

**NOT WORKING**

Search a value in the search field of the facet:
![image](https://user-images.githubusercontent.com/87638927/159679600-a7a2f88e-a7ca-4c60-a230-0b8af8840523.png)

Select the value and press enter. The application will open this page:
[https://demo7.dspace.org/search?spc.page=1&f.subject=HUMANITIES%20and%20RELIGION](https://demo7.dspace.org/search?spc.page=1&f.subject=HUMANITIES%20and%20RELIGION)
![image](https://user-images.githubusercontent.com/87638927/159679526-59e3f48e-beeb-4cc5-854f-d6d40f871855.png)

`,equals` is missing from the query and no results are shown.

**Comment by tdonohue** [comment]
Sounds good @artlowel .  Adding estimate & assigning to you.
