### ISSUE TITLE
Names and values of text variables seem to differ

### ISSUE THREAD

**Issue by mhvezina** [DSpace/dspace-angular#1576]
I came across this while revising the French translation. Not sure about this but, is there a mismatch between the name and value of the following variables ? :

https://github.com/DSpace/dspace-angular/blob/59104c4fbe1d3ea63c1ea52af5477654f3c98b9e/src/assets/i18n/en.json5#L3286

  "search.filters.filter.**entity**Type.head": "Item Type",
  "search.filters.filter.**entity**Type.placeholder": "Item Type",
  "search.filters.filter.**entity**Type.label": "Search item type",
(...)
  "search.filters.filter.**item**type.head": "Type",
  "search.filters.filter.**item**type.placeholder": "Type",
  "search.filters.filter.**item**type.label": "Search type",
  
Shouldn't we have something like (?) :

  "search.filters.filter.entityType.head": "Entity Type",
  "search.filters.filter.entityType.placeholder": "Entity Type",
  "search.filters.filter.entityType.label": "Search entity type",
(...)
  "search.filters.filter.itemtype.head": "Item Type",
  "search.filters.filter.itemtype.placeholder": "Item Type",
  "search.filters.filter.itemtype.label": "Search item type",

**Comment by tdonohue** [comment]
@mhvezina : It might actually be that these i18n keys are duplicative.  Both "Entity Type" and "Item Type" are two words for the same idea.  All Entities are "typed" Items.  So, Entities all have a Type, which can be referred to as either it's "Entity Type" or "Item Type".

It's possible that one of these keys isn't being used and should be removed.  If not, we'd have to look closer at how these are used to determine the proper change.  (I haven't had a chance to dig into where these are used in the UI)

**Comment by mhvezina** [comment]
Thank you @tdonohue. So I will only use "Type" for translation, avoiding, for now at least, to specify if it is an entity or an item. I think the context will help to understand. https://github.com/DSpace/dspace-angular/blob/75bdf3de79ce0d8f0622b6c6ca5a7617bdf013ae/src/assets/i18n/fr.json5#L4615
