### ISSUE TITLE
"Primary Bitstream" toggle on Edit Bitstream page doesn't work

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1578]
**Describe the bug**
The "Primary Bitstream" toggle on the Edit Bitstream page doesn't work, even though a success message is returned to the user.

![primary](https://user-images.githubusercontent.com/483997/159997099-58bce0ee-214d-47ca-986a-50ad35ca29c7.png)

**To Reproduce**
1. Edit an Item with multiple bitstreams
2. On the "Bitstreams" tab, edit one bitstream
3. Mark it as the Primary Bitstream by moving the toggle.  Click Save
4. You will see a "Bitstream Saved" success message.  But, if you go back to the Bitstream, you'll see that it is NOT marked as the primary bitstream

In Chrome DevTools, the following notices will appear in the console:
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8080/server/api/core/bitstreams/dcefbc84-dca2-434f-b049-23578c43e0b0/content with MIME type application/pdf. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Form submission canceled because the form is not connected
```

NOTE: Other fields on that same page work properly, though they also seem to show the "Cross-Origin Read Blocking" notice...so it's possible that's not the root cause.

**Expected behavior**
Obviously, this toggle should work since it appears on the page.

**Related work**
Depends on https://github.com/DSpace/DSpace/issues/3349 (as it appears we do not have endpoints to support this feature yet)

**Comment by tdonohue** [comment]
As discussed in today's meeting, it appears we don't yet have a REST API endpoint to support Primary Bitstreams.  So, that would need to come first.  We discussed it may be necessary in two places:
* Submission Side (selecting primary bitstream during submission), perhaps as part of the Upload endpoints: https://github.com/DSpace/RestContract/blob/main/submissionuploads.md
* Bundle Side (updating/selecting primary bitstream while editing): https://github.com/DSpace/RestContract/blob/main/bundles.md

Both of these are mentioned in ticket https://github.com/DSpace/DSpace/issues/3349, but obviously this specific ticket only depends on implementing a Bundle endpoint.  Currently, it appears the Bundle endpoint can return the primary bitstream but doesn't offer a way to update which bitstream is "primary": https://github.com/DSpace/RestContract/blob/main/bundles.md

I'll enhance the description of https://github.com/DSpace/DSpace/issues/3349 to add these details.   This ticket appears to depend on that backend ticket being resolved (or partially resolved)

**Comment by artlowel** [comment]
@tdonohue we'd like to work on this for 7.6

**Comment by tdonohue** [comment]
Per today's meeting, assigning to @artlowel / Atmire for 7.6. Thanks!

Per Steering decision on March 22, this work is *funded* development for 7.6
