### ISSUE TITLE
Bitstream edit page is broken if no policies are set

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1584]
**Describe the bug**
If you remove all the policies of a bitstream the edit bitstream page is broken and you cannot add back any policies or edit bitstream metadata.
The bitstream edit authorization page should be improved to include the breadcrumbs as the other pages and the name of the bitstream that you are editing

**To Reproduce**
1. remove all the policies associated with a bitstream
2. check the edit bitstream page (it is broken, no form is presented)
3. check the edit bitstream authorization page, it works but there is no option to add new policies nor explicit mention that no policies are in place

**Expected behavior**
It should be possible to fix this situation from the UI and still edit bitstream metadata

**Related work**
This is somehow related to https://github.com/DSpace/dspace-angular/issues/1583

**Comment by tdonohue** [comment]
Definitely seems like a high priority bug. Thanks for reporting. Pulling over to 7.3
