### ISSUE TITLE
Menu options can't contain parameters

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1586]
**Describe the bug**
It's currently impossible to add parameters to a link in the menu. The reason is that the link is put into [the `routerLink` input of an `<a>` tag](https://github.com/DSpace/dspace-angular/blob/714ea5d8f9d526e90bcfa650a81475e6bd6e90f5/src/app/shared/menu/menu-item/link-menu-item.component.html#L5), and that doesn't allow parameters directly. They will be escaped and considered to be part of the path. Instead you need to provide a `queryParams` object as a separate input

**To Reproduce**
And easy example to reproduce the behavior:
1. Add `?startsWith=e` to the end of [the browse menu links](https://github.com/DSpace/dspace-angular/blob/504604cfc7c16aa44a2044714413b6e2d7308e0d/src/app/navbar/navbar.component.ts#L80)
2. Build the app 
3. Notice that if you click any of those links you get an infinite loading screen.

**Expected behavior**
It should be possible to add params to a menu link. The easiest way to support it seems to be to add that `queryParams` property to the `LinkMenuItemModel` as well.

**Related work**
N/A

**Comment by tdonohue** [comment]
@artlowel : This seems reasonable to me. I'll add the estimate & assign back to you for your team to work on for 7.3
