### ISSUE TITLE
Scope selector is missing from search box

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1588]
**Describe the bug**

Scope selector is missing from search box. `showScopeSelector` flag has been set to `false` by default.

![image](https://user-images.githubusercontent.com/87638927/162403154-f39c7da7-538b-427a-b930-da8fce48c4ce.png)

**Expected behavior**

`showScopeSelector` flag should be set to `true` by default. It would be useful to make this configurable through the Angular configuration file (three different configuration variables for public search, MyDSpace, and relations).

**Comment by davide-negretti** [comment]
We'd like to take this task. Estimated effort is 2-4 hours.

**Comment by tdonohue** [comment]
I see that behavior on demo7.dspace.org as well.  It appears this scope selector has disappeared / isn't loading, e.g. https://demo7.dspace.org/search?query=test

@davide-negretti : I'll add this to the 7.3 board, add the estimate & assign to you for you or your team to fix it.
