### ISSUE TITLE
Separate Build step from Deployment to avoid downtime during rebuild

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1594]
**Is your feature request related to a problem? Please describe.**
Based on [this dspace-tech question](https://groups.google.com/g/dspace-tech/c/lyKYM19kJ1Y).

Currently we don't do a great job of separating the `dspace-angular` build step from the deployment step.  In other words, when using our default [UI installation instructions](https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-FrontendInstallation), we don't provide Production deployment/redeployment instructions which can minimize downtime.

Instead, currently we recommend a process that looks like this:
* Build/Deploy via `yarn run build:prod`  (builds to `./dist`)
* Startup via `pm2 dspace-angular.json` or `yarn run serve:ssr`  (runs app from `./dist`)

While this process works well, whenever you want to rebuild your application, the application will be **unavailable during the rebuild process** (usually takes around 10mins or so).  This is because we are encouraging running the application from `./dist`, and the first step of any rebuild is to destroy whatever is in `./dist`.

**Describe the solution you'd like**

Ideally, we'd provide tools & documentation to better minimize application downtime when a rebuild takes place.  This might be implemented by _one of the following approaches_ (other approaches may also work):
*  Building a custom [`ng deploy` command](https://angular.io/guide/deployment) which can copy `./dist` to a different filesystem location (e.g. `./deploy`), and then creating a new `yarn serve:prod` command that runs the application from `./deploy`.
* Or, perhaps, achieving that same approach using a custom Webpack command to copy from `./dist` to `./deploy`, and mapping it to `yarn deploy:prod`.  This would allow for you to build (`yarn build:prod`), deploy (`yarn deploy:prod`) and restart (`yarn start:prod`) as three separate steps.

**Describe alternatives or workarounds you've considered**
Alternatively, we might provide clearer documentation on how to copy the `./dist` folder to a different location and run it via PM2 (or `yarn`) from that separate directory.

**Comment by tdonohue** [comment]
@artlowel and @atarix83 : I'd appreciate your thoughts on this.  I'm not sure of the best approach here, or maybe I'm overlooking a way to achieve this more easily.

**Comment by mwoodiupui** [comment]
"Copy the `./dist` folder" is what I've always done.

**Comment by tdonohue** [comment]
@mwoodiupui and I worked out an alternative approach here, where the `dist` folder can be copied to a different location, so that it is not touched during the next rebuild.  But, there are two rules to keep in mind with this approach:
* The `dist` folder MUST NOT BE RENAMED.  We have runtime code that expects this folder to be named `dist`, and if you rename it to something like `deploy`, then the app cannot be started successfully.
* You MUST either use environment variables for configuration, or create a `./config/config.prod.yml` in the same relative location as `./dist`.

Here's how to setup that approach:
1. First, build the app: `yarn run build:prod`  (creates the `dist` folder)
2. Then, MOVE the `dist` folder to a different location outside of the `dspace-angular` project directory, e.g. `/some/where/dist`
3. Specify configs as environment variables, or create a `./config/config.prod.yml` in that same location, e.g. `/some/where/config/config.prod.yml`
4. Finally, start the app using *node* (instead of yarn) from that location: `cd /some/where; node dist/server/main`

With that setup, you can rebuild with minimal downtime.  Just repeat those steps to rebuild & redeploy.  Since the deployed version is in a different location, it will remain up while you are rebuilding.

**Comment by tdonohue** [comment]
Alternative found by @wwelling .  If we wanted to *keep* using the `dist` folder both for build & deployment, we could use an approach like described in this blog post: https://alexdevmotion.medium.com/implementing-angulars-missing-delete-output-path-after-build-option-468f83add157   It's a non-standard approach using a temp directory, but it seems like it'd work.

**Comment by mwoodiupui** [comment]
The destination tree must be writable by the user that will run `node`.  dspace-angular wants to write a combined configuration file to `dist/browser/assets/config.json`.  (We should fix that someday.)

**Comment by tdonohue** [comment]
After more thought, I've realized this ticket might just be a **Documentation Issue**.  Our existing [UI Installation Docs](https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-FrontendInstallation) are slightly backwards now that we've fixed #1410 and #1422.  By reordering a few of the steps we can simplify things.

Now that `dist` contains everything, and we have runtime configs, the corrected installation instructions should likely just be:
1. `yarn install`
2. `yarn build:prod` (to create `dist`)
3. Copy `dist` to a different "deployment" location (i.e. somewhere outside of the "dspace-angular" codebase)
4. Copy/create `config.prod.yml` in same deployment location (or use Environment variables).
5. Setup PM2 to use new `dist` location & just use Node.js to start the app.

This would provide a better separation between build & deploy, as Yarn would only be used during steps 1 & 2.  After that, we'd document how to run the application using **Node.js** directly.

(Sidenote: we still may want to solve the issue of allowing people to rename the `dist` directory to something else... as it may be a common "mistake" to rename this directory & wonder why it is no longer working.)

**Comment by mwoodiupui** [comment]
This sounds like the right approach.  (Of course I think so:  that is essentially what I have been doing all along.)

And yes, the code in `dist` should not know or care how the deployment directory is named, if we can make that happen.

**Comment by tdonohue** [comment]
Per [my last comment](https://github.com/DSpace/dspace-angular/issues/1594#issuecomment-1096823388), I just did a major refactor of the Frontend Installation docs to recommend creating a separate deployment directory.  Reviews / improvements welcome!

https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-FrontendInstallation

**Comment by tdonohue** [comment]
I'm going to close this ticket as "fixed" as the Documentation changes to our Installation Guide fix the main issue here.  In the new installation instructions, the Build step is now separate from Deployment: https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-FrontendInstallation
