### ISSUE TITLE
Import locale data for all languages

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1596]
**Describe the bug**

The pipe `number` allows to format a number according to the default `en-US` locale.

`const myNumber = 12345678.9`
`{{ myNumber }}` renders as _12345678.9_
`{{ myNumber | number }}` renders as _12,345,678.9_ with default `en-US` locale

Other locales use different decimal and thousand separators.
`{{ myNumber | number : '' : 'it-IT' }}` should renders as _12.345.678,9_

Angular requires all locales (except `en-US`) to be added manually. All locales used by DSpace 7 should be imported in `app.module.ts`.

See:

- https://angular.io/api/common/DecimalPipe
- https://angular.io/api/core/LOCALE_ID
- https://github.com/angular/angular/issues/20286#issuecomment-343649893

**Comment by davide-negretti** [comment]
We'd like to handle this issue. Estimated effort is <4 hrs

**Comment by abollini** [comment]
we reviewed that internally and it looks like a "technical issue" without any concrete examples in the current DSpace feature set. For this reason we suggest to close it or just leave in the backlog for the future. We will reopen/followup if/when a real use case emerge

**Comment by tdonohue** [comment]
Thanks @abollini. I'll close this for now as "won't fix" but we can always reopen at a later date if we determine a fix for this is necessary.
