### ISSUE TITLE
Dev mode (`yarn start:dev`) doesn't fully work in Angular 13

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1614]
**Describe the bug**
Appears to have been caused by #1567 .

The `yarn start:dev` command no longer works completely (e.g. it's not possible to login).  While the UI will build/start successfully, the entire header (including the login menu) is missing.  Here's a screenshot:
![homepage](https://user-images.githubusercontent.com/483997/165363531-2a2f0a5b-cb34-4d9a-9754-1e4ae4611474.png)

**(Notice that the entire header is missing, including logo, browse by options, login, etc.)**

When the homepage loads a number of `TypeError`s appear in the Chrome DevTools Console, related to both `lang-switch.component.ts` and `themed.component.ts`.

**To Reproduce**
I've tested this on Windows and via Docker (running Linux). Both show the same behavior.

1. Run `yarn start:dev` (or alternatively `NODE_ENV=development yarn serve`, which is the base command)
2. Once completed, access http://localhost:4000/

NOTE: It *is* possible to run the UI in semi-"dev mode" using `yarn serve` (without specifying NODE_ENV).  However, in that scenario the UI uses `config.prod.yml` and not `config.dev.yml`.

**Expected behavior**
`yarn start:dev` should work, or we should provide an alternative command to run for development.

**Related work**
Appears to have started after #1567 was merged.

**Comment by tdonohue** [comment]
@artlowel and @ybnd : I'm assigning this ticket to you as it appears to be a side effect of Angular 13 upgrade in #1567  (at least I _think_ that's where the issues may have begun...as it appears that PR made changes to the development build process.)

**Comment by ybnd** [comment]
I can't seem to reproduce this, the header is always showing up for me and no `TypeError`s to be found...
Same thing on everything I have around (MacOS, Manjaro Linux, Windows)

**Comment by artlowel** [comment]
@tdonohue Is it possible you reviewed a PR using a language that isn't available in the main branch? If so, remove your language cookie and it should work again. This is arguably a bug (however it can only occur if your cookie contains a language that no longer exists, so it's not very likely to happen in the wild), but it's been around forever, and isn't related to https://github.com/DSpace/dspace-angular/pull/1567

**Comment by tdonohue** [comment]
@artlowel : Yes, I think you are correct.  This started occurring after I did some testing of #1519 (a new Turkish translation).  I didn't make the connection that would be related to this issue.

My apologies to you and @ybnd .  It does appear this is a bug, but it likely only occurs in this odd scenario.  I'll retest things on my end to be sure that it no longer appears after clearing my cookies.

**Comment by tdonohue** [comment]
Closing, verified that this was a problem with my language cookie pointing at an unavailable translation.  The workaround is to remove the cookie, or spin up in production mode (`yarn build:prod; yarn serve:ssr`) and select a different language.
