### ISSUE TITLE
Radio buttons are broken in Angular submission

### ISSUE THREAD

**Issue by Raf-atmire** [DSpace/dspace-angular#1616]
**Describe the bug**
Radio buttons in Angular's submission form are broken. This is due to the fact that it isn't created in the correct way [this](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list.component.html#L48) is how it's created in Angular and [this](https://getbootstrap.com/docs/4.4/components/forms/#radios) is how it should be done

**To Reproduce**
1. Create an inputform with radio buttons in REST
2. Go to the submission in Angular
3. Try to select any of the options
4. You won't be able to select it

**Expected behavior**
You should be able to select a value

Atmire would like to claim this issue, estimated time to fix and test this would be 4 hours of work.

**Comment by tdonohue** [comment]
@Raf-atmire : Thanks for reporting. I'll assign this back to you to work on for 7.3 based on that estimate.  Please feel free to delegate it internally as needed.
