### ISSUE TITLE
The search bar (`ds-search-form`) with given (input) `scope` is not applied

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1635]
**Describe the bug**
When re-using the search bar on the homepage (`ds-search-form`) on for example the collection page, by giving it a set scope (`@input scope`), then a search with that bar does not contain the expected scope filter in url nor its results.

**To Reproduce**
1. Add a search bar component to the collection homepage. Add 
```
      <ds-search-form [inPlaceSearch]="false"
                      [searchPlaceholder]="'home.search-form.placeholder' | translate"
                      [scope]="communityRD?.payload.uuid">
``` 
to `src/app/community-page/community-page.component.html` 

2. Do a search on a collection homepage with or without query, it will navigate to `{uiUrl/search?query={query}` but will contain no `&scope={collectionUUID` in url, nor will the results be limited to items in that collection.

**Expected behavior**
The `@input scope` of the search bar (`ds-search-form`) should imply that if it is not empty, that this scope is used in the search from that instance of the search bar. So a `ds-search-form` on the collection home page, with scope = uuid of that collection, should go to the search showing results in that collection only (and scope in url).

**Comment by MarieVerdonck** [comment]
This will take an estimated **2 hours**

**Comment by tdonohue** [comment]
@MarieVerdonck : This sounds reasonable. I'll pull this over to the 7.3 board and assign back to you.  However, if you don't get to it, we may just move it over to 7.4 board as needed.
