### ISSUE TITLE
Users with read-only access rights should not be able to access the sidebar menu

### ISSUE THREAD

**Issue by lep-flp** [DSpace/dspace-angular#1643]
**Describe the bug:**
An eperson group with ONLY read, default_item_read, and default_bitstream_read on items/collections/communities could still access the sidebar functions: new, edit, import, and delete.

**To reproduce**

1. Log-in as top-level admin
2. Create an eperson group (say, "regular user group") and assign add a new eperson to that group
3.  Authorize the "regular user group" to ONLY have read, default_bitstream_read, and default_item_read on items/collections/communities.
4. Log-in as that newly created eperson which belongs in the "regular user group"
5. Try accessing the sidebar menu.

The user could see: new, edit, import, and export functions. Now, these functions are rendered useless, since the user does not have any elevated roles as it only has "read" access to all items/collections/communities.

**Expected Behavior:**
This eperson group should not be able to access the sidebar, they should not be able to create new items, edit items, import metadata and export metadata. These functions should only be visible if the user has elevated roles (write, add, admin, delete, etc.)

**Related work**
Too many functions available for logged in (non-admin) persons #1483

**Comment by tdonohue** [comment]
Agreed this is incorrect behavior & confusing.  We've cleaned this up slightly in pre-7.3, but users with no permissions are still shown **two menus**:  `New -> Item`, and `Edit -> Item`.  I do agree this would be good to fix further, though not sure if we'll have time prior to 7.3.

**Comment by lep-flp** [comment]
Hi! Thanks for recognizing my issue. I want to configure it myself, could you tell me which files should I configure to totally remove the sidebar for a specific user group only? Thanks!

**Comment by artlowel** [comment]
We'd like to claim this ticket

**Comment by tdonohue** [comment]
@artlowel : That sounds reasonable. I'll assign back to you for your team to work on & add the estimate.
