### ISSUE TITLE
Invalid data (with a comma) in dspace.entity.type makes item uneditable

### ISSUE THREAD

**Issue by Chris-Clawson** [DSpace/dspace-angular#1654]
DSpace Angular 7.2

Ubuntu 20.04
 web server

Accidental or improper entries in an item's dspace.entity.type metadata causes the item to hang DSpace when attempting to view or edit. The item may only then be fixed by importing a data corrected CSV spreadsheet.

**Repeatable procedure:**

* Select a normal and good item and edit the contents of dspace.entity.type with the following:
`Couture Bros., Turners Falls, Montague, Franklin County`

(This was the data erroneously added in the original problem)

Once saved, the item will display in Collection summaries (showing the bad data as an entity) but will hang DSpace and prevent viewing, editing or deletion.

**Discussion:**

This was caused in error by an associate with admin privileges who mistook the 'Relationships' tab for a place to enter keywords. I was also able to find this tab active (with a drop down menu), but have since found it only saying “Add 'dspace.entity.type' metadata to enable relationships for this item “. The main Metadata Edit tab shows 'dspace.entity.type' as being defined, but with no data in the cell. I still do not know how to activate this 'Relationships' tab and repeat the exact scenario I believe led to the problem.

(corrupted exports?)

I also originally had Collection level metadata exports either failing or providing the wrong collections. I was able to fix the original problem by successfully exporting at the Community level, deleting the contents of the bad cell and then importing back that row to DSpace.

I am sorry I can't repeat the other points raised in this discussion, but hopefully focusing on the repeatable portion will prevent the other stuff in the future.

**Comment by tdonohue** [comment]
@Chris-Clawson : Wanted to make sure you saw this was just fixed (to be released in 7.3) via #1658
