### ISSUE TITLE
Unable to add relationship

### ISSUE THREAD

**Issue by unibravo** [DSpace/dspace-angular#1661]
**Describe the bug**
Unable to add relationship
No suitable match could be found for relationship type isAuthorOfPublication between the two items

<img width="716" alt="isAuthorofPublication" src="https://user-images.githubusercontent.com/22861527/169912902-02af7f5b-d2e1-467c-ba76-acfab0404f67.png">

**To Reproduce**
1. New Item
2. Select Author...

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@unibravo : I'm not able to reproduce this issue with the latest code (pre-7.3).  So, either it's a configuration issue on your end, or perhaps it's already been fixed.  Here's a screenshot of me creating a new "Publication" entity and having already linked it to two "Person" entities in the Author field.
![entities](https://user-images.githubusercontent.com/483997/170125434-a7fb359e-c73f-4bdd-b417-bddc828a4d1f.png)

If you are still seeing this error, you should check for the specific, underlying error message behind this issue.  See our troubleshooting page for details on finding the specific error message in either your browser's DevTools or the backend logs: 
https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

Also, since it looks like you *might* be using our demo Entities data, you should make sure you've also uncommented the demo Entities submission configs in the `item-submission.xml`....as those configs properly setup the submission forms for each Collection in that demo Entities data: https://github.com/DSpace/DSpace/blob/main/dspace/config/item-submission.xml#L36-L49

**Comment by unibravo** [comment]
Dear Tim Donohue, thanks for reply.

Chrome Console:
dspace-rest-response-parsing.service.ts:155 The response for 'http://dspace.unirepos.com/server/api/discover/search?configuration=person' has the self link 'http://dspace.unirepos.com/server/api/discover/search'. These don't match. This could mean there's an issue with the REST endpoint

My configurations:
in .cfg file:
dspace.server.url = http://dspace.unirepos.com/server
dspace.ui.url = http://dspace.unirepos.com

and my Angular conf:
ui:
  ssl: false
  host: localhost
  port: 4000
  nameSpace: /
  rateLimiter:
    windowMs: 60000 # 1 minute
    max: 500 # limit each IP to 500 requests per windowMs
rest:
  ssl: false
  host: dspace.unirepos.com
  port: 80
  nameSpace: /server

Nginx Conf:

server {
        listen       80;
        server_name  dspace.unirepos.com;

        location /server {
        proxy_pass http://localhost:8080/server;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        }

        location / {
        proxy_pass http://127.0.0.1:4000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        }
}

And uncommented item-submission.xml

         
        <name-map collection-handle="default" submission-name="traditional"/>

        <name-map collection-handle="123456789/3" submission-name="Publication"/>
        <name-map collection-handle="123456789/4" submission-name="Publication"/>
        <name-map collection-handle="123456789/281" submission-name="Publication"/>
        <name-map collection-handle="123456789/5" submission-name="Publication"/>
        <name-map collection-handle="123456789/8" submission-name="OrgUnit"/>
        <name-map collection-handle="123456789/6" submission-name="Person"/>
        <name-map collection-handle="123456789/279" submission-name="Person"/>
        <name-map collection-handle="123456789/7" submission-name="Project"/>
        <name-map collection-handle="123456789/280" submission-name="Project"/>
        <name-map collection-handle="123456789/28" submission-name="Journal"/>
        <name-map collection-handle="123456789/29" submission-name="JournalVolume"/>
        <name-map collection-handle="123456789/30" submission-name="JournalIssue"/>

**Comment by tdonohue** [comment]
@unibravo : As I noted above, you should locate the underlying error message. See https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)  Without the underlying error message, this would be impossible to debug as I cannot reproduce it.

If you need additional help/support, please use one of our support options at https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by mrgurgel** [comment]
@unibravo did you solve this issue?
I'm facing it with DSpace 7.4

**Comment by MW3000** [comment]
I run into the exact same issue in DSpace 7.5.    
There is no error message neither on the browser console, nor in the backend or frontend log.
I use the sample entities configurations that come with the 7.5 release.

Please reopen this issue @tdonohue

**Comment by MW3000** [comment]
The error message on screen is triggered in `src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts` line 200: https://github.com/DSpace/dspace-angular/blob/bbec2fd038e11e65495c3bae6dfd09b6b20cdcde/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts#L200

**Comment by MW3000** [comment]
In my case the problem lied in a collection not having the right entity type associated with it. The reason was: https://github.com/DSpace/dspace-angular/issues/2123

**Comment by MW3000** [comment]
Instead of "between the two items" an error message that says "between an item of type x and an item of type y" would expose the underlaying issue (actual relationships between two item types do not match the relationships in the input form) immediately.

**Comment by tdonohue** [comment]
@MW3000 : I agree that might make better wording.  If you wanted to help out and create a PR here, it looks like that'd be a small change to relationship.effects.ts, which displays that error message here: https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts#L200

It looks like that area of the code already knows the two Item types, but just doesn't display them in the error message:  https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.ts#L171-L172

So, customizing this message might be relatively easy... just needs a volunteer.
