### ISSUE TITLE
Translation (latvian) not working because of missing comma in json5

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1662]
**Describe the bug**
Currently the translation (from `lv.json5` file) isn't working because of a missing comma [here](https://github.com/DSpace/dspace-angular/blob/main/src/assets/i18n/lv.json5#L5555) 

**To Reproduce**
1. Select the translation `Latviešu` in the dropdown
2. Shows the English labels despite having translations in the `lv.json5` file
3. When this comma is added, then it does show the translated labels

**Suggestion solution**
Let sync script check that the actual label lines end in a comma, and if not add it, so this kind of non valid json is fixed by run of the sync i18n sync script `yarn run sync-i18n`

**Comment by MarieVerdonck** [comment]
This will take an estimated **1 hour** to handle this case with the `sync-i18n-files` script

**Comment by tdonohue** [comment]
@MarieVerdonck : Please feel free to submit the PR & that way we can try to fit this into 7.3.  Assigning back to you. Thanks!
