### ISSUE TITLE
Stale page after Shibboleth authentication

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1665]
**Describe the bug**
If you begin at an object like a community and log in via Shibboleth to view restricted collections or sub-communities these objects don't appear until you reload the page in your browser.  This could be a manifestation of a more general problem with updating UI state after Shibboleth login.

**To Reproduce**
1. Navigate to a community or collection with restricted content.
2. Authenticate as an authorized user via Shibboleth
3. After authenticating the restricted content will not appear and a browser page reload is required.

**Expected behavior**
After you login as an authorized user the restricted content should appear in the UI.

Related to #1515?

**Comment by tdonohue** [comment]
This needs to be retested with 7.4, as it's possible this behavior has been fixed by #1805.

**Comment by artlowel** [comment]
We'd like to claim this ticket

**Comment by tdonohue** [comment]
Sounds good @artlowel . Assigning to you for your team to work on. Please provide an estimate when you can do so.

**Comment by mspalti** [comment]
I have a proposal for fixing this. I'll submit the PR tomorrow.

**Comment by tdonohue** [comment]
Additional fixes applied in #3011
