### ISSUE TITLE
Google Analytics Universal Analytics ID loses support on July 2023

### ISSUE THREAD

**Issue by ConfusionOrb221** [DSpace/dspace-angular#1672]
Google Analytics is going to lose support of the UA ID on July 2023 the code currently in [google-analytics.service.ts](https://github.com/DSpace/dspace-angular/blob/main/src/app/statistics/google-analytics.service.ts#L40-L46) only supports the UA identifier, this needs to be changed to use the G-ID for Google Analytics 4 to keep it up to date.

Currently we’re not using GA directly. Instead we use [angulartics2](https://github.com/angulartics/angulartics2), both for google analytics, dspace’s own analytics, as well as any other analytics we might like to add
So I’d look into upgrading to the new IDs using angulartics itself, I expect they have a different plugin we could use.

**Comment by tdonohue** [comment]
Assigning to @abollini , as this is the frontend ticket which corresponds to https://github.com/DSpace/DSpace/issues/8413.  4Science has been assigned both.
