### ISSUE TITLE
Move route subscription out of app component

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#1683]
**Describe the bug**
https://github.com/DSpace/dspace-angular/issues/1668 reported route dependent themes wouldn't be resolved correctly on first page load. This was fixed in https://github.com/DSpace/dspace-angular/pull/1669 by running that theme check on a later route event, if it hadn't already happened.

However that's a workaround. The reason for the issue seems to be that we subscribe to the route events inside a component, and when that component is first rendered, most of the events for the first route operation have already happened. So a better solution would be to move that subscription out of the component

**Expected behavior**
We should subscribe to the route in a single place, early enough to catch all route events, so that can't happen inside a component. A dedicated service, or an `APP_INITIALIZER` function is likely a better idea.

Afterwards we should roll back the changes in https://github.com/DSpace/dspace-angular/pull/1669

**Related work**
- https://github.com/DSpace/dspace-angular/issues/1668
- https://github.com/DSpace/dspace-angular/pull/1669

**Comment by artlowel** [comment]
@tdonohue I would argue that this is a high priority issue, as it seems it applies to more than just the route subscription.

We noticed a problem with a client recently that had different menu options based on the language, but because the menu is now created in a resolver instead of a component (as a part of https://github.com/DSpace/dspace-angular/pull/1627 to prevent the menus flickering on the first page load) the languages, that are initialized in app component as well, aren't set yet.

Apart from language and routing, other things are initialized in AppComponent that could turn out to be too late. E.g. [our model decorators are read there](https://github.com/DSpace/dspace-angular/blob/c4f2e8ce1147ebff8aa3668b0a9ebd00cc7135fc/src/app/app.component.ts#L118-L119). This could cause issues where a rest response can't be parsed before AppComponent has initialized, but can afterwards. [Angulartics tracking](https://github.com/DSpace/dspace-angular/blob/c4f2e8ce1147ebff8aa3668b0a9ebd00cc7135fc/src/app/app.component.ts#L156) is also initialized in app component. It might miss the first event.

I think we should change the scope of this ticket to move all initialization that isn't directly modifying the DOM out of app component, to ensure it triggers as early as possible after the app boots. 

Rather than adding yet another `APP_INITIALIZER` for this, I'd also use the opportunity to move all the code that's currently in multiple separate `APP_INITIALIZER` providers ([here](https://github.com/DSpace/dspace-angular/blob/c4f2e8ce1147ebff8aa3668b0a9ebd00cc7135fc/src/app/app.module.ts#L104-L109), [here](https://github.com/DSpace/dspace-angular/blob/bb5cdfc1a369e4b0913501c20dff45ecb236f795/src/modules/app/browser-app.module.ts#L76-L94) and [here](https://github.com/DSpace/dspace-angular/blob/bb5cdfc1a369e4b0913501c20dff45ecb236f795/src/modules/app/server-app.module.ts#L64-L76)), to a service, with an implementation for the Server and one for the Client, that does all the actual initializing we need, and does it in a predictable order. Because when using multiple `APP_INITIALIZER`s  that order isn't guaranteed. The initialization code we need to move out of app component can then also be added to this service.

We'd like to work on that. I expect it will take about **20 hours**

**Comment by tdonohue** [comment]
@artlowel : Ok, I'm fine with bumping this up, as it sounds like you are implying this could also help solve (or be a step to solving) other potential "caching" issues (where menus aren't refreshed/loaded properly)?  I wonder if this would end up having an impact on issues that reappeared after #1627 , such as #1665  (which we had fixed previously, but then appeared again after page load was improved)  

In any case, it does sound to me like this is higher priority than I initially though.  I'll add the estimate & bump up the priority, feel free to work on this for 7.4
