### ISSUE TITLE
Item action button disabled after redirect from action page

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1695]
**Describe the bug**
After withdrawing/reinstating an Item and getting redirected back to `/edit/status`, the reinstate/withdraw button is disabled.

**To Reproduce**
1. Log in as an admin
2. Edit any archived Item
3. Click "Withdraw" and confirm
   * You will be redirected back to `/edit/status`
   * The "Reinstate" button will be disabled
4. Refresh
   * The "Reinstate" button will no longer be disabled
5. Click "Reinstate" and confirm
   * You will be redirected back to `/edit/status`
   * The "Withdraw" button will be disabled
6. Refresh
   * The "Withdraw" button will no longer be disabled

**Expected behavior**
The buttons should _not_ be disabled after the initial redirect.

**Underlying issue**
This happens because the Item's authorization features are taken from the cache after the redirect; if the action changes them this does not get reflected on the status page.
Currently this is only noticeable for `withdrawItem` & `reinstateItem`.

@artlowel suggested this should be solved more generally:
* When a cached DSO is invalidated via [`DataService.invalidate()`](https://github.com/DSpace/dspace-angular/blob/26ed23d1b6ea61922de1ee431aba56dc35afd9ca/src/app/core/data/data.service.ts#L583-L583), cached authorizations related to it should be invalidated as well
* We'd need to have a way of retrieving the related authorizations, for example by keeping an index of UUID → authorization.
 Even more generally, we may want to index _resources that depend on other resources_; DSO → authorization would be a specific case of this.
* Once something like the above is in place, the bug can be solved by adding an `invalidate(item)` call to [`ItemDataService.setWithDrawn`](https://github.com/DSpace/dspace-angular/blob/26ed23d1b6ea61922de1ee431aba56dc35afd9ca/src/app/core/data/item-data.service.ts#L132-L132) and similar methods

**Related work**
#1608

**Comment by tdonohue** [comment]
@ybnd : Thanks...pulling this bug over to the 7.4 board.  Let me know if you or anyone on your team would like to work on it (or already are doing so)

**Comment by artlowel** [comment]
We'd like to claim this issue. The approach in the description will take about **12 hours**

**Comment by tdonohue** [comment]
Sounds good @artlowel !  Assigned to you for your team to work on
