### ISSUE TITLE
List grid view switcher

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#171]
Create a component to switch between the list and the grid views for sets of items, as depicted in [the mockups on the wiki](https://wiki.duraspace.org/display/DSPACE/Search+Mockup#SearchMockup-Facetsareshowninasidebar)

The icons should be links that redirect to the current page (with any set of request params it may already have) and set the view param to `list` or `grid` accordingly, overwriting it if it already exists.

The reasons to make them links are
	- to ensure they also work with js disabled.
	- for usability sake: since they redirect to a different page they should be `a` tags

Use font-awesome icons: [list](http://fontawesome.io/icon/list/) and [grid](http://fontawesome.io/icon/th-large/). Font awesome should already be included in the project

If the search sidebar component is already finished, put this component on the sidebar as shown in the mockup. If it isn't, just add it to the top of the search page somewhere. It will be moved to its correct position later.

**Comment by rivaldi8** [comment]
I've done a first implementation in [this branch](https://github.com/rivaldi8/dspace-angular/tree/bug-171-list-grid-view-switcher).  In it I've defined a new option in `SearchOptions`. My doubt now is, should I set it from `ListGridSwitchComponent` or will the parent component do so after being notified of the change in the query parameters?

**Comment by artlowel** [comment]
I'd set the request param in a new method in the SearchService, and call that method from the ListGridSwitchComponent. e.g. `this.searchService.setViewMode(ViewType.Grid)`.  That way the components don't contain too much logic.
Perhaps also rename the ListGridSwitchComponent to ViewModeSwitchcomponent or something similar, in case we ever add a third mode
