### ISSUE TITLE
In facets, vertically align checkbox with first word of option

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1711]
**Describe the bug** DSpace 7.2?
As first reported in https://groups.google.com/g/dspace-community/c/GMO020isfZQ/m/1ISexkihAwAJ,
in facets, the check box for each option seems to be vertically centered on each option. This is fine for single lines but is confusing for multi-line options. For example, the ETD collection in the Iowa State University repository running DSpace 7.2, https://dr.lib.iastate.edu/collections/0830d32e-14e1-4a4f-bb8f-271a75ed35af?scope=0830d32e-14e1-4a4f-bb8f-271a75ed35af, offers a Department facet with the long option, Civil, Construction, and Environmental Engineering. I propose putting the check box inline with the first word of each option. I observe this in Firefox but not in Chrome or Safari. Attached are screenshots of each. [Note also that checkboxes in Safari overlap the text for some options.]
___________
Firefox  
<img width="271" alt="Firefox_facet_checkbox" src="https://user-images.githubusercontent.com/13037168/176241621-f3fbe7ca-7aa1-45a8-8799-b823283cf379.png">
___________
Chrome  
<img width="271" alt="Chrome_facet_checkbot" src="https://user-images.githubusercontent.com/13037168/176241670-c298117a-f9e6-4f01-8840-f8f7c0361688.png">
___________
Safari  
<img width="271" alt="Safari_facet_checkbox" src="https://user-images.githubusercontent.com/13037168/176241700-d681b86d-bbd4-447f-9c14-94f4cf58948b.png">
___________
A clear and concise description of what the bug is. Include the version(s) of DSpace where you've seen this problem & what *web browser* you were using. Link to examples if they are public.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by ybnd** [comment]
I'm seeing slightly different misalignment on Firefox 103.0.2
<img width="269" alt="20220825-103353" src="https://user-images.githubusercontent.com/31547038/186616584-670892e4-3ce1-4110-a8a3-3db0083a3c5d.png">

**Comment by alawvt** [comment]
Thanks, @ybnd, thank you for sharing your view. Is that a site that I could test? In Firefox 104.0, the page that I linked above still looks the same as the first screenshot.

**Comment by ybnd** [comment]
@alawvt that was on the demo site: https://demo7.dspace.org/search

**Comment by alawvt** [comment]
Thanks, @ybnd, the subjects on the Demo site look fine for me, too. So maybe it is a theme issue at https://dr.lib.iastate.edu/. Therefore, I'd be fine with closing this issue, @tdonohue.

**Comment by ybnd** [comment]
I'd suggest leaving it open since the default style in FF is still off compared to other browsers (just not vertically)
& we could look at the spacing issue on Safari as well

**Comment by alawvt** [comment]
Ok. Here's Safari
<img width="278" alt="DSpace7_facets_Safari" src="https://user-images.githubusercontent.com/13037168/186670848-74b6d2c2-258c-492b-b123-216ad8714a7e.png">
and Chrome.
<img width="300" alt="DSpace7_facets_Chrome" src="https://user-images.githubusercontent.com/13037168/186670886-1e8fb0ee-7e9d-4690-8917-0d991676c9e2.png">

**Comment by tdonohue** [comment]
Closing, as alignment issues no longer exist in Firefox or Chrome or MS Edge.  I suspect this was fixed in #2018 or some similar change in 7.5
