### ISSUE TITLE
Browse menus on top must reset pagenumber to 1 when a link clicked.

### ISSUE THREAD

**Issue by erpnedir** [DSpace/dspace-angular#1713]
**Describe the bug**
On browse search results, if you click a link with a big number of results no item is shown in the opening page. This is because the page parameter in the url (bbm.page) is not reset. The new page tries to show the Page number of the previous page.

**To Reproduce**
1. Open Ds7 demo site https://demo7.dspace.org/home
2. Click Browse by Author link at the top menu https://demo7.dspace.org/browse/author
3. Navigate to page 110 https://demo7.dspace.org/browse/author?bbm.page=110
4. Click on Simmons, Cameron which have 189 items https://demo7.dspace.org/browse/author?bbm.page=110&value=Simmons,%20Cameron
5. You see that a blank page loads. https://demo7.dspace.org/browse/author?bbm.page=96&value=Simmons,%20Cameron
6. Check that the page parameter in the url that it still tries to show page 110, which is in fact the number of previous page
7. Change the url parameter bbm.page to 1. Observe that correct result is shown.
**Expected behavior**
When a link clicked at step 4 above, a second parameter for page number must be used. And that parameter must start by 1.
The bbm.page parameter must be kept in the memory. If the user clicks "All browse results" button anytime during his navigation of the author's related works, than the system must go back to the  previous bbm.page (110) at step 3. 
This way the user can continue browsing by authors, from the point he/she forked to the author.
**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Thanks for the report @erpnedir .  I've verified the bug on the demo site (using the links you've provided).  Moving this to the 7.4 board and flagging as high priority.

**Comment by erpnedir** [comment]
I made some additions to the expected behavior section. I discussed with a user  and I think this way it is better.

**Comment by artlowel** [comment]
@tdonohue Atmire would like to claim this task. 
It will take an estimated **6 hours**

**Comment by tdonohue** [comment]
@artlowel : Sounds fine. I'll assign back to you and add the estimate.
