### ISSUE TITLE
MyDSpace doesn't support entities

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#1720]
**Describe the bug**
When creating e.g. a Person item, the MyDSpace page renders it like a publication (using dc.title, dc.date.issued, dc.description.abstract, …)
This should use https://github.com/DSpace/dspace-angular/blob/main/src/app/entity-groups/research-entities/item-list-elements/search-result-list-elements/person/person-search-result-list-element.component.html instead

**To Reproduce**
1. Submit a person item, don't deposit it
2. Open it in MyDSpace
3. I will look like https://capture.dropbox.com/X731GToP0e6S0m60

**Expected behavior**
Item rendering in MyDSpace should be identical to other search results rendering, only the `Workspace` tag and the action buttons should be added

**Comment by tdonohue** [comment]
New, related ticket #1769
