### ISSUE TITLE
Virtual metadata in edit metadata page

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1722]
**Describe the bug**
The virtual relationship metadata on an item, that is added at run-time depending on the relationships that Item has with other entities, and thus not present in the DB, is present in the edit metadata page. This metadata is however not editable, since it is dependent on the relationships the item has, not actual metadata values on the item itself.

**To Reproduce**
1. Go to an item that has relationships to other entities
2. Go to the edit metadata page, eg https://demo7.dspace.org/entities/person/08f7d1b2-9bca-424e-a172-a6cd7eb943e2/edit/metadata
3. `relation.*` fiels are present, and appear editable
4. Edit one, change won't persist
5. Delete one, delete won't persist

**Expected behavior**
Since these types of metadata are not editable/delete-able directly (needs relationship changes to change) they should not appear on the `/edit/metadata` page or not _appear_ editable/delete-able (disabled on edit metadata page) since the changes won't persist.

**Comment by tdonohue** [comment]
Agreed, this is definitely a bug.  I'd have a preference for displaying the virtual metadata on `/edit/metadata`, but **disabling** the ability to edit it.  I worry leaving the virtual metadata off that page would be a confusing user experience (as the edit metadata page would only include some fields, and not all).

This is also somewhat related to https://github.com/DSpace/DSpace/issues/8299 (which is essentially the same issue, but a more generic version of it).

I'm flagging this as `medium` priority for now, but if anyone feels strongly this should be `high` priority, I'd be OK with moving it up.  I'd also be OK with a quick fix that only makes these `relation.*` fields disabled, while not addressing the entirety of the larger issue described in https://github.com/DSpace/DSpace/issues/8299
