### ISSUE TITLE
Missing translation of RegisterDOI curation task label (curation-task.task.registerdoi.label)

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#1726]
**Describe the bug**

Currently RegisterDOI does not have an associated label translation. The translation of `curation-task.task.registerdoi.label` is missing.

![image](https://user-images.githubusercontent.com/952735/179236900-4fcc5e01-29fd-4bf5-9f67-e5ca6b6572cf.png)

**To Reproduce**

1. Open "Edit Collection" view
2. Open Curate tab

**Expected behavior**

The label key is translated ;)

**Comment by tdonohue** [comment]
Added zero hour estimate as this will be included in the fix for #1729.
