### ISSUE TITLE
remove hard coded "or" label -  use i18n translation key lookup instead

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#1729]
## Describe the bug

Two template files contain a hard coded "or" which should be replaced by an translation key lookup:

```html
<span class="px-4 bg-white">or</span>
```

- src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.html
- src/app/shared/dso-selector/modal-wrappers/create-community-parent-selector/create-community-parent-selector.component.html

What is the common translation key naming scheme used in DS-UI? Could you please suggest an appropriate key name.

**Comment by corrad82-4s** [comment]
We at 4science can fix this all at once with https://github.com/DSpace/dspace-angular/issues/1728 and https://github.com/DSpace/dspace-angular/issues/1726 . Roughly it won't take longer than 1 or 2 hours

**Comment by tdonohue** [comment]
@corrad82-4s : Thanks, I'll assign all 3 of these tickets to you for 7.5.  I'll just add a 2 hour estimate to this ticket, and make the other two tickets *zero hour* estimates.
