### ISSUE TITLE
Cookie consent shows analytics usage also when GA is disabled

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1731]
**Describe the bug**
The Cookie consent dialog doesn't look to the google analytics property to decide if a consent is needed about statistics service or not. 

**To Reproduce**
This can be verified on the official demo opening the cookie consent dialog and looking to the statistics service still present when there is no google analytics key configured.

**Expected behavior**
The statistics section should appear only when appropriate

We (4Science) are interested on working on that, it should take around **2 days on the Angular side**

**Comment by tdonohue** [comment]
Agreed, this seems like a bug that should be fixed.  One thing to note is that we also need to consider the situation where a user already completes the consent dialog and then Google Analytics is enabled later.  It seems like they'd then need to recomplete the consent dialog (or at least the consent to statistics).  

In any case, moving to 7.4 and assigning to 4Science

**Comment by vins01-4science** [comment]
@tdonohue created a PR #1816 for this ISSUE, now is in waiting for reviewers.
