### ISSUE TITLE
Issues with claimed items in MyDSpace 

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1736]
When an item is claimed in the workflow, the counter in the sidebar filter facet is not updated.

Before and after claiming the first item:
![image](https://user-images.githubusercontent.com/87638927/180256780-d562b586-94d2-40c2-b1e0-71c39a7cc24c.png)
![image](https://user-images.githubusercontent.com/87638927/180256823-e17d584e-fab6-4d34-a313-80a08f8a4724.png)

If the filter is clicked, sometimes the newly claimed item is listed in the results as expected, and sometimes it is not. It may also happen that also the previously claimed items are not listed even if the REST request returns them:
![image](https://user-images.githubusercontent.com/87638927/180256964-65cbd03e-6ec0-46ba-a1c4-58e8e1995d1f.png)
![image](https://user-images.githubusercontent.com/87638927/180259508-3d836c8e-8af5-484d-8bca-14da236b90e6.png)
![image](https://user-images.githubusercontent.com/87638927/180259459-6a44c5b4-607f-4188-9516-9588838edcbb.png)

If the page is refreshed, all items will be listed:
![image](https://user-images.githubusercontent.com/87638927/180257295-a2cb9e70-dee7-4696-b084-70f7743bdeec.png)

If the item is returned to the pool, if the filter is clicked it may happen that the newly returned item is still listed among the claimed ones. Trying to return it to the pool will result in an error.

**Comment by ybnd** [comment]
Also see https://github.com/DSpace/dspace-angular/issues/1610

**Comment by tdonohue** [comment]
Yes, this seems like a possible duplicate or closely related to #1610.  I'll pull this over to the 7.4 board alongside #1610 and hopefully the same person can claim both.  If anyone is interested, let me know.

**Comment by corrad82-4s** [comment]
Hello @tdonohue , we are interested in working this issue and #1610. Our estimation is 16 hours

**Comment by tdonohue** [comment]
Sounds good @corrad82-4s .  I'll assign both tickets to you for 7.4.  I'll put the 16 hour estimate on this one, and just link up the other to it.

**Comment by corrad82-4s** [comment]
Hi @tdonohue , we have spent so far about 10 hours in analysis. We tried to restore a behavior present in version 7.1, but it won't resolve problems here reported. We will have to review estimations.
For what concerns facets counters update, we are stuck, any advice is welcome. 
Our proposal is to split work in two: first resolve and open a PR for problem affecting item status update (2nd ant 3rd point of what reported by Davide) and work separately problem affecting facet counters update reported also in #1610

**Comment by tdonohue** [comment]
@corrad82-4s : Unfortunately, I don't have immediate advice to offer here.  But, if it makes sense to break this ticket down into separate stages, I'm OK with that.  If you can fix a few of the issues, perhaps it'll help us better debug what is going on with the last issue.

So, your proposal sounds good to me (and feel free to provide an updated estimate as needed).  Let's see if that helps clarify what is happening in #1610... if it doesn't, then we can always bring this up for discussion in a future meeting to see if anyone else has ideas as to what the cause may be.
