### ISSUE TITLE
Ask current password to user when he / she sets a new password

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1737]
This is the counterpart of the REST ticket https://github.com/DSpace/DSpace/issues/8255

**Comment by abollini** [comment]
@tdonohue  we are interested in take also the angular part as we are working on the REST part. Our estimation is 3-4 days (28 hours)

**Comment by tdonohue** [comment]
@abollini : Sounds good, will assign to you and add the estimate
