### ISSUE TITLE
Session check issues

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1738]
Application will totally hang if session expires while computer is hibernated

**To Reproduce**
1. Login with any user
2. Hibernate your computer for longer period to exceed session timeout period (2h will do for sure)
3. Get you computer up again 
4. Your status is still displayed as "logged in"
5. Try to navigate anywhere without refreshing your page
6. There will be some errors in console and your page is left stuck with loading indicator

**Expected behavior**
You would be either logged out on navigation or you would be present login page on navigation

**Comment by tdonohue** [comment]
I cannot reproduce this anymore, so it appears to be fixed.  Sessions now expire after 20mins of inactivity...and you are shown a popup when they are about to expire which allows you to either "Logout" or "Extend Session".  If you continue to not respond, you are automatically logged out.

I suspect we fixed this issue when we added this Session expiration feature.
