### ISSUE TITLE
Content width

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#174]
The goal of this task is to limit the max-width of most of the content in dspace, but give us the option to keep certain things (background-colors most likely) full width.

Wrap the contents of all components with `-page` in their name in a div with the class `container`. 

In the home-component, wrap the search form and top-community list components in such a div, but leave out the news, it's background needs to retain its full width

In the home-news component change the container-fluid div to container.

Ensure you don't get double margins anywhere, by looking at all changed pages in varying window sizes, if you do, you likely need to add a div with class `row` inside the container, as it contains a negative margin that will offset the container's padding

**Comment by courtneypattison** [comment]
Hey, could I please get an invite to contribute? I'd like to submit a PR for this issue, but I don't want to mess with your workflow!

**Comment by artlowel** [comment]
Sure! I've sent you an invite.
