### ISSUE TITLE
Add thumbnail to Search list view

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1744]
**Is your feature request related to a problem? Please describe.**
In DSpace 7, thumbnails appear in Search Grid view but not List view. 
<img width="1163" alt="DSpace7_Search_grid" src="https://user-images.githubusercontent.com/13037168/182434100-7769b48c-28d2-4126-8542-4bd9a4a768a9.png">
<img width="1073" alt="DSpace7_Search_list" src="https://user-images.githubusercontent.com/13037168/182434117-3bce10af-eed5-4766-a13a-7d498a95fdf3.png">

**Describe the solution you'd like**
Please add the thumbnail to List view. This will create a view comparable to that in DSpace 6 XMLUI.

We like the current XMLUI search and browse lists because they combine thumbnail, title, author, year, search snippet or abstract snippet in a list that is easy to scroll through. We use then all the time to check and administer the repository, for example, using the thumbnail to confirm there is a file and that the thumbnail is correct, checking complete title, author, date, and indexing. It seems with the current DSpace 7 Search List and Grid Views, you can’t get all that in one view. 
<img width="1129" alt="DSpace6_XMLUI_Search_thumbnails" src="https://user-images.githubusercontent.com/13037168/182435012-d60a7192-3dad-414e-b733-98950dfa55d5.png">
WorldCat.org is also a good model
<img width="1212" alt="WorldCat_search" src="https://user-images.githubusercontent.com/13037168/182439669-e397c297-5215-4e7f-9b04-d3e1f3b3646e.png">

**Describe alternatives or workarounds you've considered**

**Additional context**

The icon for list view suggests a thumbnail.
<img width="94" alt="DSpace7_Search_view_icons" src="https://user-images.githubusercontent.com/13037168/182435690-f82e8fbc-687b-47ed-9fab-40bc4427dfa6.png">

**Comment by tdonohue** [comment]
This appears to be implemented in a branch new PR (not yet reviewed or merged) from @mspalti :#1780   So, I'll link this ticket up to that PR & assign it to @mspalti .  Hopefully this will be in 7.4

**Comment by DSquareTechnologies** [comment]
@tdonohue is this development done? Else, we have done this already. You can see it on 

https://oasis.col.org/home - Thumbnails in list view in the Recent Submissions section.
https://oasis.col.org/search?query= - Thumbnails in list view in the Search section.

**Comment by tdonohue** [comment]
@DSquareTechnologies : Yes, this feature is already being built in PR #1745 by @mspalti .  You can see that PR is linked to this ticket in the "Development" section on the right sidebar of this issue ticket.

**Comment by DSquareTechnologies** [comment]
Perfect! Happy to contribute, if required. Thanks

**Comment by alawvt** [comment]
As well implemented in DSpace 7.4
<img width="1243" alt="DSpace7_4_search_thumbnails" src="https://user-images.githubusercontent.com/13037168/195181481-200b42ce-fcbe-4c3c-a3a9-07d5950ff655.png">
