### ISSUE TITLE
Add thumbnail to Browse

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1745]
**Is your feature request related to a problem? Please describe.**
In DSpace 7 thumbnails do not appear in Browse view.
<img width="1096" alt="DSpace7_browse" src="https://user-images.githubusercontent.com/13037168/182442982-e57c5af9-fb2c-4927-b7b6-4e9734cd8b85.png">

**Describe the solution you'd like**
Please add the thumbnail to List view. This will create a view comparable to that in DSpace 6 XMLUI when webui.browse.thumbnail.show is configured in https://wiki.lyrasis.org/display/DSDOC6x/Configuration+Reference#ConfigurationReference-WEBUserInterfaceConfigurations.

We like the current XMLUI search and browse lists because they combine thumbnail, title, author, year, search snippet or abstract snippet in a list that is easy to scroll through. We use then all the time to check and administer the repository, for example, using the thumbnail to confirm there is a file and that the thumbnail is correct, checking complete title, author, date, and indexing. Users enjoy images.
<img width="867" alt="DSpace6_XMLUI_browse" src="https://user-images.githubusercontent.com/13037168/182443657-c293e4b2-615c-4059-bcbe-95520ffc4bc6.png">

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
Similar to #1744, this one also appears to be implemented by @mspalti in #1780.  Linking this up to that PR and assigning to @mspalti

**Comment by alawvt** [comment]
As well implemented in DSpace 7.4,

<img width="1062" alt="DSpace7_4_browse_thumbnails" src="https://user-images.githubusercontent.com/13037168/195183194-d5cf5454-c1ad-4c5f-a0c3-2df65a2bdb91.png">
