### ISSUE TITLE
Document the Media Viewer

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1746]
**Is your feature request related to a problem? Please describe.**
The [DSpace 7 Wiki > User Interface Configuration > Media Viewer Settings](https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-MediaViewerSettings) mentions briefly video and image viewers that are disabled by default.

**Describe the solution you'd like**
Please describe these viewers more fully, possibly including screenshots or video(s), especially if the viewers can't be tested on DSpace Demo. We are particularly interested in how the video player handle caption files, since accessibility of content is required. Does it support all image and video formats? Our current custom video player requires that we upload a movie poster, Are there additional files associated with video? Thanks. 

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
Closing, this appears to be resolved.  Details on formats supported and enabling captioning are now available in the docs: https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-MediaViewerSettings
