### ISSUE TITLE
Provide Collection Item Mapper view

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1755]
**Is your feature request related to a problem? Please describe.**
The DSpace 7 Item Mapper is part of the Edit Item interface, e.g. https://demo7.dspace.org/items/03731881-2185-4baf-a6a8-1438a4d29dc8/edit/mapper, and provides a means to map and unmap that item to one or more collections. It lists to which collections the item has been mapped.
<img width="1036" alt="DSpace7_mapping" src="https://user-images.githubusercontent.com/13037168/183519901-d0b38e09-c9f1-4f08-b187-1c0e6798d537.png">

In contrast, the DSpace 6 XMLUI Item Mapper, e.g. https://demo.dspace.org/xmlui/admin/mapper?submit_return=&administrative-continue=332d6278024f3d39200866744a665b1c796d6c1c,  is an extension of collection management.  
>"This is the item mapper tool that allows collection administrators to map items from other collections into this collection. You can search for items from other collections and map them, or browse the list of currently mapped items." 

The interface lists the number of items amapped to the collection and allows one to map and unmap multiple items in bulk.
<img width="1125" alt="DSpace6_XMLUI_mapping" src="https://user-images.githubusercontent.com/13037168/183518703-4a2a224a-de27-475d-9198-bf1c1fe1f6b6.png">
<img width="1109" alt="DSpace6_XMLUI_mapping_search" src="https://user-images.githubusercontent.com/13037168/183518678-f8751c7f-15e8-4aef-813c-5aea0c08a165.png">
<img width="1111" alt="DSpace6_XMLUI_mapping_browse" src="https://user-images.githubusercontent.com/13037168/183518692-7ee35e08-4885-45cc-9e65-c21db261d725.png">

There are several advantages to the DSpace 6 XMLUI Item Mapper that should be replicated in DSpace 7:

- A collection administrator can map items to the collection. It does not seem possible to give this authorization to a collection manager with the DSpace 7 Item Edit interface.
- A collection manager can map and unmap in bulk vs. one item at a time in DSpace 7.
- It lists which items in a collection are mapped to the collection.
- One can search by author or keyword and add all of them all at once to a mapped collection.

In our experience, the collection management interface would be preferable.

**Describe the solution you'd like**

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
@alawvt : This feature already exists.  In DSpace 7, you can map items from the "Edit Item" (which you have a screenshot above) or the "Edit Collection" screens. Either approach works.  Here it is on the Edit Collection side:
![map-item](https://user-images.githubusercontent.com/483997/183523355-b6d4b1d1-1c27-4977-8ea7-fb5d5636e5a0.png)

Closing this ticket as it's already completed and it works similarly to the XMLUI screenshots above

**Comment by alawvt** [comment]
Thanks, @tdonohue. I missed that on the Edit Collection interface. That's great that it is already there.
