### ISSUE TITLE
Preserve line breaks in metadata

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1762]
**Describe the bug**
It is very important that DSpace not alter metadata. 

In DSpace 6 XMLUI. Line breaks in the metadata are preserved even though they are not displayed on the front end.
<img width="1138" alt="DSpace6_XMLUI_linebreak_front" src="https://user-images.githubusercontent.com/13037168/184232054-d0765d51-6b86-4546-851f-e9a3fba4e04a.png">
<img width="1132" alt="DSpace6_XMLUI_linebreak_back" src="https://user-images.githubusercontent.com/13037168/184232110-27559d5e-cb42-4ace-a740-a811d6870d55.png">

However, in DSpace 7 Demo, line breaks are removed when loaded to the metadata. They are not displayed on the front end.
<img width="559" alt="DSpace7_linebreak_back" src="https://user-images.githubusercontent.com/13037168/184232430-a7a40d2c-4fab-40ff-a6e9-bca18eb0a3d0.png">
<img width="1032" alt="DSpace7_linebreak_front" src="https://user-images.githubusercontent.com/13037168/184232454-b74952b9-63fb-44f0-b7bb-1901be17042a.png">

Please preserve line breaks. (We'd be even happier if they were displayed!)

This bug is a show-stopper for us. We can't risk 35,000+ carefully formatted ETD abstracts until this is fixed.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by artlowel** [comment]
We'd like to claim this, https://github.com/DSpace/dspace-angular/issues/1763 and https://github.com/DSpace/dspace-angular/issues/1404.

The idea is to add support for line breaks by default, and optional support (disabled by default) for markdown (with a mathjax plugin enabled) in abstracts.

That would allow users to use either HTML or markdown to mark up their abstracts, and allow us to render mathjax and easily add any of [the markdown-it plugins](https://www.npmjs.com/search?q=keywords:markdown-it-plugin) that exist to easily add support for table of contents', latex, footnotes, etc later one. 

This will take an estimated 8 hours

**Comment by tdonohue** [comment]
@artlowel : Sounds fine & I'll assign back to you. 

Just as a note though, I do want to caution that we may want to look at a way to strip some HTML out of abstracts.  For example, we may want to consider blocking some tags like `<script>`, `<embed>` and `<frame>` (and similar).  I.e. if there's a way to limit to formatting HTML tags, that'd be the ideal. While Angular seems to block JS from running, it's in our best interest to avoid certain HTML tags being used.

**Comment by alawvt** [comment]
As implemented on DSpace 7.4 Demo,

<img width="1109" alt="DSpace7_4_edit_item_line_breaks" src="https://user-images.githubusercontent.com/13037168/195189299-d0efcf9e-c958-424b-80b4-b1e251c96368.png">
<img width="1034" alt="DSpace7_4_iitem_view_html_line_breaks" src="https://user-images.githubusercontent.com/13037168/195189309-5ec0f638-fc75-4705-b237-0ae77b3a44af.png">

Line breaks are preserved and displayed. Thank you very much.

HTML is not displayed. @tdonohue, Is HTML disabled in the settings for DSpace 7 Demo?

**Comment by tdonohue** [comment]
@alawvt : To clarify, HTML is not displayed at this time in these fields. However, *Markdown* and MathJax is supported when enabled: https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-Markdown/MathJaxSettings

It looks like it's not yet enabled on the Demo site, but will push out some updates to the demo site this week (likely tomorrow) to enable it.

**Comment by alawvt** [comment]
@tdonohue, thank you for this information. I would like to test the Markdown and MathJax when it is enabled. Should I start another feature request to support HTML in the abstract field?

**Comment by tdonohue** [comment]
@alawvt : It turns out that I was wrong.  The Markdown support includes support for basic HTML tags.  The docs were just updated to clarify that: https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-SettingsforrenderingMarkdown,HTMLandMathJaxinmetadata

I've also just pushed an update to the demo site to enable both Markdown (with HTML) and MathJax.  HTML tags in abstracts should now be working.

**Comment by alawvt** [comment]
@tdonohue, Thank you for checking this and adding it to the documentation. Thank you also for adding the settings to the [DSpace 7 Demo home page](https://demo7.dspace.org/home).
