### ISSUE TITLE
Display line breaks in metadata

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1763]
**Is your feature request related to a problem? Please describe.**
In DSpace 7, please display hard-coded line breaks in metadata. This will improve the readability of multi-paragraph abstracts and descriptions and render them as intended.

**Describe the solution you'd like**
In DSpace 6 XMLUI, line breaks in metadata are preserved but do to display on the front end.
<img width="992" alt="DSpace6_XMLUI_linebreaks_show_back" src="https://user-images.githubusercontent.com/13037168/184236273-3cd0f1cd-9926-4ab8-9e46-c57e7c53734d.png">
In DSpace 7, line breaks in metadata are not preserved, See #1762.

Please make line breaks appear like this.
<img width="1106" alt="DSpace6_XMLUI_linebreaks_show_front" src="https://user-images.githubusercontent.com/13037168/184236558-9e343d15-0a02-4026-8da4-8eb3e0319f99.png">

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
semi-related to #1495 (but not the same issue).  #1495 includes discussion of which HTML tags should be allowed to display in metadata fields.  This ticket might be thought of as the `<p>` HTML tag, or it could just be implemented as preserving whitespace.

**Comment by tdonohue** [comment]
Added a zero hour estimate as this will be include in fix for #1762
