### ISSUE TITLE
Improve DSpace 7 drag and drop submission

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#1765]
In MyDspace, a user can submit a new file using the drag and drop zone.

![mydspace-drag-drop](https://user-images.githubusercontent.com/19291880/184363476-fa45ace2-6645-466e-b321-26a3ce774255.png)

When doing so, he/she is prompt to select a collection :

![drag-drop-coll-selection](https://user-images.githubusercontent.com/19291880/184363594-dd04e808-8e1b-4de5-891c-07447e2bfe73.png)

Once done DSpace is displaying a notification on the top right on the screen. 

![drag-drop-confirm](https://user-images.githubusercontent.com/19291880/184363722-4df7cc81-6179-4985-8fb6-811ad82b6b89.png)

However, if the user does not clic on the link in the notification to continue editing his/her submission, he/she ends up with an incomplete empty submission in MyDSpace without knowing it. 

![drag-drop-empty](https://user-images.githubusercontent.com/19291880/184363811-fd23f019-0a0e-41a7-9da1-eebae01037e0.png)

This feature has the potential to be the most attractive and simple way to submit in DSpace, however, it works differently than the other options to submit in DSpace (which follows an slightly different process: Add Item > Select Collection > Edit submission) and the notification is misleading for the user (green color and check icon make think that the submission has been done). 

**Describe the solution you'd like**
The drag and drop submission should align with the other submission process in DSpace. 

The drag and drop option should follow a 3 step process: 

1. Drag and Drop a file
2. Select collection
3. Edit submission (once the collection has been selected, the Edit Submission page of the collection selected automaticly appears so that the user can continue his/her submission process)

![drag-drop-edit-sub](https://user-images.githubusercontent.com/19291880/184363995-58621516-4bf0-491b-a028-07ec96b6a32d.png)

The notification asking for the user to clic to continue the process, is removed.

**Comment by alawvt** [comment]
I agree that the present notification is potentially misleading.

**Comment by tdonohue** [comment]
I agree this is a usability issue.  I like the solution of sending people directly to the "Edit Submission" page after a successful drag & drop (which should allow us to remove the notification entirely).

Pulling this over to the 7.4 board.  Flagging this as high priority as it seems like a common issue.

**Comment by tdonohue** [comment]
@nibou230 : Yes, if i18n keys and translations are no longer used, they can be removed from `en.json5` (at a minimum).  Translators can then remove them from other language translation files the next time they update the translation.
