### ISSUE TITLE
Display all the fields for a Metadata Schema in one page and include IDs

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1766]
**Is your feature request related to a problem? Please describe.**
DSpace 7 Metadata Schema view, e.g., https://demo7.dspace.org/admin/registries/metadata/dc, only displays 25 fields per page. Viewing the dc schema on Demo with 106 fields takes 5 page clicks and a great memory.

**Describe the solution you'd like**
DSpace 6 XMLUI displays all the fields for a schema in one page, e.g. https://demo.dspace.org/xmlui/admin/metadata-registry?administrative-continue=2f3441797515252350683038165e7f0c5e777a56&submit_edit&schemaID=1. This is preferable for several needs:

- Comparing related fields, for instance all the dc.subject.* fields. Paging may cut related fields into two pages.
- Searching for a term with a browser search
- Copying the list for a spreadsheet

Also, DSpace XMLUI includes a column for the metadata ID. This is a very useful reference for composing SQL queries, so I would like it included in the page.
<img width="1134" alt="DSpace6_XMLUI_metadata_schema" src="https://user-images.githubusercontent.com/13037168/184433110-e812a669-36b8-4134-a4e5-6174601590f3.png">

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
@alawvt : Changing the page size is already possible (for up to 200 fields) by clicking on the gear and changing the "Results per page". See this screenshot:
![metadata-pagesize](https://user-images.githubusercontent.com/483997/186970692-b5293646-6d43-4552-a063-d38d4beaafc4.png)

That said, I'm assuming that you may be asking for a way to change the default setting from 25 to a larger number.  It looks like the default of 25 is hardcoded here (along with the pagesize options): https://github.com/DSpace/dspace-angular/blob/main/src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts#L51-L52

The `id` should be possible to display easily as well, as it looks like it's already available on that page. It likely would just involve displaying a new column for `field.id` in the big table here: https://github.com/DSpace/dspace-angular/blob/main/src/app/admin/admin-registries/metadata-schema/metadata-schema.component.html#L24-L46

Overall, I think this is a pretty easy change...but I'm giving it a low priority for now as the main issue (of displaying all fields on one page) is already fixable.  That said, it should be a change that a novice developer could make, and hopefully we can find a volunteer for it!

**Comment by alawvt** [comment]
Thanks, @tdonohue, I had missed the gear icon, which works for us. It would be helpful to add the ID column.
