### ISSUE TITLE
Display all bitstream formats on one page and include IDs.

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1767]
**Is your feature request related to a problem? Please describe.**
DSpace 7 Bitstream Format Registry e.g., https://demo7.dspace.org/admin/registries/bitstream-formats, only displays 20 bitstream formats per page. Viewing the list on Demo with 81 formats takes 5 page clicks and a good memory.

**Describe the solution you'd like**
DSpace 6 XMLUI displays all the formats one page, e.g. https://demo.dspace.org/xmlui/admin/format-registry. This is preferable for several needs:

- Comparing related formats, for instance all the video formats. Paging may cut related formats into two pages.
- Searching for a term with a browser search
- Copying the list for a spreadsheet

Also, DSpace XMLUI includes a column for the format ID. This is a very useful reference for composing SQL queries, so I would like it included in the page.
<img width="1133" alt="DSpace6_XMLUI_bistream_registry" src="https://user-images.githubusercontent.com/13037168/184443247-69d96063-5fa3-4448-a693-ffe3de4dcd51.png">

**Describe alternative

s or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment]
I agree, this should be updated & also likely aligned better with the behavior of the metadata registry (as the Bitstream format registry and metadata registry are similar in some aspects).  So, this could be done at the same time as #1766

In the case of this screen, it appears to be simply hardcoded to have 20 formats listed on a page. There's no option to change that value (like there is in the metadata registry, see my comment here https://github.com/DSpace/dspace-angular/issues/1766#issuecomment-1228810582).

Here's where it is hardcoded to 20:  https://github.com/DSpace/dspace-angular/blob/main/src/app/admin/admin-registries/bitstream-formats/bitstream-formats.component.ts#L36

Ideally, we'd make a few changes here:
1. Make that default value of 20 configurable
2. Add the option to change the page size in a gear (similar to metadata formats registry)
3. Add the `id` column -- this should be easy to do as it appears the `id` is already available in the code. It just isn't displayed.

Moving this over to the 7.4 board with `medium priority`. This likely could be done alongside #1766, as the two are very similar.
