### ISSUE TITLE
Internalization (i18n): Polish translation!

### ISSUE THREAD

**Issue by mpasternak** [DSpace/dspace-angular#1781]
Hello,

I am working on the Polish translation.

The branch is not yet ready to be submitted as a PR but I would like to create this issue, so other people looking for Polish translation can join my effort. 

I will come back soon with the pull request. In the meantime if anybody is willing to help, feel free to contact me. 

Regards,

**Comment by mpasternak** [comment]
The branch is here: https://github.com/mpasternak/dspace-angular/tree/feature/1781-polish-translation

Does anybody know any utilities that help translating files in such format as dspace-angular has? Except VScode? :)

**Comment by tdonohue** [comment]
@mpasternak : Thanks for volunteering to create a Polish Translation.  You may have already seen them, but we have some resources & tips/hints on creating translations here: https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441

Looking forward to your PR, and once it's ready I'll make sure to assign it immediately to reviewers.  Thanks again!

**Comment by mpasternak** [comment]
@tdonohue while I'm working on the translation, step by step, would you like to add me to the translations page as a contact for Polish translation? https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441
