### ISSUE TITLE
Add breadcrumb navigation (option)

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1784]
**Is your feature request related to a problem? Please describe.**
DSpace 6 XMLUI and previous versions of DSpace have breadcrumb navigation on all Community, Collection, and Item pages. This allows the user to know their location in the community hierarchy and to navigate quickly within it. For repositories with detailed hierarchies and/or duplicate collection names, it is essential for knowing the location within the hierarchy. Please make the breadcrumb trail or similar community navigation an option in DSpace 7. Some repositories may not need or want it, but for those us with extensive hierarchies, is is important.

**Describe the solution you'd like**
We have found the breadcrumb navigation in DSpace 6 XMLUI effective.
<img width="566" alt="DSpace6_XMLUI_collection_breadcrumb" src="https://user-images.githubusercontent.com/13037168/186255070-6452eaae-93ae-4579-831a-039043acc7ef.png">
<img width="568" alt="DSpace6_XMLUI_item_breadcrumb" src="https://user-images.githubusercontent.com/13037168/186255060-ac3da96c-765b-4ae4-a751-7e83ff8b308b.png">
**Describe alternatives or workarounds you've considered**

**Additional context**
Related issues have also expressed the need for a fuller community/collection path to fully distinguish collections.

**Comment by tdonohue** [comment]
@alawvt : Breadcrumb navigation already exists in DSpace 7 & can be seen on the demo site... here's an example: https://demo7.dspace.org/entities/publication/2acb4234-21b3-4036-bc2c-9440756460fd

![breadcrumbs](https://user-images.githubusercontent.com/483997/186465316-70022a5c-d80a-4d9f-93e8-b86325ccb94e.png)

As far as I'm aware, it should exist on all pages.  But, if you find a place where it's not working properly, please do let us know!

I *think* this ticket can simply be closed, unless I'm misunderstanding something you've noticed in our current breadcrumbs.

**Comment by alawvt** [comment]
Thanks, @tdonohue. #1782  shows the Workflow Item view, where the breadcrumb does not include the collection path. I will check if there are others.

**Comment by tdonohue** [comment]
Thanks @alawvt .  In that case, I'm going to close this ticket as the general breadcrumb already exists.  I'd recommend opening new tickets if you find areas where breadcrumbs are missing & recommended.  I'll move your comment about the Workflow Item view to the other ticket #1782
