### ISSUE TITLE
Default settings in `config/config.yml` are ignored

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1795]
**Describe the bug**
Discovered while attempting to customize demo7.dspace.org to enable additional optional features.

Currently, the default user interface configuration in [`/config/config.yml`](https://github.com/DSpace/dspace-angular/blob/main/config/config.yml) is ignored.  Modifications to that file seem to have no effect when running either in production (`yarn start`) or development mode (`yarn start:dev`).  This means that `config.yml` seems to have no purpose.

Instead, default configuration MUST be modified directly in `src/config/default-app-config.ts`. 

**To Reproduce**
1. Attempt to change default configurations in `config/config.yml`, e.g.
```
# Enable Item access status badges
item:
  showAccessStatuses: true

# Enable media viewer plugin
mediaViewer:
 image: true
 video: true
```
2. Start up the app in either production or dev mode.  Verify that these settings have no effect.
3. Remove those settings from `config/config.yml`.  Instead, update them in `src/config/default-app-config.ts`.
4. Start up the app in either production or dev mode. Verify those changes are respected.

**Expected behavior**
It should be possible to modify `config/config.yml` to have those default settings take effect for BOTH production & development modes.

I've flagged this as HIGH priority because https://api7.dspace.org/server/ is no longer the default backend (as specified in `config/config.yml`).  If you remove `rest` settings from your `config.prod.yml` (or `config.dev.yml`), then the UI default to using "localhost:8080" as that's what is defined in `default-app-config.ts`. 

More specifically, by default, if you spin up the UI with no configuration, it attempts to use `http://localhost:8080/api` as the backend. This URL is invalid even if you are running the backend on localhost, as running the backend on localhost defaults to `http://localhost:8080/server/api`, not `http://localhost:8080/api`

**Related work**
Might be loosely related to #1778, which reports another odd configuration issue (specific to `yarn start:dev`).  At a minimum, both of these issues might be solved together.

**Comment by artlowel** [comment]
Atmire would like to work on this and https://github.com/DSpace/dspace-angular/issues/1778 at once. Together they'll take an estimated **4 hours**

**Comment by tdonohue** [comment]
Sounds good @artlowel .  I'll assign both to you for your team to work on for 7.4
