### ISSUE TITLE
The 500 Service Unavailable error page is no longer shown

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1830]
**Describe the bug**
When the rest server is not available a 500 error page should be shown, currently in the main branch is no longer working and a blank page is shown instead
![Schermata da 2022-09-16 11-52-07](https://user-images.githubusercontent.com/2486489/190614755-45ac0b56-6b9b-4227-8c4a-44c6244f1040.png)

**To Reproduce**
1. configure the application in order to run over a not available rest server
2. run the application
3. a blank page is shown

**Expected behavior**
The Service Unavailable error page should be shown

**Related work**
https://github.com/DSpace/dspace-angular/pull/1498

**Comment by tdonohue** [comment]
Thanks for reporting this @atarix83 . I'll pull this over to the 7.4 board and flag as high priority. If you are interested in helping fix it, let me know. Not sure offhand what could have caused it.

**Comment by tdonohue** [comment]
@artlowel : Thanks, sounds good. I'll assign you to it then.
