### ISSUE TITLE
Full item page of entities missing title/name

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#1833]
**Describe the bug**
Full item pages of entities don't have a valid title because they don't always have a `dc.title`. Example Person full item page: https://demo7.dspace.org/entities/person/6f8f78e7-8ba9-45c6-841a-421b48931fee/full

Each entity page has its own solution for this, using different md field(s), defined on its simple item page, but full item page uses generic [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/full/full-item-page.component.html#L9)`ItemPageTitleFieldComponent`, defined [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/simple/field-components/specific-field/title/item-page-title-field.component.ts), which just uses `dc.title`.

**To Reproduce**
1. Go to full item page of a Person entity typed item (author); example: https://demo7.dspace.org/entities/person/6f8f78e7-8ba9-45c6-841a-421b48931fee/full
2. Verify the title is just 'Author: ' without a name filled in, while the simple item view does have the author name
3. Idem for OrgUnit entities (Organizational Unit); example: https://demo7.dspace.org/entities/orgunit/250357dd-6979-4a9b-b8ed-71cce3dee4b3/full

**Expected behavior**
All entities should have a valid title (or a fallback) on its simple item page, full item page, list view, grid view, trail/breadcrumb, etc (same in all locations for same item, preferably configured in one place)

**Proposed solution**
This issue has been partially addressed in `DSONameService` [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/breadcrumbs/dso-name.service.ts#L28). To streamline/make titles on simple and full item pages uniform, it would be best for them both to use `ItemPageTitleFieldComponent` and to alter `ItemPageTitleFieldComponent` to use `DSONameService`.

Currently `DSONameService` provides title/name for person, orgunit and default (dc.title) which likely addresses all entity cases which are now addressed individually on their simple item pages (project, journal, journal issue, etc also use `dc.title`).

Further more, it should be checked if the item titles on the list/grid views, as well as the title in the trail/crumbs, already use this `DSONameService` to make sure there is a single point of truth for the name/title of entity items. The fallback in case of no name/title in the expected md field could also be defined via this `DSONameService` but would require further changes.

**Comment by MarieVerdonck** [comment]
This will take an estimated **6 hours** to refactor/verify is used in all item title/name locations.

**Comment by pilasou** [comment]
Hi @MarieVerdonck, it seems to me that this issue offers some good leads to help on 2 feature requests we made :) : https://github.com/DSpace/dspace-angular/issues/1769 and https://github.com/DSpace/dspace-angular/issues/1834

**Comment by tdonohue** [comment]
@MarieVerdonck : This seems reasonable to do for 7.4, if you/your team has time. I'll assign you, move it over to our 7.4 board, flag as high priority and add the estimate. Thanks!

**Comment by MarieVerdonck** [comment]
> Hi @MarieVerdonck, it seems to me that this issue offers some good leads to help on 2 feature requests we made :) : #1769 and #1834

@pilasou: This would indeed streamline what is shown in different list views for the same item, but only as so far as the title/name is concerned, your request for affiliation or other identifiers to be shown in MyDSpace list view (or search item list view) would be unrelated.

However, there is already a PR open to re-use the search Item view components from the regular search in the MyDSpace search: https://github.com/DSpace/dspace-angular/pull/1825
So wanting to include `person.affiliation.name` (or other identifier fields) should after this PR only have to be changed in one component, which should be somewhat straightforward, though not in the scope of this issue.

Browsing options on community/collection pages dependent on entity types is a more complex matter, likely requiring more extensive REST and Angular changes.
