### ISSUE TITLE
Creative Commons jurisdiction chosen is ignored

### ISSUE THREAD

**Issue by toniprieto** [DSpace/dspace-angular#1836]
**Describe the bug**

When a standard Creative Commons license is selected, the user can select the jurisdiction but it is ignored by the Rest side. The Rest side uses a default configured value for the Creative Commons jurisdiction and replaces the selected value with it.

**To Reproduce**
1. Start a new submission and go to CC section
2. Select the standard Creative Commons license
3. Answer the two first question (for example select Yes and Yes ) and select a jurisdiction different from the configured in  `cc.license.jurisdiction`(default United States)
4. The selected license displayed is based on the configured jurisdiction and not the selected one.

For example, this is the result of select a Spanish jurisdiction with the United States configured as default (it should be http://creativecommons.org/licenses/by/3.0/es/ instead):

![imagen](https://user-images.githubusercontent.com/3812525/191082079-0c130f30-f3a6-4685-b9c9-7ddebb77ffd5.png)

**Expected behavior**
In previous versions, this problem was solved by not showing the user the question to select the jurisdiction. The Creative commons selector only showed the first two questions. Another option is to get the default jurisdiction from the rest side and show the jurisdiction selector with the value already selected and disabled.

**Comment by tdonohue** [comment]
Closing, fixed by #1930 and DSpace/DSpace#8545
