### ISSUE TITLE
Mydspace filters are not updated when switching from workspace to workflow task

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1840]
**Describe the bug**
In the mydspace page when switching from workspaceitem to workflowitem the filters are not updated properly. Indeed only filters that are in common between the two search configuration are refreshed, while filter present in only one configuration are not loaded during the switch

**To Reproduce**
1. login as admin user
2. open the mydspace page
3. switch show dropdown in order to list workflow tasks
4. see which filters are present in the sidebar
5. click F5 to refresh the page
6. at this point the filters should be different because are loaded properly

https://user-images.githubusercontent.com/2486489/191264027-d0051e6e-b07b-4b47-87fa-c7814a32d080.mp4

**Expected behavior**
Filter should be loaded/refreshed properly when switching search configuration

**Comment by atarix83** [comment]
@tdonohue 

we can work on this bug fix

**Comment by tdonohue** [comment]
@atarix83 : Sounds fine, please add an estimate when you have one. I'll pull this over onto our 7.4 board & assign to you

**Comment by atarix83** [comment]
@tdonohue 

it's about 3/4 hours
