### ISSUE TITLE
Example default bundles configuration in config/config.example.yml is incorrect

### ISSUE THREAD

**Issue by dsteelma-umd** [DSpace/dspace-angular#1843]
**Describe the bug**

In DSpace 7.3, Pull Request #1605 added the following to the "config/config.example.yml" file as an example of how to configure the default bundles list:

```
# The default bundles that should always be displayed as suggestions when you upload a new bundle
bundle:
  - standardBundles: [ ORIGINAL, THUMBNAIL, LICENSE ]
```

When using this example in an actual configuration, the list of bundles is not displayed in the "Bundle" field of the "Upload Bitstream" page, and the following error is in the browser console:

* Firefox:
```
ERROR TypeError: X.N.bundle.standardBundles is undefined
```

* Chrome:
```
ERROR TypeError: X.N.bundle.standardBundles is not iterable
```

In investigating this it appears that the format of this YAML is incorrect, as it generates a JavaScript object of the form:

```
{ bundle: [ { standardBundles: ['ORIGINAL', 'THUMBNAIL', 'LICENSE'] } ] }
```

As given in  "src/config/default-app-config.ts" the expected JavaScript form is:

```
  bundle: BundleConfig = {
    standardBundles: ['ORIGINAL', 'THUMBNAIL', 'LICENSE']
  };
```

This means that the default bundles list configuration in the "config/config.example.yml" file should actually be:

```
# The default bundles that should always be displayed as suggestions when you upload a new bundle
bundle:
  standardBundles: [ ORIGINAL, THUMBNAIL, LICENSE ]
```

**To Reproduce**

1) Checkout the codebase, following the "Quick start" instructions in the "README.md" file:

```
# clone the repo
git clone https://github.com/DSpace/dspace-angular.git

# change directory to our repo
cd dspace-angular
```

2) Edit the "config/config.yml" file:

```
vi config/config.yml
```

adding the following lines (directly copied from https://github.com/umd-lib/dspace-angular/blob/b9d3855c741192e4aa764d4366bc3471ab18fd20/config/config.example.yml#L239-L241):

```
# The default bundles that should always be displayed as suggestions when you upload a new bundle
bundle:
  - standardBundles: [ ORIGINAL, THUMBNAIL, LICENSE ]
```

3) Run the Angular front-end:

```
# install the local dependencies
yarn install

# start the server
yarn start
```

4) Go to http://localhost:4000/ in your browser, and login as the "dspacedemo+admin@gmail.com" user.

5) Select any publication, and edit it. On the "Edit Item" page, left-click the "Bitstreams" tab, and then left-click the "Upload" button. The "Upload bitstream" page will be displayed.

Note that on the "Upload bitstream" page, there are no items in the "Bundle" field drop-down, and there is an error in the browser console log.

**Expected behavior**

That in Step 5, at a minimum the list of default bundles will be displayed in the "Bundle" field drop-down, and that there will be no error in the browser console log.

**Related work**

The suggested fix is provided in Pull Request #1844

**Comment by tdonohue** [comment]
@dsteelma-umd : Thanks for finding this issue and sending a fix!  I'll pull this over to our 7.4 board and get someone to review this immediately.
