### ISSUE TITLE
Thumbnail placeholders in recent Item list rendered incorrectly

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1855]
**Describe the bug**
Currently, `ds-recent-item-list` has the same issues with font scaling & tthumbnails/placeholder images not being loaded as we saw with e.g. Relationships on Item pages. 
Here's a screenshot from my phone; the font scaling problem may not be as apparent in "desktop view"

![Screenshot_20220923-214901](https://user-images.githubusercontent.com/31547038/192047320-6c92b7b6-4019-46ba-89c9-241c3b00d355.jpg)

I should have caught this when reviewing #1780, and since it's right on the front page I think we should try to fit it into 7.4 if at all possible.

**To Reproduce**
Open the front page with list thumbnails enabled

**Expected behavior**
Front page thumbnail placeholders should be rendered correctly

**Related work**
#1780

**Comment by tdonohue** [comment]
@ybnd : Yes, I agree that it'd be nice to quickly fix this in 7.4.  If you want to create a quick PR, I'll gladly review it. Thanks!

**Comment by mspalti** [comment]
Ah, that was hiding in plain sight.  Thanks for fixing this one @ybnd !
