### ISSUE TITLE
Support for nodejs v18  in dspace 7.x

### ISSUE THREAD

**Issue by AllanPickett** [DSpace/dspace-angular#1865]
**Is your feature request related to a problem? Please describe.**
Nodejs v16 is the latest release supported by DSpace 7. However Nodejs v16 will be EOL September 2023. Any new installs based on the current release will have a very short lifespan to be running on a supported environment.

The EOL for nodejs was brought forward and more details can be found here :
https://nodejs.org/ar/blog/announcements/nodejs16-eol/

**Describe the solution you'd like**
Support for a newer version of nodejs e.g. v18 (lts) to be included in the next point release of dspace 7.

More info on releases  : https://endoflife.date/nodejs

**Describe alternatives or workarounds you've considered**
I am new to the dspace 7 cycle. Including nodejs. And can see you are responsive to this issue already in the past with adding support for nodejs v16.
Also being new to anything nodejs it is hard to see what the full implications or alternatives are.  

**Additional context**
Converting our customised DSpace 5 to DSpace 7 - which will then go live early 2023.

To have an estimate of when nodejs v18 is to be supported we would test against that and adjust our project timescales accordingly.

Thanks again for all the hard work - we would not be able to run our repo/archive without it.

**Comment by tdonohue** [comment]
We briefly discussed this ticket in today's Developers Mtg.  It sounds like currently the UI will not run on Node 18, but there may be minor changes we can make to allow it to run on Node 18.  Those changes are in the works, but may not be ready in time for the DSpace 7.4 release (due in early Oct).  More likely, Node 18 basic support would come in 7.5 (due in Feb).

**Comment by artlowel** [comment]
We'd like to claim this ticket

**Comment by tdonohue** [comment]
Sounds good @artlowel .  Assigning to you for your team to work on. Please provide an estimate when you can do so.

**Comment by mwoodiupui** [comment]
I've been running on Node 18 in my development environment for some time.  This patch made it work for me:

diff --git a/package.json b/package.json
index 33e337121..aee1a4083 100644
--- a/package.json
+++ b/package.json
@@ -172,7 +172,7 @@
     "eslint": "^8.2.0",
     "eslint-plugin-deprecation": "^1.3.2",
     "eslint-plugin-import": "^2.25.4",
-    "eslint-plugin-jsdoc": "^38.0.6",
+    "eslint-plugin-jsdoc": "^39.3.6",
     "eslint-plugin-unused-imports": "^2.0.0",
     "express-static-gzip": "^2.1.5",
     "fork-ts-checker-webpack-plugin": "^6.0.3",
@@ -209,7 +209,7 @@
     "ts-loader": "^5.2.0",
     "ts-node": "^8.10.2",
     "typescript": "~4.5.5",
-    "webpack": "^5.69.1",
+    "webpack": "^5.74.0",
     "webpack-bundle-analyzer": "^4.4.0",
     "webpack-cli": "^4.2.0",
     "webpack-dev-server": "^4.5.0"

**Comment by mwoodiupui** [comment]
I think I had to upgrade typedoc too.  I found a 'typedoc.new.json':
{
    "entryPointStrategy": "expand",
    "exclude": "**/*+(spec.ts|po.ts|index.ts|.json|.js|.config.ts|.aot.ts)",
    "excludeExternals": "true",
    "name": "Angular 2 UI for DSpace",
    "out": "./doc",
    "readme": "./README.md",
    "theme": "default",

    "compilerOptions": {
        "mode": "modules",
        "module": "es2020",
        "target": "es2015",
        "ignoreCompilerErrors": "true",
        "experimentalDecorators": "true",
        "emitDecoratorMetadata": "true",
        "preserveConstEnums": "true",
        "stripInternal": "true",
        "suppressExcessPropertyErrors": "true",
        "suppressImplicitAnyIndexErrors": "true"
    }
}

**Comment by artlowel** [comment]
If you want to make a PR for that @mwoodiupui that's fine too. Feel free to add me as a reviewer

**Comment by mwoodiupui** [comment]
I will note that Node v14 is no longer in active support, and security support will end in April of 2023.  We still test with it.  We should have a date in mind for ending support for v14.

We will want a test task for v18.

**Comment by tdonohue** [comment]
@mwoodiupui : Updating our tests to use Node 18 should be easy... just change this line of our `build.yml` to run against `16.x, 18.x`: https://github.com/DSpace/dspace-angular/blob/main/.github/workflows/build.yml#L28

**Comment by mwoodiupui** [comment]
@tdonohue I tried that.  e2e tests crash on Github with ECONNREFUSED.  I see nothing helpful in the log.  Suggestions?

(`yarn test` succeeds locally.)

**Comment by tdonohue** [comment]
Closing, fixed by #1946

**Comment by AllanPickett** [comment]
Thankyou everyone.
Best wishes for the holidays and the New Year.
Allan
