### ISSUE TITLE
User menu issue on narrow screens

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1890]
**Describe the bug**

When the user is authenticated, clicking on user menu icon opens a dropdown menu that includes the logout button.
On narrow screens, however, clicking on user menu icon redirects to the logout page.

![image](https://user-images.githubusercontent.com/87638927/194915757-00435ba5-86c5-47be-8d5c-ffead339ad14.png)

**Expected behavior**
On narrow screens the missing menu items should be available in the expandable menu in the upper right corner.

**Comment by davide-negretti** [comment]
We'd like to handle this one

**Comment by tdonohue** [comment]
Sounds good @davide-negretti . I've assigned this and #1891 back to you to work on for 7.5.  I'd appreciate though if you could give me a rough estimate for the number of hours it will take (you can do a combined estimate for both if that's easier)

**Comment by davide-negretti** [comment]
Hi @tdonohue 
I'd say 8-12 hrs for both issues. Unfortunately there is code shared by dspace and base themes, and testing both themes may require multiple reboots of the application.

**Comment by tdonohue** [comment]
@davide-negretti : Sounds good, as these will be done together, I'll add an estimate of 10hrs to this ticket and 0hrs to the other (adding a comment that it's included in the same estimate). Feel free to start work whenever you are ready.

**Comment by davide-negretti** [comment]
This PR is also going to fix an issue with admin sidebar, which causes the inner-wrapper in the root component to overflow on the right in some situations.
