### ISSUE TITLE
Expandable menu spacing issue

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1891]
Items in the expandable menu, showed on narrow screens, used to be horizontally aligned to the left and vertically aligned on the top. Now items are horizontally centered, and they are vertically arranged to fill all the available space:

![image](https://user-images.githubusercontent.com/87638927/194917539-63c11048-c333-47aa-8821-5e092c684646.png)

Is this the expected behavior? Shouldn't the items be vertically aligned to the top?

**Comment by davide-negretti** [comment]
We'd like to handle this one, together with #1890

**Comment by tdonohue** [comment]
Added a zero estimate to this ticket as it's included in the estimate for #1890
