### ISSUE TITLE
Current item's metadata are cleared from display in the Edit item metadata page while editing

### ISSUE THREAD

**Issue by amgciadev** [DSpace/dspace-angular#1894]
**Describe the bug**
While editing an item's metadata via the Edit item Metadata tab, occasionally all the metadata values are wiped off apart for the value currently being edited - see screenshot attached from the current DSpace7 DEMO site. 

I have replicated this behaviour both in my DSpace 7.4 updated environments and in the DEMO site, e.g. https://demo7.dspace.org/items/a1c5ed83-7bee-4e64-b66d-df3671d78459/edit/metadata

**To Reproduce**
1. As an Admin user, choose a random item and go to edit page
2. From the metadata tab, add a value and save
3. Then edit any value and after a couple of seconds the screen refreshes and no metadata values are shown

**Expected behavior**
All existing metadata are shown as expected

**Related work**
Link to any related tickets or PRs here.
![Screenshot 2022-10-11 at 08 59 41](https://user-images.githubusercontent.com/26137686/195034473-17e8ba85-2b31-4613-b407-468891a65319.png)

**Comment by amgciadev** [comment]
Forgot to attach the browser console log for the demo site. The relevant error:

tn @ main.b4b30eb84e5d44b9.js:1
main.b4b30eb84e5d44b9.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'changeType')
  
[demo7.dspace.org-1665475446192.log](https://github.com/DSpace/dspace-angular/files/9752912/demo7.dspace.org-1665475446192.log)

**Comment by tdonohue** [comment]
Thanks @amgciadev :  This sounds like some sort of UI caching issue. I'll pull this over to our 7.5 board and assign.

@artlowel : Is this of interest to your team perhaps?
