### ISSUE TITLE
sitemap entries in robots.txt are not fully qualified urls 

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#1899]
**Describe the bug**

Sitemaps entries in https://github.com/DSpace/dspace-angular/blob/main/src/robots.txt are not full qualified urls

**To Reproduce**

1. Visit the robots.txt of any DSpace 7 installation
2. Look at the sitemap urls and check if they are fully qualified urls, starting with https

**Expected behavior**

Expected: full qualified urls according to
https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt#sitemap

**Related work**

Link to any related tickets or PRs here.

**Comment by artlowel** [comment]
Fixing this will take an estimated **4h**
We'd like to claim this issue

**Comment by tdonohue** [comment]
@artlowel : Thanks for the estimate. Assigning to you for your team to work on for 7.5
