### ISSUE TITLE
Media viewer thumbnails don't take viewport width into account 

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1904]
**Describe the bug**
When running with `mediaViewer.image = true`, thumbnails on Item pages have a fixed width which doesn't look right on screen widths between 768px and 1200px

<img width="802" alt="20221017-120217" src="https://user-images.githubusercontent.com/31547038/196149786-14d81203-a5ea-4721-9d9f-dfe154c8c57f.png">

**To Reproduce**
Open any Item on the demo server (or start a local instance with `mediaViewer.image = true`)
Resize the screen somewhere between 768px and 1200px

**Expected behavior**
The "Media viewer thumbnail" should resize to fit in the left column without overlapping with the right column

**Related work**
Could be fixed at the same time as https://github.com/DSpace/dspace-angular/issues/1887

**Comment by tdonohue** [comment]
@ybnd : It looks like you claimed the related ticket.  I'll assign this to you as well & pull these over to the 7.5 board so they can be worked on when you are ready.
