### ISSUE TITLE
Clicking the Syndication Feed Icon on a community or collection results in a 404 Whitelabel Error Page

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#1905]
**Describe the bug**
Clicking the Syndication Feed Icon on a community or collection in 7.4 results in a 404 Whitelabel Error Page. Not sure if a wrong link is displayed or if the link is correct but no feed is served by the backend.

**To Reproduce**
1. Navigate to any community or collection, e.g. on the DSpace 7 Demo Site: https://demo7.dspace.org/collections/add23764-0671-4b11-8463-d8c60bf4c744
2. Click the feed icon
3. You will see a 404 Whitelabel Error Page

**Expected behavior**
I expect a valid feed that includes the publications of this community or collection

**Comment by tdonohue** [comment]
I've verified this locally & on demo7.dspace.org.  It appears, to me, that the link is incorrectly generated in the UI. 

The UI is creating feed links that look like this:
```
${dspace.server.url}/opensearch/search/search?(params)
```
That throws a 404.

Instead, the correct link is this:
```
${dspace.server.url}/opensearch/search?(params)
```

I'm not sure where the extra `/search` is coming from yet.  I'll pull this over to our board though and flag as high priority & needing a volunteer.

**Comment by nwoodward** [comment]
Looking at the history of the RSS component, the opensearch link was hard-coded until this commit that brought in the `websvc.opensearch.svccontext` parameter from dspace.cfg in the REST API – https://github.com/DSpace/dspace-angular/commit/be8a8f5f6bf9359eecc8034b22c522fe9ac1389f. But the changes to the `formulateRoute` method don't accord with the default value of `svccontext`. I'll create a small PR.
