### ISSUE TITLE
Switching view modes in "My Dspace" does not update search filters

### ISSUE THREAD

**Issue by hutattedonmyarm** [DSpace/dspace-angular#1906]
**Describe the bug**
When there are different search filters defined for "workspace" and "workflow" view modes, switching between them does not update the filter list, resulting in incorrect filters

**To Reproduce**
1. Define different filters for `workspaceConfiguration` and `workflowConfiguration` in `discovery.xml`, e.g. an additional filter for workflow.
2. Open "My DSpace"
3. Verify that workspace filters are correctly displayed
4. Switch view mode to workflow

**Expected behavior**
The filter list in the sidebar should update to reflect the different configuration.
Instead, only the workspace filters are visible. Refreshing the page does cause the missing filter to appear

**Comment by tdonohue** [comment]
@hutattedonmyarm : What version of DSpace are you reporting this for?  This sounds like the same bug as #1840, which we fixed in the 7.4 release.  Could you try this again on 7.4?
