### ISSUE TITLE
Badge / count in facet with long text are displayed incorrectly

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1915]
**Describe the bug**
When a facet value is very long the count badge go outside the facet component

**To Reproduce**
1. Do this https://demo7.dspace.org/search?query=&spc.page=1

![Screenshot from 2022-10-19 17-04-59](https://user-images.githubusercontent.com/1537527/196737874-90e9a056-00df-4e0c-8896-71a5549e38ef.png)

4Science can work on that, estimation is 3-4 hrs

**Comment by tdonohue** [comment]
Thanks @abollini for reporting this & I can reproduce it in Chrome.  I'll assign to @atarix83 and add the estimate.
