### ISSUE TITLE
Complete Polish translation

### ISSUE THREAD

**Issue by michdyk** [DSpace/dspace-angular#1931]
I want to contribute a complete Polish translation of the repository.

Because it is already in progress, I suppose that we will be able to deliver the complete translation at the beginning of November 2022.
I believe that it would be great for the community if you could put this issue in the 7.5. release.

**Comment by tdonohue** [comment]
@michdyk : We will gladly accept a PR for a Polish translation whenever one is ready.  I'll pull this ticket to the 7.5 board in the hopes that it'll be ready in time for 7.5 (which is due Feb 2023)

**Comment by michdyk** [comment]
Hi @tdonohue, We are wondering what translation file should we use as a base for our translation work. Should it be a JSON from the latest release or a recent commits JSON file?

**Comment by tdonohue** [comment]
@michdyk : We already have an (untranslated) language pack file for Polish here: https://github.com/DSpace/dspace-angular/blob/main/src/assets/i18n/pl.json5   So, you should be able to just add your translations into that existing JSON5 file.

If you are looking for more tips on how to translate DSpace 7, we have a translation guide at https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441

If you have other questions, just let us know!

**Comment by michdyk** [comment]
@tdonohue: The following file has no translations which means it contains just english version. We translated the whole system completely and precisely to contribute the full polish translation to the community. I would also kindly ask to put me as a responsible contact for polish translation at the page https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441 that you mentioned.

**Comment by tdonohue** [comment]
Hi @michdyk : Sure, I've added your name under the Polish translation. https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441

I appreciate your help on this translation.  It appears that someone else volunteered a while back and never completed the translation in `pl.json5`.  But, the `pl.json5` file is meant to contain _all Polish text_ per the instructions at https://wiki.lyrasis.org/pages/viewpage.action?pageId=117735441.  So, if you can update that file with your translation, then I'll help get it reviewed quickly & merged into the next DSpace release.  Thanks!

**Comment by michdyk** [comment]
Hi @tdonohue,
We did a pull request for Polish translation. I am not sure that I did everything correctly, so if you would have some time to review it, I will appreciate that. Here is the link to PR: https://github.com/DSpace/dspace-angular/pull/2001
I contribute for the PCG Academia company, so if that PR will be accepted, we would like to have the name of the company apart from my name on the translators' website, if it is possible.
Thanks, Michał

**Comment by tdonohue** [comment]
Thanks @michdyk !  At a glance the translation PR looks good.  I'll give it a test (and basic verification with Google Translate) when I have a chance (hopefully later this week or early next) and let you know if there are any problems.

Assuming it is accepted/merged, your name & your institution's name will be listed in our [Release Notes](https://wiki.lyrasis.org/display/DSDOC7x/Release+Notes) for the 7.5 release (due in Feb).  You can see how others are listed in past releases (see the sections named "New/Updated Language support").

**Comment by michdyk** [comment]
Thanks @tdonohue! I believe that there are not going to be any problems with the translation itself. We prepared it with great attention. The file was translated 100% manually, then we also prepared some corrections in the context of our local DSpace demo.
