### ISSUE TITLE
Syndacation feed force a sort by title asc that makes no sense

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#1935]
**Describe the bug**
The syndacation feed icon / link shown in the home page of the repository or of community/collection leads to an incorrect link to the opensearch controller that include sort parameter by title asc.

Syndacation feeds must be by their mean sorted by date accessioned desc, that is the default implemented by the controller if no sorting parameters are provided

https://github.com/DSpace/DSpace/blob/main/dspace-server-webapp/src/main/java/org/dspace/app/rest/OpenSearchController.java#L152

**To Reproduce**
1. Navigate to the DSpace 7 Demo Site: https://demo7.dspace.org/
2. Click the feed icon and check the link, you will see that the following parameters are included `&sort=dc.title&sort_direction=ASC&query=*`

**Expected behavior**
No sort parameters should be present so that the default managed on the REST side will be used

**Related work**
[Another related Syndaction feed issue](https://github.com/DSpace/dspace-angular/issues/1905)

**Comment by tdonohue** [comment]
Closing, as this appears to have been fixed by #1934
