### ISSUE TITLE
Update to Angular 5

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#194]
[Angular 5 was released](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced)

At first glance, the only things that need to change to be compatible are:
- a few OpaqueTokens that need to be replaced by InjectionTokens
- we need to replace Http with HttpClient in the DSpaceRESTv2Service

The following dependencies have no compatible version yet:
- `@angularclass/idle-preload`: 
  - Symptom: Breaks build (uses OpaqueToken)
  - Issue: https://github.com/AngularClass/angular2-idle-preload/issues/6
- `@ngrx/platform`: 
  - Symptom: peer-dependencies warning
  - Issue: https://github.com/ngrx/platform/issues/538
- `ng-bootstrap`: 
  - Symptom: peer-dependencies warning
  - Issue: https://github.com/ng-bootstrap/ng-bootstrap/issues/1938

@wellingWilliam do we still need idle-preload? it hasn't been updated in almost a year…

**Comment by artlowel** [comment]
After the update we can remove our custom transfer-state module, and [switch to the new built-in one](https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c)

**Comment by born2net** [comment]
sorry if repeating myself, but we are using previous version of ngrx and wondering if we can have it also be maintained so we can upg to ng5 (opaque token removed version)

regards

Sean

**Comment by artlowel** [comment]
@born2net You're asking in the wrong place. This project makes use of ngrx. Try https://github.com/ngrx/platform/issues

**Comment by born2net** [comment]
Oops ... sorry. tx!

**Comment by artlowel** [comment]
Angular 5 requires a different AoT webpack plugin: https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack

**Comment by artlowel** [comment]
ng-bootstrap should be compatible now. They closed https://github.com/ng-bootstrap/ng-bootstrap/issues/1938 and [released a new version](https://github.com/ng-bootstrap/ng-bootstrap/releases/tag/1.0.0-beta.6)

**Comment by tech-no-logical** [comment]
I installed beta 6, but still have the warning : 

`npm WARN @ng-bootstrap/ng-bootstrap@1.0.0-beta.6 requires a peer of @angular/forms@^4.0.3 but none was installed.`
