### ISSUE TITLE
need to fix test cases of date.util.spec.ts

### ISSUE THREAD

**Issue by Nik5992** [DSpace/dspace-angular#1941]
**Describe the bug**
While running test cases, its failing for date.util.spec.ts file

**To Reproduce**
1. run  yarn test:watch 
2. then check in browser or terminal, it shows test cases failing with test case names
https://freeimage.host/i/brnWu4

**Expected behavior**
test cases should pass without failing

**Related work**
none

**Comment by corrad82-4s** [comment]
we at 4science can look into it, estimation to solve it is 2 to 4 hours

**Comment by tdonohue** [comment]
@corrad82-4s : Thanks! I'll pull this over to the board for you to work on for 7.5.  Strangely, I cannot reproduce this locally, but it sounds like it's occurring in some timezones or OSes.

**Comment by davide-negretti** [comment]
@tdonohue I can confirm that it depends on the time zone. It is a common problem with time zones that have a positive UTC offset.
