### ISSUE TITLE
Refactoring of login components

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#1943]
DSpace currently uses a component for each login method. Currently we have`log-in-oidc` `log-in-orcid` and `log-in-shibboleth` which are basically the same, and they could be replaced with a single `log-in-external-provider` component.

**Comment by davide-negretti** [comment]
We'd like to handle this one. Estimated effort is 2-3 hours.

**Comment by tdonohue** [comment]
@davide-negretti : Sounds good & I agree this would be a worthwhile refactor.  I'll move this over to the 7.5 board and assign to you.  Feel free to delegate to other team members as needed.
