### ISSUE TITLE
Common Extendend Regex format for submission-forms

### ISSUE THREAD

**Issue by vins01-4science** [DSpace/dspace-angular#1950]
**Describe the bug**
As of now, because the same field (`regex`) is shared between `Java` and `JS/TS` languages you can't use a common flag format to make it work for both.
As an example, if you choose the _Java inline flag format_ your regular expression will be: `(?i)[a-z]+`
> This expression will search for a word made of characters between `a` and `z` in upper or lower case (i flag means `case insensitive`).
With this regex the `REST` part will work as expected, but the `anglular` one will not recognize this syntax.
- The String `hello`:
  - will be recognized valid by the `angular` part;
  - will be recognized valid by the `REST` part.
- The String `123`:
  - will be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.

> The `angular` part can have unexpected behavior, because the string `(?i)[a-z]+` is not a valid `RegExp`, and will throw an exception during the creation phase.

Similarly, if you choose the ECMAscript format: `/[a-z]+/i`.
- The String `hello`:
  - won't be recognized valid by the `angular` part;
  - won't be recognized valid by the `REST` part.
- The String `/hello/i`:
  - will be **wrongly** recognized valid by the `angular` part;
  - will be **wrongly** recognized valid by the `REST` part.

The baddest news is that `/hello/i` could have been successfully saved in DSpace, and for the String `hello` the red input-box will have a red border and a validation message will be shown saying that: _**the value is not valid for the regex**_ `/[a-z]+/i`.
The user could misunderstand this message, because the string 'hello' will be valid for the format `/[a-z]+/i` inside a regex-tester, and because we are in ECMAScript-domain this should be valid.

The solution could be use of the standard ECMAScript `/{regex}/{flag}` recognize it and split it into two parts, using them correctly to create `RegExp`. And also use this format `/{regex}/flag` as part of validation message for the user (because we show it inside the `angular` part, and I think is easily understandable, the other format could led to misunderstanding because of `?` that is also the lookaround hook).

**To Reproduce**
Insert some regex with flags /{regex}/{flags} inside input-forms definition file, or insert a regex with / as delimiter: /{regex}/. This could led to wrong / unexpected behaviors.

**Expected behavior**
We should use the extended definition for regex, that will support all of these cases:

/{regex}/{flags}
/{regex}/
{regex}
In this way we could easily parse and compute the right pattern with or without flags, and also check that the regex field contains a valid pattern.

**Related work**
Linked to this `Backend` issue: https://github.com/DSpace/DSpace/issues/8563

**Comment by vins01-4science** [comment]
@tdonohue: I need also to work on this linked issue, as it's a part of the `backend` one.
Thank you.

**Comment by tdonohue** [comment]
@vins01-4science : Sounds good, I'll assign back to you for 7.5
