### ISSUE TITLE
Admin item edit doesn't work properly after saving changes the first time

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1966]
**Describe the bug**
The admin item edit functionality doesn't work properly after saving a metadata the first time

**To Reproduce**
1. with admin user go to the edit metadata page for an item
2. edit a metadata and after confirming click on save button
3. edit the same or a new metadata
4. at this point the table content disappear and is not possible to proceed with the operation

https://user-images.githubusercontent.com/2486489/201942855-f615d637-82cf-4e15-918f-5d87de58f294.mp4

**Comment by tdonohue** [comment]
Closing, as this is no longer reproducible in 7.5.  It appears to have been fixed by #2028
