### ISSUE TITLE
Missing highlights in title in search results

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#1968]
**Describe the bug**
When a search is performed, discovery search response brings information about terms to be highlighted in title. 

`https://api7.dspace.org/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&configuration=default&query=dengue&embed=thumbnail&embed=item%2Fthumbnail&embed=accessStatus` 

returns
![image](https://user-images.githubusercontent.com/70699836/202520830-a6a32259-7787-482d-8f4d-cb27cd62d8a6.png)

but "dengue" term is not highlighted in title

![image](https://user-images.githubusercontent.com/70699836/202520916-4032aa72-de39-4cca-9839-9d126f602e67.png)

**Expected behavior**
Searched terms highlighted in title as well

**Comment by corrad82-4s** [comment]
We at 4Science are available to look into this. Roughly we estimate this update in 4 hours of work

**Comment by tdonohue** [comment]
@corrad82-4s : Sounds good. I'll pull this over to the 7.5 board and assign to you for you/your team to work on.
