### ISSUE TITLE
Thumbnails in submission forms rendered incorrectly

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1974]
**Describe the bug**
In submission, Relationships in the form don't load thumbnails and don't scale placeholder font correctly.
We've seen the same issue in other places before.

**To Reproduce**
1. Start a submission in a Collection that has a Relationship field in one of its forms
2. Add a Relationship by lookup
   (Refresh the page so that the new Relationship show up, see https://github.com/DSpace/dspace-angular/issues/1671)
   * **Thumbnail placeholders will appear even for Items that have thumbnails** (missing `followLink`?)
   * **Thumbnail placeholder text does not resize for narrow viewports**
  
![20221121-182904](https://user-images.githubusercontent.com/31547038/203121560-5dd9eec3-ab40-4784-b9f2-8e7e1e4e625a.png)

  

**Expected behavior**
Thumbnails should appear and placeholder text should scale in the same way as it does in search/browse/edit/...

**Related work**
https://github.com/DSpace/dspace-angular/pull/1780
https://github.com/DSpace/dspace-angular/issues/1883

**Comment by tdonohue** [comment]
Pulling this over to 7.5 board & flagging as high priority.  I suspect this is just a minor CSS related issue.  @mspalti : pinging you in case you have time for a quick fix.  Volunteers welcome.

**Comment by mspalti** [comment]
@tdonohue, I'll take a look.
