### ISSUE TITLE
Multiple components use "in place links" instead of buttons

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#1990]
**Describe the bug**
First noticed this on Items with many Bitstreams: the pagination buttons of the simple file section trigger an unnecessary page reload when clicked.
* This is due to the fact those buttons are `<a [routerLink]="[]">`
* If we use `<button>` instead, this won't happen (and a11y would be improved)
* There's at least three similar cases (Community list, metadata representation, related Items)

**To Reproduce**
1. Find or create an Item with more than 5 Bitstreams in the ORIGINAL Bundle 
   (e.g.: https://demo7.dspace.org/handle/10673/244311)
2. Go to the simple Item page
3. In the file section, click on "Show more" / "Collapse"
   * Each click will cause the whole page to reload
   * Pagination still works though

**Expected behavior**
Buttons that don't do any routing should not have router links.

**Related work**
https://github.com/DSpace/dspace-angular/pull/1567: One of the automatic upgrades changed these from `<a [routerLink]="">` to `<a [routerLink]="[]">` but at the time I didn't notice the bug

**Comment by ybnd** [comment]
@tdonohue Atmire would like to claim this issue. Should take about **1h** to address

**Comment by tdonohue** [comment]
@ybnd : Sounds good!  I'll assign to you for 7.5 and add the estimate.
