### ISSUE TITLE
Input field values for metadata declared with metadata.hide are hidden when opening a previously-saved submission

### ISSUE THREAD

**Issue by uofmsean** [DSpace/dspace-angular#1997]
**Describe the bug**
DSpace 7.4 (Tested with Firefox 107 and Chrome 108)
The values for input form metadata fields declared with the metadata.hide configuration are hidden on first load of a previously-saved workspace submission. This will confuse the user as they will not see the value that was previously entered (although it was saved to the database). To further confuse matters, if any input field is modified, and the "Save" button is selected, the initially hidden metadata values will appear.

**To Reproduce**
1. Declare a metadata field to be hidden via the appropriate metadata.hide parameter in local.cfg
2. Declare an input field for the metadata (e.g., onebox) in a testable input form in submission-forms.xml
3. Restart the UI and backend
4. Log in as a non-Admin user and start a new submission using the test input form
5. Enter a value for the "hidden" input field
6. Select "Save for later"
7. Verify that the database metadatavalue row is present (i.e., input value was saved)
8. Edit the previously-saved submission
9. The value for the input field will be blank
10. Edit any other input field (to enable the Save button)
11. Select Save
12. The previously entered value for the input field is now displayed

**Expected behavior**
Any input field values for metadata declared with metadata.hide should be viewable at all times during an in-progress submission. The metadata.hide declarations should only take effect once the item has been archived. This is the behaviour in DSpace 6.x and allows a "protected" metadata value to be initially entered by the submitter but subsequently hidden from view (to non-Administrators) once the item has been archived.

**Related work**
Link to any related tickets or PRs here.

**Comment by f-rapp** [comment]
Hi, We noticed the same error.
We could not reproduce steps 10 to 12, though: the field stayed blank. We tested this for a workflow item.

**Comment by uofmsean** [comment]
@f-rapp, I think for steps 10 to 12 it might have been Firefox filling in the fields automatically, although I haven't confirmed this yet.

**Comment by toniprieto** [comment]
Something similar could happen when a local admin tries to add a hidden metadata. I think users with edit item permission should be able to see this metadata. I have just submitted a PR with this change.
