### ISSUE TITLE
Hard to diagnose failures in AuthInterceptor

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#2005]
**Describe the bug**
More than once I've had to figure out some misconfiguration which resulted in an unexpected response to authentication.  Typically this is all I get in the log:

ERROR SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at AuthInterceptor.makeAuthStatusObject (/opt/ds7-scholarworks/dist/server/main.js:1:727375)
...

This is not much of a clue.  To see the entire string fed to JSON.parse might be more enlightening.  One supposes that the body of the response is HTTP rather than JSON, owing to the left broket, but the service's carefully constructed error report is swallowed.

When proxying through Apache HTTPD, what I see in the browser is that the first request hangs for a long time, followed by a "bad gateway" report from HTTPD.  The frontend service is apparently failing to respond after the SyntaxError is thrown.  I have a patch (to follow) which catches the error and tries to return a reasonable response, but it still hangs, so *that* problem seems to be further up the stack.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**
Uninterpretable responses should be reported fully to assist in diagnosis.

**Noted**
There are 12 uses of JSON.parse in the codebase.  I don't know how many of them may be vulnerable to unexpected data.

**Comment by tdonohue** [comment]
Closing, fixed by #2006 in 7.5
