### ISSUE TITLE
RxJS 5.5: Pipeable Operators

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#201]
With the angular 5 update, comes an RxJS update as well. It introduces the concept of lettable operators. The following article explains the concept in detail: https://blog.angularindepth.com/rxjs-understanding-lettable-operators-fe74dda186d3
We should switch to this way of working instead of chaining RxJS operators

**Comment by artlowel** [comment]
This article is less detailed and more to the point: https://blog.hackages.io/rxjs-5-5-piping-all-the-things-9d469d1b3f44

**Comment by artlowel** [comment]
TL;DR Where you previously wrote:

```typescript
someObservable
	.map(x => x.y)
	.filter(y => isNotEmpty(y)
	.distinctUntilChanged()
	.subscribe(…)
``` 

You can now write
```typescript
someObservable.pipe(
	map(x => x.y),
	filter(y => isNotEmpty(y),
	distinctUntilChanged()
).subscribe(…)
``` 

Which has the advantage that you only need to include the operators you actually use in the app, so it will be smaller.

It also makes it easier to reuse chunks of code like these that occur in multiple places, because you can simply assign them to a variable (they are "lettable") and reuse them somewhere else.

```typescript
let myOperations = pipe(
	map(x => x.y),
	filter(y => isNotEmpty(y),
	distinctUntilChanged()
)
…
someObservable.let(myOperations).subscribe(…)
```

**Comment by frederik** [comment]
Hi, just wanted to chip in since I just did a Angular 4->5->6 migration (including a lot of rxjs operators) on one of our projects. I used rxjs-lint as described here https://github.com/reactivex/rxjs-tslint - this worked really well at least for my last migration from 5->6 (e.g. rxjs 6). Before you explore manual options, you might want to give this a try.

**Comment by artlowel** [comment]
Thanks for the tip, I'll give it a try.

**Comment by artlowel** [comment]
@courtneypattison I wouldn't start working on this. @LotteHofstede has already used the tool @frederik suggested above to fix all rxjs operators at once in [her angular 6 branch](https://github.com/atmire/dspace-angular/tree/resolvers-branch-angular6). I'll update the task accordingly.
