### ISSUE TITLE
Export csv button should be present only in specific pages

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#2010]
**Describe the bug**
Export csv button is present every time the search component is used because is part of the [search-results.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/search/search-results/search-results.component.html#L3).
In my opinion since the search component is used in several part of the application it is logically wrong to assume that the export functionality should always be available. Its presence should be conditional.
An example is the [dynamic-lookup-relation-search-tab.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/search-tab/dynamic-lookup-relation-search-tab.component.html), used to lookup during the submission, where the export button is not useful
![Schermata da 2022-12-22 16-31-06](https://user-images.githubusercontent.com/2486489/209172243-12c33eee-0f70-4755-b0f3-2d5383393ed2.png)

**Expected behavior**
I expect the export csv is available ony in the page where is should be used, for example in the public search page or the mydspace page

**Comment by tdonohue** [comment]
@atarix83 : Agreed. I've seen this bug as well on some pages where the button is not useful. Flagging as a usability issue and moving to 7.5 in case someone has a chance to look into it.
