### ISSUE TITLE
Community/Collection logo not showing when browsing with a non-default filter

### ISSUE THREAD

**Issue by AndreaBarbasso** [DSpace/dspace-angular#2046]
**Describe the bug**
On DSpace7, while browsing Communities and Collections with a logo, if you click on any filter (_By Issue Date, By Author, ..._) the logo disappears.  
  
**Default filter:**
![image](https://user-images.githubusercontent.com/6990476/213160929-0ec0d6fa-f2ca-45bc-9ced-a11c7bb070cc.png)  
  
**By Issue Date filter:**
![image](https://user-images.githubusercontent.com/6990476/213161054-2f92d9b9-ba22-495b-9768-7bbb156d102b.png)

[Community Example](https://demo7.dspace.org/communities/065044c7-9a60-45f2-85db-904be000f5a0)  
[Collection Example](https://demo7.dspace.org/collections/74b6a434-ee15-448e-aa84-82a44f3ca7cc)  

**To Reproduce**
1. Follow any one link above and notice the Community/Collection logo;
2. Click on "By Issue Date" or any other filter.

**Expected behavior**
The logo should still be displayed.

**Comment by atarix83** [comment]
@tdonohue 

we can work on this, the estimation is around 2/4 hours
