### ISSUE TITLE
In the User Interface, text missing between  <strong> tags and after <br/> tag in Finnish and Swedish

### ISSUE THREAD

**Issue by reetagithub** [DSpace/dspace-angular#2086]
**Describe the bug**
There is text missing in Finnish an Swedish when < strong > and < br/ > tags are present in the translation key.  The key is
"cookies.consent.content-notice.description”: “Keräämme ja käsittelemme tietojasi seuraaviin tarkoituksiin: <strong>todentaminen, asetukset, kuittaus ja tilastot</strong>. <br/> Lisätietoa saat lukemalla tämän: {privacyPolicy}.“

The text within the < strong > tag is not shown in the UI. Nor is the text after < br/ > tag.

This applies to Finnish and Swedish. English is ok. I took a look at demo at https://demo7.dspace.org/home, and it seems that other languages do not have this problem, although many had English version, the text was not translated.

I noticed this at our private test server, where version is 7.4.  I do not know, if the problem persist on other translation keys, or other HTML tags.

**To Reproduce**
1. Open the home page of DSpace installation.
2. Change the language to Finnish / Swedish
3. See how many lines there are in the text in the pop up window on the lower corner on the right.
4. (This I did not do): If possible, locate other translation keys with different HTML tags in the UI and compare their length with the English versions. 

In English:
<img width="402" alt="Näyttökuva 2023-2-10 kello 6 19 50" src="https://user-images.githubusercontent.com/51482276/218000099-cf943fa2-7e68-408c-a1d5-2b4f589facd2.png">

In Finnish and Swedish:
<img width="399" alt="Näyttökuva 2023-2-10 kello 6 20 05" src="https://user-images.githubusercontent.com/51482276/218000130-d7286516-7963-4d62-b607-dd5d8d4bef98.png">

<img width="409" alt="Näyttökuva 2023-2-10 kello 6 20 17" src="https://user-images.githubusercontent.com/51482276/218000149-3879b9d1-d17c-4a59-bde9-4bb5c32f2e1d.png">

**Expected behavior**
The text shown as described in the language files fi.json5, sv.json5.
 
**Related work**
After creating this report I took a loot at you demo https://demo7.dspace.org/home. Finnish and English are ok there, all the text is shown.

**Comment by anis-moubarik** [comment]
This is fixed by pulling the latest code and configuration concerning Klaro consent manager.

**Comment by tdonohue** [comment]
Closing as this appears to be solved in 7.5
