### ISSUE TITLE
Withdrawn items crash the frontend for not-logged-in users

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#2090]
**Describe the bug**
Withdrawn items crash the frontend for not-logged-in users on the latest 7.5-snapshot

**To Reproduce**
You can try this locally or on demo7.dspace.org
**If you try it locally, this only happens if you start DSpace via `yarn start`. If you use the development mode via `yarn run start:dev` everything works as expected!**

1. Login as admin
2. Withdraw an item
3. Open the withdrawn item - it shows metadata and a note that this item is withdrawn
4. Logout!
5. Open the withdrawn item - you get a proxy error, the frontend process crashes

**Expected behavior**
The frontend should not crash. Instead it should show an empty page with a note, that this item has been withdrawn.

**Comment by tdonohue** [comment]
Thanks @MW3000 !  I can verify this locally, on the latest `main`.  It appears to be something crashing SSR (server side rendering), and this error is spit out:
```
TypeError: Cannot read properties of undefined (reading 'payload')
    at C:\dspace-angular\dist\server\main.js:1:296394
    at C:\dspace-angular\dist\server\main.js:1:4370695
    at OperatorSubscriber2._this._next (C:\dspace-angular\dist\server\main.js:1:4293062)
    at Subscriber2.next (C:\dspace-angular\dist\server\main.js:1:4243560)
    at C:\dspace-angular\dist\server\main.js:1:4326577
    at OperatorSubscriber2._this._complete (C:\dspace-angular\dist\server\main.js:1:4293318)
    at Subscriber2.complete (C:\dspace-angular\dist\server\main.js:1:4243907)
    at C:\dspace-angular\dist\server\main.js:1:4376471
    at OperatorSubscriber2._this._complete (C:\dspace-angular\dist\server\main.js:1:4293318)
    at Subscriber2.complete (C:\dspace-angular\dist\server\main.js:1:4243907)
```

@artlowel  or @ybnd : Would one of you have time to dig into this severe issue tomorrow (during your day)?  I'm not exactly sure where this is coming from & likely won't get to this before the end of my day.

**Comment by tdonohue** [comment]
I found a few extra minutes at the end of my day to look into this & located the fix.  See #2091.

It was an easy fix after all... just had to figure out which part of our code was around character 296,394 of our compiled `main.js`:
```
TypeError: Cannot read properties of undefined (reading 'payload')
    at C:\dspace-angular\dist\server\main.js:1:296394
```
