### ISSUE TITLE
No option appears for Bundle when the user is loading a bitstream of an item

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/dspace-angular#2101]
Hello @tdonohue i found an issue

**Describe the bug**
When the user tries to upload a bitstream when he is editing an item bundle options does not appear.

**To Reproduce**
1. Login as Administrator
2. Edit any item
3. Go to bitstreams section
4. click on upload button
5. try to select a bundle

![image](https://user-images.githubusercontent.com/51240376/219169623-70858fcc-840f-44f4-90ae-aeb291fcf2ff.png)

**Expected behavior**
The user should be able to see the option texts.

**Comment by tdonohue** [comment]
@CrisGuzmanS : Thanks for reporting this! I'm able to verify this as well on my end.  I'll see if I can find a volunteer to figure out a fix immediately before the 7.5 release.
