### ISSUE TITLE
Use bitstream description instead of file name in item view if present

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#2103]
**Is your feature request related to a problem? Please describe.**
As of DSpace 7.5-SNAPSHOT the item view still uses the file name for bitstreams in the item view. 

<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/191754/219294460-bca8d9d1-9543-4279-81fb-b5415593772d.png" />
</p> 

**Describe the solution you'd like**
In DSpace 4/5/6 the XMLUI would opportunistically use the bitstream description instead if it was present. This is very useful if you have messy file names and want to display something more pleasant. For example:

<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/191754/219294083-2d17be28-b5e4-4a79-93e9-4e618be7d0c0.png" />
</p>

**Comment by bram-atmire** [comment]
I would argue it's a bug instead of a new feature. If we are no longer leveraging/using bitstream descriptions in a case where we were in the past, it's a bug/regression and not a new feature.

Can confirm that I recently saw the exact same behaviour, where we tried to modify the displayed bitstream name by adding a description but where that didn't seem to have any effect.

**Comment by alanorth** [comment]
I just realized that the description _is used_ on the full item page:

<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/191754/219596843-0a408e75-6b9e-4aed-a5f4-a2d86b16b9ba.png" />
</p>

So this should be very easy to fix in the simple item view. I've submitted #2108 to fix this. Please take a look, as I'm new to Angluar. Thanks!

**Comment by tdonohue** [comment]
Moving this to the 7.6 board in case we can find a volunteer. As discussed in #2108 comments, I think the solution here needs to include *both* the description and the filename, as both were discoverable in 6.x.   So, simply replacing the filename with the description doesn't seem like a full solution.  See this comment for more details: https://github.com/DSpace/dspace-angular/pull/2108#issuecomment-1438714657

In any case, needs a volunteer

**Comment by alanorth** [comment]
FYI I've implemented this as a themed file-section component. Here's how it looks:

<p align="center">
  <img src="https://github.com/DSpace/dspace-angular/assets/191754/e18644a5-76ca-4417-b327-8a6e04d197da" width="600">
</p>

The component opportunistically uses the bitstream description and appends the file extension (via a helper function in the component). If the bitstream doesn't have a description then the old behavior is used:

<p align="center">
  <img src="https://github.com/DSpace/dspace-angular/assets/191754/304ae300-d718-4576-b70d-051eb430738d" width="600">
</p>
