### ISSUE TITLE
UX: Thumbnail is never available during the submission

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#2105]
**Describe the bug**
The upload step in the submission includes a thumbnail but this can never be present at this stage.

**To Reproduce**
1. start a new submission and upload a file
2. the upload step will show a "No thumbnail available" placeholder

**Expected behavior**
It would be better to avoid to include the thumbnail placeholder at all. The extra space could be used to provide more information about the file that are currently hidden in the edit screen (access conditions and extra metadata) or details about technical metadata (format and checksum)

**Comment by tdonohue** [comment]
Agreed, the thumbnail placeholder likely should not be displayed at all on the submission form, since it will never be visible in the submission itself.

This needs a volunteer, but it seems like a lower priority task right now.
