### ISSUE TITLE
When importing entities, duplicate entity items can be created (single collection, slow API, UX)

### ISSUE THREAD

**Issue by kshepherd** [DSpace/dspace-angular#2115]
**Describe the bug**

When importing external data objects as entities (eg. importing a new Person entity from ORCID while using the Author relation lookup for a Publication), it is possible to accidentally create *two* new entities, with just one of them related to the Publication item.

This occurs when there is a single collection configured for the entity type in question (eg Person), and the remote API is relatively slow.
The user is presented with a UI control that lists the (single) collection, but no clear indication that a `get` is currently waiting, and the collection will be auto-selected once the record is retrieved from the remote source.

If the collection is selected ("clicked") -- an action that I seem to be asked to do  -- this will trigger an import to the collection. Then, when the earlier XHR completes, I believe a second import is triggered. (I could be wrong about the exact timing or nature of the slow request)

I discovered this while using a new data source which responded considerably slower to API requests compared to ORCID. With ORCID, the get responses tended to ber quick enough that I didn't have *time* to click the button that causes an extra import.

When I added a second collection that also was configured for entity type Person, the problem disappeared because at the time of import, the user is simply presented with a list of the multiple collections and there is no auto-selection of a collection, hence no additional XHR to wait for.

**To Reproduce**
1. Configure an external source for import of an entity, and set up submission appropriately. Make sure there is just ONE collection that holds this entity type.
2. If you can, artificially slow down the API responses of the remote service.
3. Get to a point in submission where you have the lookup modal, search for an external data object and click the import button
4. Choose import as new local entity
5. Quickly, as soon as the UI changes to show the collection, click that button. It will begin an import. You might see two status popups. If the remote service isn't sufficiently slow to respond, you might need to time this carefully.
6. Check local data. There will be two duplicate entities, one of which is linked to the item in submission.

**Expected behavior**
I think this is a combination of UX and some async confusion. If there is only one collection that a new Person can be imported to, I see the sense in automatically selecting the collection, but in that case we should not present the submitter with a choice at all - this part of the process should just be skipped / invisible.

But it also seems that we need to cancel any existing request when the button is clicked, or disable the button until current requests are complete? Perhaps others have a better idea of how to tackle this.

**Comment by tdonohue** [comment]
Definitely sounds like an obscure bug, but good that you documented it clearly.  I don't have any great ideas on solving it, as it looks like it needs someone to dig into a bit deeper to figure out the best solution.

For now, moving to needs volunteer in the hopes someone can look at this in more detail.

**Comment by kshepherd** [comment]
@bram-atmire i think it is the same. if you have only one valid collection to choose from, note that you can just "wait" and it will be selected by the system after the external data import completes.
i had not caught the fact that the collection can be clicked more than once

**Comment by tdonohue** [comment]
@kshepherd : If you have any time to provide some help testing... there's a fix for #2167 / this issue submitted in #2183 .  I'd appreciate help in testing #2183 if you can find time.

**Comment by tdonohue** [comment]
Appears to be fixed by https://github.com/DSpace/dspace-angular/pull/2183 in 7.6. We can reopen later if we find it still exists.
