### ISSUE TITLE
Administer workflow actions do not work

### ISSUE THREAD

**Issue by amgciadev** [DSpace/dspace-angular#2118]
**Describe the bug**
When trying to either send back or delete a workflow item via the Administer workflow page nothing happens when clicking the buttons
**To Reproduce**
1. Log in as administrator
2. Go to the Administer workflow page
3. Choose any item and select either send back or delete
4. From the action page select the desired action

**Expected behavior**
The selected action gets performed and the user is directed back to the administer workflow

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
Verified this in 7.5.  It appears the Supervision Orders work (#2019) may have broken the "Delete" and "Send Back" buttons.  The Supervision order buttons work though.

@corrad82 and @atarix83 : Would someone on your team be available to look at this?  It appears, to me, that these buttons broke in 7.5 after #2019 was merged.

**Comment by atarix83** [comment]
hi @tdonohue 

we didn't touch that part directly in the supervion order, becasuse the buttons just redirect to pages where differents components are used.
However the involved components have been touched recently by the following comments :
https://github.com/DSpace/dspace-angular/commit/dce84dbe70d4ea200a3c38576008792e013b165f
https://github.com/DSpace/dspace-angular/commit/34e970827e362d6eb0cbb4e07ad55e45742169c9 

We can have a look anyway but not in a very short time, probably next week. Let us know if you prefer to assign to others

**Comment by tdonohue** [comment]
@atarix83 : If you can look at this next week, that's fine. There's no rush, I just wanted to get a solution built.  Apologies for not noticing which changed touched this code.
