### ISSUE TITLE
Cannot bookmark / return to an existing URL on demo site

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#212]
Browsing the demo site (https://dspace7-demo.atmire.com/) works fine if you start from the homepage.

However, you cannot seem to save a link to an existing item / community / collection and return directly to that page.

For example, these objects all exist on the demo site, and can be browsed to. But, direct links to them all will result in a Proxy Error:
* https://dspace7-demo.atmire.com/communities/7669c72a-3f2a-451f-a3b9-9210e7a4c02f
* https://dspace7-demo.atmire.com/collections/1c11f3f1-ba1f-4f36-908a-3f1ea9a557eb
* https://dspace7-demo.atmire.com/items/0ec7ff22-f211-40ab-a69e-c819b0b1f357

I have not yet tried this out locally, but I assume it likely would also occur there.

**Comment by tdonohue** [comment]
After further testing, this may be related to an issue with Angular Universal

If I turn off Javascript in my browser, I can load the homepage of the demo site.  However, browsing does not work and all other pages throw the same Proxy Error.

**Comment by artlowel** [comment]
It turned out to be an issue with the server. After a recent upgrade of packages on the server not everything had restarted properly.
