### ISSUE TITLE
browse-by-metadata-page does not work correctly on numeric "value" param

### ISSUE THREAD

**Issue by ubks-mp** [DSpace/dspace-angular#2128]
**Describe the bug**
We have metadata (Dewey Decimal Classification, DDC) wich is always saved on its numeric value like 000, 004, 220, etc.
When created an index for that field and configured in the Browse Configuration as

```webui.browse.index.5 = subjectddc:metadata:dc.subject.ddc:text```

this is available in the "All of Dspace" menu, selecting shows a result list of DDC subjects and their count.

When selecting a subject  in the results list , a new  list of items is shown - **despite the URL param ```value``` is numeric and starts with zero (0)**,
e.g. ```/browse/subjectddc?value=004``` the result is ```No items to show.``` and the text is ```Browsing by browse.metadata.subjectddc "4"```, e.g. the leading zeros are shortened.

This does not happen if value is 000 (see below) or any other value not starting with zero.
This is a problem of the SPA, the API works like expected, e.g. ```/server/api/discover/browses/subjectddc/items?spage=0&size=20&filterValue=004"``` returns the JSON with the item data.

**To Reproduce**
Any numeric value in an index with leading zeros will be shortened.

**Expected behavior**
Numeric URL values for browse index should be treated as string.

**Related work**
https://github.com/DSpace/dspace-angular/blob/1d58910d70f3d32d46d0cca2460f79f5d8b7dff1/src/app/browse-by/browse-by-metadata-page/browse-by-metadata-page.component.ts#L154
```params.value``` is the unmodified param from URL; this expression is responsible:
-  if ```params.value``` is emtpy, ```''``` is assigned
-  if ```params.value``` is assumed a number, leading zeros will be shortened by ```+params.value```
-  if ```params.value``` is a number with only zeros, ```+params.value``` will evaluate to boolean false and  ```params.value``` is assigned unmodified

Removing the first part ```+params.value``` solves the problem, but there might be a reason for that.

**Comment by tdonohue** [comment]
@ubks-mp : Thanks for reporting this. I'll pull this over to our 7.6 board.  Since it sounds like you've already found a possible fix, you are welcome to create a PR for others to test.  That might be the easiest way for us to determine if the fix you have found will work for others.  See our contributing guidelines for tips on creating PRs: https://github.com/DSpace/dspace-angular/blob/main/CONTRIBUTING.md

Otherwise, this will likely have to wait for another volunteer to investigate.
