### ISSUE TITLE
Hint is missing for Subject Keywords

### ISSUE THREAD

**Issue by Ma-Tador** [DSpace/dspace-angular#2131]
After configuring the DDC for dc.subject.ddc, the hint is not displayed in the UI. I have attached a picture from my test system.
I noticed the same behaviour for Subject Keywords in the DSpace demo site [https://demo7.dspace.org/](https://demo7.dspace.org/).
The hint is configured in the [dspace]/config/submission-forms.xml, where the dc.subject.ddc is defined.
![ddc_hint_missing](https://user-images.githubusercontent.com/86478723/222704487-05004085-7a34-4137-a39e-f2adada7a7eb.PNG)

**Comment by alexandrevryghem** [comment]
I would like to claim this issue, I will bundle it with the fix for #1770

**Comment by tdonohue** [comment]
@alexandrevryghem : Sounds good!  I'll assign this to you as well too. Thanks!
