### ISSUE TITLE
Value of dropdown changes automatically on item submission page.

### ISSUE THREAD

**Issue by aditya-sawant-dev** [DSpace/dspace-angular#2145]
**Describe the bug**
On item submission page, the value of first dropdown automatically resets to the first value present in the dropdown on pressing "enter" in any of the textbox.

**To Reproduce**
1.	Go to Item submission page.
2.	Select book from “type” dropdown. (Select any value other than first value in dropdown)
3.	Click on text box with label as "identifier" and then press enter.
4.	 After pressing enter check the value of “type” dropdown. It changes to the first value in dropdown.

**Expected behavior**
On item submission page. The value of the dropdown should not change on pressing enter in any of the text box.

**Related work**
NA

The following demo site was used :
https://demo7.dspace.org/home

Attached screenshot of the dspace demo site on which the above mentioned issue was identified.
[dspace-item-submission-bug.pdf](https://github.com/DSpace/DSpace/files/10938215/dspace-item-submission-bug.pdf)

**Comment by aditya-sawant-dev** [comment]
any update for fixes on this bug

**Comment by tdonohue** [comment]
This is waiting on a volunteer, but has been flagged as high priority. No updates other than that, but I hope we'll have a fix in 7.6
