### ISSUE TITLE
Submitter: undefined undefined

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/dspace-angular#2153]
**Describe the bug**
When there is not any submitter, an "undefined undefined" message appears.
![image](https://user-images.githubusercontent.com/51240376/225979465-603c7dec-fbe8-40d3-b612-ff4cc4918771.png)

**To Reproduce**
I am not pretty sure how to reproduce this error, but when i login as admin and i go to: 
https://demo7.dspace.org/mydspace?configuration=workflow

**Expected behavior**
The submitter should not appear if not exists or a message with "N/A". Maybe ussing the translation pipe

**Comment by alexandrevryghem** [comment]
This should be fixed with PR #2129, I replaced all the deprecated usages of `dso.name` with `DSONameService.getName()`. The result looks like this 🤷‍♂️ 
<img src="https://user-images.githubusercontent.com/43750381/227655180-98c1c7b0-2671-485c-ae03-74637ea4aea1.png" width="75%"/>
