### ISSUE TITLE
Provide a way to require Creative Commons license in submission form

### ISSUE THREAD

**Issue by wvalmorbida** [DSpace/dspace-angular#2161]
**Describe the bug**
I need the Creative Commons step to be required in submission process. I tried changing "mandatory" to "true" in step definitions (item-submission.xml) but it didn't work.

<step-definition id="cclicense" mandatory="true">...</step-definition> 

**To Reproduce**
1. Change configuration "mandatory" to "true"
2. Restart tomcat
3. Start new submission
4. Fill all required fields, except cc license
5. Submit submission
6. Done, but shouldn't

**Expected behavior**
Expected that form validation does not allow the submission to be submitted

**Comment by tdonohue** [comment]
Pulling this over to 7.6 board to see if we can find a volunteer.  I suspect the "mandatory" flag isn't being properly checked on the Angular UI side of things (just a quick guess though).

**Comment by tdonohue** [comment]
Revisiting this ticket as a duplicate was just submitted in https://github.com/DSpace/DSpace/issues/9603 

This is a misunderstanding of "mandatory", as "mandatory" in the Submission form just means the step is always displayed. It does not **require** fields to be filled out. 

See https://github.com/DSpace/DSpace/issues/9603#issuecomment-2124524264
> Not a bug, just poor wording. According to [the documentation](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-OptionalSteps):
> > "CC License" section (id="cclicense"): This step allows the user to (optionally) assign a Creative Commons license to a particular Item
>
> This is meant to be optional. ["mandatory" is a different thing](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Structureofthe%3Cstep-definition%3Etag)

> > mandatory (attribute): [true|false] When true, the step's section is displayed by default to all users in the UI. When false, the step is not displayed and must be activated explicitly by the user by selecting it in the UI or supplying data of interest to the section.

That said, I'm leaving this ticket open and recategorizing as a **feature request**.  

It's currently not possible to **require** all users to fill out the CC license field. In the future, this might be possible via a `cc.license.required` configuration which controlled whether the field could be left empty or not. (This would be similar to how we have a `webui.submit.upload.required` field to decide if uploads are required or not.)

**Comment by atarix83** [comment]
@tdonohue 
we can work on this task

**Comment by tdonohue** [comment]
Thanks @atarix83 .  I'll assign this to you then

**Comment by Sondissimo** [comment]
Hello i have provided a pr for this issue :)  https://github.com/DSpace/DSpace/pull/9639
