### ISSUE TITLE
Live import: Duplicate workspace items are created after selecting a target collection

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#2167]
**Describe the bug**

This bug appears in the live import of item metadata from an external source, for example Pubmed.
As a recap: After a search for item metadata in an external source, for example through https://demo7.dspace.org/import-external?entity=Publication, the user gets to see the search results and click the icon next to the search result to start the import for the item.

Clicking this button brings up the collection selection dialog.

There are two separate problems with this dialog that both result in duplicate workspace items to be created:

1. A user can click collections presented in this list multiple teams. With each click, a duplicate workspace item gets created.
2. In the case where only a single possible collection gets shown in the dialog, a duplicate workspace item is created every time.

**To Reproduce**

1. Go to https://demo7.dspace.org/import-external?entity=Publication
2. Search for a record in pubmed, for example with the query "blood".
3. Click on the icon on the left side of a search result, to import this publication
4. Try to click one of the presented collections in the list multiple times.

**Expected behavior**
After a single click on a collection, the user should be prevented from making additional clicks.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
This does sound like it may be the same problem as described in #2115.  Pulling this over onto the 7.6 board to see if we can find a volunteer, as it sounds like it's impacting several people already.
