### ISSUE TITLE
Mathjax code is displayed twice in the UI

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#2170]
**Describe the bug**
When creating MathJax Code in an abstracts, DSpace display the formula twice in the public UI, as shown below: 
![image](https://user-images.githubusercontent.com/19291880/228315700-945a3a35-217f-4a0c-b68d-1703b5f084a6.png)

**Expected behavior**
Formulas do not show twice.

**To Reproduce**
Open a document and in the dc.description.abstract metadata copy and past, save and then display the page in the public UI the following code: 
```Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rutrum mi ligula, eget luctus diam ultricies vitae ${\ell}$. Quisque elit libero, eleifend eu pretium a, gravida at felis. Proin sed imperdiet nibh. Integer sit amet eleifend ligula. Maecenas semper vestibulum lorem. Mauris ut tortor diam ${\color{Red}2\ell\geq\binom{d}{\lfloor\frac{d}{2} \rfloor}}$. Sed elementum erat dolor, id rhoncus augue dignissim et. Curabitur a ligula vestibulum sapien maximus ultricies dignissim at leo ${\color{Red}\textit{L}_T}$. Mauris vulputate magna at turpis eleifend, sit amet lacinia tellus malesuada. Nam nisi ex, ultrices sed posuere at, laoreet vel ligula. Aenean scelerisque in lacus sed tristique ${\color{Red}\mathcal{O}\left(\textit{L}_T\text{ log}\left(\textit{L}_T\ell \right) \right)}$. Pellentesque rhoncus viverra metus vitae scelerisque. Aliquam iaculis commodo erat, tincidunt auctor augue tincidunt sit amet. Suspendisse placerat velit ut magna vulputate semper. Praesent non aliquet tortor.```

**Comment by tdonohue** [comment]
I can verify this is occurring for me as well.  The first display is an SVG rendering of the equestion. It almost looks like the second display is plain text meant to be for accessibility or similar (haven't dug deep enough though). So, it's possible it may simply need to be hidden via SCSS or similar.  

In any case, needs a volunteer to investigate.  It's possible this is a simple misconfiguration of the MathJax library we are using, or maybe just incorrect CSS.

**Comment by nishchay7pixels** [comment]
I'll look into it.
