### ISSUE TITLE
Internalization (i18n): Vietnamese translation!

### ISSUE THREAD

**Issue by Zerosoul1990** [DSpace/dspace-angular#2172]
Hi,

We are working on translating the User interface into Vietnamese and will try to create a pull request soon upon completion of the job.

Thanks,
Vu Nguyen

**Comment by tdonohue** [comment]
Thanks @Zerosoul1990 !  That'd be great. I'll pull this over onto our 7.6 board.  If it's ready in time for 7.6, we'll get it added to that release. Otherwise, we'll work to get it into the very next release.
