### ISSUE TITLE
Fix problem with registration of new user for same email than existing user in 7.5

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#2175]
**Describe the bug**
In DSpace 7.5 you can start the registration process for a new user with an email address that is the address of an already existing user. You receive the email to complete the registration, and only when you try to finish the registration you get an unspecific error message.

**To Reproduce**
1. Create a new user with an email address
2. Finish the registration process
3. Create another user with the same email address
4. You receive an email to finish the registration process, only when you complete the registration process, you get an unspecific error message, saying "Registration failed An exception has occurred"

**Expected behavior**
When you try to register a new user with an email address for which a user exists already, the UI should tell you so, and perhaps offer to reset the password, in case you forgot the password. In no case should it start a new registration process.

**Screenshot**
That's the error message you get, when you try to complete a registration for an email address for which a user exists already:

<img width="1392" alt="Screenshot 2023-03-30 at 11 18 03" src="https://user-images.githubusercontent.com/8408850/228846004-987268dc-ec6f-48ca-939e-9dc64222958a.png">

**Comment by tdonohue** [comment]
Thanks @MW3000 . I've verified this bug occurs from the Registration page `/register`.

We already perform this same sort of check though when you create a new EPerson via the admin tools (`/access-control/epeople` -> "Add EPerson").  If you enter a duplicate email in that form, you receive a notice that says "This email is already taken".   

So, likely we just need to copy that validation logic into the `/register` page as well.

Needs a volunteer.  May not be difficult to solve as the logic exists elsewhere.

**Comment by nwoodward** [comment]
I looked into this a bit, and the problem with copying the duplicate email logic into the `/register` page is that the REST API endpoints used by the UI admin tools to check for existing users with a given email address require authentication – specifically the `/epersons/search` endpoint used to conduct a "byEmail" search. Since there isn't a user logged in during registration, much less an admin user, those endpoints aren't available. I'll keep thinking on it.

**Comment by tdonohue** [comment]
@nwoodward : Good point...and that just prompted me to recall *why* that endpoint is access restricted.  Essentially, it's for security. We don't want anyone to be able to easily "test" whether a specific email address has an account in DSpace.

So, my original idea won't work.  We cannot copy the logic over.

Instead, likely the `/register` page should *not* throw any error.  Instead, it can do one of two things:
* Send you the "forgot password" email to the email in question...as that way you realize you have an account already.
* Or, do absolutely nothing.  But, perhaps the confirmation message should say: "If you do not receive an email shortly, you may already have an account. In which case, you should use the 'forgot password' form."

The first approach is likely a bit more user friendly.

**Comment by nwoodward** [comment]
OK, you can assign it to me. I think I have a solution for the first approach ready. I'll submit it soon.
