### ISSUE TITLE
Request item stop working

### ISSUE THREAD

**Issue by aroman-arvo** [DSpace/dspace-angular#2195]
**Describe the bug**

Responding a "request item" request trough email link, to aprove or reject the resquest show an incomplete page with only the title.
![request-item](https://user-images.githubusercontent.com/116575333/233033961-dca5ed37-8a81-4c2c-82de-ce8bcbc63bca.png)

It works fine at dspace-angular v7.4

**To Reproduce**

1. Activate request a copy with Helpdesk Strategy: https://wiki.lyrasis.org/display/DSDOC7x/Request+a+Copy#RequestaCopy-(Optional)RequestingacopywithHelpDeskworkflow
2. As anonymous user, look at an embargoed item, click on the file to display the request a copy form.
3. Complete and send the request a copy form
4. As helpdesk staff, look at the email inbox
5. Open the Request a copy email and click on the link to respond to it.
6. Login to DSpace in order to respond.

Only title is shown

**Expected behavior**
A form to acept or reject request should be shown.

**Related work**
Discovered while testing [#8636](https://github.com/DSpace/DSpace/issues/8636)

**Comment by tdonohue** [comment]
@aroman-arvo :  I believe this is fixed in this small PR #2194    I'd welcome a secondary tester though, if you (or someone on your team) has time to verify that the fix is complete.
