### ISSUE TITLE
Author search result without co-author being displayed when there are multiple authors in dc.contributor.author field

### ISSUE THREAD

**Issue by yingjin** [DSpace/dspace-angular#2203]
**Describe the bug**
If there are multiple authors in dc.contributor.author field, the search result only shows the author who is being searched. However, if the authors in dc.creator field, the search result shows all co-authors as well.

**To Reproduce**
1. Query "first" in search box - https://demo7.dspace.org/search?query=first
2. The result for https://demo7.dspace.org/items/1984e894-70ee-41ea-8566-83d6477139c2 only shows first as the author, the second author is not shown.

**Expected behavior**
Expect the co-authors in the search result as well.

**Related work**

**Comment by tdonohue** [comment]
Fixed by #2983
