### ISSUE TITLE
Links to items fail initially when browsing by year

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#2214]
**Describe the bug**
I recently noticed that when choose to browse `By Issue Date` in a collection and limit results by year I see strange behavior. Instead of following the route to the item, the browse page instead reloads. After that the route to the Item works fine. However, if I return to the list after viewing the item and select the next item in the browse list I see the same result. The item route is not followed, the browse page reloads, and after that I can follow the link to the item. The pattern repeats.

**To Reproduce**
1. Choose the `by issue date` browse option
2. Limit your search to a year that has items
3. Select the first item. The browse page will reload (if you haven't visited this item before)
4. Now select the item again and you should get the item view
5. Go back to browse and select the next item in the list (repeat)

**Expected behavior**
When you select an item from the browse list the item route should always be followed.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment]
@mspalti : I was able to reproduce this on demo7.dspace.org.  Not sure of *when* this behavior started.  

But, I did notice it happens both for the global "Browse by Issue Date" (i.e. "All of DSpace" -> "By Issue Date") **and** for individual Communities/Collections:
* Browse to a Community/Collection
* Select "By Issue Date"
* Filter by a Year (must have at least one matching item)
* Click the Item title. Page will reload (like you describe).
* Click the Item title again & you will finally go to the Item page.

I'll pull this over to the 7.6 board and see if I can find a volunteer.  Definitely need to try to fix in 7.6

**Comment by mspalti** [comment]
@tdonohue: I took a look at this today. As nearly as I can tell this is not a new problem.  It's likely that it crept in with #1048. 

It seems like Angular router is not acting on the item route -- and I'm guessing this may have something to do with the way that the starts-with-date component is responding to multiple route updates. 

I find that [this line in the starts-with-date component ](https://github.com/DSpace/dspace-angular/blob/5e277414832f8241e8b5dc2a81399cb68507c6bf/src/app/shared/starts-with/date/starts-with-date.component.ts#L134) seems to be part of the problem. At least in my tests, removing it doesn't break browsing or pagination.  It also reduces browse component updates and for me it solves the problem reported in this issue. 

I can submit a PR with this small change. However this is a tricky section of code so I may be off the mark.

**Comment by tdonohue** [comment]
@mspalti : thanks for the summary.  I'm pulling in @artlowel and @YanaDePauw into this discussion, as that pagination work was done by the Atmire team. (That said, it's been a very long time since that #1048 PR was built... but they do know this code much much better than I.)

I don't have any great ideas myself (I am not familiar with this area of the code).  But, I would recommend creating a small PR if you feel you have an idea worth review.  At the very least, that might help trigger some more discussion/ideas regarding the problem.
