### ISSUE TITLE
Collection sorting on the communities page

### ISSUE THREAD

**Issue by DanGastardelli** [DSpace/dspace-angular#2218]
In DSpace versions 7.4, 7.3 and 7.2, when accessing the community page, sorting sub-communities and collections in ascending and descending order is not working (test done in google chrome).

Simulate the scenario: Enter dspace, go to communities and collections, open a community.

Exemple:

![image](https://user-images.githubusercontent.com/55243638/235193664-d8af4260-8a4b-40a7-a028-c83a716dbdc3.png)

**Comment by alexandrevryghem** [comment]
This is a duplicate of #2160
