### ISSUE TITLE
Importing files/folders

### ISSUE THREAD

**Issue by stonejlhu** [DSpace/dspace-angular#2237]
We have decided to use our dspace as a document repository, by removing files and folders off of a network drive.

Dspace does work for this but the import is a bit cumbersome. 

For example. Folder and file structure:
Folder 1
           -> Team Meetings
                ... Document 1
                ... Document 2
           -> Monthly Meetings
                ... Document 1
                ... Document 2
Folder 2
           -> Year
                       -> Current Year
                                ... Document 1
                       -> Previous Years

I would set each folder as a community and each folder of documents as a collection.  The only way I could do this was to create the XML Source file and then structure-builder to build and get the IDs, and produce an output file which I could use to import the files.  
I created a VBS script to go through these folders and create the XML structure and file structures needed and then zip up the file. 
Its not fantastic but it works.  
What I would like if possible is to somehow join the XML and zip folder parts, OR allow correctly structured zip files to be imported to a specific community and automatically create the ID for the community and collection.

I can post a copy of my vbs file if needed.  Its not fantastic but its a start.

**Comment by tdonohue** [comment]
@stonejlhu : DSpace doesn't offer a way to do what you are asking out-of-the-box.  

1. We do have a Simple Archive Format XML you can import: https://wiki.lyrasis.org/display/DSDOC7x/Importing+and+Exporting+Items+via+Simple+Archive+Format  
2. We also support importing objects via AIPs (a different XML format which describes the entire hierarchy): https://wiki.lyrasis.org/display/DSDOC7x/AIP+Backup+and+Restore
3. Or, you could bypass all those import formats and write a script directly against the DSpace 7 REST API (which provides every feature of DSpace): https://github.com/DSpace/RestContract#readme

Additional importing options are listed at https://wiki.lyrasis.org/display/DSDOC7x/Ingesting+Content+and+Metadata

If you are looking to create an entire Community/Collection hierarchy at the same time that you are importing Items, then 2 or 3 could both do that.  However neither can be pointed at a directory structure and mimic it.  You'd have to write your own scripting.  Option 1 (SAF import) is the easiest of the import tools (and most often used for this use case), but assumes you've already created the necessary Communities/Collections.

Closing this as answered as this appears to be a support question & is too specific to a single institution.  While it might be possible to build an import tool of this sort, it'd require a community volunteer to step forward and help design it.   It'd also need more detailed analysis of how to structure an import across multiple folders, as that's currently not possible.

If you have further questions, please ask them on our support lists: https://wiki.lyrasis.org/display/DSPACE/Support   It's possible others in the community have done something similar to what you are trying to achieve and can offer advice or hints/tips on those lists.
