### ISSUE TITLE
Upload section in the workspaceitem form but optional

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/dspace-angular#2238]
Hello @tdonohue and everyone 👋

**Describe the solution you'd like**
I am working directly with the Dspace API, but i would like to be able to have the /section/upload but not mandatory, instead of that it should be optional, so that the client could add or not files. Is there a way to configure it?

If i remove the upload step from my form i cannot upload files, but if i add the upload step, files are mandatory.

**Comment by tdonohue** [comment]
@CrisGuzmanS : This should already be possible via this configuration: https://github.com/DSpace/DSpace/blob/main/dspace/config/dspace.cfg#L974

As a sidenote, if you have general questions about how to do something in DSpace, I'd recommend using one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support  We try to only create tickets for known bugs or feature requests.  

Closing this as the question was answered.  This feature already exists.
