### ISSUE TITLE
Duplicate relations when creating single item relationship

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#2270]
**Describe the bug**
I've executed the following in the video bellow at my local system and also managed to replicate at demo7.dspace.org. The issue is that when you try to create a single new relation, two new are created. And when try to save, an error occurs and only one remains.

**To Reproduce**
1. Using demo7.dspace.org
2. Having entities created
3. Then create a new relation...
![duplicate-collection](https://github.com/DSpace/dspace-angular/assets/877488/7c21c97b-044b-4ddf-a509-46ba818d204f)

**Expected behavior**
Since I only assign one relation, only one should be presented to the user. But a duplication is shown.

**Comment by tdonohue** [comment]
Thanks @paulo-graca .  I can reproduce this locally.  Not sure how it occurs.

Will mention this in tomorrow's Dev meeting.

**Comment by alexandrevryghem** [comment]
This issue should be resolved with the latest changes from #3060. Maybe we can still wait until #3106 is merged, but afterwards I think we can close this issue.
