### ISSUE TITLE
dspace-angular 7.6 won't build with Node v20

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#2290]
**Describe the bug**
```
./server.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: Transform failed with 1 error:
/home/mwood/NetBeansProjects/dspace-angular/src/app/health-page/health-page.component.scss:64:84: ERROR: Unterminated string token
```
The stylesheet varies; the location is always "64:84", which likely doesn't exist in the named file.  Some component of the toolchain has very poor error recovery.  There's a Stack post somewhere about this, and it seems that everyone who comes there says none of the previous answers worked but he found a new one that does.

Even when I install `nvm` and set it to Node v18, I get the same error.

After much trial and error and Googling all over the place:  for some reason, `webpack` was evading `nvm` and using the system `node` v20.  The `css-loader` version it wanted was unable to cope, threw up its hands, and some bletcherous piece of code with rotten error recovery somehow turned that into "unterminated string token" at a nonexistent location.

To find this, I had to disable optimization (twice) in `angular.json`.  I then had to raise the "initial" budgets to 13mb/15mb to get to the server build and see the real problem that should have been reported all along.  After that I raised the `@angular/cli` version to 16.0.4 -- the latest.  That got me a `css-loader` that was, not the latest, but late enough not to wig out when running on Node v20.

So, it appears that the minimum we'll need to support building with Node v20 in some future release is:
- "@angular/cli": "^16.0.4"
- "eslint-plugin-jsdoc": "^45.0.0" (which I had previously discovered by running `yarn install`)

(`ng version` says:  "Node: 20.2.0 (Unsupported)" but built it anyway.)

**To Reproduce**
1. Install Node v20
2. `yarn build:prod`

**Expected behavior**
A clean build as on Node v18.

**Comment by mwoodiupui** [comment]
Those may not be the minimum *versions* needed, but it does seem to be the minimum set of dependency updates to make building possible.

**Comment by tdonohue** [comment]
Moving to 8.0 as this is definitely something to work on with that release.  
* Node 16 goes EOL in Sept 2023. 
* Node 18 will remain in support until April 2025. 
But, we should work on Node 20 support.
