### ISSUE TITLE
edit section in sidebar menu: edit page of selected item / collection / community does not refresh

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#2300]
This bug affects DS 7.5 and it can be reproduced in the DS 7.5 demo instance.

# bug description and steps to reproduce 

1. hover over sidebar menu and choose *Edit* menu section

2. within menu section choose entry *Community*, *Collection* or *Item*

![image](https://github.com/DSpace/dspace-angular/assets/952735/c7886a9e-e04e-4e17-b724-7bf81a8669d9)

3. (the following description assumes that a collection was chosen)

![image](https://github.com/DSpace/dspace-angular/assets/952735/06a49adc-edaa-471d-92ff-20c9f7d44dd0)

4. choose a collection from the collection list that is shown in the modal dialog (in this example _1205TestCollection_ was chosen)

5. the edit form of the selected collection is shown

![image](https://github.com/DSpace/dspace-angular/assets/952735/1a4a6c4c-c278-43a3-87e7-be8c527822a6)

6. go back to step 1 and repeat the process until step 5 (choose another collection in step 5)

After the second pass of step 5 the browser URL changes (from https://demo7.dspace.org/collections/733388bf-9adb-4218-b899-ce22deb27fdd/edit/metadata to https://demo7.dspace.org/collections/33441398-de98-4ec1-86b7-3f57688b1856/edit/metadata), but the form fields are not updated, e.g. in the *Name* input field the name of the previously chosen collection is still present (marked in the screenshot).

![image](https://github.com/DSpace/dspace-angular/assets/952735/aba01a1d-d809-4412-94a9-6674d9ada862)

If you refresh the page or open https://demo7.dspace.org/collections/33441398-de98-4ec1-86b7-3f57688b1856/edit/metadata directly, the *Name* input field contains the correct value:

![image](https://github.com/DSpace/dspace-angular/assets/952735/b6b30857-65e5-4040-9493-fc3ace6950a7)

The same (buggy) behaviour appears if you choose a community or item in step 2. Any subsequent selection of an another community or item shows the values of the community / item that was initially selected.

**Comment by tdonohue** [comment]
I can reproduce this locally... the steps are pretty simple & unfortunately occur both for "Edit -> Community" or "Edit -> Collection".

1. Go to "Edit -> Community" (or "Edit -> Collection")
2. Select a Community (or Collection).  It doesn't matter which one, but pay attention to which you have selected
3. Go back to the same "Edit -> Community" (or "Edit -> Collection")
4. Select a **different** Community (or Collection).  **Bug: Look closely. The form still contains the metadata of the previously selected Community or Collection.**

I'll see if anyone can dig into this.  It appears to be a caching issue with the form. If you reload the page, the form then reloads properly.

**Comment by saschaszott** [comment]
Thanks, @tdonohue . Items are also affected.

Normally, the UUIDs in the URL and in the Item internal ID match.

![image](https://github.com/DSpace/dspace-angular/assets/952735/13107b6d-a71b-4a26-8322-9eb2fbda1c4e) 

If the caching issue appears, the UUIDs do not match

![image](https://github.com/DSpace/dspace-angular/assets/952735/9aea750c-1b00-4396-adb3-c327c44058fb)
