### ISSUE TITLE
eperson/epeople administration: edit view does not change browser URL

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#2302]
This is a follow-up of a discussion in PR https://github.com/DSpace/dspace-angular/pull/2293#issuecomment-1587238743

When you click an edit button (marked red in the screenshot) in the **eperson/epeople administration** the page URL (in the browser) does not change (it remains unchanged: https://demo7.dspace.org/access-control/epeople)

![](https://user-images.githubusercontent.com/952735/245140358-ea336f53-e78a-44c7-84f8-5e75bf8fa1a5.png)

In contrast, in the **group administration** the UUID of the selected group is present in the URL, e.g. https://demo7.dspace.org/access-control/groups/d246bf6f-907a-4499-839d-35c25c54333a

**Comment by tdonohue** [comment]
Agreed this is a bug.  It's a minor thing, but should be fixed.  Pulling over to the 7.6 maintenance board to find a volunteer.

**Comment by alexandrevryghem** [comment]
I would like to claim this issue

**Comment by tdonohue** [comment]
@alexandrevryghem : sounds great!  Assigning you to it.

**Comment by tdonohue** [comment]
Closing, fixed by #2391
