### ISSUE TITLE
In dspace ui cannot see items option

### ISSUE THREAD

**Issue by ravikonila** [DSpace/dspace-angular#2320]
Hello
Hope you are all doing well.

In my new installation of dspace frontend and backend, all of a sudden I cannot see the Item option in UI either in New or in Edit. 
Could you please guide me on what to check further? 

Regards
Ravi

**Comment by ravikonila** [comment]
Just to add, I am using Dspace 7.5. Not sure if it is frontend or backend issue. If I use my frontend and connect Dspace demo site API, I can see Items in my UI, but could not see Items option in my local installed Dspace backend. Hence, I reinstalled my backend but now also I cannot see Items option in my frontend UI. Could someone help me in this asap. 

Regards
Ravi

**Comment by tdonohue** [comment]
Closing, questions for support should use one of our Support options listed at https://wiki.lyrasis.org/display/DSPACE/Support

I'd recommend using our troubleshooting guide to look for underlying errors: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)  Then, if the errors don't make sense, use one of the support options in the Support page above.
