### ISSUE TITLE
Feedback link should not appear in the footer when feedback feature is disabled

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#2323]
**Describe the bug**

If `feedback.recipient` REST configuration property is set to null the feedback feature is disabled. This causes `CanSendFeedback` authorization feature to be false on Angular and disables feedback page.

_Send feedback_ link should be automatically hidden on footer.

**To Reproduce**
1. Set `feedback.recipient=` in local.cfg
2. _Send feedback_ link is still visible but the page is not reachable (as expected)

**Expected behavior**
_Send feedback_ link should not be visible

**Comment by davide-negretti** [comment]
This is a quick fix and I can open a PR

**Comment by tdonohue** [comment]
@davide-negretti : If it is a small PR and you can get it created quickly, we might be able to include it in 7.6.  But 7.6 is due to be released this week...so, no promises at this point.

**Comment by davide-negretti** [comment]
@tdonohue I opened the PR
