### ISSUE TITLE
Tree doesn't update when switching between "Browse by Vocabulary" pages

### ISSUE THREAD

**Issue by nona-luypaert** [DSpace/dspace-angular#2337]
**Describe the bug**
When multiple controlled vocabularies are used in submission-forms.xml, multiple links "Browse by Vocabulary" pages are also generated. The tree isn't updated when switching from one "Browse by Vocabulary" page to another.

**To Reproduce**
1. Make sure you use at least 2 controlled vocabularies in submission.xml. (E.g. set `<vocablary>` to `nsi` [here](https://github.com/DSpace/DSpace/blob/main/dspace/config/submission-forms.xml#L200), `srsc` is still used [here](https://github.com/DSpace/DSpace/blob/main/dspace/config/submission-forms.xml#L1086).)
2. Go to the "Browse by Subject" page, the `srsc` values are displayed.
3. Then immediately go to the second "Browse by Vocabulary" page, the `srsc` values are still displayed. The tree isn't updated with the `nsi` values.
4. Refresh the page, the `nsi` values are now displayed.

**Expected behavior**
Switching from one "Browse by Vocabulary" page to another should display the correct tree.

**Related work**
- https://github.com/DSpace/dspace-angular/pull/2215
- https://github.com/DSpace/dspace-angular/pull/2296
- https://github.com/DSpace/DSpace/pull/8826

**Comment by tdonohue** [comment]
Definitely sounds like a bug.  Pulling over to the 7.6 maintenance board in the hopes of finding a volunteer.
