### ISSUE TITLE
Selected blurred/truncated text in Chrome web browser is difficult

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#234]
Minor UX issue noted as part of testing of PR #221 by @PTrottier.

In the latest Chrome browser (v64.0.3282.186), if you attempt to select any text that has been blurred/truncated, the selection "jumps" backwards as you approach the blurred text.  If you try again, you usually can (eventually) select the blurred text, but it's not a normal user experience.

**Workaround:** If you click on the blurred/truncated text first, it will expand. The full text is then easily selectable.

This behavior does not occur in Firefox. It only occurs in Chrome. It's unclear if this behavior is simply a browser-based issue, or something in our code.

**Comment by MatMercer** [comment]
Hi! I want to take a look at this issue, could you add a screenshot about the issue? Where I can take a look at it? Is it on the search page?

**Comment by tdonohue** [comment]
@MatMercer (and others): This can be currently reproduced on our demo site for DSpace 7. 

1. Search on some text (e.g. "test")
2. Switch to the "grid" view of the search results (blurred/truncated text only appears in the grid view panels). Here's a direct link to the grid view of a search for "test": https://dspace7-demo.atmire.com/search?query=test&view=grid
3. Then, in a Chrome browser, attempt to select/highlight the truncated text (with your mouse).  As you approach the truncated section, the highlighted text "jumps" around, making it difficult to actually select the text. 

We don't see this as a major issue, but it seems to only occur in Chrome (not reproducible in Firefox).

**Comment by MatMercer** [comment]
The issue is related with the `pointer-events` CSS style. Setting it to None into the `::after` pseudo element solved the issue.

Maybe there are other places that needs this fix too, I'll take a look and make a pull request when possible.

[pointer-events documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)
