### ISSUE TITLE
Collection edit has empty entity type dropdown if no entities / relationship types initialised 

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#2345]
**Describe the bug**
When you don't have a DB with the entity types initialised (with script `initialize-entities -f ../dspace/config/entities/relationship-types.xml`) the 'Entity Type' dropdown in collection is empty, causing some confusion.
If the repository does not work with entity types & relationships then they don't need to be initialised but then also this dropdown should not be present in collection create / edit form.

**To Reproduce**
1. Start with empty DB or DB with no entity types initialised
2. Go to create and/or edit collection form 
3. The entity type input (dropdown) exists but is empty

**Expected behavior**
When there are no entity types, then this field should not exist on the create and edit collection form.

**Comment by tdonohue** [comment]
Pulling this over to the 7.6.x maintenance board as we should try to fix this in a 7.6.x bug-fix release

**Comment by alexandrevryghem** [comment]
I would like to claim this issue
