### ISSUE TITLE
Wrong path in themed-deny-request-copy.component.ts

### ISSUE THREAD

**Issue by Leano1998** [DSpace/dspace-angular#2351]
**Describe the bug**
The themed-component-file of the deny-request-component in dspace-7.6 imports the not-themed version of the component from the custom-theme. It only works as long as the custom-theme exists.  
View Line 4 in [themed-deny-request-copy.components.ts](https://github.com/DSpace/dspace-angular/blob/c4342d3238b73d03cb92e8ce160884e66d14b49a/src/app/request-copy/deny-request-copy/themed-deny-request-copy.component.ts#L4C71-L4C71)
```ts
import { DenyRequestCopyComponent } from 'src/themes/custom/app/request-copy/deny-request-copy/deny-request-copy.component';
```

**To Reproduce**
1. Delete the custom-theme.
2. Try to start the frontend

**Expected behavior**
It should import the local deny-request-copy-component.

Kind regards,
Eike.

**Comment by alanorth** [comment]
Yes, good catch. It should be:

```ts
import { DenyRequestCopyComponent } from './deny-request-copy.component';
```

Very simple fix. @Leano1998 would you like to make a pull request?

**Comment by tdonohue** [comment]
This seems like a very small, simple fix... if someone can create a PR, we can get this into 7.6.1
