### ISSUE TITLE
hide search text field in the filter section if the number of facet values does not exceed the maximum number of facet values shown

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#2352]
The search text field below the facet values is not necessary if all facet values are shown, i.e. the current number of facet values does not exceed the maximum number of facet values that can be shown in a filter section. The red marked text fields in the screenshot can be omitted.

![image](https://github.com/DSpace/dspace-angular/assets/952735/e230d86d-4aad-433b-9e44-e7701ff0410c)

**Comment by floriangantner** [comment]
We've solved the problem on our running dspace-cris [instance](https://professorenkatalog.uni-bamberg.de/search?configuration=prof) by only showing the suggestions if the lastPage of the facet values entries is not reached ``` <ds-filter-input-suggestions *ngIf="!(isLastPage$ | async)" [suggestions]="(filterSearchResults | async)"```. This should concern https://github.com/DSpace/dspace-angular/blob/c4342d3238b73d03cb92e8ce160884e66d14b49a/src/app/shared/search/search-filters/search-filter/search-text-filter/search-text-filter.component.html#L20 , https://github.com/DSpace/dspace-angular/blob/c4342d3238b73d03cb92e8ce160884e66d14b49a/src/app/shared/search/search-filters/search-filter/search-hierarchy-filter/search-hierarchy-filter.component.html#L20 and https://github.com/DSpace/dspace-angular/blob/c4342d3238b73d03cb92e8ce160884e66d14b49a/src/app/shared/search/search-filters/search-filter/search-authority-filter/search-authority-filter.component.html#L20 . If no other volunteer has some better solution/idea we might take over this job. :)

**Comment by tdonohue** [comment]
Closing, fixed by #3061 (for 7.x) and #3097 (for 8.x)
