### ISSUE TITLE
feat: migrate to standalone components, directives, pipes

### ISSUE THREAD

**Issue by enea4science** [DSpace/dspace-angular#2370]
**Is your feature request related to a problem? Please describe.**
No. But having big SharedModule is an anti-pattern and slows down compilation times.

**Describe the solution you'd like**
Having standalone components, directives and pipes makes it easier to think about the dependencies of the components and are easier to refactor.

The [official standalone migration schematic](https://angular.io/guide/standalone-migration) does 99% of the work: 
```bash
ng generate @angular/core:standalone
```
There are some places where we need to use the `forwardRef` for components that are used before initialisation, but those were easy fixable.

I did a test, and the migration worked fine, the project compiles fine and didn't have any thing broken from a quick look I had.

Not all tests pass (even though they get updated by the schematic), but most of them fail because of providers, and those are easily fixable imo. 

**Additional context**
Here are screenshots from what I tried: 

<img width="432" alt="image" src="https://github.com/DSpace/dspace-angular/assets/127771679/bd152ab3-fc7b-417b-bf7e-d863dc191d21">
<img width="1393" alt="image" src="https://github.com/DSpace/dspace-angular/assets/127771679/ed3937c9-1ad2-47ba-acb1-c8b833ea2d70">

**Comment by enea4science** [comment]
Also, there would be no need for `LazyThemeModule` as standalone fixes the context issue. 

<img width="1043" alt="image" src="https://github.com/DSpace/dspace-angular/assets/127771679/cd13b8ed-4691-4213-b332-ac9c449eb8ff">

**Comment by tdonohue** [comment]
@enea4science : Thanks for this... I like this idea overall, but I suspect it needs discussion from others.  I've linked this ticket into our Developers Meeting agenda for this week, as it sounds semi-related the the Angular refactor proposal that @atarix83 will talk about.  This ticket seems to me to suggest a first step towards cleaning up our existing Angular components. https://wiki.lyrasis.org/display/DSPACE/2023-07-20+DSpace+Developers+Meeting#id-20230720DSpaceDevelopersMeeting-Agenda
