### ISSUE TITLE
Mobile navbar hamburger menu doesn't work in Firefox/Safari

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#2372]
**Describe the bug**
The toggle button for the header navbar no longer shows the navbar on Firefox & Chrome on mobile/tablet sized screens.
<img width="472" alt="20230718-123723" src="https://github.com/DSpace/dspace-angular/assets/31547038/fda84b05-033e-421d-bf92-64df14818a04">

On Safari I can observe some bar following the usual dropdown animation, but the actual menu doesn't show up.

**To Reproduce**
1. Open https://demo7.dspace.org
2. Resize the screen anywhere below a width of 768px
   * The header navbar will be replaced by a menu toggled by a "hamburger button" 
   * In Chrome, this button still toggles the menu as expected
   * **In Firefox & Safari, the menu never appears**

**Expected behavior**
The mobile navbar menu should work in all broswers.

**Comment by yashchaddha** [comment]
Hi I would like to contribute on this issue. Can i please get assigned to it?

**Comment by tdonohue** [comment]
Thanks @HamzaFarooqArif for volunteering!

**Comment by tdonohue** [comment]
@yashchaddha :  My apologies here... I just realized you volunteered prior to @HamzaFarooqArif .  I missed your message from a few days ago.

Could the two of you come to an agreement on who will claim this issue?  @HamzaFarooqArif , are you OK with my reassigning this to @yashchaddha since they volunteered first?

**Comment by yashchaddha** [comment]
Hi @tdonohue no problem

I would love to contribute on this one. 

I am also fine with @HamzaFarooqArif being my coauthor or reviewer to balance the scales

Thanks

**Comment by HamzaFarooqArif** [comment]
I apologize that I'll not be able to continue working on it. I'm unassigning me from this issue

**Comment by hugo-escire** [comment]
Hi @tdonohue. I resolve the bug. I will generate the PR.



![Image](https://github.com/DSpace/dspace-angular/assets/132490359/769b23ac-56f3-4c2d-b6ad-ab9386a66e69)
