### ISSUE TITLE
Polish translation update (based on 7.6)

### ISSUE THREAD

**Issue by michdyk** [DSpace/dspace-angular#2383]
I want to contribute an update for Polish translation, approx. 300 translations.

@tdonohue Could you assign me to this issue? 
Please let me know, if translations could be also included in 7.6.x version or only in 8.0.

By the way, I also found an old issue for Polish translation on the Backlog board: https://github.com/DSpace/dspace-angular/issues/1781
I think that is already done, so I would recommend closing that task.

**Comment by alanorth** [comment]
> By the way, I also found an old issue for Polish translation on the Backlog board: https://github.com/DSpace/dspace-angular/issues/1781

@michdyk it looks like these translations never made it into DSpace (that user never ended up making a pull request with their changes). The latest changes to the Polish strings were from you in #2001.

If you add new Polish strings they will be applied to DSpace 7.6.x and cherry-picked to `main` for 8.0.
