### ISSUE TITLE
Cache timeout causes observables to break

### ISSUE THREAD

**Issue by LotteHofstede** [DSpace/dspace-angular#239]
In the current configuration, the cache times out after 15 minutes. 
I noticed that parts of the website stop responding as expected after this timeout.
Because the observables don't seem to emit any new values anymore, observers are not notified of any changes, and can't react accordingly.
The website only starts to act normally again after a (manual) page reload.

This issue can easily be reproduced by changing the cache's `msToLive` to a few seconds instead of 15 minutes and clicking through the website.

**Comment by atarix83** [comment]
it's the same problem described in this [issue](https://github.com/DSpace/dspace-angular/issues/216) and there is already a PR opened [here ](https://github.com/DSpace/dspace-angular/pull/219)

**Comment by LotteHofstede** [comment]
Duplicate of #216, closing
