### ISSUE TITLE
Visual differentiation needed for Access Status

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#2402]
**Describe the bug**
Currently, when displaying different access status like open access, restricted access, ... there is no visual differentiation.
![image](https://github.com/DSpace/dspace-angular/assets/877488/d33dd419-d7c2-4e15-b726-369ad2ce52ce)

all look the same. 

**To Reproduce**
1. Firstly you should have content with different types of access (specific resource policies for open access, embargoed access)
2. Activate the required configuration on your client site (angular):
``` yaml
# Item Config
item:
  showAccessStatuses: true
```
3. Perform a query (can be an empty one and you will have a list of items). Please mind that this only applies to generic Items or Publications.

**Expected behavior**
I hoped to have a visual differentiation for different access status. Could be something based on a different color, a specific style class. Of course I can theme that component and do that on my side, but I think it makes more sense to have it like that for all implementations.

**Comment by pilasou** [comment]
@paulo-graca I like the idea...but talking about color design always seems to me like a pandora's box! :) There are 4 status to cover: OA, Embargo, Restricted and Metadata only. Maybe it would be possible by following a simple color code (green for OA, red for restricted, etc.), like this: 
![image](https://github.com/DSpace/dspace-angular/assets/19291880/6b38770b-dd9b-4a96-81ea-833d500fbef4)

My concern is that on a result page, it can look like fireworks:
![image](https://github.com/DSpace/dspace-angular/assets/19291880/6780a104-06f2-464f-b337-5ad9f06383d9)

**Comment by mwoodiupui** [comment]
Please bear in mind that the four states are simply names for combinations of starting and ending dates for ResourcePolicy instances.  Other combinations are possible.  Here we have two types of embargo:  limited (maximum of two years) and unlimited (can be embargoed "forever").  Collections use one or the other as required.

**Comment by tdonohue** [comment]
Not against this idea, but priority is uncertain.  It might be possible to simply make it easier for sites to color each status button differently via CSS...instead of defaulting to a specific color scheme (which can be a "pandora's box" as @pilasou notes)

For now, moving this to backlog as priority is unclear to me.

**Comment by paulo-graca** [comment]
Concluding, to avoid fireworks It would be better to add specific stylesheet classes, perhaps based on the access status itself, like:

``` html
<span class="badge badge-secondary access-status-value open-access">Open Access</span>
```

then, anyone can custom it as it pleases.

**Comment by paulo-graca** [comment]
@pilasou @mwoodiupui @tdonohue I've just created this tiny PR to address this:
https://github.com/DSpace/dspace-angular/pull/2579
