### ISSUE TITLE
How should the UI find out about authorization?

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#242]
In [the meeting of 2018-04-05](https://wiki.duraspace.org/display/DSPACE/2018-04-05+DSpace+7+Working+Group+Meeting) we had a discussion on how the UI should determine which pages, or which components can or cannot be accessible to the current user based on their role. Below are some of the arguments that were put forth.

Some authorization information can likely be described using hal links: if the link is present you can perform a certain action, if it isn't you can't. But will this work for everything? e.g. if an edit to an Item is a POST or a PATCH request to the `/items/:id` endpoint, you can't link to those.

Perhaps we need a `can-do` endpoint, where we pass an object and an action and get back true or false based on whether the current user can perform the action on the object? But perhaps having to wait would slow down the UI too much.

We could also add a separate section, like `_links` to a response from the server, that lists the actions the current user can perform on the object?

Maybe there is a standard way in HAL of doing this? And if not, how are other angular projects solving this problem?

**Comment by tdonohue** [comment]
This has had more recent discussion. See notes at https://wiki.lyrasis.org/display/DSPACE/Managing+Authorization+info+in+Angular+UI and https://wiki.lyrasis.org/display/DSPACE/REST+Authorization

**Comment by tdonohue** [comment]
Closing in favor of #664 which describes the next steps here.
