### ISSUE TITLE
Unable to add freetext values with `onebox` or `tag` input types when field uses a vocabulary

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#2435]
**Describe the bug**
In the DSpace 4/5/6 XMLUI submission form it was possible to use a onebox input type with an external `<vocabulary>`, which allowed editors to _either_ select values from a popup list or type a value freely:

<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/191754/221833395-e3414c13-dc60-4b44-8bea-00f406e20380.png" />
</p>

As of DSpace 7.x this behavior is no longer possible with both the `onebox` and `tag` input types:

<p align="center">
  <img width="600" src="https://user-images.githubusercontent.com/191754/221833510-02b989c2-516a-4a14-b2da-4d0fd146e8ff.png" />
</p>

In the screenshot above I have DSpace 7.5 configured with two fields, one a `onebox` and the other a `tag` type, both of which are using the `srsc` vocabulary. I am unable to enter any keywords that don't come from the vocabulary (I tried with comma and semicolon as you can see).

**To Reproduce**
1. Create an input field in your `submission-forms.xml` of type `onebox` or `tag` and [configure it to use an external vocabulary](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-ConfiguringControlledVocabularies) XML file like `srsc`, for example:

```xml
            <row>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Subject</label>
                    <vocabulary>srsc</vocabulary>
                    <input-type>onebox</input-type>
                    <required></required>
                </field>
            </row>
```

2. Then try to type free text values in the input box in the Angular submission form

**Expected behavior**
The user should be able to select values from the controlled vocabulary _or_ enter a free text value, unless the field is set as `closed=true` in the submission form.

**Related Work**
Perhaps related to this issue, ironically submitted by me: https://github.com/DSpace/DSpace/issues/6593. Also unclear if this is actually a bug in the Angular frontend.

**Comment by hugo-escire** [comment]
Hi @tdonohue. I want to take this issue.

cc. @alanorth

**Comment by tdonohue** [comment]
@hugo-escire : Thanks for volunteering! I'll assign you then.

**Comment by hugo-escire** [comment]
Hi @tdonohue, I'm going to work on this issue this Friday. 
Greetings 👋

**Comment by alanorth** [comment]
I was digging into this with the Angular devtools and noticed that the form properties are always set to `editable: false`, which I'm not sure if is related? I was hoping to find that it's a simple fix.

**Comment by hugo-escire** [comment]
Hi @alanorth, @tdonohue.  I had not been able to work on this issue. I hope to be able to release it as soon as possible. 🖖.
I´m installing the back-end on a VM to can replicate the bug.

**Comment by hugo-escire** [comment]
Hi @alanorth, @tdonohue .
I've been debugging. I got the onebox component to support free text. But with the configuration that you provided me, I realized that by default the closed property, vocabulary, comes true. I tried to change it, setting it to false, but it remains true.
In any case, modifications must be made to the front, so that free text can be accepted in both components.

![image](https://github.com/DSpace/dspace-angular/assets/132490359/18098bc9-0272-4d7b-ad47-41b69cb08d35)

**Comment by alanorth** [comment]
Thanks for the update @hugo-escire. It sounds like there may be a bug in the backend then, if the `closed=false` property in the input form is coming as true to Angular. Is that only for `tag` input type?

**Comment by hugo-escire** [comment]
@alanorth 
I have this problem for both components (`onebox `and `tag`). Should I wait to see if it resolves on the back side?

**Comment by alanorth** [comment]
@hugo-escire I don't know either. I tried to debug by adding three fields with the default, closed explicitly false, and closed explicitly true:

```xml
            <row>
                <field>
                    <dc-schema>dcterms</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Subjects (default)</label>
                    <input-type>onebox</input-type>
                    <required></required>
                    <vocabulary>srsc</vocabulary>
                </field>
            </row>
            <row>
                <field>
                    <dc-schema>dcterms</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Subjects (closed false)</label>
                    <input-type>onebox</input-type>
                    <required></required>
                    <vocabulary closed="false">srsc</vocabulary>
                </field>
            </row>
            <row>
                <field>
                    <dc-schema>dcterms</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Subjects (closed true)</label>
                    <input-type>onebox</input-type>
                    <required></required>
                    <vocabulary closed="true">srsc</vocabulary>
                </field>
            </row>
```

But I don't know how to see the configuration passed from the backend to Angular. @paulo-graca [showed above](https://github.com/DSpace/dspace-angular/issues/2435#issuecomment-1678011642) that Angular was receiving the correct submission form configuration. Is that from Angular dev tools or what?

**Comment by jonas-atmire** [comment]
@hugo-escire We had investigated this issue internally a while back where we added a separate free-text field during the lookup. 
Could you let me know what the current state of this is, and if we could be of any assistance?

Note that we wanted to avoid to make the lookup optional as that would be inviting people to never look anything up (Which seemed like a bad practice)
So the usecase would be to use the controlled vocab, and if it's found, that value can be selected.
If it can't be found, the manual value could be filled in
