### ISSUE TITLE
Sitemap feature not compatible with reverse proxy

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#2436]
**Describe the bug**
`server.ts` dynamically generates `robots.txt` from a template, which is well and good, but it uses the scheme, host and port from the request to render the Sitemap URLs.  This is incorrect when dspace-angular is running behind a reverse proxy, as it yields the internal scheme/host/port not the public one.

**To Reproduce**
1. Set up your DSpace instance behind a reverse proxy.
2. Request `/robots.txt` from your instance's public URL, e.g. `curl -v https://scholarworks.iupui.edu/robots.txt`.
3. Observe that the `Sitemap` entries point to the internal URL.

**Expected behavior**
The Sitemap entries should reflect the front-end's public URL.  This will require that `dspace-angular` *knows* its public URL.

**Comment by tdonohue** [comment]
@mwoodiupui : I could be mistaken, but I think this is already fixed by #2037 (in 7.5)?  Maybe it's just a matter of setting `X-Forwarded-Proto` and/or `X-Forwarded-Host` in your proxy?

For instance, this is working on our demo site which also has a proxy in place: https://demo7.dspace.org/robots.txt

**Comment by mwoodiupui** [comment]
According to Apache documentation, HTTPD just adds these headers when reverse-proxying, and I can't see any obvious way that they could have been suppressed.  https://httpd.apache.org/docs/current/mod/mod_proxy.html#x-headers  (Disappointing that it uses X-headers rather than the standardized Forwarding header but, well enough.)

By Express JS' documentation, it appears that I can scrap the code I was writing to handle various headers, and `set('trust proxy', true)`.  Since this is security related, I should make it configurable.  https://expressjs.com/en/guide/behind-proxies.html

**Comment by tdonohue** [comment]
@mwoodiupui : `X-Forwarded-Proto` isn't in that list of headers that are added automatically.  And you might want to see if there's a way to verify that `X-Forwarded-Host` is being set correctly.

My point is that I'm not sure how to reproduce this issue.  I *suspect* it may be a configuration problem (or even documentation problem) as it's also not appearing on the demo site (the current one, or the new preview one we are migrating to).  That makes me suspect it either only exists for specific Apache HTTPD setups, or maybe there's a specific Apache HTTPD configuration which you are missing?

Also, we already have the `set('trust proxy')` configuration you are looking for here: https://github.com/DSpace/dspace-angular/blob/main/server.ts#L93  It defaults to true, but it is configurable. https://github.com/DSpace/dspace-angular/blob/main/src/config/default-app-config.ts#L48

**Comment by mwoodiupui** [comment]
I 'tcpdump'ed 100 packets on port 4000, tested with `curl`, shipped the capture to a machine with Wireshark installed, ant tshark showed my GET with X-Forwarded-For, X-Forwarded-Host, and X-Forwarded-Server set as I would expect.  Yet the returned file still has `Sitemap: http://[::1]:4000/sitemap_index.xml`.  `ui.useProxies` is explicitly set to `true` in `config/config.yml`.  I've reverted all my local mod.s in `server.ts` and told PM2 to `restart all`.

**Comment by mwoodiupui** [comment]
I added a `console.log` call to log `req.headers` in the handler for `/robots.txt` and saw that the X-headers are present, but the Host header is "host: '[::1]:4000'".  That's the header that `server.ts` uses.

**Comment by mwoodiupui** [comment]
BTW some things that can go wrong:  we had built HTTPD without mod_remoteip (corrected); the test box was using mod_security and had not been reconfigured to allow 'proxy' headers (corrected).

**Comment by tdonohue** [comment]
@mwoodiupui :  I wonder if you need the `ProxyPreserveHost on` flag if you are using `mod_proxy`?  It almost sounds like the `Host` header is lost/replaced by a localhost style URL (`[::1]:4000`) when proxying. That's obviously not correct.

**Comment by tdonohue** [comment]
`RequestHeader set X-Forwarded-Proto https` might correct the HTTP problem.

It seems like our Install Docs may need an update then.  I see we don't mention `ProxyPreserveHost on`, but maybe we should? https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace

**Comment by mwoodiupui** [comment]
The handler uses `req.protocol` for the scheme.

I will update the doco.

**Comment by tdonohue** [comment]
@mwoodiupui : When "trust proxy" is set to `true` (our default value) in Express, the `req.protocol` uses the value of `X-Forwarded-Proto`.  See the docs here: https://expressjs.com/en/guide/behind-proxies.html

**Comment by mwoodiupui** [comment]
OK, that fixed it.  Doco. repaired again.  We need an Nginx expert to fix it for that server.

**Comment by tdonohue** [comment]
Closing this ticket.  Fixed in docs.  

I'll update the Nginx with what I *believe* is correct (and someone can correct me later if wrong).  I think Nginx needs:
```
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
```

**Comment by alanorth** [comment]
I had left a comment here a few days ago, but I don't see it now hmm. I said the sitemaps are working fine in a reverse proxy from nginx to DSpace 7.6 Angular. This is my nginx `proxy_params` file:

```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
