### ISSUE TITLE
Bitstreams file URL issue (dspace 7.5)

### ISSUE THREAD

**Issue by aroldorique** [DSpace/dspace-angular#2446]
Hello everybody.

I'm having a problem with the URL of my items' bitstream file links.

We have an entry in the DSN that points the address [biblioteca.mpf.mp.br/repositorio](http://biblioteca.mpf.mp.br/repositorio) to the IP of the dspace machine. We access the site normally through the link [biblioteca.mpf.mp.br/repositorio](http://biblioteca.mpf.mp.br/repositorio). The site is not yet available outside our network.

If I access an item and then go to the full item page, as shown below, I can usually download the two files available for download, without errors. Note that the "Download" link (red arrow) is formed by the URL [https://biblioteca.mpf.mp.br/repositorio/bitstreams/.](https://biblioteca.mpf.mp.br/repositorio/bitstreams/).. (yellow arrow). The link works normally and I can download the file.

![image](https://github.com/DSpace/dspace-angular/assets/31450466/37d4f1e9-72f6-4673-9ad8-4d8aa4a8f12b)

The problem occurs on the Item Edit page (picture below). If I click on the button indicated by the red arrow, which is the button to download the license.txt file, the URL formed (yellow arrow) is in the format https://biblioteca.mpf.mp.br/bitstreams/.. This link is broken because /repository is missing before /bitstreams. Does anyone know how I can fix this problem on these URLs? I need to include /repository before /bitstreams in the file links on the item edit page.

![image](https://github.com/DSpace/dspace-angular/assets/31450466/a5b33806-4dd7-4fd8-96ec-03e72063c5f5)

**Comment by tdonohue** [comment]
Moving this to our 7.6.x maintenance board.  Sounds like a bug in the Item Edit page (Bitstream tab) where these download paths are not being created properly when the DSpace site is deployed on a subpath (like https://mydspace.edu/repository/ or similar).

I suspect this is a small bug and the code just needs to use the same approach as the main download link (on the Item view).  But, needs a volunteer to investigate.
