### ISSUE TITLE
Support "starts with" in the DataService

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#247]
Fetching objects is handled by the DataServices. A browse operation is basically a findAll() on a DataService that can have options, like a scope, pagination or sort params.

In order to create an alphabetic control such as [the one on the browse by item page](http://demo.dspace.org/xmlui/browse?rpp=20&sort_by=1&type=title&etal=-1&starts_with=A&order=ASC), please add an [option](https://github.com/DSpace/dspace-angular/blob/69ca4ce904d07a366ae2caa6756cdbbecb7fe689/src/app/core/data/request.models.ts#L126) that allows you to find all objects that start with one or more specified letters (and of course still match the other params). 

[DataService.getFindAllHref](https://github.com/DSpace/dspace-angular/blob/69ca4ce904d07a366ae2caa6756cdbbecb7fe689/src/app/core/data/data.service.ts#L33) creates the REST API url to fetch the data for the specified options. Extend it to generate the correct URL based on your new "starts with" option. You can find the expected URL params on the [Rest7Contract repo](https://github.com/DSpace/Rest7Contract)

Write jasmine tests to verify that inputs with and without "starts with" options yield the expected URL.

DataService doesn't have _any_ tests at the time of writing, as it was written before improving test-coverage became a requirement for merging a PR. Please at least cover your own code, any additional effort you can do to improve the coverage of the method or class is of course appreciated.

**Comment by mohideen** [comment]
Created a PR (#282) for this issue.
