### ISSUE TITLE
StartsWith Component

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#248]
Create a component that allows a user to traverse a list by selecting a letter of the alphabet, or entering a few letters the results should start with.

See [the current browse by title page](http://demo.dspace.org/xmlui/browse?rpp=20&sort_by=1&type=title&etal=-1&starts_with=A&order=ASC) for an example

If the user clicks a link the component should update the URL to reflect the change. 

If the user enters something in the "first few letters" box, and clicks "go" the component should update the URL to reflect the change. 

Both clicking a link and entering something in the box and clicking "go" should work with javascript disabled. So use routerlinks, and a form submit

It would be nice if after a debounce of a few hundred ms, the URL would update automatically when the user enters a character in the "first few letters" input for people that do have JS enabled.

The parent component using this startwith component is responsible for watching the url change, and updating the rest call accordingly.

Add a `startsWith: string` property to the PageInfo model, and take one of those models as an `@Input`for your StartsWith component. If the input `pageInfo` has a `startsWith` value, show it in the "first few letters" box.

**Comment by AlinaBudnitzki** [comment]
Hello, I'd like to claim this task. Is it still available?

**Comment by mohideen** [comment]
@AlinaBudnitzki I have completed the component implementation but had issues with getting the TestBed setup for the unit tests. Since I have held on to this without much progress for a while, I will create a WIP PR and you can continue on this if you would like.

**Comment by mohideen** [comment]
Here is the WIP PR: https://github.com/DSpace/dspace-angular/pull/294

**Comment by AlinaBudnitzki** [comment]
@mohideen I took a look at your changes and have already a question: did you created a folder "starts-with" in folder "browse-by"? I have dspace-angular and a folder "starts-with" doesn't exist - as well as shared.module.ts 
Maybe I'm working with wrong DSpace...

**Comment by mohideen** [comment]
@AlinaBudnitzki Yes, I created the starts-with folder for the new starts-with component. But, the shared.module.ts should already exist in the master branch: https://github.com/DSpace/dspace-angular/blob/master/src/app/shared/shared.module.ts

To check out my changes you can:
```
git fetch origin pull/294/head:starts-with-component
git checkout starts-with-component
```
I am assuming you have git@github.com:DSpace/dspace-angular.git remote set as your origin in your workstation clone of dspace-angular repository.

**Comment by artlowel** [comment]
Temporarily claiming this for Stefan Fritzsche. He'll take over on this task, but he can't accept his invite yet.
