### ISSUE TITLE
Repeated requests to the server/api endpoint. 

### ISSUE THREAD

**Issue by J4bbi** [DSpace/dspace-angular#2482]
**Describe the bug**
Repeated requests are made to the `server/api` endpoint when loading a page. This is unlikely to have a good justification as the data provided on the root endpoint is practically static. It gives basic information about the repository and lists its endpoints (endpoints shortened for brevity.

```json
{
  "dspaceUI": "https://sandbox.dspace.org",
  "dspaceName": "DSpace Sandbox",
  "dspaceServer": "https://sandbox.dspace.org/server",
  "dspaceVersion": "DSpace 8.0-SNAPSHOT",
  "type": "root",
  "_links": {
    "actuator": {
      "href": "https://sandbox.dspace.org/server/actuator"
    },
    "authn": {
      "href": "https://sandbox.dspace.org/server/api/authn"
    },
  }
}
```

The following table lists the number of requests different pages make to that endpoint (these are links to the public server, some of which may at any time become unavailable).

| Page      | Number of requests to  `server/api` |
| ----------- | ----------- |
| https://sandbox.dspace.org/home      | 2       |
| https://sandbox.dspace.org/community-list   | 2        |
| https://sandbox.dspace.org/communities/8b632938-77c2-487c-81f0-e804f63e68e6   | 3       |
| https://sandbox.dspace.org/collections/ece42bb4-5ec0-4760-b727-30f9f593acb8   | 3       |
| https://sandbox.dspace.org/items/004286c4-60b8-44d7-94f7-a1658351e9a4   | 3        |
| https://sandbox.dspace.org/browse/dateissued   | 3        |
| https://sandbox.dspace.org/browse/title  | 3       |
| https://sandbox.dspace.org/entities/project/3329a278-2719-4bae-a5d5-d2039afc2fe2   | 3        |
| https://sandbox.dspace.org/statistics/items/3329a278-2719-4bae-a5d5-d2039afc2fe2   | 2        |
| https://sandbox.dspace.org/info/privacy  | 2        |

**To Reproduce**
1. Open any of the above URLs, with the network tab of your browser open
2. Sort requests by name and count the number of requests to `/server/api`

**Expected behavior**
Each page should presumably only need to request the `/server/api` endpoint once.

**Comment by tdonohue** [comment]
@J4bbi : Thanks for logging this.  I'm going to pull this into next week's DevMtg for discussion.  I can reproduce this on the Demo Sandbox site (sandbox.dspace.org) and can verify it seems odd to have multiple `GET /server/api` requests occur anytime you click on a link in DSpace.

Here's a screenshot of what I see (which is the same as what you see):

![api-requests](https://github.com/DSpace/dspace-angular/assets/483997/59f47d15-9ffa-4d89-87b6-60aacc41a6f0)

Here's how I got that screenshot:
* Go to https://sandbox.dspace.org/
* Then, open up Chrome DevTools "Network" tab.
* In UI, click on "Communities & Collections" in header.  Results in first two `GET /server/api` requests.
* In UI, click on a Community in the list.  Results in the second three `GET /server/api` requests.

All `GET /server/api` requests look to be the same & all responses are the same.  I don't understand myself why the UI needs to call this endpoint over and over for every page.

@artlowel : Pinging you in case you know a quick answer to this question.   This will also be brought to the next DevMtg for discussion.
