### ISSUE TITLE
RSS feed from search results on DSpace

### ISSUE THREAD

**Issue by nbimbe** [DSpace/dspace-angular#2489]
In a number of scholarly information systems, usually users like to maintain a search and keep going back for new additions that satisfy that search query. It will be nice to have an RSS feature that can be generated from the search results - this way, a user can simply subscribe to the Feed and be alerted for any new additions.

Such a feature will be handy for users of repository that do not allow certain users having a user profile on that system that can be used for such via the Subscription feature.

**Comment by tdonohue** [comment]
Needs a volunteer to implement.  

I *think* this would be rather easy, as the backend already supports this concept.  If you look closely at the URL behind RSS feeds for Communities/Collections, it looks like this:
`http://localhost:8080/server/opensearch/search?format=atom&scope=8b632938-77c2-487c-81f0-e804f63e68e6&query=*`

Notice that it's already a search, but the `query` param is a wildcard.  So, to make this work, the UI may just need to build a similar URL for any search...adding the query to that `query` param.

**Comment by MarieVerdonck** [comment]
Atmire would like to claim this issue
