### ISSUE TITLE
Community-List page has extra spaces after links

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#2492]
**Describe the bug**
On DSpace 7.6.1 Angular adds spaces around links, which creates a visual glitch that underlines beyond the text content on hover. The bug can be seen on the [community list page of sandbox.dspace.org](https://sandbox.dspace.org/community-list):

https://github.com/DSpace/dspace-angular/assets/191754/8698fd70-7135-492c-9a9e-fa9170966ace

I have also noticed it on browse links on the item page, but can't find an example on the DSpace demo right now.

**Expected behavior**
We should be using literal metadata values without adding whitespace.

**Comment by tdonohue** [comment]
@alanorth : This only seems to be on the `/community-list` page, so it may just be a minor bug in that page itself.  

Does not seem to be reproducible in the community list on the homepage (`/home`) or on Collections under a specific community homepage (`/communities/[uuid]`). 

So, it appears to be a minor bug in just that `/community-list` page.   It also does appear on the demo site community list page as well: https://demo.dspace.org/community-list

**Comment by alanorth** [comment]
It happens on browse links on the item page as well, but perhaps only when there are more than one. See:

![2023-09-12T20:18:39,602219525+03:00-fs8](https://github.com/DSpace/dspace-angular/assets/191754/126b60f2-8a35-4f55-939d-f6f6ffefc83c)

In this case I have regions set up as a browse link in `dspace.cfg`.

**Comment by tdonohue** [comment]
@alanorth : Ok, I see.  In any case, this doesn't seem to be a *generic* issue across all of DSpace.  It looks, to me, like a few pages have a small bug where they are accidentally inserting an extra space in some links.  

I agree it's a bug.  Just wanting to stress that it seems like we need to simply fix it page by page.  It's likely a very easy thing to fix, but the hard part will be tracking down which line of code is accidentally adding an extra space :)

**Comment by alanorth** [comment]
Sure @tdonohue. I call it like I see it. I've been noticing these bugs for months, and decided to finally file an issue. :)

**Comment by alanorth** [comment]
I found the issue. It is due to newlines in the link text in [`src/app/community-list-page/community-list/community-list.component.html`](https://github.com/DSpace/dspace-angular/blob/main/src/app/community-list-page/community-list/community-list.component.html#L38-L40):

https://github.com/DSpace/dspace-angular/blob/92a10ce9de492ae901cbe87598635435d3649e3f/src/app/community-list-page/community-list/community-list.component.html#L38-L40

There is one more in this file as well. And likely others around where the Browse links are generated. I can submit a PR for the ones I can find... it doesn't seem that these files are linted as they are not TypeScript.

**Comment by alanorth** [comment]
Ah hah, I found the other case in the browse links:

https://github.com/DSpace/dspace-angular/blob/92a10ce9de492ae901cbe87598635435d3649e3f/src/app/item-page/field-components/metadata-values/metadata-values.component.html#L32-L37

They render like this due to the newline:

![before-fs8](https://github.com/DSpace/dspace-angular/assets/191754/5bf46901-65a2-4608-af34-c32203b3f99d)

With trimming the newlines the render without the whitespace:

![after-fs8](https://github.com/DSpace/dspace-angular/assets/191754/8bfefc05-15b2-4763-8ec9-cc9d917267c7)

I'll add a fix for that to the PR.
