### ISSUE TITLE
Angular dspace doesn't start with pm2 after reboot

### ISSUE THREAD

**Issue by RichardCBravo** [DSpace/dspace-angular#2495]
**Describe the bug**
The error arises when the entire process is done to leave pm2 as a service, when restarting this error starts to appear:

/home/dspace/.pm2/logs/dspace-angular-1.log last 15 lines:

```
1|dspace-f | "),__name(clientSideRender,"clientSideRender"),__name(addCacheControl,"addCacheControl"),__name(initCache,"initCache"),__name(botCacheEnabled,"botCacheEnabled"),__name(anonymousCacheEnabled,"anonymousCacheEnabled"),__name(cacheCheck,"cacheCheck"),__name(checkCacheForRequest,"checkCacheForRequest"),__name(getCacheKey,"getCacheKey"),__name(saveToCache,"saveToCache"),__name(hasNotSucceeded,"hasNotSucceeded"),__name(retrieveHeaders,"retrieveHeaders"),__name(isUserAuthenticated,"isUserAuthenticated"),__name(serverStarted,"serverStarted"),__name(createHttpsServer,"createHttpsServer"),__name(run,"run"),__name(start,"start"),__name(healthCheck,"healthCheck");const mainModule=require.main,moduleFilename=mainModule&&mainModule.filename||"";(moduleFilename===__filename||moduleFilename.includes("iisnode"))&&start()})();var __webpack_export_target__=exports;for(var i in __webpack_exports__)__webpack_export_target__[i]=__webpack_exports__[i];__webpack_exports__.__esModule&&Object.defineProperty(__webpack_export_target__,"__esModule",{value:!0})})();


0|dspace-f | 
0|dspace-f | SyntaxError: Unexpected token '.'
0|dspace-f |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
0|dspace-f |     at Module._compile (internal/modules/cjs/loader.js:963:27)
0|dspace-f |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
0|dspace-f |     at Module.load (internal/modules/cjs/loader.js:863:32)
0|dspace-f |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
0|dspace-f |     at /home/dspace/.nvm/versions/node/v18.16.0/lib/node_modules/pm2/lib/ProcessContainer.js:303:25
0|dspace-f |     at wrapper (/home/dspace/.nvm/versions/node/v18.16.0/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
0|dspace-f |     at next (/home/dspace/.nvm/versions/node/v18.16.0/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
0|dspace-f |     at /home/dspace/.nvm/versions/node/v18.16.0/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
0|dspace-f |     at WriteStream.<anonymous> (/home/dspace/.nvm/versions/node/v18.16.0/lib/node_modules/pm2/lib/Utility.js:186:13)
```

dspace-angular.json:

```json
{
  "apps": [
    {
      "name": "dspace-siete",
      "cwd": "/home/dspace/dspace-angular",
      "script": "dist/server/main.js",
      "max_memory_restart": "1024M",
      "env": {
        "NODE_ENV": "production"
      },
      "instances": 4,
      "exec_mode": "cluster",
      "node_args": "--max_old_space_size=4096"
    }
  ]
}
```

**To Reproduce**
All commands with dspace user
1. git clone -b dspace-7.6 https://github.com/DSpace/dspace-angular.git
2. yarn install
3. yarn build:prod
4. pm2 start dspace-angular.json 
5. pm2 startup
6. root user => sudo env PATH=$PATH:/home/dspace/.nvm/versions/node/v18.17.1/bin /home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/bin/pm2 startup systemd -u dspace --hp /home/dspace
7. dspace user pm2 save
8. root user => reboot 

**Expected behavior**
It should start Angular automatically.

**Comment by alanorth** [comment]
This doesn't seem like a DSpace Angular bug to me. Can you try running the application bundle manually on the command line without the JSON manifest? For example:

```console
$ pm2 start ./dist/server/main.js --name dspace-ui -i 4
```

**Comment by RichardCBravo** [comment]
The same error occurs with the command you're suggesting. Could it be the version of PM2? I'm using version 5.3.0, which is the latest.

I'll send the error again:

/home/dspace/.pm2/logs/dspace-ui-error-2.log last 15 lines:
2|dspace-u | "),__name(clientSideRender,"clientSideRender"),__name(addCacheControl,"addCacheControl"),__name(initCache,"initCache"),__name(botCacheEnabled,"botCacheEnabled"),__name(anonymousCacheEnabled,"anonymousCacheEnabled"),__name(cacheCheck,"cacheCheck"),__name(checkCacheForRequest,"checkCacheForRequest"),__name(getCacheKey,"getCacheKey"),__name(saveToCache,"saveToCache"),__name(hasNotSucceeded,"hasNotSucceeded"),__name(retrieveHeaders,"retrieveHeaders"),__name(isUserAuthenticated,"isUserAuthenticated"),__name(serverStarted,"serverStarted"),__name(createHttpsServer,"createHttpsServer"),__name(run,"run"),__name(start,"start"),__name(healthCheck,"healthCheck");const mainModule=require.main,moduleFilename=mainModule&&mainModule.filename||"";(moduleFilename===__filename||moduleFilename.includes("iisnode"))&&start()})();var __webpack_export_target__=exports;for(var i in __webpack_exports__)__webpack_export_target__[i]=__webpack_exports__[i];__webpack_exports__.__esModule&&Object.defineProperty(__webpack_export_target__,"__esModule",{value:!0})})();
2|dspace-u |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
2|dspace-u | 
2|dspace-u | SyntaxError: Unexpected token '.'
2|dspace-u |     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2|dspace-u |     at Module._compile (internal/modules/cjs/loader.js:963:27)
2|dspace-u |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2|dspace-u |     at Module.load (internal/modules/cjs/loader.js:863:32)
2|dspace-u |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2|dspace-u |     at /home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
2|dspace-u |     at wrapper (/home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
2|dspace-u |     at next (/home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
2|dspace-u |     at /home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
2|dspace-u |     at WriteStream.<anonymous> (/home/dspace/.nvm/versions/node/v18.17.1/lib/node_modules/pm2/lib/Utility.js:186:13)

**Comment by alanorth** [comment]
This is working for me on DSpace 7.6:

```console
$ pm2 start ./dist/server/main.js --name dspace-ui -i 4
```

PM2 version 5.3.0 is correct. I think the SyntaxError in your error is suspicious. Is your manifest correct? Also, try removing the `node_modules` and doing `yarn install` again—maybe something is corrupt or out of date.

**Comment by RichardCBravo** [comment]
It keeps giving me the same error with:
`$ pm2 start ./dist/server/main.js --name dspace-ui -i 4`
`$ pm2 save`
`$ pm2 startup`
`$ reboot`

Also when I generate the crontab that executes a .sh I start it as soon as I restart, I have to add a waiting time of about 2 minutes so that the error does not occur, I add it as follows:

dspace.sh:

#!/bin/bash

#PM2
PM2="/home/dspace/.nvm/versions/node/v18.17.1/bin/pm2"
#dspace-deploy
cd /home/dspace/dspace-deploy
sleep 120
$PM2 start dspace-angular.json

exit

If I remove 'sleep', the same error appears.

I don't do any `$ pm2 save` or `$ pm2 startup` because they are the ones that give me the problem.
