### ISSUE TITLE
Can't use keyboard to select value in submission form dropdown

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#2500]
**Describe the bug**
When using the `dropdown` input type in the DSpace 7.6 submission form, it is not possible to jump to a value in the list by typing a letter. For example, I want to jump to the `Journal Article` value by pressing the letter "j" or "J":

https://github.com/DSpace/dspace-angular/assets/191754/bd9ec773-688f-4df2-8581-7ecfe6c3f101

**To Reproduce**
1. Configure a field in the submission form to use a `dropdown` type with a value pairs, for example the types.
2. Try to type a letter to jump to an item in the list

**Expected behavior**
Being able to navigate the dropdown using the keyboard is a feature of native HTML `<select>` elements in browsers (see [MDN docs with example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)).

In DSpace 6 the `dropdown` type actually presents as a list, but we can navigate the list using the keyboard:

https://github.com/DSpace/dspace-angular/assets/191754/7c398ac8-ec65-499f-88e3-0fb07daea31e

**Comment by tdonohue** [comment]
Flagged this as an accessibility bug. Pulling this over to the 7.6.x maintenance board as we must ensure every field is keyboard accessible.

**Comment by alanorth** [comment]
Fixed in #2733 via c02b46ca7d4c5baad8c8902bd7a6dc56c4ee8a0b (manual merge).
