### ISSUE TITLE
Angular SSR menu issues

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/dspace-angular#2503]
**Describe the bug**
                   
There are two bugs with the route dependent menus, both when added in the routing modules or in the `DSOEditMenuResolver` when an `OnClickMenuItemModel` is used.
Both of these issues only happen when loading the first page in production mode and are related to the SSR for thise menus.

Issue 1:
When an `OnClickMenuItemModel` is used in the `DSOEditMenuResolver` or in the data of a routing module, its function will not work correctly on the first loaded page in the browser.
For example, if there is a community or collection button and a user opens the DSpace repository on that page in their browser or hard refreshes that page, the button will throw an error in the console that the function does not exists.
Once the user navigates to a different page and comes back, the button will work correctly.

Issue 2: 
When a menu is added to a route that contains a child route `''`, the menus will be duplicated instead of being overwritten by the child values as angular does by default for the routes. 
Furthermore, this second issue will cause route dependent menus to be duplicated on the first render, making it seem like they work correctly. However, when a route is only added to the child, it will not work anymore.

**To Reproduce**

1. Add a menu section for a button in the `ItemPageRoutingModule` to the `''` route. Leave the statistics menu as is. This will result in the following route segment:
```           
          {
            path: '',
            component: ThemedItemPageComponent,
            pathMatch: 'full',
            data: {
              menu: {
                public: [{
                  id: 'function-test',
                  active: false,
                  visible: true,
                  model: {
                    type: MenuItemType.ONCLICK,
                    text: 'Click me and verify a console log is printed.',
                    function: () => console.log('Clicking the button worked!')
                  } as OnClickMenuItemModel,
                  icon: 'hand-paper',
                  index: 3,
                }],
              },
            }
          }

```
2. Build the DSpace in production mode
3. Go to an item page
4. Open the console log in your browser and hard refresh the page
5. Click the entry in the navbar menu saying "Click me and verify a console log is printed."
6. Verify that a console error shows up saying that `this.item.function is not a function`

**Expected behavior**

The button should work instead of throwing a console error.

**Related work**
Fixed in #2504

**Comment by tdonohue** [comment]
Fixed by #2504
