### ISSUE TITLE
ItemSearchResultListElementComponent not fully themable

### ISSUE THREAD

**Issue by hcayless** [DSpace/dspace-angular#2511]
**Describe the bug**
Version: 7.6, browser: any
I encountered this while attempting to customize ItemSearchResultListElementComponent so that advisor names (they are `dc.contributor`s in our metadata) wouldn't be displayed in search results (we just want author/creator). We have a theme based off the custom theme, and that component is in custom, so I copied it from the custom theme and made the relevant changes. Advisors indeed no longer show up in the search results, but they continue to show up in browse results (which uses the same component). What seems to be happening is that in browse, the component is wrapped in an [ItemListElementComponent](https://github.com/DSpace/dspace-angular/tree/main/src/app/shared/object-list/item-list-element/item-types/item) which backdoors the core version of ItemSearchResultListElementComponent instead of our customized version.

**To Reproduce**
1. Make a custom version of [ItemSearchResultListElementComponent](https://github.com/DSpace/dspace-angular/tree/main/src/themes/custom/app/shared/object-list/search-result-list-element/item-search-result/item-types/item) or just use the custom theme. and enable the component.
2. Make a visible change to the HTML.
3. Do a search. Your change should be visible.
4. Browse to where the item is visible in a result list. Notice that your change is not visible.

**Expected behavior**
The item displays the same in both search results and browse.

**Comment by alexandrevryghem** [comment]
Hey @hcayless, I tried reproducing this bug, but it works fine for me. Did you uncomment the custom theme [here](https://github.com/DSpace/dspace-angular/blob/main/src/themes/eager-themes.module.ts#L15)? If you did, could you share the changes you made to your config.yml file in order to configure the theme.

**Comment by hcayless** [comment]
Possible it's been fixed since 7.6 (which is what we've based our build on). We didn't uncomment the custom theme there, but added our own custom theme module. Is it necessary to also include the generic custom theme? Our config is here: https://gitlab.oit.duke.edu/ddr/dspace-angular/-/blob/main/config/config.yml

Just to demonstrate this is happening:

Core ItemSearchResultListElementComponent (with 'Foo' appended to the title):
<img width="1227" alt="Screenshot 2023-11-06 at 7 31 09 AM" src="https://github.com/DSpace/dspace-angular/assets/23493/1e922512-ac74-458b-adf1-76f0900a1a2b">

Result (in browse):
<img width="1208" alt="Screenshot 2023-11-06 at 7 33 39 AM" src="https://github.com/DSpace/dspace-angular/assets/23493/5868a4db-77a5-4cba-97e0-0f4e7afd567b">

Themed ItemSearchResultListElementComponent (with 'Bar' appended to the title):
<img width="1234" alt="Screenshot 2023-11-06 at 7 31 56 AM" src="https://github.com/DSpace/dspace-angular/assets/23493/01030e41-c814-4645-9d17-892b4a57c914">

Result (in search):
<img width="1001" alt="Screenshot 2023-11-06 at 7 33 07 AM" src="https://github.com/DSpace/dspace-angular/assets/23493/4f32962d-d4b3-40db-9775-418afc2bcba1">
