### ISSUE TITLE
When you enter the wrong username/password combination, the login dropdown turns blank

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#2515]
**Describe the bug**
If you enter the wrong combination of username and password in the login dropdown, or on the login page. The component turns blank entirely. I can reproduce this on https://demo.dspace.org and on https://sandbox.dspace.org

<img width="380" alt="image" src="https://github.com/DSpace/dspace-angular/assets/1567693/7f8bc0fc-1262-4ca9-9654-5365cded1820">

**To Reproduce**
1. Click the "log in" link in the header
2. Enter a username and password combination that doesn't exist
3. Click the "log in" button

**Expected behavior**
It should show an error message and allow you to try again.

**Related work**
Possibly related to https://github.com/DSpace/dspace-angular/pull/2414?

**Comment by artlowel** [comment]
The reason seems to be [this `d-none`](https://github.com/DSpace/dspace-angular/blob/0905a53db5eca45220809831663ba8d6761e55c5/src/app/shared/log-in/log-in.component.html#L4). While the idea is good, it looks like contentRef doesn't update here when you get an error

**Comment by tdonohue** [comment]
@artlowel : Thanks for figuring this out.  Assigning back to you for you or your team to work on.  Also pinging @alexandrevryghem  who added that code.

**Comment by alanorth** [comment]
I see the empty login dropdown _very often_ after refreshing the page. I haven't yet figured out why, but suspect it happens when reloading too soon after restarting the backend or frontend in dev mode. I am used to shift-refreshing the home page to fix it...

**Comment by tdonohue** [comment]
I've found that I'm able to reproduce this in Firefox but NOT in Chrome.  In Firefox, I see the exact behavior shown in the description (entire login dropdown turns blank).  In Chrome though, the login dropdown flashes blank but then shows the error message as expected. Nonetheless, it seems like it affects some browsers.

I'll test the fix PR next and see if it resolves the issue for me in Firefox.

**Comment by alanorth** [comment]
@tdonohue ah that explains it. I use Firefox explicitly and see the blank login drop down SO frequently that I was surprised nobody had noticed yet (it's certainly not only limited to a wrong username/password combination).
