### ISSUE TITLE
DSpace 7.6: Handle redirects not working when frontend runs under a nameSpace other than /

### ISSUE THREAD

**Issue by ttoljamo** [DSpace/dspace-angular#2517]
**Describe the bug**
In DSpace 7.6, handle redirects are not working when the frontend is configured to run under a nameSpace other than server root (e.g. example.com/dspace): the redirects lack the nameSpace context. 

**To Reproduce**
1. Create a Community 
2. Navigate to the Community's page
3. Click on the "Permanent URI for this community" link: e.g. https://example.com/dspace/handle/123456789/9.
4. Error: The redirect lands us on a page that does not exist: e.g. https://example.com/communities/e0703287-3079-42af-aa42-7b2754d0eba1
5. Edit the URL by hand to add the nameSpace to get to the working page: https://example.com/dspace/communities/e0703287-3079-42af-aa42-7b2754d0eba1

**Expected behavior**
The redirect should acknowledge the nameSpace configuration. 

This issue is regression: I tested this with DSpace 7.5 on the same server, with the same apache proxy settings, and the redirect works swimmingly. 

**Related work**
Could this be related to #2265 and #2331?

**Comment by alanorth** [comment]
Hi @ttoljamo, I can't confirm the bug since I'm not using a custom namespace, but this [recent patch](https://github.com/DSpace/dspace-angular/pull/2473) fixes other issues with custom namespaces.
