### ISSUE TITLE
Disabled Add More + button in submission

### ISSUE THREAD

**Issue by MarieVerdonck** [DSpace/dspace-angular#2535]
**Describe the bug**
What is the function of the (disabled) [+Add More] button in top right corner of submission?  Based on the code this button would have functionality if there are 'disabled' sections, how are they defined? 
![Screenshot 2023-10-04 at 17 21 54](https://github.com/DSpace/dspace-angular/assets/5233724/1a71555d-498f-48da-a7bf-806cfb20e286)

~~Possibly:~~
~~In `item-submission.xml` steps can have a `visibility` part in the scope, with options: `HIDDEN("hidden"), READONLY("read-only"), EDITABLE("editable")` => `collection` selection is supposedly 'hidden' though in submission, & is not part of these "disabled" sections~~
~~https://demo.dspace.org/server/#https://demo.dspace.org/server/api/config/submissionsections => visibility for collection step not set.~~

Disabled sections are sections with [mandatory=false](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Structureofthe%3Cstep-definition%3Etag) for the `step-definition` in `item-submission.xml`

In any case if there are no such 'disabled' sections should the [+Add More] button not be hidden instead of just disabled

**To Reproduce**
1. Go to submission in regular submission form, eg https://demo.dspace.org/workspaceitems/33406/edit
2. There is a disabled [+Add More] button in top right corner of submission causing confusion

**Expected behavior**
Button hidden if no 'disabled' sections
Unclear what disabled sections are / how button can be used if there are such sections

**Related work**
Link to any related tickets or PRs here.
Disabled instead of hide in case of no disabled section done in https://github.com/DSpace/dspace-angular/commit/c73b4c71bfdada159ac35864505073239c800445
Part of:
https://github.com/DSpace/dspace-angular/pull/279/commits
https://github.com/DSpace/dspace-angular/pull/381/commits

**Comment by hutattedonmyarm** [comment]
Disabled sections are sections with [mandatory=false](https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Structureofthe%3Cstep-definition%3Etag)

They will not be displayed by default in the submission process, but can be added with this button

**Comment by MarieVerdonck** [comment]
@hutattedonmyarm 
Thanks for this info! Updated this issue & the related PR's instructions for reviewers with this.

Verified setting `mandatory="false"` in `item-submission.xml`: `<step-definition id="traditionalpagetwo" mandatory="false">` on the default second describe step does indeed make this add button show again after changes of PR, and is not disabled but a dropdown allowing you to add this non-mandatory step.

**Comment by alanorth** [comment]
Closed with #2536 for `dspace-7_x` and #2544 for `main`.
