### ISSUE TITLE
Add the starts-with component to the browse-by components

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#254]
This task depends on #248, #252 and #253.

Add the starts-with component to the top of the browse by title and browse by metadata components. Use the `pageInfo` object from the `paginatedList` that is used by the rest of the browse component to initialize the starts-with component. Update the code that watches the route for changes having to do with browse to also take in to account changes to the starts-with param.

**Comment by tdonohue** [comment]
Closing as this was fixed by #364
