### ISSUE TITLE
Add contextual search boxes to Community and Collection pages

### ISSUE THREAD

**Issue by dheles** [DSpace/dspace-angular#2555]
Large repositories with lots of Communities and Collections can be difficult to search and navigate, especially when the names of many of the Collections are similar.

DSpace 6 had contextual search boxes on each Community and Collection page, which made it easier for users to find the items they were looking for. It would be useful to add this feature back into the current version.

It is of course possible to do an open search, then select the Community or Collection. However, this requires an additional step which was not previously necessary. Also, in the limited view of the Community / Collection selection interface, it can be hard to accurately choose the right one, when many are available and have similar names.

**Comment by alanorth** [comment]
@dheles thanks for filing this. The lack of a "Search within this collection" box is unfortunate. For example, in our DSpace 6 repository we have this on every community and collection:

![Screenshot 2024-01-05 at 11-25-29 ILRI articles in journals-fs8](https://github.com/DSpace/dspace-angular/assets/191754/20142b1c-1eea-4614-82e5-d987b8bec9db)

I wonder if we can use the `ds-themed-search-form` component on community and collection pages...

**Comment by alanorth** [comment]
No, this doesn't seem to work. I've [added the search form to my themed collection page](https://github.com/ilri/dspace-angular/commit/9182a3bdde1100eadc6282f86eb6e515c5995a23). Clicking the search button shows items in the collection, but you cannot use any search terms (neither free text nor Solr syntax).

![Screenshot 2024-01-08 at 16-45-56 ILRI articles in journals-fs8](https://github.com/DSpace/dspace-angular/assets/191754/3e3cc7f8-9a7d-4b5e-bf28-c0fb9f0f642b)

The form posts and reloads the items, but it's not actually searching.
