### ISSUE TITLE
DSpace 7: Missing delete button for non-repeatable field with value pairs 

### ISSUE THREAD

**Issue by f-rapp** [DSpace/dspace-angular#2569]
**Description**
Missing delete button for non-repeatable field with value pairs

**To reproduce**
Select a value for a non-repeatable field with value pairs. E.g. Language "English".
Try to delete the value and go back to no entry.

**Expected behavior**
There should be a delete button to empty the field.
or:
There should be an emtpy entry in the dropdown that you can fall back to. Please note: If there is an empty value included in the value-pairs already, that's not a solution. This empty value is not displayed properly, and if selected, it says "undefined".

**Related work**
https://github.com/DSpace/dspace-angular/issues/2568

**Comment by tdonohue** [comment]
Closing as this is the same issue as #2568.  So, it's a duplicate.  The only difference in these fields is that one is repeatable.  The core bug is that the value cannot be removed or cleared...so the same fix will solve both tickets.
