### ISSUE TITLE
Mock AdminGuard

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#257]
Currently there is no way on the rest api to verify in advance whether or not someone has access to a certain resource.

In order to fence off admin only sections of the UI until there is rest support, please write a mock AdminGuard that will check the `'isAdmin'` key in localStorage. If the key exists and contains the value `TRUE` the guard should activate the route, otherwise it shouldn't. 

Note: because the code runs server side as well, first check whether `window` and `localStorage` exist using: 
```typescript
if (typeof window === 'object' && hasValue(window.localStorage)) {
```

Devs can then run `localStorage.setItem('isAdmin', true)`  in the browser's console to test admin features.

Later, when there is rest support to check your role, we can replace the implementation with something that actually works.

See [the angular guide](https://angular.io/guide/router#milestone-5-route-guards) for more info about guards

**Comment by mjmarttila** [comment]
I'll claim this one.

**Comment by mjmarttila** [comment]
https://github.com/DSpace/dspace-angular/pull/267
