### ISSUE TITLE
delete metadatafields from multiple metadataschema

### ISSUE THREAD

**Issue by floriangantner** [DSpace/dspace-angular#2599]
**Describe the bug**
There is some inconsistency in deleting metadatafields among multiple schemas. When fields from multiple metadataschemas are ticked/selected than these ticks are not shown after browsing through other schemas and multiple fields are deleted.

We discovered the bug in Dspace Cris aligned to Dspace 7.5 where the functionality of the code should not have been modified a lot and we did not found some similar issue in this board describing this behavior. If someone from the community might confirm that this behavior can be reproduced in recent Dspace?

**To Reproduce**
1. Create `dc.aa` and `dcterms.aab` fields (or some other names/schemas of your choice)
2. Go to metadataschema registry
3. Go to dc schema and tick :heavy_check_mark: `dc.aa`
4. Go back to the metadataregistry using the back button
5. Go to `dc` vocabulary and confirm that the field `dc.aa` is not marked
6. Go back to metadataschema registry using the back button 
7. Go to `dcterms` vocabulary and tick :heavy_check_mark: `dcterms.aab`
8. Click the delete button and wait for the response. It should say that two fields were deleted
9. Checking the browser console there should be two DELETE Requests

Screencast of steps 2 to 8 (without mouse pointer):
[Screencast from 06.11.2023 12:49:33.webm](https://github.com/DSpace/dspace-angular/assets/33422716/ececded5-f516-44d4-81b7-ca4983bff964)

**Expected behavior**
We are not sure if the intended behavior is that metadatafields can only be deleted among one metadataschema at once 
(in this case the first selected schema is wrong and the selection should be reset when going back, e.g. by deselectingAllMetadataField when the component is destroyed (https://github.com/DSpace/dspace-angular/blob/e62832f9d3fdb4140566d3e64c12675c1deb8923/src/app/admin/admin-registries/metadata-schema/metadata-schema.component.ts#L209)) 
**or**
that the metadatafields can be selected and deleted among all metadataschemas (in this case the selected ticks are not shown correctly after browsing though multiple schemas).

**Related work**

**Comment by tdonohue** [comment]
This sounds like a bug. It should not be possible to delete fields in several schemas *at the same time*.  Once you leave the edit schema page to go to a different schema, the prior selected fields should be reset.  It sounds like that's not occurring, which would mean this is a bug.
