### ISSUE TITLE
Some Item edit pages are accessible by anonymous users

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#2609]
**Describe the bug**
A few of the `item/*/edit/*` pages do not seem to have properly configured guards.
As far as I see all of these pages are non-functional, so the impact of this bug is minimal.

It's likely that there are other similar cases -- would be good to look for more examples and address them in one go.

**To Reproduce**
1. Go to any of the following pages without logging in to DSpace:
   * https://demo.dspace.org/items/70076a29-850a-4af5-b382-2cce72ed5205/edit/access-control
   * https://demo.dspace.org/items/70076a29-850a-4af5-b382-2cce72ed5205/edit/curate
2. The actual page will render, but will not be usable (e.g. due to missing data, failing REST requests)

**Expected behavior**
Users without the necessary authorizations (and especially anonymous users) should not have access to administrator pages.
Instead, they should be redirected to the login page, or be shown a 403 page.

**Related work**
https://github.com/DSpace/dspace-angular/pull/2247

**Comment by tdonohue** [comment]
@ybnd : If you (or your team) happen to have any time in the next few days, it would be good to patch these quickly for 7.6.1 (which I hope we get out next week sometime). I agree the pages don't seem to be usable at all, but it'd be good to fix them nonetheless.
