### ISSUE TITLE
Mapped items do not paginate correctly

### ISSUE THREAD

**Issue by dheles** [DSpace/dspace-angular#2613]
**Describe the bug**
When a collection contains more than one page of mapped items (default: 10/page), using the pagination controls does not load new results. The same 10 items are returned with every page. (Observed in versions 7.5, 7.6, & 7.6.1 - current snapshot)

Test collection demonstrating this issue (must be logged-in as an administrator to observe):
https://demo.dspace.org/collections/d2cce7f8-f418-409b-aec4-a3ff7e4f04f8/edit/mapper?spc.page=1

<img width="360" alt="Screenshot 2023-11-09 at 12 33 50 PM" src="https://github.com/DSpace/dspace-angular/assets/2560887/13d03a63-122d-4b10-974f-e34fd57c66de">
<img width="362" alt="Screenshot 2023-11-09 at 12 34 04 PM" src="https://github.com/DSpace/dspace-angular/assets/2560887/5fa26cd7-dfca-4145-9a46-9ed2c064e086">

**To Reproduce**
1. Map more than 10 items to a collection
2. Browse mapped items
3. Paginate between mapped items

**Expected behavior**
Paginating should load new mapped items

**Comment by tdonohue** [comment]
Can verify on demo site (via links above).  Moving this to the 7.6.x board in search of a volunteer.
