### ISSUE TITLE
edit-item view: random order of buttons in status tab

### ISSUE THREAD

**Issue by vins01-4science** [DSpace/dspace-angular#2618]
We've observed a random order of buttons in the status tab of the edit item view:

Order of buttons in initial request:

![image](https://github.com/DSpace/dspace-angular/assets/107129187/5d8e166e-479f-40de-be12-084f7b3fb6de)

(different) Order of buttons in a subsequent request:

![image](https://github.com/DSpace/dspace-angular/assets/107129187/0e786625-ee8b-466a-9ea9-e1eca7cfb4df)

- Open the edit item view of an arbitrary DS item
- check the order of buttons
- logout / login again
- open the edit item view again
- check the order of buttons

Currently, it is not clear to me what types of actions change the order.

Expected behavior
The order should be fixed. Permanently deletion should be the last option.

**Comment by vins01-4science** [comment]
We @4Science can work on this issue and provide the fix.

**Comment by tdonohue** [comment]
Thanks @vins01-4science .  Moving this to the 7.6.x maintenance board for tracking purposes.  Feel free to create a PR once you've found a solution.
