### ISSUE TITLE
Having issues implementing pagination component in custom theme

### ISSUE THREAD

**Issue by MCristofalo** [DSpace/dspace-angular#2643]
**Describe the bug**
Hello DSpace team, it's a pleasure to get in contact.

We're currently using your product for a website we´re working on making a  custom theme for the Angular frontend app.

In the documentation, your team mentions we just have to copy components from the custom theme. 
We noticed while working there are a few that aren't in this theme folder and have tried implementing some with the method stated in the documentation but had no luck...

The first component giving us issues is the search filter (app/shared/search/search-filters/search-filter). If we add it to our theme folder and add it to lazy loader it shows blank, just the heading title. Is it possible to customize this component? if so how would we be able to do this?  Or may this be a bug?

The other component that we try to do this same process without luck is the pagination component.

If we add to theme and include in eager file for theme folder it just doesn't work. We apply the same changes to the main component and this issues persists.

Is this possible in the current version?

Best,

**To Reproduce**
1. Add pagination to custom theme folder
2. Adjust imports
3. Import pagination in lazy theme module declarations

**Related work**
Personal site

**Comment by tdonohue** [comment]
We recommend support questions be asked on mailing lists per our Support guidelines: https://wiki.lyrasis.org/display/DSPACE/Support

I see you've already asked this on `dspace-community` mailing list, so I added an answer there instead. https://groups.google.com/g/dspace-community/c/vu6CyCmI7u8

Closing this ticket as the question was answered on mailing lists.
