### ISSUE TITLE
Shibboleth login often fails on redirect back to DSpace

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#2669]
**Describe the bug**
When you try to log in using Shibboleth, you'll often notice you're not logged in when you get redirected to DSpace. When this happens you'll see console errors with messages like "undefined doesn't contain the link …", that indicate something is going wrong with calls to retrieve the links on `/api`

Note that this is a timing issue so it doesn't happen every time, but well over 50% of the time in my tests

**To Reproduce**
1. Log in using Shibboleth
2. When you're redirected back to DSpace, you'll notice you're not logged in and there are errors with messages like "undefined doesn't contain the link …" in the console

**Expected behavior**
You should be logged in, and there should be no console errors

**Related work**
This has the same cause as https://github.com/DSpace/dspace-angular/issues/1027. https://github.com/DSpace/dspace-angular/pull/1056 fixed it for Dataservices, but not for the HALEndpointService. That wasn't a problem because HAL endpoint requests were never set to stale, until https://github.com/DSpace/dspace-angular/pull/2510 changed that in 7.6.1. It's also the reason why [I couldn't get invalidateRootCache to work when listenForRouteChanges was first called](https://github.com/DSpace/dspace-angular/pull/2510): it caused HALEndpointService to return stale requests, but I didn't realize that's what was happening at the time

**Comment by mspalti** [comment]
We were seeing this issue. I applied the changes in #2670 and logins started to succeed. However, after logging into a collection recent submissions don't appear without a page reload. I see #2670 is in draft mode now so perhaps you are aware of this problem @artlowel . fyi

**Comment by tdonohue** [comment]
Closing, fixed by #2670 and #2731
