### ISSUE TITLE
Shibboleth: User is not redirected to previous page after login, and stuck on Log in page

### ISSUE THREAD

**Issue by misilot** [DSpace/dspace-angular#2671]
**Describe the bug**
DSpace 7.6.1 -- When going to a deep link for submission such as https://server/submit?collection=6d684812-6d29-4564-8b51-f5670957936b, I am redirected to the Choose login page. Sometimes it redirects (if like in a incongito window), other times it just returns to the log in chooser page.

DSpace is trying to go to this page after logging in: https://server/server/api/authn/shibboleth?redirectUrl=https://server/submit?collection=6d684812-6d29-4564-8b51-f5670957936b

**To Reproduce**
1. Enable Shibboleth
2. Create a deep link to a collection user can submit to (/submit?collection=collection-uuid)
3. Select Shibboleth Authentication
4. Login to IdP
5. You get returned to the login page, and not redirected to the submit page, and are stuck here, and can keep clicking Log in, and the UI never recognizes you are logged in. (It may if you eventually do a couple of hard refreshes)

**Expected behavior**
1. Logged into DSpace
2. Redirected to the deep linked collection submission page
3. This seems to work on dspace demo with a local account.

**Related work**

**Comment by tdonohue** [comment]
@misilot : This might be a duplicate of (or directly related to) #2669 ?  If so, there's a possible fix already in #2670 that you may want to test out to see if it solves the problem for you.

**Comment by misilot** [comment]
Thanks @tdonohue that seems to have fixed my issue!

It still hits the Log in page for 3-4 seconds before finally redirecting though.
