### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#27]
Add a mechanism to configure environment variables.

[This is the equivalent in the prototype](https://github.com/DSpace-Labs/angular2-ui-prototype/blob/master/config.ts) however it has the downside of having the values on git. It would be better to have a mechanism where the keys can be on git, but the values remain in a file local to the environment.

**Comment by atarix83** [comment]
I think to create this model for environment variables :

1.  `/src/config.ts` 
    This is the file to import into Components;
2. `/config/environment.dev.json and /config/environment.prod.json`
    This is where we put our env settings for the different environments. We need to have a json file for every enviroment (e.g. `dev`, `prod`);
3. `/config/environment.common.json`
 This is where we put our env settings shared between the environments;
4. All files in config dir are not committed on git but are imported on building into config.ts depending on running enviroment.

Would it be a good scenario?

**Comment by artlowel** [comment]
Sounds good.

Maybe we could also provide a `environment.default.json` file on git that isn't used but serves as a template for the dev and prod files.
