### ISSUE TITLE
Upgrade the mirador-share-plugin to v0.16.0

### ISSUE THREAD

**Issue by francescopioscognamiglio** [DSpace/dspace-angular#2708]
**Is your feature request related to a problem? Please describe.**
Opening the mirador viewer on a IIIF item, the "copy" button does not trigger any action if you click on it.
So it's not clear whether you clicked on it or not.

This issue was fixed in `v0.16.0`  of the mirador-share-plugin (https://github.com/ProjectMirador/mirador-share-plugin/tree/v0.16.0).

The pull request https://github.com/ProjectMirador/mirador-share-plugin/pull/49 describes our expected behavior:
> Click on each "copy" button and see that a notification window is triggered in the top center (it should have a green background, with a success icon and message that says "Link/Code/Manifest copied to clipboard!")

**Additional context**
The code of the Mirador Share plugin is here https://github.com/ProjectMirador/mirador-share-plugin.

**Comment by tdonohue** [comment]
Closing, fixed in #3476, #3490 and #3519
