### ISSUE TITLE
Avoid excess load of bots going into search facet links on entity pages

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#2709]
**Describe the bug**
We're seeing in search console for several of our clients that bots go into facet links on entity pages. Given that this doesn't contribute to the quality of the indexing (e.g. bots shouldn't be going there) and that processing these requests is resource intensive, we better avoid this behaviour al together.

**To Reproduce**
1. Look at search console for an actively indexed DSpace 7 site, that has entities enabled
2. Look for the patterns in the reports of crawled urls for things like:
 
`entities/orgunit/25913818-6714-4be5-89a6-f70c8facdf7e?f.author=Wang`

**Expected behavior**
Robots should be blocked from doing this

**Proposed solution**
Add following disallow directive in robots.txt:

`Disallow: /entities/*?f`

**Related work**

Previously incorrectly created in the back-end Git repo as https://github.com/DSpace/DSpace/issues/9227

**Comment by alanorth** [comment]
Thanks @bram-atmire! I can imagine this is a huge load (like crawling search and browse as well) and an obvious win for bots that respect robots.txt. I'm wondering if [Google's interpretation of the robot exclusion protocol](https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt#url-matching-based-on-path-values) supports wildcards such as this after path elements. It seems _maybe_? Have you tried it on a live site?

As a sysadmin I'd block these patterns in Apache / nginx just to be sure—as the Russian saying goes: "_trust, but verify_".

<hr>

Side note, we have several patterns with trailing wildcards that will be ignored by Google bot.

**Comment by hutattedonmyarm** [comment]
Wouldn't it be useful to (additionally) use add the `rel="nofollow"` attribute to the anchor tags in the search filters? This way we don't have to rely on how wildcards are handled by crawlers

**Comment by alanorth** [comment]
@hutattedonmyarm if we use `rel="nofollow"` on search pages it would be a sign for bots to not crawl them, but they still have to load the page to read the anchor tags. In theory the `robots.txt` method should be better because bots can read it before.

**Comment by hutattedonmyarm** [comment]
@alanorth Not the whole page, I was only talking about the links in `search-filters.component`. So the checkboxes which check/uncheck all the filters in the search results sidebar. These are implemented as links. Currently, crawlers follow them, because they're part of an entities page. But they only lead to search results

**Comment by alanorth** [comment]
@hutattedonmyarm oh yes, I was confusing the `rel=nofollow` with other robot instructions in head meta tags. I think you are right that we should make those links `rel=nofollow`.
