### ISSUE TITLE
Search configuration should be unset when performing a global search from MyDSpace

### ISSUE THREAD

**Issue by davide-negretti** [DSpace/dspace-angular#2723]
When the user performs a _global_ search starting from MyDSpace page the current search configuration (e.g. `workspace`) is not unset. It is unlikely that the user wants to perform a restricted search when using the header search box, so the configuration should be unset.

**To Reproduce**
- login
- open MyDSpace
  - the URL is https://demo.dspace.org/mydspace?configuration=workspace
- use the search box in the header to perform a global search
  - the configuration is not unset
  - the URL is https://demo.dspace.org/search?configuration=workspace&query=SEARCH_QUERY

**Expected behavior**
The configuration should be unset, and the URL should be https://demo.dspace.org/search?&query=SEARCH_QUERY

**Comment by alexandrevryghem** [comment]
This issue has been fixed in #2818

**Comment by tdonohue** [comment]
Closing as fixed by #2818 (main) and #2824 (dspace-7_x).  Fixed in 7.6.2 and 8.0
