### ISSUE TITLE
Infinite scroll not working when in mydspace

### ISSUE THREAD

**Issue by Sondissimo** [DSpace/dspace-angular#2767]
**Describe the bug**
The bug seems to block the infinite scroll and not show all of the available collections to create  for example an item when in my dspace

**To Reproduce**
1. Go into my dspace
2. Then try to add for example a new publication
3. When the list of collections is shown scroll down
4. Now the infinite scrolldown will block and not all the collection are shown

**Expected behavior**
The infinite scroll should simply continue until all collection are shown

**Related work**
https://github.com/DSpace/dspace-angular/pull/2768#event-11586157483

**Comment by alanorth** [comment]
I can reproduce this on demo.dspace.org, but not on my own DSpace 7.6.1 instance.

**Comment by atarix83** [comment]
@alanorth 

it could depend on the fact if you have more pages to show when the dropdown menu is opened. However it occurs on both sandbox and demo instances so we think it should be fixed
