### ISSUE TITLE
Unable to add specific metadata field/value to item

### ISSUE THREAD

**Issue by LEavestaff** [DSpace/dspace-angular#2815]
**Describe the bug**
We are unable to add the metafield 'dc.description' to an item in the edit item page in the UI. The field does not appear in the dropdown, and it gives the error message 'Please choose a valid metadata field'. This is despite us having the metadata field registered, and we have tried removing adding back the field in the registry but the issue still remains. It seems to be only this field that has the issue.

![image](https://github.com/DSpace/dspace-angular/assets/112828735/0f6b306b-d6a4-44d2-ba9d-add43f0d8ede)
![image](https://github.com/DSpace/dspace-angular/assets/112828735/45f6d2e8-fd72-4f67-8e20-d80993018fc4)

We have a customised instance of DSpace 7.5 installed currently. We first noticed this issue before production release last year but are unable to diagnose the issue.

**To Reproduce**
1. Login as an admin
2. Find an item and then edit the item
3. Add new field in the edit item view and type 'dc.description'

**Expected behavior**
Field 'dc.description' is accepted as a valid metadata field to be added

**Related work**
N/A

**Comment by LEavestaff** [comment]
Have done some extensive digging, and here is what I've found:

On our instances of DSpace 7.5, our non-qualified metadata fields appear at the end of the dropdown list. Pair this with the querying of metadata field options only bringing back 10 results, this seemingly causes the 'Please choose a valid metadata field' error to occur. Upon checking the demo site (running 7.6.2), this is not the case there.

I suspect this was fixed in 7.6, with the DSpace backend fix [#8758](https://github.com/DSpace/DSpace/pull/8758). We will be updating to 7.6.1 later in the year, at which point I may be able to provide an update on resolution. For now I'm happy to close this issue.

**Comment by stuartayeates** [comment]
We had a very similar issue which was fixed with a '~/bin/dspace index-discovery' 

The problem was that these were stored in the solr index, which needed to be rebuilt.

**Comment by LEavestaff** [comment]
> We had a very similar issue which was fixed with a '~/bin/dspace index-discovery'
> 
> The problem was that these were stored in the solr index, which needed to be rebuilt.

We have unfortunately tried that command many times and no resolution (and done many rebuilds usign the -b option). As I noted, I suspect the real fix lies in the changes from 7.5 to 7.6. May I know which version of DSpace you were running when you had the issue @stuartayeates?

**Comment by stuartayeates** [comment]
This is in 7.6.

**Comment by tdonohue** [comment]
For what it's worth, this bug doesn't seem to be reproducible on https://demo.dspace.org (which is currently running pre-7.6.2 code from the `dspace-7_x` branch).  It's unclear to me if it occurred in earlier versions, but it doesn't seem to be occurring anymore.
