### ISSUE TITLE
200 Status codes are returned for pages with non-resolving identifiers

### ISSUE THREAD

**Issue by jensvannerum** [DSpace/dspace-angular#2817]
**Describe the bug**
As reported by @bram-atmire in https://github.com/DSpace/dspace-angular/issues/2554#issuecomment-1888669254

200 OK status codes are being returned for URL's with missing identifiers, this should return a 404 not found

**To Reproduce**
1. send a request to a url of a missing identifier like mentioned in Bram's original comment

**Expected behavior**
Receive a 404 status code

**Related work**
https://github.com/DSpace/dspace-angular/issues/2554

**Comment by alanorth** [comment]
Oh yes, Angular returns HTTP 200 for anything that is `/handle/x/x`, including sub paths. For example:

```console
$ curl --head https://demo.dspace.org/handle/foo/bar
HTTP/2 200
$ curl --head https://demo.dspace.org/handle/10673/2008/dspace
HTTP/2 200
$ curl --head https://demo.dspace.org/handle/10673/200x
HTTP/2 200
$ curl --head https://demo.dspace.org/handle/10000000/093991991
HTTP/2 200
```
