### ISSUE TITLE
Partially updated view navigating from browsing community to "All of DSpace"

### ISSUE THREAD

**Issue by ghadf** [DSpace/dspace-angular#2823]
**Describe the bug**
When navigating from browsing items in a community by issue date, by author, etc to the corresponding "All of DSpace" menu option, the address bar and items shown reflect the navigation but the page otherwise appears the same, as if still browsing items within the community. This only occurs when the "All of DSpace" option matches the currently displayed community browse option.

Observed with dspace-angular 7.6.1 in Chrome 121 and Edge 121 on Windows; reproduced on https://demo.dspace.org/.

**To Reproduce**
1. Open the community list eg https://demo.dspace.org/community-list.
2. Click any community.
3. Click By Issue Date, or By Author, etc.
4. Click All of DSpace -> same option as step 3.

The list of items is updated correctly, but the rest of the page is not, eg breadcrumbs are unchanged and the community name and browse controls are still visible.

**Expected behavior**
When using "All of DSpace" menu options while browsing a community, the resulting page should always look the same as using those options from the home page or direct links.

**Comment by alexandrevryghem** [comment]
@ghadf: This has been fixed on dspace 8.0 see this this ticket: #2425

**Comment by ghadf** [comment]
Sorry for the waste of time, obviously I missed that one. Closing since this is a duplicate and https://github.com/DSpace/dspace-angular/issues/2425#issuecomment-1942445729 implies "won't fix" for 7.6.
