### ISSUE TITLE
minimum date range in search-range-filter-component.ts should be configurable.

### ISSUE THREAD

**Issue by tantz001** [DSpace/dspace-angular#2829]
**Is your feature request related to a problem? Please describe.**
facet by date range does not work correctly when the repository contains dc.date.issued values earlier than the hard-coded value of 1950.  Users cannot extend the date earlier by any means.

**Describe the solution you'd like**
1. (ok) the variable min in search-range-filter.component.ts is a configuration option in config.yml
2. (better) minimum is based on the current minimum dc.date.issued in the repository

**Describe alternatives or workarounds you've considered**
hard coding another arbitrarily small value in search-range-filter.component.ts 

**Additional context**
for instance, https://demo.dspace.org/search?query=time

**Comment by alexandrevryghem** [comment]
This ticket can be closed, since it's a duplicate of #1723 I think

**Comment by tantz001** [comment]
Agreed, thank you.
