### ISSUE TITLE
Minor bugs with COAR Notify initial implementation

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2842]
**Describe the bug**
Two minor bugs were not yet addressed in the initial COAR Notify PR #2681 
1. An error occurs in the UI when `ldn.enable=false` is set. See https://github.com/DSpace/dspace-angular/pull/2681#issuecomment-1971611625  (Partially fixed by #2751)
2. ~~Duplicate i18n keys exist. The ones added by this PR should be removed as they override the changes made in https://github.com/DSpace/dspace-angular/pull/2759 . See https://github.com/DSpace/dspace-angular/pull/2681#pullrequestreview-1909507036~~  (Fixed by #2751)

These issues must be resolved in a small PR or in the follow-up work in #2751

**Comment by tdonohue** [comment]
**UPDATE:** #2751 solved **most of these bugs**.  However, the `TypeError` that occurs when `ldn.enable=false` **still occurs** only on the Item view page.  See this comment for details: https://github.com/DSpace/dspace-angular/pull/2751#pullrequestreview-1915217029

Once that TypeError on the Item view page is solved, this bug ticket can be closed.

**Comment by frabacche** [comment]
@tdonohue pr linked to this issue at [here](https://github.com/DSpace/dspace-angular/pull/2856).
