### ISSUE TITLE
Janitor Support

### ISSUE THREAD

**Issue by PTrottier** [DSpace/dspace-angular#286]
Hello everyone!

You can contribute to dspace-angular in a breeze using [Janitor](https://janitor.technology) today! It makes your work easier by giving you access to a ready made environment to work on the project. 

Currently, the dspace-angular environment is made using Docker image (think of it like a sandbox) and is found under the Janitor Technology [collection](https://hub.docker.com/r/janitortechnology/dspace/) of images. I think it would be great to decentralize this by bringing the Dockerfile (a used to make the Docker image) to this repository. The following outlines the requirements for Janitor: https://discourse.janitor.technology/t/how-to-add-a-project/165/3

I would love to hear your thoughts on this addition?

For more information on DSpace's Docker initiative, see: https://dspace-labs.github.io/DSpace-Docker-Images/

cc @jankeromnes, @terrywbrady

**Comment by artlowel** [comment]
I'd love to make it easier to support janitor, but dspace-angular already has a [Dockerfile](https://github.com/DSpace/dspace-angular/blob/5820e9ca814a9fab154fe057fe42d7d815da58d8/Dockerfile). @terrywbrady added it in #278 . Can the existing Dockerfile be tweaked to work with janitor and [dspace7-compose](https://github.com/DSpace-Labs/DSpace-Docker-Images/tree/master/docker-compose-files/dspace7-compose) at the same time?

**Comment by terrywbrady** [comment]
@PTrottier , could you put together a PR illustrating how the Janitor Dockerfile could reside in the repo along with the existing Dockerfile?  It would be helpful to compare the 2 Dockerfiles side by side.

**Comment by tdonohue** [comment]
Closing, as this seems outdated at this time
