### ISSUE TITLE
DSpace 8 New User Registration does not work when recaptcha disabled

### ISSUE THREAD

**Issue by librariankimberly** [DSpace/dspace-angular#2918]
Cannot register a new user
Browsers: Firefox, Edge, Chrome

DSpace 8.0 Sandbox https://sandbox.dspace.org/register

**To Reproduce**
1. Go to DSpace 8.0 Sandbox https://sandbox.dspace.org/register
2. Click on Login in upper right corner
3. Click on New User? Click here to register.
4. Enter email address on registration page.
5. Click the Register button.

**Expected behavior**
I expected to see exactly what happens on the DSpace 7 Demo Site (where this is working, I just checked it.) What should happen is the button performs a function where a confirmation email is sent and a message appears that states this.

What is actually happening on the DSpace 8 Sandbox is NOTHING. I am one of three people listed in the test plan who has experienced this.

**Related work**
Link to any related tickets or PRs here.

**Comment by dheles** [comment]
This appears to be a recaptcha failure. From the dev tools console (when i click the Register button):
```
ERROR ReferenceError: grecaptcha is not defined
    executeRecaptcha https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    executeRecaptcha https://sandbox.dspace.org/2970.01c13afef817848e.js:1
    N https://sandbox.dspace.org/2970.01c13afef817848e.js:1
    ty https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    B https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    decoratePreventDefault https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    onInvokeTask https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    runTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    q https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    tt https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    vt https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
[main.84102cf2433b3eab.js:1:1888559](https://sandbox.dspace.org/main.84102cf2433b3eab.js)
    handleError https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    M0 https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    ty https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    B https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    decoratePreventDefault https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    onInvokeTask https://sandbox.dspace.org/main.84102cf2433b3eab.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    runTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    invokeTask https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    q https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    tt https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
    vt https://sandbox.dspace.org/polyfills.dcf1c31205c39edd.js:1
```
Is "grecaptcha" a typo, perhaps?

**Comment by dheles** [comment]
It looks like `registration.verification.enabled` needs to be set to true. It's currently false.

**Comment by tdonohue** [comment]
@dheles : It does seem like a bug with the verification process.  By *default* `registration.verification.enabled` is supposed to be false, which **should allow** for registration to proceed *without requiring a Recaptcha*.

However, it appears that some area of the code is *requiring* a Recaptcha (even though it's not been enabled).  That sounds like the bug here.  The registration should *not* require Recaptcha when `registration.verification.enabled=false`

**Comment by dheles** [comment]
@tdonohue Thanks for the clarification. I wonder if it would be worthwhile to enable recaptcha (temporarily, perhaps) to confirm that users *can* register themselves to the sandbox when it's on. Just to rule out any additional bugs downstream of this point-of-failure.

**Comment by Leano1998** [comment]
Hey,
the problem is - as far as I can see it - that in the code of the html-template file, its only checked, if you're using captcha version v2 or v3 and if it's invisible or not and not, if the registration verification is enabled at all.

**Comment by librariankimberly** [comment]
It would be helpful to be register new users for the testathon. I'm still not clear on if this is a bug or was intentionally disabled for the testathon? If this was intentionally disabled can it be enabled?

**Comment by tdonohue** [comment]
User Registration is currently not behaving properly. A possible fix is being tested in #2931.  So, this is a bug.  I'm hoping, if the fix works, we can push an update to the Sandbox later today.

**Comment by librariankimberly** [comment]
That's great, thanks!

**Comment by tdonohue** [comment]
The bug fix in #2931 works! I'm deploying it to sandbox.dspace.org. (However, the deploy process will take about 30-60 minutes because it requires first rebuilding all Docker images since Sandbox runs off those Docker images)

**Comment by tdonohue** [comment]
I can verify that User Registration on https://sandbox.dspace.org is working again.  I've just tested it and ran into no issues.

**Comment by librariankimberly** [comment]
[celebrate]     Chapman, Kimberly A - (kimberl... reacted to your message:
________________________________
From: Tim Donohue ***@***.***>
Sent: Monday, April 15, 2024 6:43:50 PM
To: DSpace/dspace-angular ***@***.***>
Cc: Chapman, Kimberly A - (kimberlychapman) ***@***.***>; Author ***@***.***>
Subject: [EXT]Re: [DSpace/dspace-angular] DSpace 8 New User Registration does not work when recaptcha disabled (Issue #2918)


External Email

I can verify that User Registration on https://sandbox.dspace.org is working again. I've just tested it and ran into no issues.
