### ISSUE TITLE
The Item version input form is not displayed in DSPace 8, preventing the creation of a new version of an item.

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#2923]
**Describe the bug**
In DSpace 8 Sandbox I try to create a new version for different items (with or without file, with relations and without), results are differents (sometimes UI is freezing, sometimes I only get a confirmation that a version has been created. However, I never get to the new submission form for the new version as describe in the document: https://wiki.lyrasis.org/display/DSDOC8x/Versioned+Item

**To Reproduce**
1. Connect as administrator
2. Find and open an item in the repository
3. Clic on the new version button in the upper left of the page ![image](https://github.com/DSpace/dspace-angular/assets/19291880/b2d36d32-fe66-405e-b6c0-bdd54ead10e5)
4. Add text to describe the version and then clic on Create
5. Want a few seconds, a confirmation message appears: New version has been created with version number 2
6. But, the new version submission form is not displayed.

**Expected behavior**
Should work in described in the documentation  https://wiki.lyrasis.org/display/DSDOC8x/Versioned+Item

**Comment by tdonohue** [comment]
Might be related to https://github.com/DSpace/dspace-angular/pull/2761 (This PR sounds similar but needs testing).
