### ISSUE TITLE
New submission page infinite loading 

### ISSUE THREAD

**Issue by GraziaQuercia** [DSpace/dspace-angular#2932]
When adding a new submission, the page is stuck on loadingthe form.

How to reproduce:
- Log in to DSpace 8 sandbox
- From the left admin menu, click on New
- Click on item
- Select the collection (example Articles)
The page will continuously load.
![image](https://github.com/DSpace/dspace-angular/assets/124360978/76c8dd56-4de4-421e-899e-181eec2d6d09)

The submission page should load with no issue and show the collection form to deposit an item.

**Comment by tdonohue** [comment]
@GraziaQuercia : Thanks for reporting.  However, I can no longer reproduce this issue on the Sandbox, so I suspect it was a temporary issue. It's possible either the sandbox was restarting itself or temporarily overwhelmed.  Please try again and see if this is working.

I'm able to get this to work on my end:
* Login as an Admin (dspacedemo+admin@gmail.com) on sandbox.dspace.org
* Go to "New" -> "Item"
* Select "Articles" collection
* Submission form loads in a few seconds.

If it's still not working for you, please let me know on this ticket. Let us know what browser you are using, or anything else you feel you might be doing different than I am.  It's always possible I've overlooked something, and perhaps with more details we'll be able to figure out what is going on.

For now, I'll close this. But we can reopen if it is found to still be reproducible.  Thanks!

**Comment by CecileGass** [comment]
Good afternoon, just to let you know I just tested this and it works perfectly! Best regards.
