### ISSUE TITLE
Editing an in-progress submission results in an empty form

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2940]
**Describe the bug**
If you save a submission for later & then edit it, you get an empty form.  Reloading the page (f5) will cause the metadata to finally load.

**To Reproduce**
1. Start a new Submission
2. Enter some metadata
3. Click "Save for Later"
4. On MyDSpace page, find your submission (browse or search for it)
5. Click Edit
6. The Submission form will be empty.  Your metadata entered in step 2 is missing
7. Reload page in browser.  Metadata will then appear.

**Expected behavior**
Editing a submission should work like in DSpace 7

**Comment by artlowel** [comment]
@tdonohue I can't seem to reproduce this issue on sandbox by following the steps above. However it does sound suspiciously like the issue I had in late march but couldn't reproduce in the community codebase then. 

@kshepherd and @pnbecker asked me about the fix, and were able to solve one of their metadata-disappearing-issues in the submission with it as well. 

I'll create a PR for it so you can see if it fixes this too

**Comment by tdonohue** [comment]
@artlowel : You are correct.  I cannot seem to reproduce this either, which is odd.  It was happening consistently for me before.  It must have been the site being overwhelmed or something else going on at that particular point in time.

I still will review the PR (which I see you just created) as I wonder if it will make this less likely to occur in the future.
