### ISSUE TITLE
Clicking "Save" on Create Community/Collection should provide user feedback

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2941]
**Describe the bug**
If you Create a new Community or Collection, clicking "Save" appears to do nothing.  It's unclear if you've clicked the button or if the backend is processing.  This is semi-related to #2914 

**To Reproduce**
1. Create a new Community or Collection  via "New -> Community" or "New -> Collection"
    * NOTE: This is most visible on https://sandbox.dspace.org when creating a new Collection, as this action may take 5-10 seconds to complete.
3. Fill out metadata
4. Click Save.  Notice the button remains enabled & it may not even be clear that you pressed the button.

**Expected behavior**
Some visual feedback should be given to the user.   Either the button should disable (like the submission form behavior) or some sort of "Processing.." message should appear or similar.

**Related work**
Semi-related to #2914.  Because Collection creation can take >2 seconds, it's important to give the user feedback.

**Comment by artlowel** [comment]
@tdonohue We can work on this
