### ISSUE TITLE
Item Mapper hangs when a search is run

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#2953]
**Describe the bug**
Currently on https://sandbox.dspace.org and on `main` (when run locally), the Item Mapper hangs when you perform a search
**To Reproduce**
1. Login as Admin
2. Edit Collection
3. Item Mapper tab  (note: some errors appear in DevTools Console when accessing this tab?)
4. Click on "Map new items" subtab and enter a search term.  Click Search
5. Results will load but the page with "hang" and it will be impossible to interact with the page anymore.  You must close your browser window or reload to regain control.

Unclear if the issue is a frontend or backend bug.

**Expected behavior**
Item Mapper should work as normal

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue

**Comment by tdonohue** [comment]
Thanks @alexandrevryghem !  Assigning to your for you/your team to work on.
