### ISSUE TITLE
COAR Notify website link on COAR Notify Support page doesn't work (v8 testathon)

### ISSUE THREAD

**Issue by keithgee** [DSpace/dspace-angular#2964]
When clicked on, the COAR Notify website link doesn't load the COAR website. The address of the link appears as `unsafe:\"https://notify.coar-repositories.org/\"`

**To Reproduce**
1. Navigate to the COAR Notify Support page at https://sandbox.dspace.org/info/coar-notify-support
2. Click on the COAR Notify website link in the first paragraph.

Nothing happens.

**Expected behavior**
The COAR Notify website page should load.

**Comment by alexandrevryghem** [comment]
I can work on this I still have other small UI improvements that I need to contribute

**Comment by tdonohue** [comment]
@alexandrevryghem : Sounds good. Assigning to you.
