### ISSUE TITLE
Unfocused search component views in modals remain visible on mobile screens

### ISSUE THREAD

**Issue by ybnd** [DSpace/dspace-angular#2970]
**Describe the bug**
A clear and concise description of what the bug is. Include the version(s) of DSpace where you've seen this problem & what *web browser* you were using. Link to examples if they are public.

**To Reproduce**
1. Edit an Entity in DSpace (e.g. from https://demo.dspace.org/search?query=dspace.entity.type:Publication&spc.page=1)
2. Go to the "Relationships" tab
3. Click on one of the "+ Add" buttons to open a lookup modal
4. Resize the screen
    * You will see a small sliver of the search tools view on the left hand side
5. Click on "Search tools"
    * You will still see a small sliver of the search results view on the right hand side
    * Because of the sliding animation this will be all the more noticeable

**Expected behavior**
The "Search tools" view should not be visible when the "Results" view is focused and vice versa.
The content should only be visible when it appears within the borders of the modal it is in.

**Comment by alexandrevryghem** [comment]
I already fixed this on 8.0 in #2732, so I'm assigning myself in order to create a backport for the `dspace-7_x` branch

**Comment by tdonohue** [comment]
Fixed by #3027 in 7.6.2.  Fixed by #2732 in 8.0
