### ISSUE TITLE
media viewer struggles on loading bitstreams with restricted access conditions

### ISSUE THREAD

**Issue by floriangantner** [DSpace/dspace-angular#2982]
**Describe the bug**
Tested during testathon .
The media viewer struggles with displaying bitstreams which have some restricted access condition. As an user it is unclear why these information are not shown.

**To Reproduce**
1. Create some item with two images or video files and openaccess condition for both bitstream.
2. Publish the item.
3. Set one of the bitstream to access condition administrator, lease before now date or embargo in future date. Probably the first/primary bitstream.
4. Open the item in the image viewer.
4a. the video case: The video cannot be loaded, but pagination between the video files is possible
4b: the image case: The image cannot be loaded, also no pagination to previous/next bitstream is possible when the current bitstream is restricted.

![Screenshot 2024-04-25 at 16-58-03 Test with multiple Screencasts](https://github.com/DSpace/dspace-angular/assets/33422716/4249f707-6bef-4733-b785-45408a0f81ba)

![Screenshot 2024-04-25 at 17-00-56 Test with multiple screenshots](https://github.com/DSpace/dspace-angular/assets/33422716/4e223516-54d1-4ac6-ba8b-c42127fe732d)

![Screenshot 2024-04-25 at 17-01-04 Test with multiple screenshots](https://github.com/DSpace/dspace-angular/assets/33422716/27f4a04c-f23a-4e69-8b66-277ee26e08a8)

**Expected behavior**
We would expect some placeholder image or additional message or thumbstone to be shown which mentions (when enabled) the request-a-copy feature as the download link. Another way would be to exclude the restricted bitstreams  from the gallery view or the video list.

**Related work**

**Comment by alexandrevryghem** [comment]
I think this is a duplicate of #1887

**Comment by floriangantner** [comment]
> I think this is a duplicate of #1887

sorry my fault - it is probably some duplicate of the referenced issue which description looks quite similar to this bug
