### ISSUE TITLE
Advanced Workflow actions button results in 404 page

### ISSUE THREAD

**Issue by GarrafaGalactica** [DSpace/dspace-angular#3031]
**Describe the bug**
When you press the button for any advanced workflow action, it redirects to the corresponding page (or at least what worked before), but after a while, it redirects to a 404 page.
![output](https://github.com/DSpace/dspace-angular/assets/83254680/d913312d-a219-4114-a3ee-c9305e1770ce)

**To Reproduce**
1. Go to the workflow task list and search for a workflow with any advanced workflow action (you can add the option to editaction).
2. Click the button to navigate to the advanced workflow action page.
3. Wait until you get the 404 page

**Expected behavior**
It needs to render the page dedicated to that advanced workflow action

**Comment by tdonohue** [comment]
@GarrafaGalactica : What version of DSpace is this?  DSpace 7.6.x?  current `main` (pre-8.0)?

**Comment by GarrafaGalactica** [comment]
Current main (pre-8.0)

**Comment by tdonohue** [comment]
Ok, I'll pull this over to the 8.0 board.  Needs a volunteer to investigate this.
