### ISSUE TITLE
Cannot Delete an Entity which has Relationships

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#3068]
**Describe the bug**
If you attempt to delete an Entity which has existing relationships, the Delete page will hang indefinitely and you will not be able to complete the deletion or exit the page.

**To Reproduce**
1. Find an Entity which has at least one relationship (e.g. a Publication linked to a Person, or a Person linked to a Publication)
2. Login as an Admin
3. Edit that Entity
4. Go to the "Status" tab
5. Click "Permanently delete" button
6. You will see the "Delete Item" page.  But, you will be unable to interact with the system any longer. The page will become unresponsive and the buttons at the bottom & links in the header will no longer work.
    * At this point, you have to close your tab/window to interact with the application again.

This issue ONLY impacts 8.x and is reproducible on https://sandbox.dspace.org/   
Deletion of Entities works fine on https://demo.dspace.org/ (running 7.6.x)

**Expected behavior**
It should be possible to delete Entities that have relationships, just as you could in 7.x

**Comment by tdonohue** [comment]
@alexandrevryghem and @artlowel : Pinging you on this new issue as it may be semi-related to #3060 .  This bug is not about creation of relationships though, but rather about *deletion*.  If you want to claim it, let me know.  I think we have to fix this in 8.0 as it's no longer possible to delete Entities until you first remove all relationships.

**Comment by artlowel** [comment]
@tdonohue I investigated this issue. You're right in saying that it's similar to https://github.com/DSpace/dspace-angular/pull/3060, but unfortunately the fix will also be similar in scale. We basically need to refactor [item-delete.component.html](https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/edit-item-page/item-delete/item-delete.component.html) to get all the direct function calls out of it. Calling functions from HTML always used to be problematic for performance, so I don't think this is a new bug in DSpace 8, but it seems that with the update to Angular 17 these sorts of issues have become more severe. It used to be slow, now it breaks the page.

I won't have time to work on this before OR. I could try to get it on Alex's plate for next week, but given the complexity I wouldn't expect a PR before the second half of next week
