### ISSUE TITLE
Remove Bitstreams on edit-item-page doesn't work 

### ISSUE THREAD

**Issue by Leano1998** [DSpace/dspace-angular#3116]
**Describe the bug**
A new issue appeared, where you can't remove the bitstreams of an item using the edit-item-page. After selecting bitstreams for deletion, the **Save**-button stays deactivated. Only if you select bitstreams of all existing bundles, the button is clickable. 

**To Reproduce**
1. Login as an site-administrator
2. Open the edit-item-page of an item with attached bitstreams
3. Navigate to the *Bitstreams*-tab.
4. Click on the tiny garbage-can of one bitstream for deleting it.
5. Try to click *Save* in order to apply the changes (you can also try to *Discard* the changes, it won't work either) 

**Expected behavior**

The **Save** or **Discard** buttons should be clickable.

**Comment by tdonohue** [comment]
This is reproducible on Sandbox and Demo.  Not sure why/how this is occurring or when it began.

@artlowel or @atarix83 : Do either of your teams have time to look into this quickly early next week?

**Comment by alexandrevryghem** [comment]
@Leano1998 : It's because it causes performance issues, I can take a look at this

**Comment by Leano1998** [comment]
Ah, I thought so, Thank you @alexandrevryghem

**Comment by tdonohue** [comment]
Thanks @alexandrevryghem !  I'll assign this to you then.
