### ISSUE TITLE
ngVars cause duplicate thumbnail bitstream requests

### ISSUE THREAD

**Issue by bram-atmire** [DSpace/dspace-angular#3134]
**Describe the bug**
On pages where thumbnails are requested, Angular sends 2 requests to retrieve the bitstream instead of one.

![Screenshot 2024-06-18 at 14 16 19](https://github.com/DSpace/dspace-angular/assets/958314/388a8eab-a284-41cf-80e9-d1857e54233d)

**Cause & solution approach**

This is likely caused by the use of ngVars [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/thumbnail/thumbnail.component.html#L1) and [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/thumbnail/thumbnail.component.html#L9)

One path to address this would be to replace the occurences with their values.

**To Reproduce**
1. Open up inspect element
2. Go to https://demo.dspace.org/search?spc.page=1&query=%22A%20Strength-Based%20Approach%20to%20Indigeneity,%20Equity,%20Diversity,%20and%20Inclusion%20Program%20Evaluation%20in%20Higher%20Education%22 this is a search that should return two items with thumbnails
3. Check how many "content" requests there are

**Expected behavior**
There should be 2 content requests, one per file

**Observed behavior**
There are 2 requests per file

**Related work**
Link to any related tickets or PRs here.

**Comment by alanorth** [comment]
Good catch, @bram-atmire! I see it on our DSpace 7.6.1 instance too, though in Firefox at least each of the second requests are cached and take 0ms.

![2024-06-20T09:09:33,018418137+03:00-fs8](https://github.com/DSpace/dspace-angular/assets/191754/6e79f069-0fcd-4686-ad8e-f1d6ebf21c8e)

**Comment by bram-atmire** [comment]
you're right Alan, I can also see that in Chrome, if you have "Disable Cache" DISABLED (so if caching is ON) the duplicate requests are not visible.

Nevertheless, we likely still better clean up the use of ngVars anyway.

**Comment by ybnd** [comment]
We'd like to claim this one
