### ISSUE TITLE
Can't save cookie preferences when declining Google ReCaptcha cookies

### ISSUE THREAD

**Issue by LotteHofstede** [DSpace/dspace-angular#3145]
**Describe the bug**
When declining the Google ReCaptcha cookies in the Klaro popup, your cookie preferences will not be saved.

**To Reproduce**
1. Make sure your Google ReCaptcha key is configured in the backend
2. Open a new window where your cookie preferences aren't saved yet (new incognito/private window)
3.
    a. Click 'Decline' on the cookie pop-up
             OR 
    b. 'Customize' and then 'Accept selected', and make sure the 'Registration and Password recovery' is disabled on the cookies pop-up
4. Refresh the page
5. The Klaro cookies pop-up shows up again, even though you saved your preferences

**Expected behavior**
The Klaro cookies pop-up should not show again after declining optional cookies, because your preferences are saved

**Comment by kshepherd** [comment]
I have encountered this issue, too. If one of the services that expects to use the recaptcha is not enabled, the cookes are ignored but continue to prompt.
