### ISSUE TITLE
Grant document copy request is not working in dspace cris 7 

### ISSUE THREAD

**Issue by abhishek2316** [DSpace/dspace-angular#3174]
## Describe the bug
I am using DSpace CRIS 2023.01.00 Version. Here, I am the Administrator and I have to send the copy or Grant document copy request. In that, The send button is not working. 

I have tried all the changes like in local.cfg , dspace.cfg and in requestitem.xml. But still that send button is not working. 
Also, I have check my Gmail configuration, that is correct. 

So, Please tell me what are the changes I need to do or else there is some bug from your side. or You have not enabled this feature yet, because I have read in the google groups discussion(https://groups.google.com/g/dspace-devel/c/LIQMEMnTEtw).

Therefore, Please provide me the way. So, That this bug will get resolve.

**Comment by tdonohue** [comment]
Closing as DSpace-CRIS is a separate product from DSpace.  DSpace-CRIS is a product of 4Science (based on DSpace), while DSpace is a community-built product.  https://wiki.lyrasis.org/display/DSPACECRIS

This bug should be reported to 4Science directly as it's not something the DSpace team can fix.
