### ISSUE TITLE
Discussion: should we use http forwards for requests like /handle/<prefix>/<suffix>?

### ISSUE THREAD

**Issue by pnbecker** [DSpace/dspace-angular#3215]
The community is currently investigating the performance of DSpace and how it can be improved. One idea is to have better caches and to use caches in front of DSpace.

The DSpace frontend currently supports different URLs for community-, collection- and item pages. By default is uses the uuid in the url. It still supports (for good reasons) the old URLs that were used up to DSpace 6 containing the handle but not the uuid. When a url using the handle is opened, dspace-angular serves the contents of the page and changes the address in the browser's address bar to the uuid, using JavaScript. I would like to discuss if it wouldn't be better to send back an http 30X status and to do a proper http forward to the new url.

Mainly I see two reasons, why we should prefer a proper http forward above serving the content and rewriting the address bar with javaScript:
1. If you run an external proxy, it will cache the URL with the uuid as well as the URL with the handle and treats them as two separate pages within the cache. This uses more memory for a caching solution than necessary. It also makes it harder to remove cached objects, if the content changes. If we would send back http forwards, the proxy could work with that or store that, which is a very small piece of information compared to a complete http site.
2. Search engines don't like duplicate content. The current way dspace-angular treats the handle URLs let them appear like duplicate content within the same domain. A clear http forward would be better regarding SEO.

What were the reasons to implement the current behavior? What do you think of this?

**Comment by kshepherd** [comment]
To add to this, here are the Google Scholar recommendations from https://scholar.google.com/intl/en/scholar/inclusion.html#crawl

> If you need to move your articles to new URLs, set up HTTP 301 redirects from the old location of each article to its new location. Do not redirect article URLs to the homepage - users need to see at least the abstract when they click on your URL in Google results.

Google developer pages has some more info about duplicate and canonical URLs: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls

**Comment by tdonohue** [comment]
This sounds related to #2265. We already perform a 301 redirect when SSR is triggered...but when CSR is used, the redirect is occurring via Javascript.   I'm not against performing a 301 at all times, but there may be a reason that wasn't done in the first place.

**Comment by pnbecker** [comment]
@tdonohue that helps. thank you. I might have look onto a 7.5 code base. my fault. thank you!
