### ISSUE TITLE
FontAwesome 5

### ISSUE THREAD

**Issue by LotteHofstede** [DSpace/dspace-angular#326]
While working on the implementation of the [admin menu](https://wiki.duraspace.org/display/DSPACE/Menu+Mockups), I decided it would be better to upgrade to FontAwesome 5 (we're currently at 4.7). Because the whole library has been rewritten, upgrading as early as possible seemed like the best way to get as little issues and conflicts in the future.

### Why upgrade?
FA5 has a lot more features and icons than it's predecessor, see: https://fontawesome.com/how-to-use/on-the-web. Since version 5 there is also an SVG + JS version, which has even more possibilities than the original Fonts + CSS version.
Fortunately for us there is an [angular implementation](https://github.com/FortAwesome/angular-fontawesome) of the SVG/JS version available, which supports [tree shaking](https://github.com/FortAwesome/angular-fontawesome#tree-shaking).

### Issue
While adding the Yarn libraries to our project and importing them in our `AppModule`, I ran into an issue with the `DomSanitizer` class when running DSpace-angular with SSR. The FA-Icon component expects the `DomSanitizer` (which is part of the `BrowserModule`) as a constructor argument, but somehow the injected dependency cannot be resolved. 

### Temporary solution
For now I solved this by using the Webfonts + SCSS version of the library. Unfortunately, the Fonts files are loaded as a whole, so unlike the SVG implementation, tree shaking is less useful here. It also misses quite some functionality in comparison to the SVG/JS version.

It would be ideal if we could get the [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome) library to work.

**Comment by tdonohue** [comment]
This appears to be outdated, as we've already updated to FontAwesome v5.  Closing
