### ISSUE TITLE
Misspelling in en.json5 file for the word 'occurred'

### ISSUE THREAD

**Issue by wangra8** [DSpace/dspace-angular#3330]
## Describe the bug
Misspelling found in [en.json5](https://github.com/DSpace/dspace-angular/blob/dspace-7_x/src/assets/i18n/en.json5) file for the word `occurred` which appears as `occured` throughout DSpace (at least 4 times in the file). 

## To Reproduce
1. User reported this when they intentionally try to reset a password using an eperson account that does not exist.
2. A message will display with the following text and the typo:
" forgot-email.form.error.content": "An error `occured` when attempting to reset the password for the account associated with the following email address: {{ email }}"

## Expected behavior
The word `occured` should be spelled as `occurred`.

**Comment by tdonohue** [comment]
Needs a volunteer to create a PR.  It should be easy to do though as it's a simple typo.

**Comment by wangra8** [comment]
Hi @tdonohue Thank you for reviewing this Github issue, we have a volunteer from our team [@alphapetjg](https://github.com/alphapetjg) who is happy to contribute. Thank you!
