### ISSUE TITLE
Organize imports

### ISSUE THREAD

**Issue by courtneypattison** [DSpace/dspace-angular#336]
Maybe sorting and separating the imports like the [style guide suggests](https://angular.io/guide/styleguide#import-line-spacing) would freshen up the code :) I'm making a PR with the style seen in [Angular's location service](https://github.com/angular/angular/blob/master/aio/src/app/shared/location.service.ts): standard imports, newline, third party imports, newline, and then app imports all alphabetized. Just close this issue if you think it's silly!

**Comment by artlowel** [comment]
I don't think it's silly, but fixing this everywhere, without an automatic way to enforce these rules afterwards seems like a waste.

So I'd like to know how you did it (hopefully in an automatic way), that way we can add it to our recommended IDE settings, or create lint rules to check for it, to ensure all following PRs will follow these rules.

With the preview release coming up early next year, we have a few big PRs coming up, and merging #337 now would cause a huge number of merge conflicts in those PRs, for comparatively little gain.

So I'd put #337 on hold until right after the preview version has been released, fix all the merge conflicts then, and from then on make it a requirement that new PRs follow these rules (if we can automate it)

**Comment by courtneypattison** [comment]
I'm glad you're open to this change! I just used a Visual Studio Code extension [TypeScript Import Sorter](https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter) with a few adjustments to the rules:
```
"importSorter.sortConfiguration.customOrderingRules.rules": [
        {
            "type": "importMember",
            "regex": "^$",
            "orderLevel": 5
        },
        {
            "regex": "^@angular/",
            "orderLevel": 10
        },
        {
            "regex": "^[^.]",
            "orderLevel": 15
        },
        {
            "regex": "^[.]",
            "orderLevel": 30
        }
    ]
```
It allows you to do directory deep or on save sort. The sorting is easy to enforce with the [TSLint ordered imports rule](https://palantir.github.io/tslint/rules/ordered-imports/). I'd be happy to update the PR with whatever ordering rules you'd like at a time when there would be fewer merge conflicts.

**Comment by cwilper** [comment]
I'd like to see some ordering enforced too. I would favor rules that would at the very least let us set `ordered-imports` to `true` in tslint config, but I'd want to make sure that whatever rules are adopted, they are easy to adhere to for developers using various IDEs.

Fwiw, IntelliJ/WebStorm can automatically highlight and fix imports that are mis-ordered according to tslint config by suggesting changes in the editor. It also has "Organize Imports" that can alpha-order modules and the import list from each.
