### ISSUE TITLE
Item page sometimes fails to load

### ISSUE THREAD

**Issue by jaril1** [DSpace/dspace-angular#3425]
## Describe the bug
The Item page randomly gets stuck and doesn't load the content. The issue occurs for anonymous users in 8.x. I believe this is related to the implementation of the correction types (loading them).

## To Reproduce
This can be reproduced randomly e.g. by navigating several times between the Simple item page and Full item page.

<img width="1092" alt="DSpace screenshot 2024-10-11" src="https://github.com/user-attachments/assets/ac414f96-f902-4ea1-b76e-ad6cd28b7b48">

**Comment by jlipka** [comment]
Might be related to [#3584](https://github.com/DSpace/dspace-angular/issues/3584)
