### ISSUE TITLE
Communities created without a title cannot be accessed

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#343]
Currently the REST API demo has two communities with no name/title: https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/core/communities

These communities are listed on the Angular UI homepage with a blank name.  Since the name provides the link to that Community, there's no way to visit that Community (to either edit it or delete it).

The Angular UI should handle unnamed Communities/Collections/Items/Bitstreams by replacing the empty text with a standard (translatable) word like "Unnamed".

**Comment by alexandrevryghem** [comment]
Atmire would like to claim this issue. I will try to find all the places where this could potenitally happen and use the `DSONameService` instead to retrieve the name. I will also try and find all the other places where this fix needs to be applied for example on `/community-list`. There are a lot of usages of `.name` (they can all be found using `\.name[^a-zA-Z]`) so finding them, fixing them & fixing the tests will an estimate of 5 hours.

**Comment by tdonohue** [comment]
Sure, @alexandrevryghem .  Sounds good, I'll assign this to you then.  Before getting started, please make sure to verify that this bug is still valid (as it's many years old now, and it's possible that it may not be accurate anymore.)

**Comment by alexandrevryghem** [comment]
I checked and it's still broken on [demo7.dspace.org](https://demo7.dspace.org/home?tl.page=35) on the home page:
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/43750381/221704984-0fcaeda5-4be0-4298-9856-3952ae47de30.png">
On the community and collection page:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/43750381/221706071-c297e2a1-96be-42b2-a72c-e6339f3da528.png">
and more
