### ISSUE TITLE
Withdrawn item tombstone page

### ISSUE THREAD

**Issue by YanaDePauw** [DSpace/dspace-angular#346]
A page needs to be added to serve as a tombstone when the item is withdrawn. 

Currently the REST API returns a 401 Unauthorized when a withdrawn item is accessed by an anonymous user.  
So, this depends on a fix to https://github.com/DSpace/DSpace/issues/3245

Once this issue is fixed, a component should be added to render the tombstone page for a withdrawn item

**Comment by tdonohue** [comment]
Just realized this was never implemented.  Currently, if unauthenticated, you are sent to the login screen.  If authenticated (but not an admin) then a withdrawn item shows a "403 Forbidden" error (after login). No tombstone is given.

@artlowel : Assigning this to your team for analysis. If this is a "quick fix", then I think we may want to get it into 7.0 (low priority though).  If there's something missing on the REST backend, this may have to wait for 7.1.

**Comment by tdonohue** [comment]
Depends on https://jira.lyrasis.org/browse/DS-4456 (which is not yet fixed & needs recreation)

**Comment by artlowel** [comment]
This will take an estimated **4 hours**
