### ISSUE TITLE
[Configurable Entities] Replace the term 'entity' with 'item' in strings that come from the server

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#353]
#352 replaces the term 'entity' with 'item' everywhere in the UI, but there's still a few occurrences remaining, where the term needs to match what the REST API returns: 
- https://github.com/DSpace/dspace-angular/pull/352/files#diff-f01ac8e9341ce7cf64c31b7afa03eaadR210
- https://github.com/DSpace/dspace-angular/pull/352/files#diff-f01ac8e9341ce7cf64c31b7afa03eaadR239
- https://github.com/DSpace/dspace-angular/pull/352/files#diff-27e529a10130f34d5d41756dc136d8a7R14

**Comment by tdonohue** [comment]
Closing as obsolete. No longer needed.
