### ISSUE TITLE
Adding missing French translations

### ISSUE THREAD

**Issue by nimabehforouz** [DSpace/dspace-angular#3556]
Some French translations are missing in the fr.json5 file. I have identified some (e.g. "access-control-option-start-date", "access-control-option-start-date-note" and "item.edit.tabs.access-control.head", but still needs some work.
src/assets/i18n/fr.json5
![Screenshot 2024-10-24 155031](https://github.com/user-attachments/assets/4bea217a-b862-4909-8738-b13cb4f95f05)

**Comment by tdonohue** [comment]
@nimabehforouz : we rely on volunteers to maintain & update our translation files.  So, this will wait on a volunteer to claim it and update the French translation.  Please do let us know though if you are willing to send along an update (via a Pull Request) or know of someone else at your institution who is working on it.

Needs a volunteer.

**Comment by nimabehforouz** [comment]
@tdonohue Thank you Tim. I would like to claim it myself.

**Comment by pilasou** [comment]
Bonjour, @nimabehforouz, j'ai également identifié une grande quantité de libellés en plus de ceux sur la fonctionnalité des contrôles d'accès. Il y en a beaucoup pour le module ORCID et le "researcher profile" ainsi que pour les nouveaux services propre à DSPace 8 (COAR Notify, LDN service). J'avais également commencé à travailler sur les traductions du contrôle d'accès. Si cela vous convient, je peux laisser de côté la partie contrôle d'accès et continuer la traduction que j'ai débuté du Profil chercheur et d'ORCID, ainsi que nouvelles fonctionnalités DSpace 8. Merci!

**Comment by nimabehforouz** [comment]
Bonjour @pilasou. Oui bonne idée, je vais continuer à travailler sur les traductions du contrôle d'accès et on va organiser une rencontre pour en discuter. Merci!

**Comment by tdonohue** [comment]
Closing. Fixed by #3587.  Also ported to 8.x for the 8.1 release.
