### ISSUE TITLE
Lack of community/collection information when editing a person's access control

### ISSUE THREAD

**Issue by Andrea-Guevara** [DSpace/dspace-angular#3571]
## Describe the bug
When editing a person, in the people access control session, in the “Member of these groups:” table, the communities/collections column shows no information.

## To Reproduce
1. Log in as administrator.
2. In the sidebar, go to the access control area and then click on eperson.
3. Edit someone.
4. Notice that the table showing the groups the person belongs to doesn't show any information about the community/collection.

![eperson-form-component-table](https://github.com/user-attachments/assets/d9eccbaa-d7c0-4e97-b623-9e188cd12bfc)

## Expected behavior
The community/collection column should return some information about the community or collection to which this person has access.

## Related work
I analyzed the code, because in version 7.5 of dspace angular the table returns all the information correctly, but as of version 7.6 the community/collection column returns empty. And there really was a change in the code that made this happen.

![eperson-form-component-7-5](https://github.com/user-attachments/assets/64ff11fb-e3fe-4a0c-ac48-2cedfb761b3e)

![eperson-form-component-7-6](https://github.com/user-attachments/assets/86284e0c-2a87-470e-908e-cbdb7347c56d)

**Comment by Andrea-Guevara** [comment]
Hello @tdonohue, good afternoon!

I was wondering. Will this problem also be fixed in versions 7 and 8?

**Comment by tdonohue** [comment]
@Andrea-Guevara : as noted in this comment, I've asked for the PR to be backported.  It is not backported as of now, but I also hope it will be fixed in 7.6.x and 8.x.  https://github.com/DSpace/dspace-angular/pull/3585#issuecomment-2469184341

**Comment by Andrea-Guevara** [comment]
@tdonohue Thank you for clarifying :)
