### ISSUE TITLE
Major updates needed to the french translation file

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#3578]
## Describe the bug
No french translations are available for some major features available on DSpace. 

Mainly: 

- Researcher Profile
- ORCID module
- Access control
- Subscriptions
- COAR Notify
- LDN

**Comment by pilasou** [comment]
I am working on it, I hope to make a PR soon.

**Comment by tdonohue** [comment]
@pilasou : Some of these French translation issues were also submitted as #3556 by @nimabehforouz    So, the two of you may wish to coordinate to ensure your translation work doesn't conflict.
