### ISSUE TITLE
Cookie dialog has a strange text in current DSpace 8.1 Snapshot

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#3618]
## Describe the bug
The text to the cookie dialog changed in the most recent DSpace 8.1 Snapshot. It now says:
"Hi! Could we please enable some additional services for ? You can always change or withdraw your consent later.”
I cannot find this string or a reference to klaro since this change happened

![Screenshot 2024-11-06 at 19 44 52](https://github.com/user-attachments/assets/cfc593c7-fb5e-4c3e-b7e6-504b708efddf)

## To Reproduce
1. Clear your browser cache and go to https://demo.dspace.org or run a local out of the box frontend

## Expected behavior
I do not remember the old text, but it was a complete and more reasonable sentence. It should be reverted to the old text

**Comment by tdonohue** [comment]
Fixed by #3586, which is waiting on reviews/testers

**Comment by MW3000** [comment]
Oh, sorry I missed the existing Issue. I tested your fix in DSpace 8 in worked. We can probably close this as a duplicate?

**Comment by tdonohue** [comment]
@MW3000 : I didn't create an issue ticket. I just created a PR immediately.  So, we can leave this open, as I've already linked my PR up to it...that way this issue will auto-close when the PR is merged.

**Comment by tdonohue** [comment]
Closing, fixed by #3625 and #3626
