### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by br00tm** [DSpace/dspace-angular#3623]
Im trying to install via docker, but using an especific ip adress. And somehow is running an error, the Dspace UI keeps getting too long to up, and when its up, gets the 500 error, ive changed everything to this especific ip adress, but nothing works out

**Comment by tdonohue** [comment]
Closing.  This ticketing system is for bug reports & feature requests. Please use our support options for detailed support questions: https://wiki.lyrasis.org/display/DSPACE/Support

Regarding a 500 error, that's a common installation issue listed at https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-%22500ServiceUnavailable%22fromtheUserInterface

Finally, I do want to warn that we currently do NOT have a production-ready Docker installation for DSpace.  The Docker images are only guaranteed to be usable in development scenarios. See the warning at the top of our Docker README: https://github.com/DSpace/dspace-angular/tree/main/docker#readme

**Comment by br00tm** [comment]
So if i want to install it on docker, i need to do the full manually instalation, both front and back?

**Comment by br00tm** [comment]
So if i want to install it on docker, i need to do the full manually instalation, both front and back?

**Comment by tdonohue** [comment]
As I said, we do not have Docker installation instructions for DSpace at this time.  You are better off using the Support channels linked to in my prior comment.

You are also welcome to use our (development-oriented) Docker images as examples, but we cannot help in running them in Production at this time.  Again, see the note in the README which also says that: https://github.com/DSpace/dspace-angular/tree/main/docker#readme
