### ISSUE TITLE
Collection and Community homepages need redesign (look cluttered)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#365]
As noted in https://github.com/DSpace/dspace-angular/pull/360#pullrequestreview-206026095, with the addition of Browse By links (in a bulleted list), the Community & Collection homepages are beginning to look quite "cluttered".  

We should try to cleanup the design of these pages. It could be as simple as looking to better replicate the Mirage 2 design, e.g. http://demo.dspace.org/xmlui/handle/10673/1   But, other ideas are welcome as well.

**Comment by tdonohue** [comment]
Laura Henze at NYU has offered to claim this ticket & bring back some ideas also based on feedback they received in user interviews regarding current DSpace user experience

**Comment by tdonohue** [comment]
A small note on this redesign.  Because Community/Collection URLs no longer have the Handle as part of the path, we need to find a way to display the Handle URI for Communities/Collections in the page itself.

This is loosely related to #256 , which is the ticket about ensure Handle URIs redirect to the proper location in DSpace 7 (not yet implemented).  Handle URIs are already displayed on Item pages (as they were in DSpace 6 and below). We just need to determine a way to make them known for Communities/Collections in DSpace 7 (especially since many DSpace configurations are still Handle based, e.g. submission forms for Collections)

**Comment by lhenze** [comment]
Hi Tim, that makes sense.  I'll try putting the Handle link between the description (if any) and the list of subcommunities and collections, and we can discuss if it seems to have appropriate prominence there.

**Comment by tdonohue** [comment]
Closing, as this redesign occurred.  If further redesign is necessary, we can open new tickets for it
