### ISSUE TITLE
Roles are hardcoded in the UI

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#393]
We should put some more thought in to the way authorizations work.

The MyDSpace PR [added a RoleService and methods like isSubmitter, isAdmin, …](https://github.com/DSpace/dspace-angular/pull/384#discussion_r273979125), and then the client contains logic to decide if I'm role X, then I should do Y.

To me it makes a lot more sense to have the client not have a concept of roles at all, but have the REST API determine what the client can and cannot do. E.g. through the available HAL links (there is only an edit link if the user can edit the object), or using a way in which the client can ask: "can I perform action X?".

**Comment by mwoodiupui** [comment]
The further we can push this sort of decision down the layer stack, the easier it will be to make *consistent* decisions across the GUI and the various M2M interfaces.  We have had recurring problems with consistency in the past.

There may not be time to do that perfectly and completely, given our current schedule, but I think we should push access decisions down as far as is practical in the available time, and be careful to avoid making it difficult to move them even deeper into the stack later.

Anyway, more thought:  yes please.

**Comment by tdonohue** [comment]
Directly related to #242

**Comment by tdonohue** [comment]
Closing as resolved by #664 (and any other followup work elated to that)
