### ISSUE TITLE
Use npm shrinkwrap

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#40]
[shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) is a tool built in to npm that creates a json file with the versions of all dependencies, and their dependencies, currently installed.

You add this file to git, and all subsequent npm installs will use those exact versions of dependencies, instead of the latest version in each range.

This can help ensure that everyone is working with the exact same set of pacakges, and that no issues can arise simply because a new version of a package we depend on was released.

The downside is that after you install add a new dependency to package.json, you have to run `npm shrinkwrap` again. If you're not adding new dependencies nothing changes

**Comment by artlowel** [comment]
I found out that since npm version 3 you do not need to run `npm shrinkwrap` again after installing a new lib. It happens automatically.

**Comment by wwelling** [comment]
Does shrinkwrap automatically update after changing dependency version? Is there any benefit over specifying specific versions in package.json? Even if not, it seems safer for community development. Can we get readme updates on this?

**Comment by artlowel** [comment]
It only updates automatically if you use commands to update package.json, not if you change dependencies in the file manually. So, you're right that's something that should be included in the readme.

The advantage over using specific versions in package.json is that it locks down the versions of dependecies of dependencies as well. Adding all those to package.json would make it hard to interpret.

**Comment by wwelling** [comment]
That makes sense. Thanks.
