### ISSUE TITLE
Overriding REST HOST issues

### ISSUE THREAD

**Issue by terrywbrady** [DSpace/dspace-angular#403]
The docker configuration in https://github.com/DSpace-Labs/DSpace-Docker-Images/blob/master/docker-compose-files/dspace-compose/d7.override.yml works well for a localhost execution in Docker.

While attempting to run this in Docker on AWS, I noticed 2 bugs
- Changes to the DSPACE_REST_ variables seemed to have not effect
- The server did not run in DEV mode without an atual environment.dev.js file

@pnbecker , FYI

**Comment by tdonohue** [comment]
Closing. This is fixed as we use DSPACE_REST env variables in our travis configs right now. https://github.com/DSpace/dspace-angular/blob/master/.travis.yml
