### ISSUE TITLE
Empty tooltips on item pages

### ISSUE THREAD

**Issue by LotteHofstede** [DSpace/dspace-angular#404]
Whenever a tooltip does not have any content, it should not be shown at all when hovering over a link on an item/entities detail page.

Example of what empty tooltips look like at the moment: 
![image](https://user-images.githubusercontent.com/11385967/58094665-88804600-7bd1-11e9-8889-129ac3a2dfb7.png)

Example page on the demo server: 
https://dspace7-demo.atmire.com/items/4041630a-af2c-46d7-b1be-a4c1ef77e5b5

**Comment by pgmArvo** [comment]
Greetings.
After hovering over the links in the example page provided in the demo i didn't show any tooltip.
Did i miss something or is this issue solved?

**Comment by tdonohue** [comment]
This appears solved to me as well. Closing
