### ISSUE TITLE
No paging for long community lists.

### ISSUE THREAD

**Issue by tantz001** [DSpace/dspace-angular#405]
On community pages with more than 20 "Communities of this Community", there is no way to navigate beyond those first 20.  No paging options, no previous nor next buttons.  See the screenshot.  There are more than 150 sub-communities here.

![Screen Shot 2019-05-21 at 9 18 24 AM](https://user-images.githubusercontent.com/10133817/58104249-19dbc200-7baa-11e9-9870-0e0c0254cdaa.png)

**Comment by alexandrevryghem** [comment]
Closing this issue as this was already implemented in #505
