### ISSUE TITLE
BrowseDefinition should be split up in to normalized and client-side models

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#436]
BrowseDefinition is used both as the model for the rest response, and as the model to use in the rest of the angular app.  For every other model these are split in to two classes.  Even if they would be identical, for consistency's sake it would be better to split BrowseDefinition up as well.

**Comment by tdonohue** [comment]
@artlowel : I'm reviewing old tickets. Is this still valid?  I suspect we can close as I believe we refactored out all "normalized" object models, correct?

**Comment by artlowel** [comment]
We have. I'll close this
