### ISSUE TITLE
Text colors: increase contrast for link colors and .text-muted

### ISSUE THREAD

**Issue by lhenze** [DSpace/dspace-angular#449]
For WCAG 2.0 compliance,  text needs to have "at least 4.5:1" contrast.

Link color ($cyan) is currently #2790B0;  a higher contrast option is  **#007C88**

Text-muted is currently #2790B0; a higher contrast option is **#757575**

**Comment by pgmArvo** [comment]
Changuing and checking contrast color to comply WCAG 2.0's requirements.

**Comment by lhenze** [comment]
I made a "work in progress" PR because I wasn't sure the best way to make those changes.  
In particular, where the text-muted was defined, and if we we to look at the color scheme holistically, or individually darken colors as needed. 

https://github.com/DSpace/dspace-angular/pull/450/commits/c23814e7b7def20b75b1e7e75efc064687d8e8e9

**Comment by pgmArvo** [comment]
Before seeing your message did my own changues.
They are very similar to the ones of your commit, but, in my opinion, more suitable to the structure of the project.
Should I make my own pull request?

**Comment by lhenze** [comment]
Please do; I am still learning about the structure of the project and it would be great to see a different approach.

**Comment by tdonohue** [comment]
Closing, this is replaced by #1149.  So, this old ticket is a duplicate.
