### ISSUE TITLE
Login action always redirects to homepage

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#451]
This ticket duplicates an old issue in DSpace 6: https://jira.duraspace.org/browse/DS-570

As noted by @bram-atmire in the latest comment on that old ticket, the Angular UI also has this behavior.  When you login, you jump back to the homepage.

Here's how to reproduce:
1. Browse to a Community, Collection or Item (doesn't matter which)
2. Click "Log In" and fill in username & password
3. Rather than staying on the page you are on, you will jump back to the homepage.

Expected behavior is that, after logging in, you should remain on whatever page you are currently on.

**Comment by pgmArvo** [comment]
I'm currently trying to solve this bug. I will report if I make any progress.

**Comment by mspalti** [comment]
This bug was fixed in this PR:

https://github.com/DSpace/dspace-angular/pull/467
