### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#47]
Create a component for the footer. Take a look at the prototype for [an example](https://github.com/DSpace-Labs/angular2-ui-prototype/blob/master/src/app/app.component.ts). Note that for the prototype it was part of the AppComponent and never refactored in to its own component.

Use the same content as the prototype

Automatically set the end-year in the copyright message to the current year. That way people don't need to remember to update that i18n message every year. Angular's built-in [DatePipe](https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html) could be useful for this

Make it stick to the bottom [using flexbox.](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/)

As it is a single-use component that is only referenced in AppComponent's template, it belongs in the [CoreModule](https://angular.io/styleguide#!#04-11). Create that module if it doesn't exist yet.

**Comment by atarix83** [comment]
It's possible to fix footer to the bottom with applying a simple CSS styles. Whether to use flexbox is not preferred I think we should avoid the use of it.

Let me know what do you think.

**Comment by artlowel** [comment]
I don't think we should avoid flexbox any longer.
[caniuse.com](http://caniuse.com/#search=flex) says `display:flex` is supported down to IE10 which should be more than enough backwards-compatibility

But if you have a CSS2 solution that works as well the flexbox solution and isn't based on a hack (such as adding 10000px of padding-bottom and -10000px of margin-bottom) that's fine as well.

**Comment by wwelling** [comment]
I suggest using ```display: table```

such as

```
body,
html {
  height: 100%;
  margin: 0;
  padding: 0;
}

app {
  display: table;
  width: 100%;
  height: 100%;
  overflow-x: hidden;
}

main {
  display: table-row;
  table-layout: fixed;
  height: 100%;
  padding-top: 15px;
}

footer {
  display: table-row;
  width: 100%;
  text-align: center;
}
```

**Comment by wwelling** [comment]
IE10 is only partial support of flexbox. As it turns out this partial support does not support display flex for sticky footer.

**Comment by atarix83** [comment]
well, I've applied [this solution](https://codepen.io/pirrera/pen/BzLbC) and It seems to work properly also on microsoft edge emulating IE10

**Comment by artlowel** [comment]
IIRC we've used a flexbox based sticky footer that worked on IE10 in a project recently. I'll see if I can find the details.

I'd also rather avoid `display: table`. It affects how other css rules inside of it work.
It no longer becomes possible to use text-overflow without setting an explicit width to a container for example. That's problematic in a responsive UI.

**Comment by artlowel** [comment]
@atarix83 The problem with that solution is that you need to provide a fixed height for the footer in pixels. But if we can't use flexbox it may still be the best solution.

**Comment by wwelling** [comment]
Wrapping the router-outlet in a bootstrap container-fluid restores all the responsiveness and should avoid the affects on other css you described @artlowel

**Comment by atarix83** [comment]
of course I can use flexbox, I thought that was a simple solution, but I didn't think the problem of having a fixed height

**Comment by artlowel** [comment]
>IIRC we've used a flexbox based sticky footer that worked on IE10 in a project recently. I'll see if I can find the details.

I found the project, and indeed, the footer isn't sticky on IE10. It is on IE11, edge, and other browsers. But it doesn't break anything in IE10 either, it's just a regular footer. So honestly that's fine by me, especially at this stage, and for something that only impacts the look, not the usability.

In my opinion we should use the optimal way of solving a problem in CSS without worrying too much about workarounds for older browsers. If a CSS property is supported by the last two versions of all major browsers (you can verify that on [caniuse.com](http://caniuse.com/). Note that for Microsoft that means Edge 13 and 14, and _not_ IE) we should be able to use it.

If it turns out something is too much of a problem, we can always add a workaround later.

**Comment by atarix83** [comment]
I've applied flexbox solution but there is a drawback. 
flexbox use to add a CSS class to body and to do this I had to change the `app.component`'s selector to `body`.
This generate a warning on build, because  the selector of a component should be named kebab-case.

Do you know another way to add a class to body without changing selector?

**Comment by artlowel** [comment]
Renaming the component should never be the solution to a CSS problem. 
But are you sure it has to be `<body>`? 
I'd bet that they actually mean "the wrapper around header, main content and footer" and that it'll work with any old DOM element.

**Comment by atarix83** [comment]
Unfortunately i tried only with a wrapper, but it seems to work only with that class applied on body

**Comment by artlowel** [comment]
How about something like [this](http://codepen.io/anon/pen/LxMqRG)
