### ISSUE TITLE
Refactor existing code to match Module style guide

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#48]
The style guide has been updated with recommendations about how to use modules: https://angular.io/styleguide#!#04-09

- The recommendation is now to create a separate module for each feature
	- The main reasons are because it creates better separation of concerns
	- makes it easier to lazy load them
	- makes it easier to test
- They also recommend a SharedModule
	- that should contain components and pipes that are used all over the application
	- we already have this, but it also contains services, and the recommendation is now to add services to a different globally shared module:
- And a CoreModule
	- that should contain Singletons that need to be shared throughout the application -> services
	- The module helps to ensure all your services are actually singletons. They should be added to the provider's list of only the CoreModule, and not anywhere else
	- It should also contain other single use components, that are only used in the appComponent. a sidebar-component or a notification component would be examples of those
	- We don't have a CoreModule yet
	- Note that not every service needs to be in this module, if it's only need across a subset of the app, move it up to the first module that encompasses them all, not further

Refactor the current code to fit this structure.

**Comment by tdonohue** [comment]
This appears to possibly have been done in #152?

**Comment by artlowel** [comment]
Yes, this can be closed
