### ISSUE TITLE
The trusty travis image is getting old

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#481]
We currently run our travis tests on the trusty ubuntu image. While trusty is an LTS version, it no longer receives standard support and will only receive important security updates since April 2019 until April 2022. We've already had [some issues](https://github.com/DSpace/dspace-angular/pull/480) due to this. We'll likely have more in the future.

**Comment by tdonohue** [comment]
Closing as fixed by https://github.com/DSpace/dspace-angular/pull/480

**Comment by tdonohue** [comment]
Whoops, closed too soon.  #480 is a simple workaround for now.  Will leave this open until we can *update* our Travis settings to use a newer ubuntu image.
