### ISSUE TITLE
Dropdown UI Component endlessly reloads value-pairs

### ISSUE THREAD

**Issue by Flusspferd123** [DSpace/dspace-angular#482]
The dropDown implementation has got a little bug. E.g. the language dropdown:  When scrolling the list it never reaches the end of the list. (Configured as a value-pair in submission-forms.xml) Instead it keeps reloading the list and therefore the user gets the impression that he has not seen all values

**Comment by tdonohue** [comment]
As noted in a duplicate ticket (#668) by @Aziris, this bug also appears in the Type dropdown.  Here's the details on reproducing: 

1. Log in to be able to create new item
2. Go to create new Item page and observe the "type" dropdown
3. Once you open it and scroll down, new items get added endlesly

**Comment by atarix83** [comment]
This issue has been resolved after authority refactoring https://github.com/DSpace/dspace-angular/pull/751 and can be closed

**Comment by tdonohue** [comment]
Closing.  Thanks for the note, @atarix83 !  You are correct, this was fixed in beta4 by #751.
