### ISSUE TITLE
performance issues on submission 

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#487]
This issue is related to PR #432 
When submitting with a large number of collection available, after the page is fully loaded a slowdown occurs with the interaction of the form.

This is due to the way the collection list is retrieved when submission page is loading.
Even if the submission page seems to be loaded, the [submission-form-collection.component.ts](https://github.com/4Science/dspace-angular/blob/95d1495397d8af7fe2ebd3dd5b5fb9d4595de962/src/app/submission/form/collection/submission-form-collection.component.ts#L65) is still retrieving the collection list by using [getAuthorizedCollectionByCommunity](https://github.com/4Science/dspace-angular/blob/67b09e379427810e44472591a6c15e5dc1846aaa/src/app/core/data/collection-data.service.ts#L51). Unfortunately to have the entire collection list we need the entire community list, but this cause an extremely expensive REST call (because of fetching all logos and licenses) that is the cause the delay reported.

A possible solution should be to add, on REST side, a parent link to the collection model, in order to retrieve parent community information from collection

**Comment by tdonohue** [comment]
This issue is dependent on this REST API ticket: https://jira.lyrasis.org/browse/DS-4504

Once there's a way in the REST API to provide a list of Collections you can submit to (in a performant way), then we will need to update *both* the (optional) Collection dropdown in the submission UI as well as the Collection selector in the Admin side menu.

**Comment by heathergreerklein** [comment]
Closing, as fixed by https://github.com/DSpace/DSpace/pull/2771
