### ISSUE TITLE
Run all tests at once

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#49]
It would be useful to be able to run all tests at once using a single command. For example to use in Travis CI. However it should still be possible to run them separately during development.

I would also create a pree2e script that triggers webdriver:update to ensure protractor doesn't fail because webdriver:update hasn't run.

**Comment by sourcedump** [comment]
Hello!
the 'webdriver:update' it's a one shot command and you don't need to run it each time.
Moreover if you have a remote Selenium server you don't need to run it at all.
Are you sure you want to use it in a 'pree2e'?
When you say 'all tests' you mean unit test and e2e together?
Thanks

**Comment by artlowel** [comment]
Yes, when I say 'all tests' I mean both unit tests and e2e tests.

`webdriver:update` downloads its dependencies to the node_modules folder. If you check out a branch with a different package.json, it's best to remove that folder (run `npm run clean`) and run `npm install` again to ensure you're working with the correct set of packages for that branch. Afterwards, if you want to run the e2e tests, you have to run `webdriver:update` again. As you can imagine, when reviewing PR's this happens all the time.

Besides, if you run `webdriver:update` when it's not needed, it doesn't do anything and just exists. Running it every time doesn't do any harm.
