### ISSUE TITLE
Collection Section fozen on item submit page

### ISSUE THREAD

**Issue by JuliusGruber** [DSpace/dspace-angular#492]
When i try to add an item after the first login i get the following error. Also the collection-section widget is frozen not leting me choose another collection.

`core.js:1673 ERROR TypeError: Cannot add property searchParams, object is not extensible
   at CollectionDataService../src/app/core/data/collection-data.service.ts.CollectionDataService.getAuthorizedCollectionByCommunity (collection-data.service.ts:68)`

![collectionSection](https://user-images.githubusercontent.com/2971611/65785942-da277700-e155-11e9-8a9d-914bf2a47c9d.PNG)

**Comment by tdonohue** [comment]
@JuliusGruber noted on Slack that these bugs seemed to appear after #432 was merged.

The first error is new, while the collection-section widget being frozen sounds like this previously noted performance error: #487 

@atarix83 : could you take a closer look at this?

**Comment by atarix83** [comment]
@tdonohue 
I think this problem is no longer existing

**Comment by tdonohue** [comment]
You are correct, @atarix83 . This is an outdated bug that has since been fixed.  Closing
