### ISSUE TITLE
Question: should components be stateless?

### ISSUE THREAD

**Issue by antoine-atmire** [DSpace/dspace-angular#58]
Using redux means the application state is stored in only one place.
This means to me that components should not introduce their own state variables, but rather access the state via functions.

State variables add unnecessary complexity. They can get out of sync if they aren't managed properly - which is exactly what redux wants to avoid. With functions you're always sure to get the current state.

To illustrate what I mean I made a commit where I "fix" the header component.

https://github.com/antoine-atmire/dspace-angular/commit/1e9550dfc6939f6070416537d3cc4ca8c8f9d0da

**Comment by artlowel** [comment]
>They can get out of sync if they aren't managed properly

Can you think of an example? As far as I can tell, as long as the variables in the components are observing the state in the store, and not using any other source of information, it's just convenience, and not really a problem. 

I checked the ngrx example project, to see how they handle it, and they also seem to use these local observables. e.g. https://github.com/ngrx/example-app/blob/master/src/app/containers/find-book-page.ts#L21

**Comment by antoine-atmire** [comment]
I don't think the observable will get out of sync. I'm just concerned someone might inadvertently reassign the field variable and get unexpected results then. This should be unlikely, as the way to update the state of the app is not by reassigning variables. If possible I'd make the fields final/constant, but converting them to functions would also eliminate the problem. 
I guess it's a choice of style. Unless there's a difference in reusing rxjs observables as opposed to getting a new one from the store everytime. (probably not)

**Comment by antoine-atmire** [comment]
I agree it's a good idea to stick with the same style as the ngrx example project.
