### ISSUE TITLE
@types/lodash version higher than 4.14.50 causes build errors

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#59]
lodash is a transitive dependency of this project. The latest versions are no longer compatible with TypeScript versions < 2.1. At the moment this project uses TypeScript 2.0.10.

The build errors you get as a consequence look like this:
```
    ERROR in [default] /Users/art/tmp/dspace-angular/node_modules/@types/lodash/index.d.ts:244:12
    Duplicate identifier '_'.

    ERROR in [default] /Users/art/tmp/dspace-angular/node_modules/@types/lodash/index.d.ts:244:15
    Cannot find namespace '_'.

    ERROR in [default] /Users/art/tmp/dspace-angular/node_modules/@types/lodash/index.d.ts:246:24
    Cannot find name 'Partial'.

    ERROR in [default] /Users/art/tmp/dspace-angular/node_modules/@types/lodash/index.d.ts:248:18
    Duplicate identifier '_'.

    ERROR in [default] /Users/art/tmp/dspace-angular/node_modules/@types/lodash/index.d.ts:366:38
    Cannot find namespace '_'.
…
```

Using npm-shrinkwrap should prevent this problem for now. 

If you add a new dependency and have to recreate npm-shrinkwrap.json you may run in to this again. If that dependency doesn't depend on @types/lodash > 4.15.50 but uses a range, you can safely set the @types/lodash version back to 4.15.50 in npm-shrinkwrap.json manually.

**Comment by wwelling** [comment]
You can also add this as a dev dependency and re shrink wrap: ```"@types/lodash": "ts2.0"```

**Comment by artlowel** [comment]
`@types/jasmine` has the same issue. I had to add "@types/lodash": "ts2.0" and "@types/jasmine": "2.5.41" as dev dependencies in #66 
We need to remember to remove those when we upgrade to TypeScript 2.1
