### ISSUE TITLE
Name appears as "undefined undefined ()" immediately after login

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#599]
Reproducible on demo site (https://dspace7-demo.atmire.com/) & current `master` (as of today).

Immediately after login, if I click on the user icon in the upper right, I see this
![undefined-eperson](https://user-images.githubusercontent.com/483997/75568844-a78ded00-5a19-11ea-8c01-5915f9342422.png)

If I browse around to other pages (e.g. /submit), eventually the correct name and email will appear.  So, it seems like it just initially doesn't load properly.

**Comment by abollini** [comment]
just a guess but the /login endpoint embedd the eperson, so this could be another place where projection full is required.
BTW: it would be useful to note in a jira ticket all the place where we are forcing projection full in the angular side as I would like to have an explicit IT with such option on the REST side so to avoid in future to break things accidentally
