### ISSUE TITLE
Edit Item - Manage Resource Policies / Roles

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#601]
Edit Item - Manage Resource Policies / Roles
https://docs.google.com/spreadsheets/d/1NTJ_ZZL2J_q0XbUqTesVxztOVmDOj9-RG57krKZjWbs/edit#gid=0 (row 28)

- Add a link to the item policies page to the item status tab
- Create the policies page component
- Show the current policies for the Item, and each bundle and bitstream within the item
- Add the ability to edit or remove each exiting policy
- When showing groups, add a link to their edit group page
- Add the ability to add a new policy for the item and each bundle and bitstream within the item
- Add methods to the ItemDataService, or a dedicated PolicyService to retrieve all policies for an item grouped by bundle and bitstream
- support CRUD for policies → you should be able to reuse DataService code for this

**Comment by tdonohue** [comment]
Fixed by #645
