### ISSUE TITLE
Need alternative link index to make use of embeds

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#626]
Now that support for the embed params is merged on both the [rest](https://github.com/DSpace/DSpace/pull/2670) and the [angular](https://github.com/DSpace/dspace-angular/pull/588) side, I've noticed that in many cases it gives us no advantage.

For example the logo on a collection is linked as `/collection/${uuid}/logo`. When the server embeds that logo bitstream, the UI currently indexes it under its self link: `/bitstream/${uuid}` and the link of the request that it came with: `/collections/${uuid}`

Later when we retrieve `/collection/${uuid}/logo` the UI doesn't know we already have that logo cached because it isn't indexed that way, so it is requested again. Only after this second request can we find it under `/collections/${uuid}/logo` because this time we did request it directly.

So we need an additional index to map alternative links for cached objects to their self link.

We need to take this index and the request index in to account when updating links as well: e.g. if you update the bitstream format for a bitstream, the self link for that format will change, but the link from the bitstream to the format won't. It will still be `/bitstream/${uuid}/format`. So these alternative links need to be removed from all indexes (request and the new index proposed above) when the relations between objects change.

By my estimate, adding the index, ensuring it is updated when relevant, used whenever we retrieve something, and ensuring it and the request index are cleared when relations change will take 16 hours to implement.

**Comment by tdonohue** [comment]
@artlowel : I've tentatively added this to beta3 in our spreadsheet: https://docs.google.com/spreadsheets/d/1NTJ_ZZL2J_q0XbUqTesVxztOVmDOj9-RG57krKZjWbs/edit#gid=0
