### ISSUE TITLE
Delete of an item doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#630]
When from the item's delete page trying to permanently delete item nothing happens.

![Schermata da 2020-03-23 09-51-51](https://user-images.githubusercontent.com/2486489/77299210-691fe100-6cec-11ea-8482-4f06f24a3e2f.png)

Moreover when an item isn't an entity, I noted that a request fails while delete page is loading  : 
`http://localhost:8080/server/api/core/entitytypes/0`

**Comment by tdonohue** [comment]
I've verified this as well. It doesn't work on `master` as of May 11 either.  Might be possibly related to #662 (or the same developer could tackle both).
