### ISSUE TITLE
Cache should be authorization aware

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#635]
During the test of the PR: https://github.com/DSpace/DSpace/pull/2707#pullrequestreview-382744007 @benbosman as noted that after login as a privileged user the page was not automatically updated to show the additional communities/collection that was available to such user.

This indicate a more general issue with the current angular cache / component refresh mechanism as it is expected that many components visualize data that can vary when an user is loggedin / logged off.
The quicker fix could be to force a reload of the page when a user loggedin

**Comment by artlowel** [comment]
Yes the solution should be to do a hard refresh after authenticating and storing the token in the cookie. This already happens when you log out, it makes sense to also add it when you log in.
