### ISSUE TITLE
Creating new community and collection is not working on the angular-ui using the beta1 version of DSpace 7

### ISSUE THREAD

**Issue by kanasznagyzoltan** [DSpace/dspace-angular#639]
After a fresh installation of DSpace 7 Beta 1 I could not create a community or a collection using the angular ui frontend. I am using the frontend with an admin user created by the dspace console application.

When I click on the create a new top-level community button i got this error message in the Crome console bar
![image](https://user-images.githubusercontent.com/32355628/78078319-3cce2980-73aa-11ea-86f9-fe72d5349c57.png)

When I am trying to create new collection i got this error message also in the Chrome console
![image](https://user-images.githubusercontent.com/32355628/78078451-83238880-73aa-11ea-92e1-2c48238b5329.png)

**Comment by tdonohue** [comment]
This bug has been fixed by #640 (which was just merged)
