### ISSUE TITLE
Force the browser not to use a cached html page after the user changes

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#654]
PR #653 adds a feature where you can impersonate another user as an admin. When you impersonate a user, there will be a hard refresh, to ensure no state from the admin user is kept while you're impersonating. Likewise, when you stop impersonating, there's a hard refresh.

An unresolved issue with this PR is that the browser can cache the html rendered on the server for the user you were impersonating. An example of that is the user dropdown in the header. If your browser's cache is enabled, it will still show the user you were impersonating even after you've stopped.

I can think of two ways around that: whenever we do these authentication hard refreshes, we can pass a unique GET param, e.g. the current time in milliseconds, to force the browser to retrieve the html from the server again. The downside of that is that the user will see that random param in the url briefly. It will disappear when they go to another page.

Alternatively we could configure our express server to instruct clients not to cache html pages. That's not as far-fetched an idea as it may seem at first, because the bulk of the payload of our app is in JS files, and for authorized users it is probably best that they never cache it, as the server needs to generate the html based on up to date info. However the downside is that it means it won't be cached for anomymous users either. 

For clarity, I'm talking about the response headers that determine caching behavior on the client side. So this isn't about the case where different clients request the same page and we can optimize the server performance by caching it on the server, but rather where the same client requests the same page multiple times and their browser can optimize performance by caching it locally.

**Comment by atarix83** [comment]
@artlowel If I properly understood, the problem occurs because we hard refresh the page after logout. 
I think that another possible and simpler solution could be to avoid the hard refresh of the page and to simply reset the state on logout. I found a simply way to do that https://medium.com/@moneychaudhary/how-to-reset-the-state-or-clear-the-store-on-logout-in-ngrx-store-d2bd6304f8f3
Maybe there could be some side effect if we didn't implemented our states properly (although I don't think that's the case), but I think it's the right way to go.
Let me know what do you think about that.

**Comment by artlowel** [comment]
@atarix83 I tried it out, and while it works to clear the store, it breaks a number of features that expect certain things to be initialized inside the store (e.g. the menu will be empty, as it's populated by having pages to add menu options when they load for the first time). To do it this way, we'd also need to reinitialize everything after clearing the store.

So I came up with a variation on the random number solution i proposed above that's a little more robust in my opinion. I added a `/reload/:timestamp` route that redirects to the homepage. After a logout I redirect to that instead. That page can't be cached, so the browser is forced to fetch it again from the server, but the user is immediately redirected to `/home` so that random number isn't in their URL for more than a fraction of a second.

You can see this in action in #653 

For me this solves the issue, so I'm going to close the ticket here. If anybody disagrees, feel free to reopen.
