### ISSUE TITLE
Authentication issue when SSR is disabled

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#655]
This issue occurs only when SSR is disabled.
Once you are logged in and refresh page then you are no longer logged in.

**Comment by artlowel** [comment]
I think this is a duplicate of #428 or at least related.

I've looked in to this before, and I think it is an issue with the CORS config on the rest side. The reason it does work with SSR is because the node server doesn't enforce CORS rules.

**Comment by atarix83** [comment]
closed because duplicate #289
