### ISSUE TITLE
Edit item's metadata doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#662]
After editing an item's metadata, from item edit page, an error occurs when trying to save changes so they are not premanently saved on rest side

![Schermata da 2020-05-11 10-29-13](https://user-images.githubusercontent.com/2486489/81540860-92670000-9372-11ea-8b2c-7c3bfb52f3e6.png)

**Comment by tdonohue** [comment]
I am seeing this same bug. After pressing the Save button, no request is sent to the REST API. Instead, the browser's console shows a `ERROR TypeError: Cannot read property 'key' of undefined`.  This error is repeated each time you press the Save button.

**Comment by lomadi** [comment]
Maybe this is related to the bug, that the "key" of the metadata field ist wrong (at least this happens when the metadta field is generated by the UI). The cause is the inconsistent usage of "" and null.
