### ISSUE TITLE
Support for checking user permissions via /api/authz/features REST endpoint

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#664]
Per discussion in https://github.com/DSpace/dspace-angular/pull/653#issuecomment-626636737, we realized that the Angular UI currently does not support calling/caching feature-based authorizations.

This initial ticket should just involve implementing a way to easily check feature-based authorizations using the `/api/authz/features/` endpoint.  More specifically, select 1-2 features currently implemented on that endpoint and ensure permissions can be checked against in the appropriate area of the Angular UI (e.g. the "LoginOnBehalfOf" feature should enable/disable that button for Administrators, or the "AdministratorOf" feature should enable/disable the Admin sidebar based on whether you are an AdministratorOf the Site object.)
 
* REST Contract: https://github.com/DSpace/Rest7Contract/blob/main/features.md

This initial ticket should *not* attempt to implement all feature checks in the Angular UI.  Instead, after the first 1-2 are implemented (& merged), additional ticket(s) should be created to address the list of other features.

**Comment by artlowel** [comment]
For this first task I propose we:
- Implement services and models for the features and authorisations endpoints
- toggle the visibility of the impersonate button based on the `loginOnBehalfOf` feature
- Create an AdminGuard based on the `AdministratorOf` feature on the site object and use it for the admin module routes
- Also use the `AdministratorOf` feature on the site object to toggle the visibility of the menu options for the admin module

This will take an estimated **16h**

**Comment by tdonohue** [comment]
Per last week's DSpace 7 meeting, once a PR exists for this ticket it should be assigned to @atarix83 and @tdonohue .
