### ISSUE TITLE
Issues with the edit community and collection pages

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#666]
### 1. No PATCH Support
Since the `DataService.update()` method switched from PUT to PATCH requests, editing a community or a collection no longer works properly. The shared edit component should be fixed to support PATCH.

### 2. Adding or changing the logo doesn't always work.
There are also some irregularities when adding or changing the logo for a collection or community, although they may be solved automatically if we fix patch properly

### 3. Edit no longer selects current collection/community by default
If you open the edit menu from the sidebar on a community or collection page, that specific community or collection is no longer selected by default

### 4. Editing a Community, Collection or Item doesn't handle errors properly
See #665 

It makes sense to fix these all in one go. I estimate that will take about 10 hours.

**Comment by tdonohue** [comment]
Closing as fixed by #701
