### ISSUE TITLE
"Recently Added Items" doesn't exist on homepage & community pages

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#667]
Per a discussion in Slack, it was noted that the "Recently Added Items" (or Recent Submissions) listing doesn't appear on the homepage in the Angular UI.  Instead, they only appear on Collection homepages.

In v6 XMLUI, this feature exists on the homepage and lists the recently added items across the entire repository.  In v6 JSPUI, this feature does *not* exist on the homepage.

So, currently the Angular UI acts more like the v6 JSPUI in this manner.  While I'm not against us leaving it that way, I do not recall whether this was a formal decision.  Therefore this ticket is here as a reminder to revisit this feature. It's also a place for others to add feedback on which behavior (JSPUI vs XMLUI) they prefer to see in the Angular UI.

**Comment by olli-gold** [comment]
We are using this feature on JSPUI (DSpace CRIS 5.x) and I would like to have it in DSpace 7 on Angular UI.

**Comment by tdonohue** [comment]
Related ticket https://github.com/DSpace/DSpace/issues/3290

**Comment by DSquareTechnologies** [comment]
@tdonohue Do we want to replicate XMLUI's Recent Submission functionality in 7? Team here is working on the same and inputs will be helpful to align the development with the roadmap. Thanks

**Comment by DSquareTechnologies** [comment]
Hi Tim,

Yes, we have started working on this item and got some success already. 
Next two days are bank holidays here and team will be back on Monday. 
Let me get them together and arrange for next steps.

Regards,

Narendra

**Comment by DSquareTechnologies** [comment]
Hi Tim,

Here are few screenshots of Recent Submissions added on the Repository 
and Community's homepages. "View more" option like version 6 to be 
added, or better would be to add pagination like it appear under the 
community list on the home page.

What should be our next steps?

Thanks,

Narendra

**Comment by DSquareTechnologies** [comment]
![community_page](https://user-images.githubusercontent.com/6321834/149808741-ea17a5af-68c4-40aa-93cf-4f0dbe45fa2e.png)
![home Page](https://user-images.githubusercontent.com/6321834/149808746-367416fa-98a3-4eb2-93c9-3624207526d4.png)

@tdonohue Looks like screenshots did not come in the above communication. Attaching them here.

**Comment by DSquareTechnologies** [comment]
@tdonohue here is the updated Recent Submissions section with pagination.
![Community Page_recent items_paginated](https://user-images.githubusercontent.com/6321834/150110444-87e9f7ca-c05f-4bd0-853f-954d7dcfd233.JPG)

**Comment by DSquareTechnologies** [comment]
Feedback during WG meeting 01/20/22
Need to separate out Recent Submissions from the community list. Following suggestions are received:
a. Pagination below the recent submissions section can be replaced with the "show more" and "Show less" links to make the list expandable. 
b. Another option can be as demonstrated in the https://wiki.lyrasis.org/pages/viewpage.action?pageId=204308676&preview=/204308676/204308678/DSpace-theme-home-white-flat.jpg

DSquare to work on the option and get back with the response.

**Comment by DSquareTechnologies** [comment]
> Feedback during WG meeting 01/20/22
> 
> Need to separate out Recent Submissions from the community list. Following suggestions are received:
> 
> a. Pagination below the recent submissions section can be replaced with the "show more" and "Show less" links to make the list expandable. 
> 
> b. Another option can be as demonstrated in the https://wiki.lyrasis.org/pages/viewpage.action?pageId=204308676&preview=/204308676/204308678/DSpace-theme-home-white-flat.jpg
> 
> 
> 
> DSquare to work on the option and get back with the response.

@tdonohue attaching the wireframe showing Recent Submissions with option of "Show more". Will attach one more option soon. 
![image](https://user-images.githubusercontent.com/6321834/151285232-474a9668-cccc-4297-9709-2e698b459911.png)

**Comment by DSquareTechnologies** [comment]
@tdonohue Here is option 2 having Previous and Next buttons under the Recent Submissions list. This is similar to the Previous and Next buttons available on the Browse by Title page. The thought process is to maintain uniformity with regard to user experience.
![Recent submissions_wireframe v2](https://user-images.githubusercontent.com/6321834/151300098-117bc6f1-03de-4a13-8f4b-77222b7c4e80.png)

**Comment by DSquareTechnologies** [comment]
Option 3 - Pagination similar to the Community section with a separator between community list and Recent Submissions.
![Recent submissions_wireframe v3](https://user-images.githubusercontent.com/6321834/151300313-cf24304b-708f-4ba0-b02f-f379e6c3011a.png)

**Comment by DSquareTechnologies** [comment]
Feedback during the working group meeting dated 02/03/2022

- Recent Submissions to have Load more button at the bottom of the list.
- The "Load more" button should be left-aligned.
- Upon clicking the Load more button, users will be redirected to the search results page, and items will list in descending order based on the submission date.
- Recent submissions count should be configurable. If the count = 0 then the section should disappear.

**Comment by alawvt** [comment]
Implemented with thumbnails in DSpace 7.4 on DSpace 7 Demo. 
Recently Added Items appear on the Home page,
<img width="1085" alt="DSpace7_4_recent_items" src="https://user-images.githubusercontent.com/13037168/195195767-08d48b12-e68f-495d-b599-4c23b75f295a.png">

But Recently Added Items do not appear on the Community page,
<img width="1160" alt="DSpace7_4_recent_items_not_on_community" src="https://user-images.githubusercontent.com/13037168/195196495-9d999034-d2a4-46bb-861d-684931b00421.png">

As before, they do appear on the Collection page.

@tdonohue, was this intentional to not enable them on the Community page?

**Comment by tdonohue** [comment]
@alawvt : This feature was donated work, and the developer only donated code to add Recent Submissions to the homepage.  So, we likely need a separate ticket about adding them also to the Community page, as that has not yet been done.  Would you be willing to create a ticket for us?  I suspect on the Community page they could be added quickly if they are similar to the Collection page... where "Recent Submissions" is listed in the "Browse" options of the Collection

**Comment by alawvt** [comment]
Yes, I have continued this with #1901. Thanks.
