### ISSUE TITLE
Angular with "Invalid Host header"

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#670]
I'm getting an issue related with the recent changes to angular (angular-cli). 
Configuration examples are sparse and my last configuration stopped working. I'm using Apache with mod proxy and now I'm getting "`Invalid Host header`". 
I saw that this "The problem occurs because webpack-dev-server 2.4.4 adds a host check" could be the issue. Any ideas, or missing configuration?

My src/environments/environment.dev.ts file has:
```
export const environment = {
  rest: {
    ssl: true,
    host: 'myhost.pt',
    port: 443,
    // NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
    nameSpace: '/server/api',
  },
  ui: {
    ssl: false,
    host: 'myhost.pt',
    port: 3000,
    // NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
    nameSpace: '/',
  },
```	

but I noticed that, running: `yarn start:dev`
the log presents me the message:
`** Angular Live Development Server is listening on localhost:4000, open your browser on http://localhost:4000/ **`

Am I missing something?

**Comment by paulo-graca** [comment]
@artlowel this is what I see when accessing it with a SSH tunnel for my server:

![image](https://user-images.githubusercontent.com/877488/81946203-fc8fd700-95f6-11ea-9e8f-2120ce80c077.png)

**Comment by paulo-graca** [comment]
This is what I see when accessing the server (with Apache and proxypass):
![image](https://user-images.githubusercontent.com/877488/81947128-1a117080-95f8-11ea-8536-486368cbce4c.png)

**Comment by paulo-graca** [comment]
It seems to me that the `ui` settings are being ignored.

**Comment by paulo-graca** [comment]
As @artlowel suggested to temporally solve this we need to change this line:
https://github.com/DSpace/dspace-angular/blob/4c480889201c0e127358e9df7b3a560779de7f43/package.json#L20

«You could change this to `ng serve --disable-host-check`  »

or «alternatively you could try to specify your host and port there, with `--host myhost.pt` and `--port 3000` but without `--disable-host-check`

**Comment by tdonohue** [comment]
@artlowel and @paulo-graca : Is this considered "fixed"?  Or do we need improvements to either our documentation or our default `package.json` in order to consider this "fixed"?

I'm just trying to determine what actions we need here, if any, to move this ticket forward.

**Comment by artlowel** [comment]
No, it isn't fixed yet. There are certain settings in the UI section of the environment that aren't taken in to account in all situations. @LotteHofstede will create a PR to fix this next week.

**Comment by paulo-graca** [comment]
This PR #677 solves this issue.
