### ISSUE TITLE
Facets are not sending required "operator" field to the REST API

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#672]
Related to https://jira.lyrasis.org/browse/DS-4500

Currently, when you select a facet (any facet) from the search page, the request to the REST API looks like this:

https://dspace7.4science.cloud/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&f.author=Marioni,%20John

However, as documented in the [REST Contract](https://github.com/DSpace/Rest7Contract/blob/master/search-endpoint.md#matching-dspace-objects-search-results), the `f.` filter field requires *two subparts*, a value and an operator:

`f.[filter_name]=[filter_value],[filter_operator]`

Currently the Angular UI *only* passes the `value` (in the above example an author name) and leaves out the `operator`.   So, to correct the above request, `,equals` should be appended as the operator, e.g.:

https://dspace7.4science.cloud/server/api/discover/search/objects?sort=score,DESC&page=0&size=10&f.author=Marioni,%20John,equals

This same behavior exists for *all filters*.  However, it's worse for authors, which have a comma separated first/last name, and therefore the first name is assumed (by the REST API backend) to be the `operator`.  Somehow this doesn't currently cause an error in the response, but as detailed in [DS-4500](https://jira.lyrasis.org/browse/DS-4500) it should be updated to return an error.

**Comment by abollini** [comment]
@tdonohue this looks to have been solved

**Comment by tdonohue** [comment]
Thanks for the note, @abollini . I agree, it does look solved in latest `main`. Not sure exactly when this was fixed, but obviously either in 7.0 or 7.1
