### ISSUE TITLE
Fix support for context sensitive menus

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#686]
Currently it isn’t possible to add or replace menu options just anywhere. The menu, its service and reducers were designed to be able to do that, but it never worked properly

One problem is that menu sections are currently initialized inside components. That way they can’t be inherited by subroutes. Like breadcrumbs they need to move to data on the route. While doing that however, we should still retain support for menu sections that are added and removed in code.

Another problem is that sectionComponents isn’t an observable, but updated inside a subscribe. That way, angular’s change detection won’t pick it up. It should ideally turn in to an observable derived from the one it’s subscribed to, or if that’s not possible turn in to a behaviorsubject and call `next()` on it inside the subcribe.

Estimated amount of effort: **14h**

Edit: increased estimate by 2h to account for moving the existing menu sections to their respective modules

**Comment by tdonohue** [comment]
@artlowel : Could you describe what features this might enable?  I do understand the general issue here and it seems worth fixing at some point, but I'm unsure how to prioritize as I'm not sure I understand the big picture here.  Is this to help us enable the ability to have different menus for non-admins (and therefore hide the admin sidebar altogether if you are not a full admin or Community/Collection admin)?

**Comment by artlowel** [comment]
It will allow both the admin and public menus to differ depending on the route. 

It will also allow us to specify menu sections and links in the module or the component they link to, rather than having to put them all in a single file. This will ensure that you can have optional modules in dspace that can be enabled or disabled without also having to add and remove menu sections in a shared file.

I wouldn't hide the sidebar if you're not a full admin, it will contain fewer options, but some will still be needed. We may want to consider giving it a different color depending on your access rights though

**Comment by tdonohue** [comment]
Because beta3 seems like it's getting quite full, I'll tentatively add this to beta4.
