### ISSUE TITLE
"Author" field in Submit page does not work

### ISSUE THREAD

**Issue by Aziris** [DSpace/dspace-angular#688]
Hi, there are 2 bugs :
1. Author, although marked as repeatable=true, is only available once, no + or add more option is present
2. Author lookup does not allow to effectively select any of listed authors, you can filter and mark them, but there is no "add" option, neither this selection has any effect if you close the lookup element

**Comment by tdonohue** [comment]
I'm able to reproduce both of these bugs on the demo site at https://dspace7-demo.atmire.com/

I believe this used to work, but there is no way to manually enter multiple authors & selecting multiple authors in the Lookup popout window is not saved back to the submission form itself.

**Comment by tdonohue** [comment]
This bug will be fixed by #541
