### ISSUE TITLE
Cannot create top-level Community

### ISSUE THREAD

**Issue by ttornyai** [DSpace/dspace-angular#706]
- Using current master (2020.06.16) of dspace-angular
- For backend, using dspace/dspace:dspace-7_x docker image (running in docker)

I set up a local dspace-angular with a backend, and the backend runs in docker. Either dspace-angular runs in docker or not, when I try to create a top-level community with dspace-angular, the submit button does nothing, and the following error is in the browser console:

![dspace-angular-console-log](https://user-images.githubusercontent.com/64202731/84746182-e38f9280-afb5-11ea-8f61-954821321f07.png)

The dspace backend log doesn't show any error message

**Comment by artlowel** [comment]
I can reproduce this issue.

It should be fixed by #701

**Comment by tdonohue** [comment]
Closing as fixed by #701
