### ISSUE TITLE
In dev mode, when authenticated, certain URLs redirect to the home page.

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#711]
If you're in dev mode, and you're logged in and go to an item page by typing in its URL, you'll be redirected to the home page. You can navigate to that same item page by clicking links in the UI just fine. Only going straight to it by entering the URL causes the issue.

I expect this will be because the act of logging you in also triggers a redirect, which it should only do if you came from somewhere else. Since it only happens in dev mode, I suspect it's related to #702 , so perhaps you're interested in this, @atarix83 ?

**Comment by atarix83** [comment]
ok @artlowel I'll have a look on it
