### ISSUE TITLE
Cache Redesign

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#718]
### The issues
The way caching works in dspace 7 has a number of issues:

1. **When an object's cache time to live (TTL) has elapsed. It is automatically removed from the cache.** It is unclear for a component developer that this has happened and how to deal with it when it does. Most components simply break, or keep loading indefinitely.
2. **Responses and objects are cached in separate parts of the store and have separate TTL.** But both the response and the object are necessary when we need the object in a component. If you mix requests with long and short TTLs for the same objects these can get out of sync, where the response is still valid, but the object isn't anymore. The result is hard to diagnose issues in the UI. These occur often when working with the submission and mydspace due to the very short cache times in use there.
3. **An object can be removed from the cache before it's been used once**. If you use a very short TTL (a few ms) it's perfectly possible that the object is already removed by the time you first try to render it, in the best case this results in pages that sometimes work, sometimes don't (if the processing takes slightly too long), or in the worst case: infinite loops of requests.
4. **RemoteDataObjects are constructed every time they're needed.** To construct them we combine info from the response and the object cache, have some logic to determine the state, but that logic basically duplicates what we already do when parsing a request, but doesn't work exactly te same way, which leads to issues: e.g. a RemoteDataObject isn't deemed to be successful if it has no payload, but if the response was a 204 that's incorrect. Constructing them when needed also leads to long, hard to debug methods, and takes up resources.
5. **Changes made in one place (creating/updating/deleting an object) can cause other cached objects or responses to become outdated, even though they're still valid according to their TTL.** Currently the developer implementing the change has to consider all the places their change could have an effect, and manually clear the cache for all of them. It would be better to automate this as much as possible
6. **We can't take advantage of an embedded lists of objects at the moment**, because lists aren't cached in the object cache, but stored as part of the response. Only lists that were requested using their self link can be cached at the moment.
7. **Our attempts at abstracting away the cache has made working with it harder not easier.** Every time any component needs anything from the rest api, they call the dataservice, which creates a request object, and passes it off to the request service. The request service then checks if the thing being requested is already cached, if it is it doesn't actually send the request, but returns the cached result. The original reason to do this was that developers should just program as if there was no cache and we'd be able to disable the cache or swap it out with a different implementation etc. In practice it doesn't work like that at all. Every component or service that interacts with the request service has to take in to account this behavior, there are cases where we can't help but force bypass this behavior, it has led to complicated code with a bunch of edge cases, a bug chunk of memory that's needed to track all the requests that were never sent etc. And we're not even close to being able to turn off the cache without breaking absolutely everything.
8. **data.service.ts needs interfaces for subtasks.** We encourage every service that corresponds with a rest endpoint to inherit from it. But most endpoints only support a fraction of the methods dataservice provides. So we either inherit, and a lot of methods don't work, or use delegation, but don't have interfaces to enforce which methods the delegating service has. This makes it possible for someone to add an `@dataservice` annotation on a service that isn't one, and we'd only know about it at runtime. We should at least create a separate interface for each atomic bit of functionality in dataservice, and perhaps also split up dataservice in to multiple smaller classes, and use composition rather than inheritance for the implementing services.

A lot of these issues are only noticeable when you're dealing with very short TTLs or a mix of short and long ones on the same page. Which is why most of these have flown under the radar for a long time. But with most PRs we make these days there is at least _some_ workaround the developer needs to do in order to deal with one or more of these issues. Those take time and effort, and the workarounds are often slightly different from one another leading to slightly different edge cases and bugs.

### Proposed solution

To deal with these issues I propose we do the following:

- **We remove the TTL from the object cache, we store it only with the response.** 
	- Objects already have a link back to the request id they came with. We can use that to find the response and check if it's still valid. 
	- So checking an object's validity will be identical to checking the validity of the response it came in with.
	- This will address issue 2.
- **We store the response as a RemoteDataObject**
	- The way we use response info is by translating it to a RemoteDataObject first, so we're better off just storing it that way immediately.
	- That way we remove the duplicate logic for determining the state, everything will happen in the reducer. 
	- Combined with the point above that means: the state of the object in the cache = the state of the response it came in on = the state of the RemoteDataObject.
	- The only thing that needs to happen when it is requested is to resolve the link to the object in the cache, which can happen the same way it happens for all other links.
	- This will address issue 4
- **We no longer remove expired objects from the cache automatically**
	- instead we add an extra state to RemoteDataObjects: `stale`. 
	- An object's state will change to stale when its validity is checked and its expiration date has passed. 
	- It can also be set to stale when we know it is invalid for other reasons, more below. 
	- Stale objects won't disappear from any component they're being shown in. 
	- The developer for a component can choose to use the stale state to let the user know, but they're not obliged to. 
	- For performance reasons, objects won't automatically be set to stale if their TTL expires because that would mean keeping track of hundreds of timers. The state only changes when it is retrieved or otherwise invalidated. 
	- As a consequence, if you're e.g. looking at an item page, and leave it open for a few hours without interacting, nothing will break (unlike now) but the cache won't set that item to stale because we have no cause to check its validity. Clicking the full item page link would, because it means it is retrieved from the cache once again and checked. 
	- This will address issues 1 and 3.
- **Lists will be stored in the object cache as well**. 
	- Lists have self links in the rest response, so there is no good reason not to cache them. 
	- Currently those self links are attached to the pageinfo object inside the paginated list, but that doesn't correspond to the response. 
	- We should move the _links section to the list itself. 
	- Each object inside the list is already cached separately in the object cache. We'll model that by adding a  `page` link to the paginated list's _links section. It will contain HALLinks to every object in the list. 
	- This will address issue 6.
- **The requestservice will send every request it receives**
	- dataservices will check the cache for a valid object before sending a request
	- Only if the check fails (the object isn't cached or is stale), the dataservice will send a request to the request service.
	- If a certain method for a specific service *never* needs a cached object, it can simply leave out the check.
	- We no longer need forceBypassChace, the request id mapping index, or observable.race() calls for retrieving a request which should make everything more straightforward and should improve performance.
	- This will address issue 7.
- **Deleting an object will automatically invalidate any list it was part of**
	- since the object in the cache has a reference to the request that put it there (in fact we'll change that to a reference to every request that has ever added this object, more below) we can use that info to automatically set those responses to stale. 
	- This will address issue 5.
- **Updating an object requires no automatic invalidations**
	- If you update something in the object cache that was part of a list, that list will already update automatically. The list only contains the self link to that object, so if the object that link points to changes, the list will change as well
	- However when the updated object comes back to overwrite the old version in the object cache, we should still keep track of the original request id. That way, if you first update something that came as part of a list, and subsequently delete it, we'll still know which list to invalidate.
	- This will address issue 5.
- **Creating an object still requires knowing what to invalidate**
	- When you create something new, the cache can't possibly know which lists it might be added to. Some are easy to predict, e.g. if you create a collection it's probably a good idea to invalidate its community's collection list, but there's nothing we can do that's valid across the board.
	- So in order to make manually invalidating in this case easier for the developer to do and make the code easier to read, we'll add invalidate methods to each dataservice that should allow a developer to invalidate the responses to GET requests that service can send.
	- This will address issue 5.
- **Dataservice methods can automatically re-retrieve stale objects**
	- We'll add a `tap()` to the bottom of any dataservice method that represents a GET request, 
	- Inside we'll check if the RemoteDataObject being returned has switched to stale
	- If it has, we'll send a new request to the same URL.
	- Doing it in a `tap()` will ensure that this re-request will only happen if something is still subscribed to the result, i.e. when it's still being used.
	- You'll be able to disable this behavior when calling the dataservice method, but it will be enabled by default.
	- This will address issue 1.
- **We'll split dataservice methods up in to chunks of functionality and create interfaces for them**
	- e.g. CreateDataService, ReadDataService, PutDataService, PatchDataService, DeleteDataService, SearchDataService, …
	- In that case DSODataservice would only implement ReadDataService, while CommunityDataService would implement them all.
	- This will address issue 8

I estimate this will take **120 - 160 hours**

I expect implementing the changes described here will take about half that time. The other half is reserved for dealing with the consequences of the changes elsewhere in the codebase: removing workarounds that are no longer necessary, components that expect plain observables instead of remotedata, templates that specifically test for the success state, so that will break when the object becomes stale, etc. 

I also expect that a lot of tests will need to be changed, or rewritten entirely. The amount effort that will take is very hard to predict.

**Comment by artlowel** [comment]
Closing. 
Replaced by #739, #740, #741, and #742

**Comment by tdonohue** [comment]
Just for the public record, I talked with @artlowel & @lieven-atmire about this yesterday and together we worked to split this up into 4 separate tasks (which can be scheduled separately) as noted above.  @heathergreerklein and I also talked yesterday about this and decided that the first task (#739) is a high priority bug, so it has been scheduled for beta4.
