### ISSUE TITLE
Simple default theme for UI

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#727]
# Rescoped as of March 4, 2020

## Dependencies
* This ticket depends on #729 (See PRs #1035 and #1042), which makes all (public) components themeable & creates our strategy for theming
    * Themes are all under `/src/themes/`, with an easily modifiable template/scaffolding in `/src/themes/custom`
* This ticket also relates to #728 , which has been re-scoped to be about cleanup of all existing components (under `/src/app`) for accessibility and easier theming (based on default Bootstrap)

## Scope of Ticket
The goal of this ticket is to provide a very basic, default theme under `/src/themes/dspace` which extends the work in #728 in very minor ways (CSS & Images primarily)
* This ticket is scoped to overlaying basic CSS / color scheme / image over the default Bootstrap styles of the components.
* We agree that all HTML-level changes to components should be done directly in #728    
    * No changes to Components or HTML should be made in `/src/themes/dspace`, as we all agree that we only want to maintain *one copy* of Components/HTML (the copy in `/src/app/`
    
## DSpace UI Theming Guidelines
1. All default HTML / Component code lives in `/src/app` . It should _only use default Bootstrap styling_.
2. Any theming work above "default Bootstrap styling" belongs under `/src/themes/` in our default Theme.  The default Theme should include no HTML changes.

~Re-scoped from release plan. Create a simple theme that will provide an example or template for how to create a local theme.~

**Comment by tdonohue** [comment]
This refers to the Mantis theme. This should build on the base Bootstrap default.

**Comment by tdonohue** [comment]
This should be a very simple example theme that overrides default styles/look & feel of the base "Mantis" theme.

**Comment by tdonohue** [comment]
Depends on our upgrade to Angular 10: #787 as we'll be switching to Ivy (https://angular.io/guide/ivy) which will result in changes to the current theming strategies.

**Comment by tdonohue** [comment]
In today's discussion of #728 , we've re-scoped this ticket again.

This is NOT about creating a second theme, but more around creating a *basic, example theme* which can be used as a "template" for anyone who wishes to override the DSpace 7 theme.  This basic, example theme may be the *default theme* which just overrides a few basic default Bootstrap styles.

Based on today's discussion, we'd like this theme scoped to the following:
* Concentrate on the header/footer as those are the seconds most likely to be customized by institutions installing DSpace 7. 
    * We like the idea of a smaller header (ideally all one line), similar to some of the designs at https://wiki.lyrasis.org/pages/viewpage.action?pageId=204308676  (However, the login/globe can be on that same line instead of in a separate gray bar at the top)
    * We like the idea of having a double footer (as many institutions seem to use that), also in those same designs (see wiki page above). The upper section of the footer can just be "lorem ipsum" but can provide an example for institutions to easily override (or comment out and disable) 
* Minor changes elsewhere are fine, but it should be kept very minor as the goal is to hopefully hire a designer for 7.1 or 7.2.
    * One minor change noted is to remove the duplication of the DSpace logo (e.g. on the homepage it appears in the header, the footer and the news section....it may only be needed in the header) 

This tasks depends on both #728 and #729 being completed.  It should be re-estimated at that time, and I hope it'd be much less than 30 hours (assuming the cleanup can be kept very minor)

**Comment by tdonohue** [comment]
Updated scope of this ticket per today's discussion. See updates in [description above](https://github.com/DSpace/dspace-angular/issues/727#issue-648473818)
