### ISSUE TITLE
LoadingService

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#73]
Create a service to track everything that is loading. 

It should have a `track` method that takes an `Observable<boolean>`

It should offer an `isLoading` `Observable<boolean>` that is true when any its tracked Observables are true, false otherwise. [CombineLatest](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/combinelatest.md) is probably useful here

Afterwards, Components that are waiting for something to load should register an Observable with the LoadingService.
e.g. `this.loadingService.track(this.remoteData.isLoading)`

**Comment by wwelling** [comment]
@artlowel do we still want to create a service for tracking asynchronous loading? 

Angular [NgIf](https://angular.io/api/common/NgIf) provides a convenient way to display a loader while an observable or promise is being resolved. 

The [AsyncPipe](https://angular.io/api/common/AsyncPipe) pretty much already does what this service would do. [async_pipe.ts](https://github.com/angular/angular/blob/4.4.4/packages/common/src/pipes/async_pipe.ts#L43-L145)

We could easily create a component that centers a progress loader and have it displayed until the remote data is retrieved. Also, local assignment is a preferred way to minimize the binding to asynchronous data.

In the current paradigm with [RemoteData](https://github.com/DSpace/dspace-angular/blob/202891b55a148615f109db272ba9ab7cf989b2a5/src/app/core/data/remote-data.ts) we could do the following:

```
<div *ngIf="remoteData.hasSucceeded | async; else loading">
  <div *ngIf="remoteData.payload | async; let payload">
    <span>{{ payload.type }}</span>
    <ds-example [payload]="payload"></ds-example>
    <p>{{ payload.text }}</p>
  </div>
</div>
<ng-template #loading><ds-loading></ds-loading></ng-template>
```

There is a lack of granularity with the approach of not rendering an entire component based on the success of an asynchronous request. 

Such as the [community-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bcommunity-page/community-page.component.html) component. The entire html of this component will not render until the [RemoteData](https://github.com/DSpace/dspace-angular/blob/202891b55a148615f109db272ba9ab7cf989b2a5/src/app/core/data/remote-data.ts) hasSucceeded observable resolves.

Yet there is another asynchronous request pending that could of already returned, the logo data. Rendering the logo should not be held up by another request.

This is just one example and is a limitation of how it is implemented so far. Components should be granular and rendering of content should not be held up by pending requests that will not be templated within the given component.


Here are most, if not all, the places we bind to asynchronous content:

[community-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bcommunity-page/community-page.component.html)
[collection-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bcollection-page/collection-page.component.html)
[top-level-community-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bhome/top-level-community-list/top-level-community-list.component.html)
[item-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bitem-page/simple/item-page.component.html)
[full-item-page](https://github.com/DSpace/dspace-angular/blob/master/src/app/%2Bitem-page/full/full-item-page.component.html)

**Comment by artlowel** [comment]
Currently I can't think of a situation in which the logo could be already present in the cache while the collection is still pending. The logo is embedded in  the collection's response. And even if it wasn't, the logo would only start to be downloaded once the collection has come in, because the collection holds the only "pointer" to the logo

But let's say we have a different relation, e.g. you start on a collection page, and navigate to an item page. At that point, it is feasible the item still needs to be fetched while the collection is already cached, so we could show the "Parent Collection"-section of the page while the item's isLoading is still true. But if we don't have the item, how do we know which collection is its parent? The collection object may already be cached but before we have the relation, it's of no use. 

Now of course we could deduce the collection we came from must be related to the item, and show it before we have confirmation the Item is related to it, but in my opinion that would be a workaround that hardcodes an assumption about the datamodel that doesn't come from the server, for the small benefit of showing a part of the page slightly earlier.

**Comment by wwelling** [comment]
All that makes since. I assume that is true with the item metadata of a full item view as well. I guess I was making the case to attempt to avoid having the ngIf around any content that is already to be displayed.

Anyhow, what do you think about not going with a loader service and just using ngIf else and create a loading component? Is there something I am missing about the loader service that would be a better approach? Even with a loader service you would need another ngIf to determine whether or not to display the progress animation.

**Comment by artlowel** [comment]
The idea for the loading service was that you'd have only have a single ngIf somewhere that shows a single loading message/spinner/whatever while anything anywhere is loading. That spinner/message doesn't necessarily need to hide everything until everything is done loading, but it could prevent the situation where each component shows its own spinner and you end up with a dozen spinners on a page. 

It could also ensure that the developer of a component doesn't need to worry about the state of the isLoading observable at all, just use a RemoteData object and the loading spinner/message will be updated. (e.g. by having the RemoteDataBuildService supply the LoadingService with the isLoading observable whenever a RemoteData object is requested)

**Comment by wwelling** [comment]
I am afraid I don't know how that would work. I will have to think it over. In the meantime is #159 acceptable to provide loading notification between route changes?

**Comment by artlowel** [comment]
Do I understand it correctly if I say that for #159 you'll look at the topmost remotedata object to decide whether or not to show the loading animation?

If so, that's fine for now.

**Comment by wwelling** [comment]
Yes, that is correct. As it appears the candidate locations so far all use hasSucceeded condition to render.

**Comment by artlowel** [comment]
Ok, but to determine whether or not to show the loading animation, please use [isLoading](https://github.com/DSpace/dspace-angular/blob/master/src/app/core/data/remote-data.ts#L55), because hasSucceeded will also be false if the server has returned an error.

**Comment by wwelling** [comment]
Good point. Wouldn’t there also need to be a handler for hasFailed. Maybe an error component that can take inputs to notify the user.

**Comment by wwelling** [comment]
@artlowel I am not having any success with isLoading

https://github.com/wwelling/dspace-angular/blob/master/src/app/%2Bhome/top-level-community-list/top-level-community-list.component.html#L13

The following strategy is working however.

https://github.com/wwelling/dspace-angular/blob/master/src/app/%2Bcommunity-page/community-page.component.html#L1

**Comment by artlowel** [comment]
You're right, RemoteData.state has a bug: #165 
I made a PR

**Comment by wwelling** [comment]
Thanks. I will review ASAP.

**Comment by tdonohue** [comment]
@artlowel : I believe this is completed, as I know we have a loading service.

**Comment by artlowel** [comment]
Actually we don't. But we haven't needed it so far, and this is over two years old. So we can close this.
