### ISSUE TITLE
Cookie Preferences per account

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#735]
Estimate: 24 hours
Expressing interest: 4Science

Panel for the user to disallow tracking and 3rd party cookies & storage of those settings

Related to backend ticket: https://github.com/DSpace/DSpace/issues/2807

**Comment by abollini** [comment]
we (4science) are happy to leave this ticket to others if they can work on that in the next weeks. We suggest to investigate the integration of an existing cookie management solution instead than attempt to build our own, see for instance
https://github.com/osano/cookieconsent

**Comment by artlowel** [comment]
Thanks. We (Atmire) are interested in working on this ticket.

However I'm not convinced we have a lot to gain from using a plugin like the one you linked. The hard part isn't showing a banner with a few buttons on it. The hard part is storing and retrieving the result on the backend for signed in users, and actually enforcing the user's choices. These things will need to be tailored to DSpace anyway.

Using a general purpose plugin like this one also comes with disadvantages: It isn't an angular component, so interacting with it from inside the app is going to be a bit clunky. It also doesn't share styles or i18n messages with the rest of the UI, so people would always have to customize it separately. 

I'm also not sure that this particular plugin complies with EU law as it only allows a user to accept or decline all cookies at once, not individual categories (functional, analytical, etc). 

We'll be sure to look for alternatives before starting, but I just did a quick web search and I didn't find anything that's better and leaves me feeling confident it'll be maintained, so I'm not optimistic

**Comment by abollini** [comment]
You are off course free and welcome to analyze which is the better approach, I just want to share also the second option that was in our list
https://klaro.kiprotect.com/#features

please consider how much easier or hard could be to
- customize/configure the solution depending on the use or less of google analytics
- support in future additional third party service (addthis, sharethis, etc)

**Comment by artlowel** [comment]
Thanks, klaro looks a lot better at first sight.

We'll keep those use cases in mind.

**Comment by tdonohue** [comment]
@artlowel and @abollini : As discussed in today's meeting, this is related directly to the backend ticket: https://github.com/DSpace/DSpace/issues/2807  We discussed that it is reasonable to look at using Klaro (as noted above) and that it's also reasonable to store these cookie preferences within EPerson metadata (using the "dspace" schema or another appropriate schema).

Additionally, I was just reviewing the GDPR Working Group (chaired by @pnbecker ) notes on Cookie preferences.  Here's what they had in their report:

> Cookies
>Use of cookies in the system
>A GDPR-compliant DSpace will have no mandatory cookies, besides one cookie needed for identifying logged-in users ("login cookie"), one for storing his cookie preferences ("preference cookie") and one for recording acknowlegment of the privacy statement ("acknowledgement cookie"). These cookies must not be used for any other purposes. Nevertheless, more additional cookies can be added to DSpace as long as they are requesting consent on the cookies preference panel (see below "cookie consent form").
>
>Cookies must not be permanent unless the user agrees to permanent storage. Furthermore the Working Group recommends to make cookies permanent only if it offers additional convenience to the user. Examples are the aforementioned cookies:
>
> * Making the login cookie permanent frees the user from having to log in on every visit.
> * A permanent preference cookie will make sure the user will not have to think about his cookie preferences on subsequent visits again.
> * A permanent acknowledgement cookie will do the same for the privacy statement.
>DSpace core functionality should be kept free of functionality that needs more cookies as much as possible, especially third-party cookies. Therefore, components of DSpace that need external services should always be optional, from the operators' perspective and also from end users' perspective. Examples of such components:
>
> * PlumX/Altmetrics integration
> * Social Media Plugins
> * Statistics/Tracking tools like Google Analytics
> Also, we recommend to keep DSpace free from dependencies to external services like Content Delivery Networks. This should be discussed with the DSpace Committer Group.
> 
> Cookie consent form
> A GDPR-compliant DSpace must present users it considers to be first-time visitors a cookie consent form. That form will explain the login cookie (see above) as necessary cookie to provide minimum functionality of the site, the function of any other cookie, an **opt-in** choice to enable or disable those cookies individually, and inform whether any of these cookies are stored permanently. It will offer the **opt-in** choice to store the cookie preferences of the user on a permanent basis and explain that an additional permanent cookie is needed for that. The form also explains to the user how to change his/her cookie preferences and will easily be reachable in the UI.
> 
> Having temporary preference and acknowledgement cookies might inconvenience frequent visitors because they will need to go through the privacy statement and cookie preference form again. Nevertheless, DSpace will not try to use other means to prevent that inconvenience, since that would need an identification method the visitor did not agree to. Most cookie consent forms present a huge green button "allow all cookies". While we do not want to push the user towards simply allowing all cookies, we would recommend a user friendly layout and therefore see the benefit of an "allow all cookies button".

The full report can be found at: https://wiki.lyrasis.org/display/PSFDGWG/Result+summary+for+DSpace+Leadership+Group  (_Please be aware that this report is not public at this time. However, I've just given both of you access_)
