### ISSUE TITLE
citation_pdf_url must be based on the Angular UI Hostname

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#737]
Estimate TBD

May require a passthrough component in UI which can be used as a direct download URL.  See https://github.com/DSpace/DSpace/issues/2809

**Comment by artlowel** [comment]
As discussed in the last meeting we'll experiment on the demo server with httpd config to avoid having to proxy all downloads.

We'll then also need the service required for #846 to get the UI hostname. So we're likely best off tackling them at the same time.

Together they'll take an estimated **8h**

**Comment by tdonohue** [comment]
Thanks @artlowel! Sounds good. I've assigned both to you, but feel free to reassign elsewhere as needed.

**Comment by tdonohue** [comment]
@artlowel : Quick followup question: The "backend" for this ticket is in https://github.com/DSpace/DSpace/issues/2809 (which also is missing an estimate).  Do you anticipate those changes to also be included in the `8 hr` estimate you provided?

Now that I look at this more directly, I'm actually wondering whether all the changes here could be done on the frontend (meaning we close the backend ticket). 
* It looks like the `citation_*` tags are now all generated on the frontend in [`metadata.service.ts`](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/metadata/metadata.service.ts), based on the metadata passed from the backend.  
* That means the old Backend configuration [`google-metadata.properties` ](https://github.com/DSpace/DSpace/blob/main/dspace/config/crosswalks/google-metadata.properties) looks like it _might be obsolete_.

This direction seems fine to me overall. We may (eventually) want to make these `meta` tags more configurable (in `environment.common.ts` or similar), but I'd consider that "out of scope" for this particular ticket.  If we agree on this direction, I can create a separate ticket for making it configurable (and likely that would be scheduled for 7.1 or 7.2 as I don't see it as very high priority for 7.0).

**Comment by artlowel** [comment]
For now the assumption is that there will be no rest work, and that everything can be done using url manipulation in the UI, and an httpd proxy config. But since there's some trial and error involved perhaps hold off on closing the rest ticket until we have a working proposal on the UI side? Or if you prefer close it, knowing that we may need to reopen if some rest change ends up being necessary.

**Comment by tdonohue** [comment]
@artlowel : I'll leave the REST ticket open then & set it to a "zero" estimate (and add a comment to describe why). If you find work is needed, let us know and we can update the estimate once you know more.  Thanks!

**Comment by tdonohue** [comment]
@artlowel : Just a quick follow-up to this task.  Per the DSpace 7 Working Group meeting a few weeks ago, I asked the Google Scholar team about how "strict" this requirement is.  For example, does it need to match the hostname *exactly*, or are different subdomains allowable.

The answer is that **the hostname must match exactly**.  They also said "this is needed as a security constraint".

So, it looks like we'll definitely need to setup a "proxy" of some sort, either via the installation instructions (a special configuration of httpd or similar) or a way to proxy all downloads through the UI.  If the latter, we might want a simple way to turn it on/off, as such a proxy obviously wouldn't be necessary for all installations.
