### ISSUE TITLE
Cache redesign part 3: Simplify the invalidation of cached objects

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#741]
## References
This ticket corresponds to issue 5 from #718. 

That ticket was too big to tackle at once so we split it up in to smaller, more manageable chunks of work.

## Description

Changes made in one place (creating/updating/deleting an object) can cause other cached objects or responses to become outdated, even though they're still valid according to their TTL.

Currently the developer implementing the change has to consider all the places their change could have an effect, and manually clear the cache for all of them. It would be better to automate this as much as possible

## Proposed solution

- **Deleting an object will automatically invalidate any list it was part of**
	- since the object in the cache has a reference to the request that put it there (in fact we'll change that to a reference to every request that has ever added this object, more below) we can use that info to automatically set those responses to stale. 
- **Updating an object requires no automatic invalidations**
	- If you update something in the object cache that was part of a list, that list will already update automatically. The list only contains the self link to that object, so if the object that link points to changes, the list will change as well
	- However when the updated object comes back to overwrite the old version in the object cache, we should still keep track of the original request id. That way, if you first update something that came as part of a list, and subsequently delete it, we'll still know which list to invalidate.
- **Creating an object still requires knowing what to invalidate**
	- When you create something new, the cache can't possibly know which lists it might be added to. Some are easy to predict, e.g. if you create a collection it's probably a good idea to invalidate its community's collection list, but there's nothing we can do that's valid across the board.
	- So in order to make manually invalidating in this case easier for the developer to do and make the code easier to read, we'll add invalidate methods to each dataservice that should allow a developer to invalidate the responses to GET requests that service can send.

This will take an estimated **24 - 32h**

**Comment by tdonohue** [comment]
Tentatively added to 7.1, unless we find a clear reason this needs to be done earlier

**Comment by tdonohue** [comment]
@artlowel : Per today's meeting, leaving this assigned to you / your team for implementation as part of 7.2.  Feel free to start implementation when ready.
