### ISSUE TITLE
The metadata autocomplete queries should be sent to the server, not run on the client

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#750]
Currently the metadata autocomplete works by fetching all metadata fields and all schemas and querying them client side. This blocks the UI 10 - 30 seconds on pages where it used. 

It got a lot worse since #697 removed the hacks in the response parser that stored embedded schemas as direct properties of the fields. Since those schema's use alternative links, they can't be cached until #652 is merged. As a consequence the metadata autocomplete got _a lot_ slower still. So #749 will disable the autocomplete and validation for now. 

We should re-implement both of those after a search endpoint for metadatafields is added, and those queries can happen on the rest side.

Required REST implementation: https://github.com/DSpace/DSpace/pull/2899

**Comment by tdonohue** [comment]
Closing, as this was fixed by #860
