### ISSUE TITLE
The harvesting client (XMLUI only) should be ported to dspace 7 

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#761]
From release plan spreadsheet

Estimate from release plan: 24 hours
Expressing interest: none

https://wiki.lyrasis.org/display/DSDOC6x/OAI#OAI-OAI-PMH/OAI-OREHarvester(Client)

This includes ability to kick off harvest from collection level and site level harvesting status (XMLUI Control Panel). We currently don't have the REST for the Control Panel.

Done:
- The content source tab on the edit collection page has been added an allows you to configure the params and store them to the server

Still to do:
- Start harvesting and show the status

Specs:
- Add UI elements to start a harvest and show the status
- Start jobs using the scripts&processes endpoint
- Get the status from the collection /harvest endpoint

**Comment by artlowel** [comment]
@tdonohue we'd like to claim this one

**Comment by tdonohue** [comment]
@artlowel : Sounds good. Assigning to you for your team to work on.  Keep in mind, this estimate is really old, so you may first want to analyze whether it is accurate (and let me know if it is not).
