### ISSUE TITLE
Authorization as someone with Collection Admin rights

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#764]
From release plan spreadsheet

Estimate from release plan: 4 hours
Expressing interest: none

https://wiki.lyrasis.org/display/DSPACE/Managing+Authorization+info+in+Angular+UI

**Comment by tdonohue** [comment]
Closing, as this has been implemented already in 7.0 and tested during Testathon. Any specific issues are in separate tickets.
