### ISSUE TITLE
View Authorization Groups

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#766]
From release plan spreadsheet

Estimate from release plan: 5 hours
Expressing interest: none

- Create/modify a service to be able to retrieve the groups for the current user
- List them on the profile page

**Comment by abollini** [comment]
as we are working on other aspect of the group management it would be convenient for us to work on that in the coming weeks. Can we get assigned of this task?

**Comment by tdonohue** [comment]
Closing as this was already implemented in 7.0. See a logged in user's profile page.
