### ISSUE TITLE
Make an Item private (from Submission UI)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#768]
From release plan spreadsheet

Estimate from release plan: 6 hours
Expressing interest: none

Need option to make Item Private during submission. Depends on Embargo Item Metadata (form Submission UI Only)

- Add the private item checkbox to the access section component
- Ensure the service can parse the response, and send patches concerning the private item status

**Comment by tdonohue** [comment]
Closing, fixed by #1475 

NOTE: In the UI, we've redesigned this into a "Discoverable" checkbox.  By default it's checked, meaning the Item will findable via search/browse. When unchecked, it's only findable via a direct link (which is the old definition of a "private" item)
