### ISSUE TITLE
Sherpa-Romeo Integration

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#769]
From release plan spreadsheet

Estimate from release plan: 40 hours
Expressing interest: none

No additional notes

Related REST ticket https://github.com/DSpace/DSpace/issues/2840

**Comment by tdonohue** [comment]
Basic SHERPA/RoMEO integration already exists in 7.0. Needs discussion as to what additional features are needed. May be overestimated.

**Comment by abollini** [comment]
See comment in https://github.com/DSpace/DSpace/issues/2840 the Sherpa/RoMEO submission panel is mostly readonly, we can eventually think about a "force refresh" button. I would reduce the estimation to 3 days
