### ISSUE TITLE
DS-4277: Layout of search results in MyDSpace

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#773]
This is a duplicate of [DS-4277](https://jira.lyrasis.org/browse/DS-4277)

Estimate from release plan: none
Expressing interest: none

The MyDSpace page contains a search for items submitted by the current user, or in the user's task pool.
The layout of the items in this list doesn't seem to use the discovery component for item lists.
This implies that changes applied to the displayed metadata in discovery are not applied to the MyDSpace page
For consistency reasons, it's best to use the same component, and add the applicable buttons underneath, instead of creating a duplicate component for rendering the item list

**Comment by abollini** [comment]
@tdonohue this is in the scope of https://github.com/DSpace/dspace-angular/issues/1044 and should be closed

**Comment by tdonohue** [comment]
Thanks @abollini .  Closing this in favor of #1044 then, which is already assigned & in progress.
