### ISSUE TITLE
Export Collection (to ZIP)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#775]
From release plan spreadsheet

Estimate from release plan: none
Expressing interest: none

Likely should be redesigned to use the scripts & processes endpoint.

Depends on REST ticket https://github.com/DSpace/DSpace/issues/2843

**Comment by abollini** [comment]
Do we need to implement a "SAF" option under the Export menu or a button on the collection home page to use as shortcut? or both? if we need to add a button shortcut in the collection home should we have one (standard mode?) or two as in the previous versions to distinguish between the migrate and the standard mode?

**Comment by tdonohue** [comment]
Closing, fixed by https://github.com/DSpace/dspace-angular/pull/1827 in 7.4
