### ISSUE TITLE
More easily embargo an archived Item (using a form)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#778]
From release plan spreadsheet

Estimate from release plan: none
Expressing interest: none

Related REST ticket: https://github.com/DSpace/DSpace/issues/2846

**Comment by tdonohue** [comment]
This can already be done in 7.0 via "Edit Item" -> "Authorizations" by adding a new policy restricting the Item to a group (e.g. Administrator) until a specific _end date_ passes.

So, this ticket is really just about making that process *easier* (perhaps via an Embargo button, or via a new submission-style edit option like described in #2876)

**Comment by tdonohue** [comment]
Closing as fixed by the Bulk Access management tool added in 7.6: https://wiki.lyrasis.org/display/DSDOC7x/Bulk+Access+Management

Using that tool you can now add an embargo to a single item or multiple via a form.
