### ISSUE TITLE
Batch Import (from ZIP)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#783]
From release plan spreadsheet

Estimate from release plan: 14 hours
Expressing interest: none

No additional notes

**Comment by abollini** [comment]
@tdonohue we are interested in that. We can work on it after / in parallel with the other higher priority tickets already claimed

**Comment by abollini** [comment]
do we need to add a SAF option under the import menu from where one can select the collection or should we include a shortcut button in the collection home page? or both?

**Comment by tdonohue** [comment]
@abollini : I'd recommend this only be in the import menu (alongside existing import from CSV).  So, the Import menu might become:
```
* Import
    * Metadata
    * Zip
```

I don't think there's any need to replicate the import mechanism to the Collection homepage, as no other imports can occur at that location. I'd like to keep tools together as much as possible in the side menu.

Please let me know if you'd like to be assigned for this work or not.
