### ISSUE TITLE
Edit Homepage News from Admin UI (JSPUI Only)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#784]
From release plan spreadsheet

Estimate from release plan: 8 hours
Expressing interest: none

No additional notes

Requires Backend/REST support.  Early discussion in https://github.com/DSpace/RestContract/pull/45

**Comment by abollini** [comment]
we want to note that this feature has been implemented in DSpace-CRIS and we will be happy to donate it as-is on a volunteer basis. The approach used in DSpace-CRIS is the one that I have suggested as "alternative" in the REST contract discussion

https://github.com/DSpace/RestContract/pull/45#pullrequestreview-201920581

we use special metadata attached to the site object

**Comment by tdonohue** [comment]
Closing in favor of #3200, which is a duplicate ticket but has screenshots and more details.
