### ISSUE TITLE
Upgrade to Angular 10

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#787]
From release plan spreadsheet

Estimate from release plan: 40 hours
Expressing interest: none

Angular 8 (which we are currently on) ends LTS support on Nov 28, 2020.

Angular Support policy/schedule: https://angular.io/guide/releases#support-policy-and-schedule

**Comment by saschaszott** [comment]
At the moment DSpace Angular depends on Angular 8 which is in LTS state and reaches EOL in 11/2020. The current Angular major release is 10.x. Are you planning to update the Angular dependency and ship DS 7.0 with Angular 10.x?

**Comment by artlowel** [comment]
But the upgrades from [8 to 9](https://update.angular.io/?l=3&v=8.0-9.0) and [9 to 10](https://update.angular.io/?l=3&v=9.0-10.0) have more steps than usual. In part due to the switch to Ivy. Now we have CLI support we _can_ make use of the cli upgrader to do at least some of the work automatically, but I've tried it, and it still needs a lot of manual help before the app will build.

So I'd put the estimate to upgrade from 8 to 9 at **40h**, same as last time. And if we do the upgrade from 9 to 10 at the same time we'll save _some_ time, but since the upgrade is more complicated than average, I wouldn't put it lower than **20 additional hours**

**Comment by tdonohue** [comment]
Thanks for the notes/estimate, @artlowel .  Given your feedback here, I'd like us to upgrade directly to Angular 10 (which gives us more time before our next upgrade).  So, I'll update this ticket to say **60hrs**.

(Obviously, if the developer claiming this ticket notices major issues in the Angular 9 to 10 upgrade, we could later choose to stop at Angular 9 for DSpace 7.0 & delay the Angular 10 upgrade for 7.1 or 7.2.  That said, I'd rather we try to get to Angular 10 now if at all possible.)

**Comment by tdonohue** [comment]
As decided in today's meeting, I'm assigning this to @atarix83 for the 4Science team to work on.  This ticket is deemed as `high priority` (as we cannot start other tasks like theming until completed).  @abollini estimated that 4Science should be able to complete this by/around the first week in Dec.

**Comment by abollini** [comment]
for some unknown reasons github refuse to post this comment that was agreed in the last dev mtg  in the last 7 days, at the end it seems to be related to some content that broken the rendering... that said, I try to add it again rephrasing a bit :)

the updated estimation for this task is **72 hours** (that has been already spent up to the 3 Dec **plus probably a couple of other days**  that would be required once that we figurate out how to deal with the issue in the prod build (see the description in the PR #970 ) so say 100 hours to be on the safe side

**Comment by abollini** [comment]
As anticipated in the dev mtg of the 2021-01-14 the complexity of this task was higher than expected, the final cost on the 4Science side including the latest fix done on the 15th Jan that should "finalize" the contribution is **112 hours**.

**Comment by tdonohue** [comment]
@artlowel : Could you add your final hours into this ticket (just as a reminder to me that you had paid time on this task as well)?  Thanks!

**Comment by artlowel** [comment]
I spent 7 hours in total on this PR
