### ISSUE TITLE
RSS/ATOM Feeds

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#788]
From release plan spreadsheet

Estimate from release plan: 8 hours
Expressing interest: none

RSS content must appear off root path of UI (like robots.txt & sitemaps).  "- Proxy the backend's RSS feeds on the express.js server
- Add/adapt service to retrieve RSS config from backend (e.g. whether or not it's enabled)
- Add RSS buttons to the UI if it's enabled
- Backend needs to be determined (might be content negiotiation on the search/discovery endpoint). Once figured out, might become more certain.

Requires: https://github.com/DSpace/DSpace/issues/2864

**Comment by tdonohue** [comment]
Updated this to a 0-hour estimate as the code was donated early in #1444 and https://github.com/DSpace/DSpace/pull/8064
