### ISSUE TITLE
Configuration isn't integrated in a useful way

### ISSUE THREAD

**Issue by wwelling** [DSpace/dspace-angular#79]
The configuration UI URL is not used within the server.ts and server.aot.ts.  The node express engine binds to the port and address. It should get the values from a configuration file.

The production and development builds and tests are not dictating what environment configuration to use.

Cache time to live isn't setting anything in the server or client side cache. server.ts and server.aot.ts sets the Cache-Control per request but does not reference a configuration.

Whether or not to preboot is a property of the ngApp response. I do not see any reason to ever prevent the browser from rehydrating the universal cache set during pre-render on the server side node. For this to even make since it would have to condition on the configuration everywhere in the code where an asynchronous response is put into the universal cache.

Also, the process to get the environment configuration seems a bit more complex then necessary.

**Comment by artlowel** [comment]
>Cache time to live isn't setting anything in the server or client side cache

The cache time to live is currently used as [the default time for own cache](https://github.com/DSpace/dspace-angular/blob/34d9aece7e27631effd28d9f590a0c09c48da0e1/src/app/core/data-services/data.effects.ts#L41) in the ngrx store, where it is used to determine whether or not a cached request or object is [still valid](https://github.com/DSpace/dspace-angular/blob/34d9aece7e27631effd28d9f590a0c09c48da0e1/src/app/core/cache/object-cache.service.ts#L121). 

>everywhere in the code where an asynchronous response is put into the universal cache.

Nothing but the state of the ngrx store is ever put in to the universal cache. At the moment, I don't really see a reason to. As we're working with redux, we should keep everything in the ngrx store. So async responses are cached in the store, and the state of the store is put in to the universal cache.

> I do not see any reason to ever prevent the browser from rehydrating the universal cache

The option to disabling the rehydrate step was added to make it easier to debug the actions that happen on the ngrx store. If rehydration is enabled all you see in the [redux-devtools](https://github.com/gaearon/redux-devtools) is a single rehydrate action. If you want to see how the server got to that state, you can disable rehydration and then all steps from the initial  state to the present state will be performed on the client, so you can debug them, rollback, change action payloads, etc.

**Comment by wwelling** [comment]
Ok, that configuration may be useful. But still the universal cache should not be populated by the node, server side, if it is not going to be rehydrated by the client. Why not just have the configuration disable pre-render altogether?

**Comment by artlowel** [comment]
I agree, that would be better.
