### ISSUE TITLE
Control Panel

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#801]
From release plan spreadsheet
Estimate from release plan: TBD
Expressing interest: none

This is an XMLUI only feature in 6.x.  Unclear what is possible in Angular -- requires discussion.

Depends on REST ticket https://github.com/DSpace/DSpace/issues/2877

**Comment by abollini** [comment]
We are working on a proposal for that based on standard approach to this kind of issue in the Spring community. If our proposal and estimation will found the favor of the community we will be interested in having this issue assigned

**Comment by tdonohue** [comment]
@LucaGiamminonni : I summarized today's discussion in this comment on the other ticket: https://github.com/DSpace/DSpace/issues/2877#issuecomment-1050113535

I'll assign this ticket to you for 7.3.  Please provide an estimate for the effort it will take to build the basic Control Panel UI which only views the "info" and "health" actuators.
