### ISSUE TITLE
Additional configurable workflow steps: "Score review workflow"

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#802]
From release plan spreadsheet
Estimate from release plan: 9 hours
Expressing interest: none

- ScoreReviewStep
    - Add a component to enter the score. 
    - Enforce that the score is a valid percentage
    - Add buttons to submit the score, or leave the step
    - Add a method to the appropriate submission service to send the score to the REST API
Assumes render workflow action dynamically is completed. UNCERTAIN

**Comment by tdonohue** [comment]
Closing, this was fixed in 7.5 in #2039
