### ISSUE TITLE
Manage Subscriptions

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#803]
From release plan spreadsheet
Estimate from release plan: 13 hours
Expressing interest: none

- Create a service to retrieve, add, remove subscriptions on REST
- Add the ability to subscribe/unsubscribe on the collection page itself
- show an overview of active subscriptions on the profile page with the ability to remove them

**Comment by abollini** [comment]
we want to note that the subscription functionality have been extended and implemented in DSpace-CRIS 7.
If what we have done in DSpace-CRIS is of interest of the DSpace community and can be accepted as is eventually disabling part of the feature that cannot be immediately ported we are available to make a more accurate estimation for the porting work.
We can anticipate that it should took not less than 24 hours on the Angular side.

The feature has been improved on this aspects:
- it is possible to subscribe also community and item
- subscriptions have a type: content (default of dspace) or statistics
- frequency of notification can be defined by the user (daily, weekly, monthly)
