### ISSUE TITLE
Additional configurable workflow steps: "Select Single Reviewer Workflow"

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#804]
From release plan spreadsheet
Estimate from release plan: 18 hours
Expressing interest: none

- AssignStep
    - Add a component to select a reviewer to assign
    - Add methods to a submission service to search for applicable reviewers, and to assign a reviewer to a workflowitem
- ReviewStep
    - Everything should already be in place on the UI side
Assumes render workflow action dynamically is completed. UNCERTAIN

**Comment by tdonohue** [comment]
Closing, this was fixed in 7.5 in https://github.com/DSpace/dspace-angular/pull/2039
