### ISSUE TITLE
Submission via an identifier

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#805]
From the release plan spreadsheet; no additional notes were included.
Estimate from release plan: TBD
Expressing interest: none

**Comment by tdonohue** [comment]
test comment (comments not working across all issues)

**Comment by tdonohue** [comment]
Closing, as (along with #2872) this appears to duplicate #2834 No additional information is provided in this ticket, and they sound like the same feature.  Additionally, basic submission via identifier (from MyDSpace) functionality exists in 7.0.
