### ISSUE TITLE
Type-bind submission

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#806]
From the release plan spreadsheet; no additional notes were included.
Estimate from release plan: 16 hours
Expressing interest: none

* Related REST ticket: https://github.com/DSpace/DSpace/issues/2873
* Related DSpace PR: https://github.com/DSpace/DSpace/pull/8175
* Related dspace-angular PR: https://github.com/DSpace/dspace-angular/pull/1529

**Comment by sheriljosesao** [comment]
Hey, 

I had installed and run and instance of DSpace 7 and came across this issue with the form not presenting fields according to its type-bind. I was wondering if this is a known issue and if it's currently being worked on.

**Comment by tdonohue** [comment]
@sheriljosesao : This feature does not yet exist in DSpace 7.  It's currently scheduled to be developed as part of the 7.2 release, so it will not be available in 7.0.  See Projects/Milestone sections on the sidebar of this issue ticket

**Comment by pnbecker** [comment]
We got a contract to develop this. Of course, we will create a pull-request once we're done with it.

**Comment by abollini** [comment]
This is already supported in DSpace-CRIS so you should take a look to backport the feature.
It was introduced in the first 7 version so it is a bit hard now to find all the reference but I'm able to track down the feature to these commits on the Angular side
https://github.com/4Science/dspace-angular/commit/64a4211d7e23f8c154a6259b096387f0b3a3e95d
https://github.com/4Science/dspace-angular/commit/7fa9185f01bc46f688820f27f7f9ba16d5365145

you should start to explore the code looking to this service https://github.com/4Science/dspace-angular/blob/dspace-cris-7/src/app/shared/form/builder/ds-dynamic-form-ui/ds-dynamic-type-bind-relation.service.ts

**Comment by pnbecker** [comment]
@abollini Thank you. That helps a lot. We will definitely take a look!

**Comment by kshepherd** [comment]
@abollini thanks for this - can I clarify something further -- is the type binding in DSpace-CRIS for both input fields and available relations, or just relations?

**Comment by kshepherd** [comment]
I've opened PRs for DSpace and dspace-angular. They need work on tests before they're fully ready, but they can be practically tested as of now.

**Comment by pnbecker** [comment]
PR is here: https://github.com/DSpace/dspace-angular/pull/1529
