### ISSUE TITLE
Edit Default Deposit License from Admin UI (JSPUI Only)

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#809]
From the release plan spreadsheet; no additional notes were included.
Estimate from release plan: 8 hours
Expressing interest: none

Depends on REST ticket https://github.com/DSpace/DSpace/issues/2879

**Comment by tdonohue** [comment]
Closing in favor of #3200, which is a duplicate ticket but has screenshots and more details.
