### ISSUE TITLE
Warnings about usage of `eval` when running `yarn start`

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#81]
**Environment:** Windows 10, Yarn 0.21.3, Node 6.10.1, npm 3.10.10

After running `yarn start`, I see the following in the output (just before `yarn run server` is triggered, near the end)

```
$ rollup -c rollup-server.js && rollup -c rollup-client.js
Use of `eval` (in D:\programming\dspace-angular\dist\server\index.js) is strongly discouraged, as it poses security risks and may cause
issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
Use of `eval` (in D:\programming\dspace-angular\dist\client\main.bundle.js) is strongly discouraged, as it poses security risks and may
cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details
```

The warnings link over to this message from rollup: https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval

However, as I don't see any usages of `eval` in our codebase, it's unclear where it is being pulled in from. Nonetheless, it seems like we should have a ticket to track this.

**Comment by wwelling** [comment]
This was resolved a while back. It was caused by an import in rollup.config.js. Closing now.

**Comment by wwelling** [comment]
This turns out to be still happening. Reopening.

**Comment by tdonohue** [comment]
Closing this again. I'm no longer seeing this error message in my current environment (Windows 10, Yarn v1.3.2, NPM v5.6.0, Node v6.10.1) when I run `yarn start`
