### ISSUE TITLE
Signposting 

### ISSUE THREAD

**Issue by heathergreerklein** [DSpace/dspace-angular#811]
From the release plan spreadsheet; no additional notes were included.
Estimate from release plan: 32 hours
Expressing interest: none

Depends on REST ticket https://github.com/DSpace/DSpace/issues/2881

**Comment by tdonohue** [comment]
@abollini : Same here, will assign to your team for 7.3.  However, please review the original estimates, as they are nearly 2 years old...let me know if they need updating.
