### ISSUE TITLE
Issue with submission form's tag field

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#816]
**Describe the bug**
After merge of https://github.com/DSpace/dspace-angular/pull/541 the `tag` field of the submission form doesn't work properly. Indeed if you try to save the submission after entering one or more entry the submission form breaks with several errors 
![Schermata da 2020-07-23 13-35-48](https://user-images.githubusercontent.com/2486489/88286819-a2477c80-ccf1-11ea-8273-824014246374.png)
  

**To Reproduce**

- start a new submission
- add one or more entries to the `Subject Keywords` field
- save submission

**Related work**
https://github.com/DSpace/dspace-angular/pull/541

**Comment by artlowel** [comment]
This appears to be fixed by #751
