### ISSUE TITLE
LocaleInterceptor blocks new request

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#819]
**Describe the bug**
The new [LocaleInterceptor](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/locale/locale.interceptor.ts) blocks every new rest request when it can't retrieve the logged eperson object because the related entry cache object is expired. This is made in the [LocaleService](https://github.com/DSpace/dspace-angular/blob/095d5f3299913598d732e8619c5f278336dd5af0/src/app/core/locale/locale.service.ts#L79-L94) and was due a bug reported in [this issue](https://github.com/DSpace/dspace-angular/issues/739). The severe consequence is that the application is blocked after this error occurs.
A temporary workaround, until [cache issuea](https://github.com/DSpace/dspace-angular/issues/739) are fixed, is to disabled [that part of the code](https://github.com/DSpace/dspace-angular/blob/095d5f3299913598d732e8619c5f278336dd5af0/src/app/core/locale/locale.service.ts#L79-L94)

**Comment by tdonohue** [comment]
Thanks for reporting this @atarix83 ! This does sound like an obvious bug we need fixing, and also sounds related to #739.  For now I've added to the beta4 Todo list.

@artlowel : Any thoughts on whether we should solve this issue separately?  Or would you rather we bundle this as part of your current work on #739?

**Comment by artlowel** [comment]
The way @atarix83 describes it, it should go away if the caching issue is fixed. But in general, blocking the entire app because we can't get the eperson language seems problematic. 

It would probably be good to have a fix on the side of the interceptor as well: where if the eperson is undefined, we don't include the eperson language in the request, rather than blocking the request.

**Comment by atarix83** [comment]
@artlowel I agree, but the issue is on  [getAuthenticatedUserFromStore](https://github.com/DSpace/dspace-angular/blob/8b639bc7bab1e16491f1d2fe945e1960e494b9d7/src/app/core/auth/auth.service.ts#L205) method that doesn't emit a value due to `getAllSucceededRemoteDataPayload` operator. I made some test but I can't find a way to allow the observable to emit an eperson on success and undefined on error. I tried to replace `getAllSucceededRemoteDataPayload` with `getFinishedRemoteData` but it seems that even if the request is successful the RemoteData is emitted two time, the first time with an undefined payload, the second one with the eperson object. I encountered this bug in the past, but in this specific case it does not allow to have a working solution.
Do you have any idea?

**Comment by artlowel** [comment]
@atarix83 after looking at it closer, I don't see a way to deal with the fact that the first payload will always be undefined either. Perhaps just leave out the eperson language until the cache is fixed.
