### ISSUE TITLE
Metadata edit - removing metadata value gives error response

### ISSUE THREAD

**Issue by Atmire-Kristof** [DSpace/dspace-angular#821]
**Description**
When trying to remove a metadata value from an object (e.g. item) that contains multiple values for the same metadata field, the console displays a 400 error response and the metadata changes aren't saved on the server. This only happens when trying to remove any value but the last one (from the list of values within the same metadata field).
Viewing the patch request sent to the REST API shows it's not trying to simply delete the selected value, but instead replace this value with the next one in the list.

**To Reproduce**
Steps to reproduce the behavior (ensure your browser console is open to view the error response and request):
1. Create or find an item containing at least 2 values for the same metadata field
2. Delete the first occurrence of this value (make sure the page is reloaded after adding metadata values, otherwise the order might be incorrect)
3. Click Save

**Expected behavior**
A correct patch request to be sent (simply deleting the selected value(s))

**Comment by tdonohue** [comment]
Verified this bug still exists today by attempting to delete the *first* author on an Item that had 3 authors.

**Comment by artlowel** [comment]
This will take an estimated **6h** to fix

**Comment by artlowel** [comment]
@tdonohue Heads up, after we started investigating this issue, it turns out it is more complicated than it seemed at first. It will take closer to **16h** to fix.
