### ISSUE TITLE
Upgrade to Angular 4

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#83]
Angular 4 has been released. 

A little background info: Angular 3 never existed, and the step from Angular 2 to 4 is a lot smaller than the step from 1 to 2 was. It's comparable DSpace 3 in that regard. You can find the reasoning behind the change [here](http://angularjs.blogspot.be/2016/12/ok-let-me-explain-its-going-to-be.html)

[This blogpost](http://angularjs.blogspot.be/2017/03/angular-400-now-available.html) gives an overview of what's new, and how to migrate.

In our case migration won't be quite as simple as it is explained in that blogpost, because of Universal. Angular Universal used to be a separate project, but is included in Angular 4 now, so our dependencies and likely also a lot of the universal specific files (server.ts, node.module.ts, browser.module.ts, …) will need to change.

Universal starter, the boilerplate project we started from, has an open issue to migrate to 4: https://github.com/angular/universal-starter/issues/376

**Comment by wwelling** [comment]
Here are some things I noticed will change:

- ```server.ts``` and ```server.aot.ts``` will change considerably, will now use the new [view engine](https://github.com/FrozenPandaz/ng-universal-demo/blob/master/src/modules/ng-express-engine/express-engine.ts)
- when [@angular-cli](https://github.com/angular/angular-cli/pull/5194) is up to date, will only require one server file, should be named ```main.server.ts```
- only require one ```client.ts```, should be names ```main.browser.ts```
- will no longer need to compile sass manually, sass-loader will work with AoT and Universal
- ```OpaqueToken``` will become ```InjectionToken<T>``` and no longer need to use @Inject
- no longer need workarounds or polyfills

Here is a project that has contributions from the universal-starter developers:
https://github.com/FrozenPandaz/ng-universal-demo

Here is a pull request showing how the redux state can be put into universal cache and retrieved from there:
https://github.com/FrozenPandaz/ng-universal-demo/pull/5

This project also has a superior webpack setup and decomposition. Worth looking into.

**Comment by wwelling** [comment]
We should also move from [ng2-translate](https://www.npmjs.com/package/ng2-translate) to [ngx-translate](http://www.ngx-translate.com/).

Here is a translation loader for Universal: https://gist.github.com/ocombe/593d21598d988bf6a8609ba5fc00b67e

This allows the server to user the file system instead of http to get the translation files.

**Comment by nix1947** [comment]
Personal Fellings:
What I think is, Developer productivity is killed by these trends, and, what I think personally, is google angular project is one of the flops open source project that I have ever seen. and I am fade up with these frequent release.

Are DSpace developer are thinking about adopting another js framework like react? which is comparatively stable than angular.

**Comment by tdonohue** [comment]
@nix1947 : no, the DSpace developers will not be switching away from Angular (to some other JS framework). We went through a detailed analysis of platforms (not just JS frameworks) and our analysis resulted in the selection of Angular for the next DSpace UI. See this page for the details of our analysis of platforms and various prototypes on various frameworks: https://wiki.duraspace.org/display/DSPACE/DSpace+UI+Prototype+Challenge

**Comment by wwelling** [comment]
https://angular.io/docs/ts/latest/guide/universal.html

**Comment by wwelling** [comment]
https://github.com/ng-seed/universal

**Comment by tdonohue** [comment]
@wwelling : Now that OR2017 is behind us, I've moved this Upgrade to Angular 4 ticket into the "Ready" column. If you are still interested in claiming this and moving it forward rapidly (in the next week or two), this would be the ideal time to do so...as I anticipate very little development activity on the Angular UI in next few weeks.

**Comment by wwelling** [comment]
@tdonohue I will give it a try. Should be able to get it done by mid next week. If more urgent anyone else who is willing can give it a try as well.

**Comment by tdonohue** [comment]
@wwelling : That timeline sounds fine. If for some reason you aren't able to get to it, let me know, or unassign it from yourself. But, as you seem to have the most immediate experience with Angular 4, I suspect this may be easiest for you to implement, if you can get to it next week.  Thanks!
