### ISSUE TITLE
Freshly created collection does not get pre-selected for Item insertion

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#831]
1. Create top-level Community "Community 1"
2. It gets displayed in view mode
3. Pick option to create new Collection
4. Community "Community 1" is preselected in "new Collection" Community selector : "search.resourceid:047eb94a-d0d0-41bd-b761-6643d6d253ef"
5. Pick "Community 1" and add "Collection 1"
6. Collection "Collection 1" is displayed in view mode
7. Pick option to add new Item
8. New Item dialog does not preselect the "Collection 1" in collection picker

Expected - the collection, which is currently open in DSpace  (view or edit modes) should be pre-selected in collection picker.

**Comment by artlowel** [comment]
The estimate for this ticket is included in my estimate for [#843](https://github.com/DSpace/dspace-angular/issues/843#issuecomment-708333342)

**Comment by tdonohue** [comment]
Thanks. I've added a **0 hour** estimate to this ticket, as it will be solved by #843
