### ISSUE TITLE
Edit of an eperson doesn't work

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#837]
If you try to edit an eperson, for instance the one that come from the sample shibboleth integration to add them a Firstname and Lastname the system says that the changes are saved but the patch request sent to the backend is empty so no changes occur

**Comment by tdonohue** [comment]
@abollini : This ticket appears to have been "lost" for some time.  This sounds like a serious issue, so I'm flagging as `high priority` for 7.0.  However, it first needs to be validated (to see if it still exists).  Can you or someone on your team analyze this ticket?

**Comment by tdonohue** [comment]
Closing, I've retested this on https://demo7.dspace.org/ today & this is now working. I can successfully edit both a user profile & other eperson names (when logged in as an Admin).  I've verified the PATCH is not empty and the changes are saved to the backend (as they persist after logout & re-login).

I'm not sure where/when it was fixed, but it's fixed!
