### ISSUE TITLE
Submission UI - file upload doesn't support different ID

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#844]
**Describe the bug**
When using the UploadStep with a different ID than "upload" (e.g. to use other access conditions or make the file upload optional), the UI breaks.
This is occurring because the UI mixes the ID with the type (it uses the type assuming it's the ID)

**To Reproduce**
1. In item-submission.xml create an upload step with ID upload2 and type upload
2. Upload a file in the UI
3. The uploaded file is not displayed because the UI assumes the ID is upload

**Expected behavior**
The ID of the section is used to determine which files are associated

**Comment by benbosman** [comment]
@tdonohue we can handle this bug if desired since we already detected the problem

**Comment by tdonohue** [comment]
@benbosman : Sounds fine, I've assigned it to you.  Feel free to reassign internally as necessary.
