### ISSUE TITLE
citation_abstract_html_url must be based on the Angular UI Hostname

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#846]
**Describe the bug**
The citation_abstract_html_url contains the localhost URL instead of the Angular UI Hostname

**To Reproduce**
1. Open https://dspace7-demo.atmire.com/items/1974d7d3-9648-4dbe-b083-56374f5314e4
2. The page contains `<meta property="citation_abstract_html_url" content="http://localhost:3000//items/1974d7d3-9648-4dbe-b083-56374f5314e4">`

**Comment by artlowel** [comment]
This will take an estimated **4h**

**Comment by tdonohue** [comment]
Removed `Estimate TBD` label because this will be fixed as part of #737...so it's adding zero hours to the (combined) estimate provided in that other ticket.
