### ISSUE TITLE
Manage Resource Policies of Communities & Collections

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#848]
In DSpace 6, it was possible to Manage the Resource Policies of a Community or Collection in order to access restrict either (by changing the READ policy to a non-"Anonymous" group).  In the XMLUI however, this was only accessible via the Sitewide "Access Control" page (e.g. http://demo.dspace.org/xmlui/admin/authorize)

In DSpace 7, we already have the ability to manage Item-level policies via #601 if you visit `/items/[uuid]/edit/authorizations` in the UI

We should consider a similar implementation for Communities & Collections available off the `/collections/[uuid]/edit/authorizations` (and `/communities` for Communities).  Ideally, it'd be similar to the existing Item-level feature: it'd be directly available via the Edit page, and it'd (hopefully) use similar components.

I believe the necessary REST API features already exist, primarily in the [resourcepolicies endpoint](https://github.com/DSpace/Rest7Contract/blob/main/resourcepolicies.md)

Somewhat related to #781 (because this feature was a part of the Advanced Policy Manager in v6.x)

**Comment by atarix83** [comment]
estimation for this task is about 6 hours

we are interested to claim this task
