### ISSUE TITLE
BrowseBy list are statically configured

### ISSUE THREAD

**Issue by LucaGiamminonni** [DSpace/dspace-angular#852]
**Describe the bug**
The browseBy list present in the community and collection pages are not dynamically discovered using the api/discover/browses endpoint but are read from a static configuration present within the environment. In detail, the available browseBy are read from the browseBy.types property of the environment.

**To Reproduce**
1. Go under the Communities & Collections section
2. Select a community or a collection
3. Verify that the browseBy shown are only those present in the environment.browseBy.types property and that no calls to a REST endpoint are made to obtain them

**Expected behavior**
The browseBy list present in the community and collection pages should be dynamically obtained using the api/discover/browses endpoint. This implies that the browseBy.types property of the environment must be removed and where used it must be replaced with the configurations provided by the REST interface. 
Since in the browseBy.types list is indicated the type of browse (date, title, metadata), it is necessary to modify the existing endpoint api/discover/browses to add this information. As a possible solution to extend the current REST endpoint I propose to: 
- add the sorting type to the objects belonging to the sortOptions property
- add a defaultSort property that matches the name of the default sort for that browse; in this way, using this property it will be possible to obtain the type of browse by searching for the type of sort of the one configured as default.

**Comment by tdonohue** [comment]
I'm tentatively scheduling this for 7.1.  For the 7.0 release, at this time, I don't think it matters too much if the BrowseBy types need to be configured/ordered in your `environment.common.ts` here: https://github.com/DSpace/dspace-angular/blob/main/src/environments/environment.common.ts#L172

Longer term, you are right, it'd be nice if this was setup automatically based on the REST API.
