### ISSUE TITLE
Results in MyDspace displayed inconsistently (not 10x as configured)

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#859]
Load the MyDspace page (demo site on https://dspace7-demo.atmire.com/mydspace?configuration=workspace).

As per configs on left side there should be 10x records per page, instead the results seem to be filtered after fetching 10 results and in reality you get 2/3/5 etc results on each page.

Expected : display exactly 10 results in page unless there is not enough to fill a full page.

**Comment by tdonohue** [comment]
In today's meeting, it was mentioned that this bug might be a backend Solr issue and might be solved by https://github.com/DSpace/DSpace/pull/2744 (once that work is completed)

**Comment by tdonohue** [comment]
This may already be solved...Assigning to myself to retest it.

**Comment by tdonohue** [comment]
Closing. I've verified this has been fixed & is no longer reproducible on our demo site at https://demo7.dspace.org/

This was likely solved by https://github.com/DSpace/DSpace/pull/3133, but it's possible other recent fixes to the MyDSpace page also helped resolve it.
