### ISSUE TITLE
Fix or address string escaping / replacement issues reported by LGTM

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#876]
LGTM is currently reporting **four** potential "security" issues with string escaping/replacing in `metadata.utils.ts` and `auth.interceptor.ts`. We should analyze these and determine either a fix, or possibly tell LGTM to ignore the issue (if it is determined to not be an issue for DSpace).

These issues are listed as the **last four** issues in this list of security issues:
* https://lgtm.com/projects/g/DSpace/dspace-angular?mode=list&tag=security

**Comment by atarix83** [comment]
estimation is about 2 hours
