### ISSUE TITLE
Handle pages not supported yet

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#883]
**Describe the bug**
When clicking on the handle at e.g. https://dspace7-demo.atmire.com/items/17307a98-0e78-45a6-83c3-7829eee024c6, the handle is not resolved. The handle link also doesn't use the router, it's generated server-side.
Looks like a bug in the DsoRedirectDataService

**Comment by abollini** [comment]
About the handle link this is also related to https://github.com/DSpace/dspace-angular/issues/887 (for community and collection we currently don't have a generated link in the metadata)

**Comment by artlowel** [comment]
The reason for this issue is that the DsoRedirectDataService looks for responses with a status code in de 200 range, but rest returns a 302.

This will take an estimated **2h** to fix

Atmire would like to claim this issue

**Comment by tdonohue** [comment]
Thanks @artlowel .  Sounds good & I've assigned back to you (for your team) & moved to "in progress" column
