### ISSUE TITLE
Cannot complete a new submission on demo site or locally (when forgetting to click "+" next to repeatable field)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#884]
**Describe the bug**
Cannot complete a new submission either locally or on https://dspace7-demo.atmire.com/  In both cases, after completing the submission form (getting green checkmarks on all sections), the "Deposit" button enables.  But, when I click "Deposit", I get an immediate popup saying that some sections are incomplete & the form continues to display "Saving...." forever.

**To Reproduce**
1. Login as an Admin (cannot login as a submitter as submitters don't yet have rights to do a submission, see #658)
2. Start a new submission (collection doesn't seem to matter)
3. Complete all sections, until "Deposit" button enables
4. Click "Deposit" and you'll see the popup & the submission form will hang & never complete

In Chrome Dev Tools a few errors immediately appear:
* First, I see `Error: Effect "n.saveAndDepost$" dispatched an invalid action` with the JSON data from the submission form.  The `type` of action appears to be `dspace/submission/UPDATE_SECTION_DATA`.
* Then, I see `Error TypeError: Actions must have a type property`

**Expected behavior**
Obviously, the submission should be completed successfully.

**Comment by tdonohue** [comment]
After further testing, I've found this is caused by #864 , so I'll schedule this for beta 5 alongside that.

If I click on the "+" next to the Author field (as it is repeatable), then my submission **works**

If I forget to click on the "+" next to the Author field, the submission form gets confused into thinking my section is complete.  I'll see the green checkmark & the "Deposit" button enables.  But, clicking "Deposit" doesn't work & results in the above errors.

**Comment by tdonohue** [comment]
Scheduling this for beta 5 and adding a **zero hour** estimate as this bug will be fixed by #864 .  Therefore this ticket is just kept open as an FYI of the error that occurs until #864 is fixed.

**Comment by KevinVdV** [comment]
Found an additional use case that is prob related to this one (if it isn't ping me then I will create a separate ticket):

- Start a submission
- Fill in the mandatory metadata fields
- Add at least 2 authors
- Upload a file
- Check the license acceptance box
- The deposit button becomes active
- Remove an author
- The deposit button is inactive now (even though there is still an author left)

**Comment by tdonohue** [comment]
We expect this bug will be fixed by the (in progress) fix for #971
