### ISSUE TITLE
The "new" admin sidebar menu options don't provide enough context

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#889]
**Describe the bug**
We find users are confused by the new → collection and new → item admin sidebar options.
If you select new → collection for example, you see a dialog that says: "Search for a community", with a list of communities below. For inexperienced users it isn't clear _why_ they need to search for a community. The new → item dialog has the same issue.

Simply adding a bit of text above the search box that says something along the lines of: "Search for a community to create the collection in" would go a long way.

**To Reproduce**
1. Authenticate as an admin
2. in the sidebar, select new → collection or new → item
3. Look at the dialog that appears.

**Expected behavior**
The user should be told why they need to seach for a community or collection when creating a collection or item.

**Related work**
It would make sense to solve this in the context of #843, #831 and #890

**Comment by artlowel** [comment]
The estimate for this ticket is included in my estimate for [#843](https://github.com/DSpace/dspace-angular/issues/843#issuecomment-708333342)

**Comment by tdonohue** [comment]
Thanks. I've added a **0 hour** estimate to this ticket, as it will be solved by #843
