### ISSUE TITLE
Community Home Page

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#89]
Add a community home page component
Their route should be`/communities/:id`
The component should show the following fields if they exist:

 - title
 - logo
 - introductory text (html)
 - news (html - also referred to as sidebarText)
 - copyright text (html)

Create a smart component at the root that connects to the CommunityDataService to fetch the data,
Use small dumb components (i.e. a component that gets all its information through inputs rather than services) for each of the fields. 
Ensure the html fields get rendered as html.

For adaptability's sake, it would be best if you'd take the approach of the [simple-item-view component in the prototype](https://github.com/DSpace-Labs/angular2-ui-prototype/blob/master/src/app/dspace/components/simple-item-view.component.ts), where you create [a single wrapping component](https://github.com/DSpace-Labs/angular2-ui-prototype/blob/master/src/app/dspace/components/item/view-element.component.ts) to render a section of the page, and then [a specific component](https://github.com/DSpace-Labs/angular2-ui-prototype/blob/master/src/app/dspace/components/item/authors.component.ts) that makes use of the wrapping component, for each field on the page. 
That way, if an institution using this UI later on, wants to customize the way e.g. news is rendered, they only need to touch the news component and nothing else. The wrapping component ensures that you can still re-use as much code as possible.

For the layout, I'd say base yourself [on the prototype](http://ui-prototype.atmire.com/communities/93?page=1), rather than the current DSpace UIs

**Comment by rivaldi8** [comment]
@christian-scheible Are you working on it or did it get auto-assigned to you after changing the state?

**Comment by christian-scheible** [comment]
@rivaldi8 I am working on it. But it will be more or less a copy of your work on the collection home page. So if you would like to to that I could try solving another on.

**Comment by rivaldi8** [comment]
No, no problem, go ahead. I was just preparing to work on it and noticed I hadn't assigned it to me.
