### ISSUE TITLE
The new/edit admin menu dialogs are inconsistent

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#890]
**Describe the bug**
The dialogs you get to search for a DSO when you use the new or edit admin sidebar features are inconsistent.

The new → item search dialog improves upon the others by adding the parent object to each result (that way, if you have multiple collections with the same name, you can tell them apart using their parent communities), and by adding the ability to scroll down to get the next page of results.

However these improvements were never added to any of the other dialogs, making the user experience inconsistent.

**To Reproduce**
1. Authenticate as an administrator
2. In the sidebar, select new → item
3. Compare this to edit → collection for example: it is the same search, but it looks different and is a lot less user friendly

**Expected behavior**
I expect all these dialogs to work in a consistent manner, and to have the features (parent reference, scroll for the next page) that the new → item dialog has.

**Related work**
- The PR that added the new → item dropdown: #708
- It would make sense to solve this in the context of #843, #831 and #889

**Comment by artlowel** [comment]
The estimate for this ticket is included in my estimate for [#843](https://github.com/DSpace/dspace-angular/issues/843#issuecomment-708333342)

**Comment by tdonohue** [comment]
Thanks. I've added a **0 hour** estimate to this ticket, as it will be solved by #843
