### ISSUE TITLE
Add option for the admin to creat login page before using their dspace repository

### ISSUE THREAD

**Issue by ahlam94** [DSpace/dspace-angular#892]
I suggest to add an option that help admin to create login/signup page before anyone can browse their dspace as there may be some universities for example want to limit the access to their publications

**Comment by tdonohue** [comment]
@ahlam94 : I'm not sure I understand this request.  Could you describe what you mean by "add an option that help admin to create login/signup page"?

In DSpace 7 there is no need to create a login or signup page.  Both of those already exist "out of the box".  By default, users can register with your DSpace & create a login, but that gives them *no special permissions* on any publications store in DSpace.  So, administrators can control access to their publications without the need to create a special login or signup page.

So, I think the feature you are looking for may already exist.  But, it's possible I'm misunderstanding your request.

**Comment by tdonohue** [comment]
@ahlam94 : DSpace only forces you to sign in when you attempt to access a restricted page or file.  So, by default, if you are *not signed in* then you will only see pages/items which have publicly visible metadata.  That said, as soon as you attempt to access a Collection or Item or File which is restricted, then DSpace will force you to login first.  DSpace is built to allow you flexibility in deciding which content can be publicly accessible and which content must be access restricted (requiring login).  

DSpace does *not* require a login for all users as that would break all Search Engine Optimization (i.e. your content would never be findable in Google or Google Scholar, as those web spiders would be blocked from authenticating).  That said, if you wanted to force everyone to login before they can access your DSpace, you could choose to put your DSpace behind a local firewall (which requires login), or you could access restrict all Communities/Collections/Items (in which case, they could see the homepage without logging in, but would be asked to authenticate as soon as they clicked on a different page).

All in all, DSpace won't include a feature that forces all users to login first, as you can achieve that by installing DSpace behind a firewall or similar.  Most institutions who use DSpace want to make at least some content available publicly (and findable in Google), and requiring a login from all users would block that capability.
