### ISSUE TITLE
Delete group is unfinished

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#893]
**Describe the bug**
The groups page has delete buttons for groups that aren't permanent, but if you click them you always get an error notification saying: 'not yet implemented in backend'. However the proper DELETE call to the backend is made, so if you're allowed to delete a group it will succeed and you also get a success notification. If it fails, you get a non specific error notification on top of the 'not implemented' error.

**To Reproduce**
1. Authenticate as an administrator
2. From the sidebar select Access Control → Groups
3. in the list that appears try to delete a group

**Expected behavior**
- The 'not implemented' notification should be removed
- If the delete fails, the error message from the rest api should be shown to explain to the user why it can't be deleted, instead of a non-specific 'delete failed' message 
- Whether the delete button is shown or not should depend on the canDelete feature, not the `permanent` property of a group
- It would be good to add the delete button to the group detail page as well, to be consistent with EPersons.

**Comment by artlowel** [comment]
This can be fixed in an estimated **4h**

**Comment by tdonohue** [comment]
Updated estimate per https://github.com/DSpace/dspace-angular/pull/925#issuecomment-726232636
