### ISSUE TITLE
TypeError: Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#897]
Try to access property `uuid` of undefined variable `metadata` in `FilterInputSuggestionsComponent` which leads to a type error (as shown in Chrome's web dev console). This error occurs only in context of facet filter generation. 

The error is issued by the statement at line 80 ([file](https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/input-suggestions/filter-suggestions/filter-input-suggestions.component.ts#L80))

```js
    this.objectUpdatesService.setValidFieldUpdate(this.url, this.metadata.uuid, this.valid);
```

1. clone git repo dspace-angular (use branch `main`)
2. run `yarn install` 
3. run `yarn start`
4. open Chrome browser and dev console
5. go to http://localhost:4000/search
6. click into search form input field

Error message in dev console:
```
ERROR TypeError: Cannot read property 'uuid' of undefined
    at t.checkIfValidInput (filter-input-suggestions.component.ts:80)
    at Object.handleEvent (filter-input-suggestions.component.ngfactory.js.pre-build-optimizer.js:48)
    at Object.handleEvent (core.js.pre-build-optimizer.js:29239)
    at Object.handleEvent (core.js.pre-build-optimizer.js:29784)
    at qp (core.js.pre-build-optimizer.js:19859)
    at core.js.pre-build-optimizer.js:21044
    at t.i [as _next] (core.js.pre-build-optimizer.js:23747)
    at t.__tryOrUnsub (Subscriber.js.pre-build-optimizer.js:194)
    at t.next (Subscriber.js.pre-build-optimizer.js:132)
    at t._next (Subscriber.js.pre-build-optimizer.js:76)
```

PR that fixes the problem follows.

**Comment by tdonohue** [comment]
@artlowel : would you be willing to estimate the work here (as you provided feedback on a better proposed solution in the PR #898)?  This seems like it's becoming higher priority to me...as this same bug seems to appear in other PRs (e.g. PR #894 hits this error as [I noted in this comment](https://github.com/DSpace/dspace-angular/pull/894#pullrequestreview-517099725))

**Comment by artlowel** [comment]
This can be fixed in an estimated **2h**

Atmire wants to claim this ticket

**Comment by tdonohue** [comment]
Thanks @artlowel . Sounds good. I've assigned this back to you & moved to "in progress" so that work from your team can begin.  Please keep in mind, this was previously flagged as `high priority` as this same issue has been hit via other tests (see other PRs mentioning this bug above). Thanks!
