### ISSUE TITLE
Browse pages show news section

### ISSUE THREAD

**Issue by samuelcambien** [DSpace/dspace-angular#900]
On the browse pages, when a scope is selected, the 'dc.description' and 'dc.description.tableofcontents' metadata of the scope community/collection is shown in the header. This seems a bit strange, and it also wasn't like this in DSpace 6.

To reproduce:
- Add 'dc.description' and 'dc.description.tableofcontents' metadata to a community
- Go to the browse page for this community
- For example: https://dspace7-demo.atmire.com/browse/title?scope=4358b240-4b96-468b-8a69-077874338a5b

Expected behaviour:
- The metadata is not shown

Observed behaviour:
- The metadata is shown above the browse results

**Comment by samuelcambien** [comment]
I hear now this would be a feature rather than a bug

**Comment by tdonohue** [comment]
@samuelcambien : I also would not consider this a bug. In my opinion it makes sense as the browse controls are now more dynamic and allow you to essentially change the view while remaining on the Community/Collection page.

So, I'm going to close this as "won't fix", as I think it's OK as-is.  *However*, if we hear users (e.g. repository managers) complain about this behavior during testing (or upcoming Testathon) we can always reopen this at a later time and brainstorm an alternative display.  Thanks!
