### ISSUE TITLE
minor bug: multiple input elements with same value (name) of attribute id

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#902]
The search page contains multiple `input` elements with the same value (current value is `name`) of attribute `id`.

1. open web dev tools in Chrome
2. go to https://dspace7-demo.atmire.com/search
3. three warnings show up in JS console 

```html
[DOM] Found 3 elements with non-unique id #name: (More info: https://goo.gl/9p2vKq) 

<input _ngcontent-dspace-angular-c34 autocomplete=​"off" class=​"form-control suggestion_input ng-untouched ng-pristine ng-invalid" formcontrolname=​"metadataNameField" id=​"name" ng-model-options=​"{standalone:​ true}​" type=​"text" name=​"f.author" placeholder=​"Author name">​
<input _ngcontent-dspace-angular-c34 autocomplete="off" class="form-control suggestion_input ng-untouched ng-pristine ng-invalid" formcontrolname="metadataNameField" id="name" ng-model-options="{standalone: true}" type="text" name="f.subject" placeholder="Subject">
<input _ngcontent-dspace-angular-c34 autocomplete="off" class="form-control suggestion_input ng-untouched ng-pristine ng-invalid" formcontrolname="metadataNameField" id="name" ng-model-options="{standalone: true}" type="text" name="f.entityType" placeholder="Item Type">
```

**Expected behavior**

values of id attribute must be unique

**Comment by Raf-atmire** [comment]
Hi @saschaszott , I've tried to reproduce the issue on the mentioned URL, but I'm unable to see the warnings that you've mentioned in the console.
I've navigated to the mentioned URL, opened the console and pressed refresh a couple of times, but I've been unable to see the errors that you've mentioned. Could you provide some more details on how to see those please?

**Comment by artlowel** [comment]
This was fixed by https://github.com/DSpace/dspace-angular/pull/941. Closing
