### ISSUE TITLE
Problems with environment files merging

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#909]
Environment files merging functionality in _set-env.ts_ file leads to issues in resulting environment.ts file.

When using below attached common(standard) and dev  environment files, the merge process runs weirdly and I cannot get resulting environment.ts file to produce expected results.

Source/resulting files (extension renamed from .ts to .txt)
[environment.common.txt](https://github.com/DSpace/DSpace/files/5403599/environment.common.txt)
[environment.dev.txt](https://github.com/DSpace/DSpace/files/5403600/environment.dev.txt)
[environment.txt](https://github.com/DSpace/DSpace/files/5403601/environment.txt)

Expected: 
1) Have values from _dev_ environment file to override common values, in some cases the value gets overriden, in some "merged" (suspecting that the arrays get merged)
2) Have to define only the values you expect to override
3) As per README file, the _dev_ file should be created from _template_ file, without imports (?)

Currently having following issues with this aproach:
1) You have to provide a full copy of environment file for _dev_, which makes "merge" process unnecessary, trying to skip anything in _dev_ config leads to startup errors
2) If I try to configure _dev_ to use only 2 languages - resulting configuration contains all languages + the 2 requested, eventually ending up as full list of languages configured
3) even worse for "browseBy/types" - these get a duplicated UI elements in communities and collections

**Comment by tdonohue** [comment]
I've transferred this issue over to `dspace-angular` as it's a front-end configuration ticket.

In terms of the merging of configs, it looks like we are simply using the default behavior of [deepmerge](https://github.com/TehShrike/deepmerge).   Best as I can tell, that default behavior looks like it *combines* arrays (no overwriting values).  We might want to consider whether the `overwriteMerge` behavior would make more sense for these configurations -- as that seems like it aligns better with the expectations laid out in this ticket.

Thoughts on this @artlowel?  It looks like the current behavior came in during our switch to Angular CL in #625

**Comment by artlowel** [comment]
I agree that the current behavior should be changed. But it is difficult to have a solution for arrays that works in all cases. If you overwrite, indeed you'll need to add everything you want to keep. But that is also the way it works for arrays in local.cfg in dspace 6 as well.

An alternative could be to merge based on index. But in that case, what if you want to remove an option from environment.common.ts, such as the languages in @Aziris' example. If the array in your local file is shorter, it would just override the first few options and be padded with the remaining options in environment.common.ts. And what would we do when you want to keep everything but override the 3rd element in the list for example? Add a few undefined's first?

We could also write a merge function that checks for an `id` property on the array elements, and merges the ones with matching ids, in that case you could set something with a specific id to undefined if you wanted to get rid of it. But in that case we might as well swap from an array to an object where the keys function as ids anyway.

So considering all of these, my preference would be to use overwriteMerge, and to go over everything that's currently an array to see if we're not better off converting it in to an object.

**Comment by tdonohue** [comment]
@artlowel : I agree with your suggestions here that we should look towards a "tweaked" version of `overwriteMerge`.  Do you have any rough guesses on how much effort this would be?   In my opinion, this seems like something we should attempt to improve *now* (in beta5), so that configuration works more as expected in 7.0....rather than delaying this for a 7.1, which would make for a possibly awkward upgrade between 7.0 to 7.1.

So, that said, do you agree with adding this to beta 5?  If so, would you be comfortable giving this an estimate?

**Comment by artlowel** [comment]
@tdonohue I'm not sure what you mean by 'tweaked'? My suggestion was to use overwriteMerge as is, but to minimize the problem of having to copy values from the default config by verifying if there are config options that are currently arrays but don't need to be (because the order isn't important), and if so turn them in to objects.

This can be done in an estimated **2h**

**Comment by tdonohue** [comment]
@artlowel : Apologies, I completely misstated your position/proposal.  I meant to reference your note to "go over everything that's currently an array to see if we're not better off converting it in to an object" -- which is similar to "tweaking" the configuration to align better with `overwriteMerge`.  I must've been typing that reply in a hurry and shortened it to something that doesn't make sense (as it also doesn't make sense to me now...I realize you were not trying to modify the behavior of `overwriteMerge`).

In any case, I like your proposal to switch to `overwriteMerge` & review our existing configurations to align better with that.  Thanks also for the estimate, I've added it to this ticket.
