### ISSUE TITLE
404 page status code

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#91]
The status code of the current 404 page is 200. It should be 404.

**Comment by rivaldi8** [comment]
I've searched for a way to set the status code, but I haven't found any reference or example of how to do so. All examples I've seen redirect to a component like our `PageNotFoundComponent`, but don't do anything about the status code.

Is there some well-known way to do this that I've missed?

**Comment by artlowel** [comment]
Maybe this is of some help?:
https://github.com/angular/universal/issues/667

We can only set the status code on the server side for the initial page request, afterwards, in the client-side code you can no longer change the status code, because the request that has already arrived at the browser. That is probably why examples that don't work with universal don't set the status code

**Comment by rivaldi8** [comment]
Ok, I hadn't thought about Universal. Anyway, I see it's a bit tricky. I'd rather go after easier stuff for now :)

**Comment by patrickmichalina** [comment]
@rivaldi8 this way is easier:

https://github.com/patrickmichalina/fusebox-angular-universal-starter/blob/master/src/client/app/shared/services/server-response.service.ts

**Comment by rivaldi8** [comment]
@patrickmichalina Thanks for the tip! I'll try again.
