### ISSUE TITLE
Grid view displays only 2 columns next to each other

### ISSUE THREAD

**Issue by Aziris** [DSpace/dspace-angular#914]
Although you may have 9(3x3) elements on screen, they tend to take only 2 columns, placing the 3rd column below the first.

![image](https://user-images.githubusercontent.com/2697696/96717962-ff65d380-13af-11eb-9efe-d0294b727fb8.png)

![image](https://user-images.githubusercontent.com/2697696/96718060-1efcfc00-13b0-11eb-98c1-4c203bb94e14.png)

card-columns has width : 841,
each card-column has width 280.33

All 3 columns should be fitting next to each other.

Browsers checked:  Chrome / Edge

**Comment by tdonohue** [comment]
This looks like a duplicate of #895, which already has a PR to fix it: #901.
