### ISSUE TITLE
New Item submit form does not change associated collection if picked from admin side bar

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#922]
can be reproduced on demo site : https://dspace7-demo.atmire.com/

1. Log in and open New Item form
2. While in this form, pick from sidebar New/Item
3. Select a different collection from pop-up
4. Nothing visually noticeable happens to New Item form - associated collection does not get changed

Expected that the action would have the collection change or would not be available at this point.

**Comment by tdonohue** [comment]
@Aziris : I'm not sure I understand this ticket.  I've tried the steps you described, creating a new Item by selecting a collection from the popup.  After selecting a collection, I see the submission form load & it shows that selected Collection at the top of the submission form (in the "Collection" field).

So, I'm not seeing any bug based on the steps you've described.  But, maybe I'm misunderstanding the steps?

**Comment by MarisArins** [comment]
Here I will describe the steps that I take with some pictures.

1. Open new Item page 
![image](https://user-images.githubusercontent.com/2697696/97733586-b9f88300-1ae0-11eb-84f7-7744ef053c4a.png)

2. Still in new Item form click sidebar "new Item" option again:
![image](https://user-images.githubusercontent.com/2697696/97733830-02b03c00-1ae1-11eb-9f45-24143df06ddf.png)

3. Pick different collection this time (Brasil/Collecion)

4. Nothing changes, no messages 


Possibly after such a step a new "new Item" page could be presented with picked Collection. Another possibility this "new Item" feature could be disabled while in this page.

**Comment by tdonohue** [comment]
Thanks for clarifying @MarisArins .

I can reproduce this after all by doing:
* Login as a submitter
* Select New -> Item & choose a collection.  I go to the submission form for that collection
* Select New -> Item *again* & choose a different collection.  Nothing happens...I remain on the submission form for the original Collection.

To me, this is a lower-priority bug/usability issue.  It seems unlikely many users would try to do this, as it's much easier to simply change the collection using the "Collection" dropdown on the submission form.  So, I'm tentatively scheduling this for fixing in 7.2

**Comment by tdonohue** [comment]
Stumbled on this old ticket. Re-tested today on demo7.dspace.org and it's no longer reproducible.  It appears this was fixed in 7.0
