### ISSUE TITLE
Restricted items do not present login page

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#923]
1. Create a new Item
2. Add Read access to Admin user
3. Remove Read access to Anonymous group
4. Log out
5. Try to access directly the restricted Item , eg.  https://dspace7-demo.atmire.com/items/cedc5c50-b9d9-4187-ad83-b31c2a21acde

Application does not end page loading process, though in Network tab you can see some requests with 401 response code.

Expected result :  System presents login page and notifies user that the resource is restricted and requires authorization.

P.S. Login with inadequate user role should also present propper notification.

**Comment by tdonohue** [comment]
@artlowel : Could you or someone on your team estimate this?  I agree that a 401 response from the backend likely should end up showing the *login form* instead of a generic "401 unauthorized" page.  So, this is slightly related to the work in #891

**Comment by artlowel** [comment]
This can be done in an estimated **2h**

Atmire would like to claim this ticket

**Comment by tdonohue** [comment]
Thanks @artlowel .  Sounds good, and I've assigned this back to you & moved to "in progress" so that work can begin.
