### ISSUE TITLE
Generic Items "appear" as though they are always Publication Entities / Publication seems to be the "default" Item

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#936]
**Describe the bug**
Generic Item pages always appear to be Publication Entities, and are always prefixed with "Publication:" on Item page.  This behavior can easily be seen on the Demo site, e.g. https://dspace7-demo.atmire.com/items/1cc071d0-aaf5-4206-afab-cad8a64cdb47

Additionally, the code in the Angular UI seems to treat "Publication" as the default type of Item, and several "generic" components are prefixed with `Publication`. For example:
* `PublicationComponent`: https://github.com/DSpace/dspace-angular/blob/main/src/app/%2Bitem-page/simple/item-types/publication/publication.component.ts
* `PublicationListComponent`: https://github.com/DSpace/dspace-angular/blob/main/src/app/shared/object-list/item-list-element/item-types/publication/publication-list-element.component.ts
* `PublicationSidebarSearchListElementComponent` being added by #930 

**Expected behavior**
Two main points:
1. Generic Items should never appear as though they have a "type", as it makes it difficult to distinguish them from Publication Entities.  Additionally, generic items may _often_ be used for things that are not "publications" (e.g. working papers, preprints, A/V, images, etc)
2. Because Publication Entities are *not enabled by default*, any **generic** components should be prefixed with `Item` or similar.

**Comment by tdonohue** [comment]
@artlowel : would you (or someone on your team) be willing to estimate this task?

**Comment by artlowel** [comment]
This would mean going over all components containing a line matching the search `@listableObjectComponent(Item`.   
I count 9 right now.
- If they also have a second `@listableObjectComponent` line: split them up, and replace references to the item type with a more generic term, or remove them.
- if they don't, look for any reference to an item type. If they exist, it may also need to be split up.

This can be done in an estimated **4h**

**Comment by artlowel** [comment]
Atmire would like to claim this ticket

**Comment by tdonohue** [comment]
Thanks @artlowel .  I've added the estimate & assigned back to you for your team to work on
