### ISSUE TITLE
Highlight withdrawn Items in collections

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#947]
Currently, when admin looks at collection, he sees withdrawn items the same as regular, archived items: 

![image](https://user-images.githubusercontent.com/2697696/99649624-1a823c80-2a5d-11eb-82ad-6ece95a2c010.png)

Regular users would not see the withdrawn Items, but for admin there is no way to tell which items are going to be missing for users, as they all are visually the same.

Some kind of special style class , graying-out or extra label would be required to tell the difference between archived and withdrawn items.

**Comment by tdonohue** [comment]
I agree this is a usability issue.  I like the suggestion to provide an extra label (similar to `Research Project` label in the above screenshot perhaps).  

@artlowel , do you see any issues with this idea?  If you agree, could you look at this concept & provide an estimate here?

**Comment by artlowel** [comment]
We can add the same badges that are used in the administrative search to withdrawn and private items (unless there's a good reason not to do it for the latter):
![image](https://user-images.githubusercontent.com/1567693/100984659-4c120200-354b-11eb-9af6-b1ec3ddb5f88.png)

This will take an estimated **4h**

**Comment by tdonohue** [comment]
That seems fine to me, @artlowel .  Thanks!  Updated ticket with estimate

**Comment by artlowel** [comment]
We'd like to start work on this issue
