### ISSUE TITLE
Wrong occurrence of submission form Identifier field deleted

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#949]
**Describe the bug**
When we have two values ​​for the same metadata and we want to delete the second, after saving the first is deleted and the second kept.

**To Reproduce**
1. Login as admin
2. Start a submission in collection Books
3. Insert an identifier of type ISSN and click +
4. Insert an identifier of type ISSN and click +
5. Save the submission form
![caso2error2](https://user-images.githubusercontent.com/63857/99660304-78fde980-2a62-11eb-9f81-adaaa020529e.png)
6. Delete the second row
![caso2error3](https://user-images.githubusercontent.com/63857/99660327-8024f780-2a62-11eb-8698-f01d37930698.png)
7. Save the submission form
8. The form updates, the first is deleted and the second is kept.
![caso2error4](https://user-images.githubusercontent.com/63857/99660365-8f0baa00-2a62-11eb-8a49-9bf0a4cd3e21.png)

This is the (wrong) performed patch operation:
![caso2error](https://user-images.githubusercontent.com/63857/99659974-fe34ce80-2a61-11eb-9768-b092088104b5.png)

**Expected behavior**
The right row should be deleted.

**Comment by tdonohue** [comment]
As discussed in today's meeting, we expect this bug will be fixed by the (in progress) fix for #971. Therefore, I'm adding a **0hr** estimate to this bug. If we later find it is not fixed, then we can reanalyze at that time.

**Comment by tdonohue** [comment]
Retested this today & verified that PR #1025 fixes this issue
