### ISSUE TITLE
Upload dropzone is shown in the submission if there's no upload section

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#957]
**Describe the bug**
If you configure a submission without an upload section, the upload drop zone at the top of the page is still shown.

**To Reproduce**
1. Configure a collection without an upload section in the submission
2. Authenticate in the UI
3. Submit an item to that collection
4. Verify that you can still see the drop zone.

**Expected behavior**
I'd expect the upload drop zone only to be visible if the submission has an upload section

**Comment by tdonohue** [comment]
Definitely a bug.  Adding to Beta 5 for now, though flagging as "low priority" (as it may not matter if this ends up delayed).  Needs an estimate of the effort.

**Comment by atarix83** [comment]
@tdonohue this can be fixed in 1 hour

**Comment by tdonohue** [comment]
Thanks @atarix83 .  I've added that estimate to the ticket. I'll keep this in Beta 5 since it's such a small change.

**Comment by tdonohue** [comment]
PR #1053 had to be reverted, as it broke the submission form. Reopening & assigning back to @LotteHofstede

**Comment by tdonohue** [comment]
Fixed by #1087
