### ISSUE TITLE
The Edit Collection - Item Mapper page has disappeared

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#974]
**Describe the bug**
In https://github.com/DSpace/dspace-angular/pull/348, a page was added to edit the mapped items in a collection. Now I can no longer see any links to it in the UI, and if you go to the route directly you get a 404.

**To Reproduce**
1. Authenticate as an admin
2. Go to the edit/mapper route of a collection
3. Verify that you get a 404

**Expected behavior**
The page should be linked from the edit collection page, and work if you go to the url directly

**Related work**
The page was added by https://github.com/DSpace/dspace-angular/pull/348

**Comment by artlowel** [comment]
The issue seems to be that the links to retrieve and store mapped items have been renamed on the rest side, and were never updated on the angular side.

It also seems that there never was a link for the item mapper on the edit collection page. So I propose we simply add it as a tab.

That should take an estimate **3h**

**Comment by tdonohue** [comment]
Thanks for noticing this & giving it an estimate, @artlowel .  I'll move this over into Beta 5 as it seems the task is not yet complete.  If you'd like to claim it for your team, let me know.
