### ISSUE TITLE
The page title and breadcrumb trail are not set consistently.

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#976]
**Describe the bug**
Not all pages set a page title or breadcrumb trail, which causes them to retain the title and trail of the previous page. The names are also inconsistent e.g. for the home page it's "DSpace Angular :: Home" for the Community list it's "DSpace - Community List" etc.

**To Reproduce**
1. Go to the [community list page](https://dspace7-demo.atmire.com/community-list). Note there is no breadcrumb trail, but the page title says "DSpace - Community List"
2. Click a community. Note that there _is_ a trail now, but the page title still says "DSpace - Community List" instead of the name of the Community.

This is just one example, there are plenty more

**Expected behavior**
Every page should have a distinct page title and breadcrumb trail, and the values, delimiters, etc. should be consistent across the repository

**Related work**
This can likely be fixed in the context of https://github.com/DSpace/dspace-angular/issues/728. But I created this as a separate issue to ensure we don't lose track of it.

**Comment by tdonohue** [comment]
As discussed today, this should be fixed in the context of #728 (i.e. assigned to the same person).  Adding an extra **4 hours** to this ticket to ensure it can be addressed at the same time.
