### ISSUE TITLE
Submission Form - error message "There was an issue when saving the item, please try again later." appears randomly and item has to be discarded even if there are no errors in form

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/dspace-angular#986]
The error message "There was an issue when saving the item, please try again later" appears randomly - even when just starting to submit an item (and not having populated any fields yet). 
Once this message appears, one has to discard the item, because even when _all_ sections are "green", pressing the 'Save' button or 'Save for later' button or the 'Deposit' button also then gives the message "There was an issue when saving the item, please try again later". On the one hand, users should be able to fix an error and continue with the population of the submission form.  On the other hand, the problem here is that there _is_ no error.

**Comment by tdonohue** [comment]
This might be either the validation issue again in #931 (as we've seen very odd errors from that), or (if you are running this locally), it's possible you don't have the fixes from #960 (which fixed some odd auto-save bug where the form would auto-save at very odd intervals).  We'd need more information here to determine what might be going on.  Thanks!

**Comment by tdonohue** [comment]
I've also seen behavior like this in #950 and #1032.  When reproducing those bugs, the form becomes unusable & you have to reload the entire form to fix the error.

However, I'm closing this ticket as it doesn't have enough information on how to reproduce it.  I suspect what you are seeing is the behavior described in one of the other tickets (that I've linked to) and all of those are currently being worked on.
