### ISSUE TITLE
Submission Form - cannot edit uploaded file because Group field is mandatory and has no input values in drop-down

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/dspace-angular#987]
I submit a new Article item.
I upload a file.
In the 'Upload Files' section I add a description, choose 'embargo' as access condition type and choose the dates.
However, The Group field is mandatory, but there are no values to choose from in the drop-down - hence I cannot save any of the previously-entered file metadata.

**Comment by tdonohue** [comment]
Thanks, this is a duplicate of #869 (which we are currently working on).  Closing as a duplicate
