### ISSUE TITLE
Submission Form - error message for mandatory fields missing/incorrect for some input types

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/dspace-angular#989]
I submit a new Article.
If I do not populate the mandatory 'Title' field, I get message "You must enter a main title for this item" - correct.
If I do not populate the mandatory 'Date of Issue' field, I get message "You must enter at least the year" - correct.
If I do not populate the mandatory 'Author' field, I get either no message or **"error.validation.required"** - incorrect

**Comment by tdonohue** [comment]
This is a configuration issue (Author was accidentally set to "required") which is fixed in https://github.com/DSpace/DSpace/pull/3115.  It's also a validation issue on repeatable fields which we are fixing in #931.  So, I'm closing this as this issue is covered elsewhere.  Thanks!
