### ISSUE TITLE
Check relationship.effects.spec.ts after Angular 10 upgrade

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#993]
During Angular 10 upgrade the relationship.effects.spec.ts has been redesign because it used a spy on rxjs's debounceTime operator and due to jasmine update this is not possible. To allow to test with asynchronous operator we replaced the use of spy with the more appropriate [TestScheduler function](https://ngrx.io/guide/effects/testing#with-testscheduler). It works for almost all class's tests, with the exception of a few which required to be reviewed by comparing them with the implementation. It is likely, in fact, that previously the tests were successful only because the specs had no expectations. Here the link to the tests that need a review :

https://github.com/4Science/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts#L142
https://github.com/4Science/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts#L213
https://github.com/4Science/dspace-angular/blob/main/src/app/shared/form/builder/ds-dynamic-form-ui/relation-lookup-modal/relationship.effects.spec.ts#L234

**Comment by artlowel** [comment]
Here I would roll back the changes that were made, and use the proposal I made for #992 to spy on debounceTime. It seems that the approach tried here with the scheduler and flush can't work for debounceTime. There's an open ticket for it: https://github.com/angular/angular/issues/25457#issuecomment-728876345

But we can inject debounceTime, spy on it that way and its input value immediately as we did before.

This will take an estimated **4h**. It makes sense to do this at the same time as #992
