### ISSUE TITLE
Separate configuration from codebase to make it more responsive

### ISSUE THREAD

**Issue by mwoodiupui** [DSpace/dspace-angular#995]
Configuration of dspace-angular is currently set in stone at build time, which is painfully awkward for development and testing, and not much better in production.  Every little tweak requires a rebuild of several minutes' duration, followed by reinstallation and restart.

To the greatest extent possible, site-specific configuration should be separated from the codebase into external storage provided at startup time.  This poses a problem for the browser environment: how to distribute configuration data at startup.

To address this problem, we should ask ourselves what is the minimum information that the UI needs and how can it get that information.  I believe that the answer is: the URL for the current page (that is: the initial page), which can be obtained from a property of a global object.  Given this, the bootstrapping code can fetch a JSON configuration object from the server-resident UI code when it is fetching the code bundles.  So the UI code really doesn't need any site-specific information compiled-in.

We would need to design a configuration language, express the current configuration in that language, and define a method for the server-resident UI code to be told where to find the configuration.

We would need to create server-resident code to express the configuration as JSON and deliver the object via a URL that the
browser-resident code can compose from its knowledge of where it came from.

Perhaps the simplest approach would be to turn the current configuration files into a file in JSON format, and just transmit that file to the browser on request.  The server-resident UI can separately read the same file to load its own configuration.  The current files are very nearly JSON already.

I would suggest that a few configuration properties be overridable from the server process environment at startup:  the server and REST URL components.  Currently this is done, but at build time.  The override should instead be done at startup time.

We *could* put the configuration behind an endpoint on the REST service, but I feel that this unnecessarily entangles dspace-angular with dspace-server for no particular gain.  I suggest that the front-end configuration mechanism should be encapsulated in the front-end project.

**Comment by tdonohue** [comment]
This sounds like it'd need more discussion/analysis before it could be actionable.  Putting it in 7.1 board for now, to at least get discussion started then.  At that point we can better determine need/priority.

**Comment by tdonohue** [comment]
Closing, as this has since been fixed.  Configs in UI are now loaded at runtime (not build time) as of 7.2 and above. https://wiki.lyrasis.org/display/DSDOC7x/User+Interface+Configuration#UserInterfaceConfiguration-In7.2orabove
